### ISSUE TITLE
3 "libmate-menu2" recent upgrade breaks panel function in Leap 15.1 install

### ISSUE THREAD

**Issue by esteelpaz** [mate-desktop/mate-panel#1011]
#### Expected behaviour
added a MATE "pattern" to a recent Leap 15.1 install looking for MATE DE behaviors

#### Actual behaviour
Recent updates to "libmate-menu2" "mate-menus" and "mate-menus-lang" packages to the OpenSUSE package versions ending in -lp151.3.5.1 succeeded in breaking the top and bottom panels and toolbar launcher function in the MATE pattern of Leap 15,1.  When I downgraded the packages it seemed to bring the toolbar back, but when I logged out of the session I couldn't get back in . . . it went to a grey window.

#### Steps to reproduce the behaviour
Problem has been confirmed on the OpenSUSE forum > technical help> applications by other user

#### MATE general version
? can't confirm that now

#### Linux Distribution
OpenSUSE Leap 15.1

**Comment by esteelpaz** [comment]
Link to OpenSUSE forum thread;

[](url)[https://forums.opensuse.org/showthread.php/537376-New-GNOME-install-added-MATE-but-it-has-no-top-panels-to-open-apps-with](url)

**Comment by raveit65** [comment]
Version of mate-menus?
Version of mate-panel?

**Comment by esteelpaz** [comment]
@raveit65

As mentioned above, another OpenSUSE user tracked the problem to three packages when he upgraded to the current versions recommended, "libmate-menu2 (1.20.0-lp151.3.5.1-x86_64), "mate-menu" and "mate-menus-lang" each of the same number.

Since I can't log into the offended system right now to check anything, I have my desktop computer running 15.1 with a non-upgraded version of MATE, where MATE is working and it shows the MATE panel as version 1.20.1 . . . that install was from a couple months back and has been updated regularly until this recent issue.  The laptop with the problem was a fresh install using the same flash drive installer, but run on this recent Friday, and then MATE added on Saturday, coming up as broken.

Another user on the OpenSUSE forum reported this issue on Bugzilla after I had started this one here . . . .  [Bug 1149132  Patch openSUSE-2019-2028 broke MATE [](url)(https://bugzilla.opensuse.org/show_bug.cgi?id=1149132)](url)

**Comment by raveit65** [comment]
Please use `dnf history` from console, (old run level3) to show us what you did updated, you don't need to login to a desktop.
I don't use openSuse and i don't know what updates are `recent`
And we need to known which version of  mate-menus and mate-panel is installed.
`rpm -qa mate-menus` `rpm -qa mate-panel`.
All this command you can do from command line...
I think have a feeling what the problem is. but i need to know exact package versions.
This sounds like a packaging issue in your distro....

**Comment by esteelpaz** [comment]
@raveit65:

I'm not entirely console literate, like I'm not sure what "dnf history" is but I'll check it in a minute.  I ran your "rpm" commands in the laptop via GNOME Classic and got . . . 

```~$ rpm -qa mate-menus rpm -qa mate-panel
mate-menus-1.20.0-lp151.2.5.x86_64
mate-panel-1.20.1-lp151.3.5.x86_64
rpm-4.14.1-lp151.13.10.x86_64
`
But, yeah, in Leap 15.1 the "dnf history" or "sudo dnf history" is not "understood."  But it seems like the forum agrees that this is a "packaging issue in the distro" . . .

**Comment by esteelpaz** [comment]
Sorry, the "code" thing didn't seem to work very well:

~$ rpm -qa mate-menus rpm -qa mate-panel
mate-menus-1.20.0-lp151.2.5.x86_64
mate-panel-1.20.1-lp151.3.5.x86_64
rpm-4.14.1-lp151.13.10.x86_64

**Comment by esteelpaz** [comment]
@raveit65:

Did that give you anything helpful, or anything else you need from me?  If you need me to run specific commands then please spell them out and I'll run them, etc.

**Comment by raveit65** [comment]
@XRevan86 Can you please take a look at it?

**Comment by raveit65** [comment]
@esteelpaz 
Can you please give me a link to the git history of mate-menus package in opensuse?
I like to know what `Patch openSUSE-2019-2028` is.

**Comment by esteelpaz** [comment]
@raveit65:

Happy to do that, but if you would be kind enough to describe the commands
to run, or where to look for a file, etc on "git history of mate-menus
package"???  I'm fairly new to OpenSUSE, although even after many years in
linux I don't recall seeing "git history" mentioned in any forum threads
dealing with the many problems that went along with running on PPC
computers . . . .

F

**Comment by raveit65** [comment]
@esteelpaz 
No, i am not familiar with opensuse infrastructure. I am serching for a website link where i can see the build history of mate-menus in opensuse. Similar like this  from fedora.
https://src.fedoraproject.org/rpms/mate-menus/commits/master
I need to know what opensuse maintainer did with that package?

**Comment by raveit65** [comment]
I found this page, but the culprit version isn't listed (mate-menus-1.20.0-lp151.3.5.1.x86_64, from forum post)
https://packagehub.suse.com/packages/mate-menus/
Honestly, you need to contact open suse mate maintainer, we can't help you here when it is a packaging issue.
I call him again here.
@XRevan86 
Huston we have a problem...

**Comment by esteelpaz** [comment]
@raveit65:

I'll look over what you linked in a bit and see if I can make sense of it .
. . one of the admins on the OpenSUSE forums started a bugzilla bug report
on the problem, haven't seen any post on it in a couple days or more . . .
but, hopefully something is happening on it . . . .

Busy lately, but I'll check what I can, it might help???

F

**Comment by raveit65** [comment]
See https://build.opensuse.org/package/show/openSUSE:Leap:15.1:Update/mate-menus
Python2 support is dropped for mate-menus.
That means mate-panel, mate-screensaver and mate-menu needs to be updated with patches too.

**Comment by esteelpaz** [comment]
@raveit65:

I pasted your data here over in the bugzilla bug report . . . so far no replies on it . . . doesn't exactly seem like it is "fever pitch" on getting this issue straightened out???  But thanks for your time spent on it . . . hopefully that helps the opensuse devs get it tidied up???  I'll post back here if there are any "developments" . . . .

**Comment by raveit65** [comment]
Does the issue still exists?

**Comment by esteelpaz** [comment]
This was from 2019 . . . I'm up to Leap 15.5 . . . might have switched that to XFCE . . . but I have some Gecko MATE DE installs that the panel seems to be working fine.  

I'd say this was resolved.
