### ISSUE TITLE
Adding the launcher to the panel causes the opened web taskbar tab to be obscured by the icon

### ISSUE THREAD

**Issue by nanxiongchao** [mate-desktop/mate-panel#1012]
#### Expected behaviour
After adding the launcher to the panel, the tabs that have been opened in the mate-panel should remain visible.

#### Actual behaviour
After adding the launcher to the panel, the opened tab in the mate-panel is overwritten by the new icon. You cannot switch the window by clicking the tab with the mouse. You need to drag the window list bar to adjust it.

#### Steps to reproduce the behaviour
Open the application menu in mate-panel, select the system tool or other group, right click and select Add this launcher to panel

#### MATE general version
1.8.0

#### Package version
1.8.1-2

#### Linux Distribution
fedora21

**Comment by raveit65** [comment]
I am sorry to say fedora 21 has reached EOL since several years.
I can't send any update to fedora build system.
Please update to current releases f29, f30 or fedora next (f31).
And MATE-1.8.x has reached EOL too....

**Comment by nanxiongchao** [comment]
I also tested it in fedora29, the problem still exists.

Steps to reproduce the behaviour:
1. Open a tab window
2. Dragging the window list bar to the application launch tray and make sure to get close to it
3. adding the new launcher to the panel
4. You will find that the opened window disappears and needs to be manually dragged out to display again.

Package version:
1.20.3
Linux Distribution:
fedora29

**Comment by raveit65** [comment]
f29 use Mate 1.22. please update.
Mate 1.20 is EOL!
Btw. what is a opened tab window (1)?

**Comment by nanxiongchao** [comment]
Thank you for your guidance!
Unfortunately, my system environment here has no conditions to upgrade, even though I want to feedback to solve this problem.
Is it possible to verify this question according to my description with the help of others? I think it should be simple and intuitive to reproduce it.
The "opened tab window" I described earlier means a window that opens, such as firefox, caja, etc. This window will display a tab in the window list in the mate-panel.

**Comment by raveit65** [comment]
> Unfortunately, my system environment here has no conditions to upgrade......

Why upgrade?
`dnf update` should update MATE in your f29 installation.

**Comment by raveit65** [comment]
I don't have an installation with mate-1.20 or 1.8. So i am not able to reproduce it.
Any way, reopened.

**Comment by nanxiongchao** [comment]
It can only be tested in fedora29 or above. I think the problems I found in earlier versions also exist in the latest version, just that I have no environment to test.

**Comment by raveit65** [comment]
Why you can't update your f29 installation to MATE 1.22 with that command?
`dnf update`

**Comment by nanxiongchao** [comment]
My machine is a mips-based system, and fedora has no ready-made packages. 
Building a new mate environment requires a lot of work to do, but now it's just finding a bug and validation, using the existing environment to verify is the most efficient method.

**Comment by yetist** [comment]
@nanxiongchao 

I think the problem you reported is this, right?

![Peek 2019-09-10 19-59](https://user-images.githubusercontent.com/665058/64612240-eb5a4f00-d405-11e9-9a96-4a7b705b56aa.gif)

**Comment by nanxiongchao** [comment]
Yes!
You are right!

**Comment by nanxiongchao** [comment]
@raveit65 @yetist
Can anyone solve this problem?

**Comment by yetist** [comment]
I confirm that this issue exists in the master, I will fix it soon.

**Comment by nanxiongchao** [comment]
@yetist 
Thanks!
I tested it and the problem has been solved.
Is it a better solution: put the newly added launcher on the left side of the window list instead of increasing it to the right, which is more convenient for management and aesthetics.

**Comment by lukefromdc** [comment]
I just confirmed this issue, it's the window list buttons that get hidden. If there is no available space between the window list and the menu and other launchers to the left of it, than adding a launcher puts it in the panel to the right of the window list-but reduces the width of the window list to ZERO except for the drag handle. Drag the launcher out of the way and the window list expands back out. 

Also, the proposed fix works well, putting the new launcher to the LEFT of the window list and pushing the window list over by that amount of space. Good catch even if "opened web taskbar tab" was not easily understood by folks as "taskbar button"
