### ISSUE TITLE
stuck on the clock or weather applet when reaching it using keybord navigation , mate-panel 1.22.1

### ISSUE THREAD

**Issue by DidierSpaier** [mate-desktop/mate-panel#1020]
#### Expected behaviour
After having reached the top panel pressing Ctrl+Alt+Tab then the Clock or the Weather applet pressing the right or left arrow keys, we should be able to continue navigating on the panel with these keys. 

#### Actual behaviour
We are stuck on the Weather or Clock applet of which the drop down menu is opened as if we had pressed enter or the down key (keyboard trap). This is a regression from 1.18 

#### Steps to reproduce the behaviour
Pres Ctrl+Alt+Tab to focus the top panel, then move the cursor with the left of right arrow key until we reach one of the applets. After that the left and right arrow keys do not produce any effect.

#### MATE general version
1.22.1

#### Package version
1.22.1
#### Linux Distribution
Slint 14.2.1 as of 15 September 2019 (I am its maintainer and packager).
I observed same behavior on Mageia 7.1

#### Link to downstream report of your Distribution
http://slint.fr/pipermail/slint_slint.fr/2019-September/001035.html

This bug is very annoying for blind users using a screen reader, as they can't use a mouse.

Best,

Didier

PS maybe other applets have the same issue, I didn't check them all.

**Comment by DidierSpaier** [comment]
Confirmed by another user (Kyle), distribution ArchLinuxARM, same versions.

In his own words "I can't leave anything once I get on a panel. I get stuck there".

**Comment by alexarnaud** [comment]
@texou- Do you reproduce this issue?

Best regards.

**Comment by Texou-** [comment]
Hi,

It was fixed in 1.22.2 or in Debian (mate 1.22.1) (the patch was
backported).

Regards

Le 23/09/2019 à 09:52, Alex ARNAUD a écrit :

**Comment by DidierSpaier** [comment]
I confirm that this is fixed here (Slint64-14.2.1) upgrading mate-panel to 1.22.2

Best regards

**Comment by alexarnaud** [comment]
@DidierSpaier Could you please close this issue if it works as expected?

Best regards.
