### ISSUE TITLE
Mate panel crashed randomly while using or dragging windows

### ISSUE THREAD

**Issue by dmknght** [mate-desktop/mate-panel#1022]
#### Expected behaviour
Uhm no crash?

#### Actual behaviour
Mate panel crashed and disappeared. Here is the log in `.xsession-errors`
```
window 0x3a0000b specified for 0x3a00009 (Open File).
Window manager warning: Invalid WM_TRANSIENT_FOR window 0x3a0000b specified for 0x3a00015 (Load Optio).
Window manager warning: Invalid WM_TRANSIENT_FOR window 0x3a0000b specified for 0x3a0001f (Initial An).
Window manager warning: Invalid WM_TRANSIENT_FOR window 0x3a0000b specified for 0x3a00009 (Open File).
Window manager warning: Invalid WM_TRANSIENT_FOR window 0x3a0000b specified for 0x3a00015 (Load Optio).
Window manager warning: Invalid WM_TRANSIENT_FOR window 0x3a0000b specified for 0x3a0001f (Initial An).
Window manager warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) (child_setup specified)
```
#### Steps to reproduce the behaviour
Drag and drop windows and it crashes randomly.

#### MATE general version
MATE 1.22.1

#### Package version
```
Package: mate-desktop
Version: 1.22.1-1
Priority: optional
Section: x11
```

#### Linux Distribution
Parrot Security OS 4.7

### System spec
- 2 monitors 22 inc full HD
- Nvidia gtx 960

**Comment by lukefromdc** [comment]
Do you mean dragging windows on the desktop, or dragging and dropping the window list buttons (the rectangles windows can be minimized into or otherwise interacted from) within the panel?

**Comment by dmknght** [comment]
I meant dragging windows on the desktop. I think it relates the incorrect position while dragging that i created as well in mate-desktop or somewhere

**Comment by lukefromdc** [comment]
Dragging windows on the desktop should have no effect on the panel whatsoever. Are you using marco, compiz, or something else? It looks like the window manager is sending something odd to the tasklist and that is crashing the panel. Do you have wncklet built in-process or out? To tell, look in your installer package: if you have a file names libwnck-applet.so anywhere (mine is in /org/ayatana/NotificationItem/nm_applet) you have wncket (which includes the tray) built in-process, and crashing it will take down the whole panel. If you have a file names wnck-applet in something like /usr/libexec instead, you have the wncklet applet build out of process, and the applet should not take the rest of the panel down if it crashes or is crashed by a WM issue.

**Comment by dmknght** [comment]
I am seeing `Macro (adaptive compositor)` is enabled in mate tweak. I don't see the `libwnck-applet.so` anywere.

**Comment by lukefromdc** [comment]
Is Marco the same thing as compton? I've never heard of it before. 
OK, if you don't have libwnck-applet.so than you probably have wnck-applet and wncklet is built out-of-process. Thus, for the whole panel to crash is odd, though of course it is one window being managed by the window manager. 

I have never once seen an issue like this on my system and cannot duplicate it. Someone else on the team will probably have to help with this. You can help them by getting a backtrace from the crash. Here's how to get it:

1: make sure you have a terminal launcher on the desktop or several terminals running, so you can get to a terminal on your X11 session without using the panel. Make sure you have gdb installed, and install whatever package (a dbg package?) includes the debugging symbols for mate-panel, or simply install any local build you have with make install (which will include the debugging symbols by default)

2: from terminal run `mate-panel --replace` which will give you a panel instance that does not autospawn again when killed/stopped

3: run` killall mate-panel` to stop that panel running

4. Now run` gdb mate-panel` and when that comes up in terminal type `run` to start the panel. When the panel comes up, invoke the crash

5: gdb is still running, the panel is stopped but still "frozen" on the screen. In the terminal with gdb running, type` thread apply all bt full ` and then page through the resulting text until the end. Cut and paste it into a text file and post it here, after first looking it over to ensure nothing sensitive was captured.

6: you can then type `quit` in gdb's terminal and` mate-panel` to restart the panel normally. If you are getting a lot of crashes though you may have to start a new session

**Comment by dmknght** [comment]
I think the `macro` means system is using effect. However i don't think it is using compton because there is an other line `Macro (Compton GPU compositor)`. I'll do your debug steps as soon as possible because i am doing something else right now. I afraid this bug is hard to track because it happens randomly and not very often.
Do you think graphic driver causes this bug?

**Comment by lukefromdc** [comment]
The panel should not NORMALLY be affected by a GPU driver bug, but I have in fact seen a rendering issue caused by a driver bug in the past so I would not rule it out. 

I do have mate-tweak installed but not compton, only marco, metacity, compiz(used normally), and also both Cinnamon and gnome-shell(which are window managers among other things). Thus the WM options I get from mate-tweak are  Marco (no compositor), Marco (adaptive compositor), and Compiz(advanced GPU accelerated desktop effects).  

Thus, by "Macro" I am guessing you mean "Marco" and are misspelling it or something is mistranslating it. Thus, "adaptive compositor" is Marco's normal CPU compositor, should work without issue, and should only be affected by GPU bugs to the extent that the 2d accelerated path(which usually uses the 3d path internally these days) is affected by them.

If you can run compiz (either version) and your problem goes away, that confirms a bug in marco. Same if you have metacity or IceWM  installed (which will not be shown in mate-tweak but can be started with `metacity --replace` or` icewm --replace` and using either of them stops the crashes

**Comment by dmknght** [comment]
Sorry i am having no dump file right now but the mate panel just crashed 3 sec ago when i opened a file in archive file. I'll disable macro and see if it happens again

**Comment by raveit65** [comment]
Does the issue still exists?

**Comment by dmknght** [comment]
I haven't used mate for 4 years :) idk if it's still there.
