### ISSUE TITLE
Build, install failure with libxml2_2.9.4+dfsg1-7+b3 in Debian Unstable due to no longer provided .la file

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#1036]
#### Expected behaviour
Build finishes 

#### Actual behaviour
libclock-applet.lai cannot be build due to libxml2.la no longer being provided by the latest libxml2 and libxml2-dev, had to create an empty dummy file to sucessfully install, and had to run` make` twice to get past a "not a valid libtool archive" error prior to that. No doubt that got past the missing file, but did not build libclock-applet.lai. An install with the empty dummy file however behaved normally

The .la files are going away generally, libglib now can only be build with meson, I don't know if Debian's build ships .la files but I have to add them back manually or mate-panel won't build. A meson build of gtk3 also does not produce .la files, but an autotools build does. No idea if Debian is still shipping those but if so they are probably going away too. In general we need to remove all dependencies on .la files shipped by any package.

#### Steps to reproduce the behaviour
Update Debian Unstable to include libxml2_9.9.4+dsfg1-7+b3 and libxml2-dev_2.9.4+dfsg1-7+b3

Configure mate-panel with these options (behavior w others not tested)
`./autogen.sh  --with-in-process-applets=wncklet,clock,fish,notification-area --prefix=/usr libdir=/usr/lib/x86_64-linux-gnu --sysconfdir=/etc --enable-shared=yes --enable-static=no --disable-maintainer-mode --disable-schemas-compile
`
run `make -j` for a fast, parallel build, the build will fail with this error:

```
 CCLD     libclock-applet.la
/bin/sed: can't read /usr/lib/libxml2.la: No such file or directory
libtool:   error: '/usr/lib/libxml2.la' is not a valid libtool archive
```
run` make` and the build will now finish
run `make install` and the install will fail with
```
/usr/bin/install: cannot stat '.libs/libclock-applet.lai': No such file or directory
make[5]: *** [Makefile:767: install-clock_appletlibLTLIBRARIES] Error 1

create an empty file in applets/clock/.libs and name it libclock-applet.lai , the install will now finish and the clock will actually work

```

#### MATE general version
1.23 from git master

#### Package version
locally compiled from git master

#### Linux Distribution
Debian Unstable

#### Link to downstream report of your Distribution
None as this is a local build

**Comment by sc0w** [comment]
`libxml2_9.9.4+dsfg1-7+b3` ? I can't see that version in sid

**Comment by raveit65** [comment]
On fedora or any other rpm-based distro we remove the static libs (.a/.la) in generally during building the rpm package since years.
Eg. my spec file fro mate-panel:
```
find %{buildroot} -name '*.la' -exec rm -rf {} ';'
find %{buildroot} -name '*.a' -exec rm -rf {} ';'
```
https://src.fedoraproject.org/rpms/mate-panel/blob/master/f/mate-panel.spec#_113

I don't think that static libs are used for deb-based distros.
https://packages.debian.org/buster/amd64/mate-panel/filelist
See at debian-package repo, the .la files will be removed.
https://github.com/mate-desktop/debian-packages/blob/master/mate-panel/debian/rules#L15
And their configure flags:
```
dh_auto_configure $(DHFLAGS) -- \
		--disable-silent-rules \
		--localstatedir=/var \
		--libexecdir=/usr/lib/mate-panel \
		--disable-static \
		--enable-introspection \
		--enable-gtk-doc
```
https://github.com/mate-desktop/debian-packages/blob/master/mate-panel/debian/rules#L25

**Comment by lukefromdc** [comment]
> `libxml2_9.9.4+dsfg1-7+b3` ? I can't see that version in sid

Oh yeah: Correct version is libxml2_2.9.4+dfsg1-7+b3

**Comment by cwendling** [comment]
disclaimer: I didn't actually try this.  But generally, these .la issue only exist if the file is referenced explicitly, which should mean that one of the package on the system (or the package being built) was build with libtool against a libxml2 version that *did* provide that .la file.  Rebuilding it all should fix it.  Note that this might require cleaning a log in the builddirs, not merely running a `make` on top of an already configured builddir.

**Comment by lukefromdc** [comment]
I found not long ago that any attempt to build mate-panel against an install of glib or gtk3 that did not provide .la files always failed (again in the applets) even with mate-desktop built with meson and not providing such files itself and mate-panel build with --disable-static (which stops .a file generation)

**Comment by raveit65** [comment]
@lukefromdc 
Still an issue?

**Comment by lukefromdc** [comment]
Not having any trouble with this with current libxml, so this could simply mean that will all underlying packages built without that .la file existing it is no longer used. It's not on my system (though a 2.8mb .a file is included in Debian's libxml2-dev package).

All my GTK3 builds have included these files (made by hand) but that's another deal and I haven't tried building without them anytime recently
