### ISSUE TITLE
High heap memory usage

### ISSUE THREAD

**Issue by somakd** [mate-desktop/mate-panel#1044]
#### Expected behaviour
RAM usage should stay more less constant.

#### Actual behaviour
Initial RAM usage at around 60MB. Within a day, RAM usage increases to 2GB. Current screenshot produced when mate-panel was using 440MB.
![Screenshot at 2019-12-06 08-43-48](https://user-images.githubusercontent.com/8738603/70331229-ad9e7400-1804-11ea-8327-23d52656ef5b.png)

#### Steps to reproduce the behaviour
Normal continuous use for a day.

#### MATE general version
1.22.2

#### Package version
1.22.2-1

#### Linux Distribution
Linux 5.3.12-1-MANJARO #1 SMP PREEMPT Thu Nov 21 10:55:53 UTC 2019 x86_64 GNU/Linux

**Comment by somakd** [comment]
Upon running 
`mate-panel --replace &`
the memory usage drops back to normal.
![Screenshot at 2019-12-06 08-54-13](https://user-images.githubusercontent.com/8738603/70331788-d6733900-1805-11ea-843a-c1a098dca1ec.png)

**Comment by lukefromdc** [comment]
We have similar prior reports
https://github.com/mate-desktop/mate-panel/issues/809 for applets built in-process 
https://github.com/mate-desktop/mate-panel/issues/738 another high RAM use report
and even 
https://github.com/mate-desktop/mate-panel/issues/115
from all the way back in 2013 (so this is an old problem, possibly
inherited from gnome-panel 2.32 or earlier

Unfortunately there is so much complexity and enough memory leaks in the panel  to make Valgrind (useful for finding memory leaks) hard to use. It slows the panel to a near stop and when I got it to work I could never get a full set of results and was "spammed" with so much text. In additon, anything out of process claims the memory use for itself, while in-process it is mate-panel RAM usage

**Comment by somakd** [comment]
Gotcha. Thanks.
So I've added a kronjob for running `mate-panel --replace > /dev/null 2>&1` every 30 minutes. A dirty solution to a nasty problem.

**Comment by rcaridade145** [comment]
What applets have you got in the panel? @lukefromdc there is a report concerning the clock applet and timezones from gnome panel https://bugzilla.gnome.org/show_bug.cgi?id=688967

**Comment by raveit65** [comment]
Does the issue still exists with current master or >= mate-panel-1.24.1 ?

**Comment by somakd** [comment]
Don't know. I moved to Openbox the very next day.

**Comment by raveit65** [comment]
Bye Bye
