### ISSUE TITLE
Is it possible to reliably detect the current color of the top bar panel?

### ISSUE THREAD

**Issue by jerblack** [mate-desktop/mate-panel#1045]
I have an app I wrote in Go that runs in the system tray on Windows, OSX, and Linux, and I'm trying to ensure that my icon is always easily visible, which means detecting if a dark theme is enabled and putting up a black icon if the panel is light and a white icon if the panel is dark. I've figured out deterministic ways to accomplish this with Windows, OSX, Ubuntu, and Kubuntu so far, but there doesn't appear to be a single file or dconf setting I can look at in Mate to get that kind of information.   

I found that if the user sets their panel color to a solid color, it shows up in `/org/mate/panel/toplevels/top/background/color`.
But if they choose a default theme or install a custom one, it looks like the color could come from some combination of gtk2, gtk3, and metacity themes, and I'm not clear which setting in each the panel color is coming from. 
Is there a method I am missing that would allow me to programmatically lookup the actual color of the current panel that the indicator applet is embedded in? Failing that, which setting in the theme files is the panel color pulling from, and is there an order of precedence?

**Comment by lukefromdc** [comment]
One way would be to use a symbolic icon, and set the color for it to be
the same color as the text on the panel. A theme forcing regular icons
would override that, but could be overriden in turn with a cssprovider
for the applet. 

To avoid any issues with tray widgets (popup menus are an example) not
inheriting from the panel, you could have your cssprovider fetch the color
used by panel text directly. Not at my desktop now do details of.that have
to wait.
