### ISSUE TITLE
autohidden panel leaves 1 pixel unusable - possible privacy issue

### ISSUE THREAD

**Issue by Loader009** [mate-desktop/mate-panel#1048]
#### Expected behaviour
I expected an autohidden panel to use 0 pixel, to be merely an overlay on any other window layer.
Thus, on a 1920x1200 screen, it should've let us use the complete range of 1920 pixels in width or 1200 pixels in height.

#### Actual behaviour
In practice the autohidden panel uses 1 pixel, letting us use at most 1920 minus 1 pixel in width or 1200 minus 1 pixel (per autohidden panel) in height.
This leads to a privacy issue, related to browsers, which reports the window-size and trackers (which are anywhere) use this to track users even without cookies etc. (of course only true whenever javascript is allowed).
It also affects other programs, resulting in using a (slightly) lower resolution with maximized windows.

#### Steps to reproduce the behaviour
Create a panel and let it autohide.

#### MATE general version
1.22.2

#### Package version
Version: 1.22.2-1
Maintainer: Debian+Ubuntu MATE Packaging Team <debian-mate@lists.debian.org>

#### Linux Distribution
ParrotOS (parrotlinux.org)
security focused rolling release distribution, based on debian
```
$uname -a
Linux parrot 5.3.0-3parrot3-amd64 #1 SMP Parrot 5.3.9-3parrot3 (2019-11-23) x86_64 GNU/Linux
```

**Comment by Loader009** [comment]
I'll close this in about a month if there is no reaction to this.
I dislike to have open issues in my overview.

A "wontfix" is enough for me, I am not going to discuss a decision.

**Comment by lukefromdc** [comment]
Any browser that allows you to be tracked by your monitor size (and MATE is a common desktop so non-unique) is a bigger privacy problem than this, tracking system fonts and so much more. If you want any semblence of privacy at all, with or without this issue, you absolutely must block the trackers and adservers, all sites and all of the time with no whitelisted sites. Setting all the privacy options in modern Firefox, then installing NoScript is a good start. 

Blocking "interest-based ads" is an absolute must, if you don't do this you will be followed all over the net by the same ads (and malware installers targetting Windows), and more and more marketers will get nearly your entire surfing history.

**Comment by Loader009** [comment]
@lukefromdc yesm that's right and I use a few privacy extensions (uMatrix instead of NoScript since uMatrix has more features for blocking).
But at the end I think that I will need to rethink my privacy strategy and use statistics with browser sizes, to determine the most used size. That's also the reason that I will close this issue, I forgot it last time.

Btw. I use top and bottom panels, most people use bottom only. I also noted the typical windows 10 browser-window size once, but this is not doable on my configuration. (Can't find it right now.)
