### ISSUE TITLE
applets are not read by Orca screenreader when focused for the first time

### ISSUE THREAD

**Issue by vojtapolasek** [mate-desktop/mate-panel#1052]
This behaviour is very ocnfusing especially for new users.

#### Expected behaviour

After focusing the panel and using the "tab" key to cycle through all applets for the first time after logging in, Orca should read their names / content.

#### Actual behaviour

While cycling through applets for the first time, nothing is announced. When you cycle for the secound round, it starts working. It also partially works if you use shift+tab to cycle backwards but only sporadically.

#### Steps to reproduce the behaviour

1. Log in to a Mate session
2. Start the Orca screenreader
3. Fosuc the panel, for example with ctrl+alt+tab
4. Press tab. Notice that icons in the notification area (for example Nextcloud sync client) get announced. But other icons get focused but nothing is read.
5. continue switching applets til you get back to the first one.
6. Continue switching applets. Now they are announced.

#### MATE general version

1.22.2

#### Package version

1.22.2-1

#### Linux Distribution

Arch Linux

**Comment by tyrylu** [comment]
Same behavior with Mate 1.24 on Fedora 32.

**Comment by mhussaincov** [comment]
hmmm?
you must have a incorrect setting,
make sure that in preferences assistive technology is enabled, and you
then log out and back in to your user session,
it would be helpful if you were to tell us the folowing,
what distribution you are running?

what version of this desktop enviroment has this issue happened with?
what version of the orca screen reader you on?
and lastly have you tryed
mate-panel --replace?
doo answer back.

On 12/03/2020, Lukáš Tyrychtr <notifications@github.com> wrote:
> Same behavior with Mate 1.24 on Fedora 32.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mate-desktop/mate-panel/issues/1052#issuecomment-598233414


-- 
kind regards,
Majid Hussain

**Comment by mhussaincov** [comment]
hey there last poster,
you running the mate spin of fedora mate?
or did you install mate ontop of another desktop?


On 12/03/2020, Majid Hussain <mhussaincov93@gmail.com> wrote:
> hmmm?
> you must have a incorrect setting,
> make sure that in preferences assistive technology is enabled, and you
> then log out and back in to your user session,
> it would be helpful if you were to tell us the folowing,
> what distribution you are running?
>
> what version of this desktop enviroment has this issue happened with?
> what version of the orca screen reader you on?
> and lastly have you tryed
> mate-panel --replace?
> doo answer back.
>
> On 12/03/2020, Lukáš Tyrychtr <notifications@github.com> wrote:
>> Same behavior with Mate 1.24 on Fedora 32.
>>
>> --
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/mate-desktop/mate-panel/issues/1052#issuecomment-598233414
>
>
> --
> kind regards,
> Majid Hussain
>


-- 
kind regards,
Majid Hussain

**Comment by tyrylu** [comment]
First, it was a F 32 workstation with Mate installed afterwards with orca 3.35.92. Accessibility support and such was turned on, and no, i did not forget to relogin after the update...

**Comment by vojtapolasek** [comment]
Hi, for me it unfortunately still persists. mate-desktop version 1.24, Arch Linux. Accessibility is turned on in settings. If you need more info I will be glad to provide it. I would really like to get this working but I don't know how to help you.

**Comment by vojtapolasek** [comment]
Hello, the issue still persists, unfortunately it seems that it appears also in Fedora 32 and further. Please could we arrange some testing? How can I help you to reproduce the issue?

**Comment by raveit65** [comment]
Does the issue still exists?

**Comment by tyrylu** [comment]
I can't reproduce it under Fedora 38, but I'd like at least a second confirmation from someone else.

**Comment by vojtapolasek** [comment]
I can't reproduce it anymore under F38 and Arch Linux. However, I found out that for example the battery applet is not read. I will open extra issue for that.
