### ISSUE TITLE
Unable to add Application Launchers to the MATE Panel

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/mate-panel#1055]
#### Expected behaviour

It should be possible to add Application launchers to the MATE Panel via right-click Add to Panel.

#### Actual behaviour

It is not possible to add any Application launchers to the MATE Panel via Add to Panel.

#### Steps to reproduce the behaviour

Right-click MATE Panel, click Add to Panel..., select Application Launcher and click add. All the applications are insensitive.

![gray-add-to-panel-item](https://user-images.githubusercontent.com/304639/74740822-85df7980-5253-11ea-8fc5-2d80f11c9358.png)

#### MATE general version

1.24.0

#### Package version

mate-panel 1.24.0-1

#### Linux Distribution

  * Ubuntu Focal (20.40)
  * Debian Sid
  * Majaro
  * Fedora 31

#### Link to downstream report of your Distribution

  * https://bugs.launchpad.net/bugs/1863435

**Comment by flexiondotorg** [comment]
@monsta reports that this apparently stopped working following this commit:

  * https://github.com/mate-desktop/mate-panel/commit/d6f085fe853cedcf612c0b4a8b3a40585414dfa4

@wmww Any ideas?

**Comment by wmww** [comment]
Somewhere, the enabled variable isn't getting set or patched through to where it needs to be, and is defaulting to false. I'll take a look later today if no one has fixed it by then. please update here or tag me in #mate-dev if there are updates.

**Comment by lukefromdc** [comment]
I have not had this problem, have been able with an existing install to freely add and remove panel applets. Maybe this is only new installs (no previous configuration), or is it distro-specific?

**Comment by monsta** [comment]
It affected only the app launchers, not the applets. Now it's fixed via #1056.
