### ISSUE TITLE
Notification Area applet lacks usable right-click panel-move

### ISSUE THREAD

**Issue by imcdgh** [mate-desktop/mate-panel#1070]
#### Expected behaviour
Right-click in Notification Area (panel applet) should activate panel-menu with "move" etc.

#### Actual behaviour
Each sub-applet of Notification Area (eg, blueman, ..., power-manager) has its own binding
for right-click.

#### Steps to reproduce the behaviour
Right-click on a sub-applet of the  Notification Area applet, eg power-manager, see
there is no way to "move" (slide) the whole Notification Area applet along the panel.
If you're lucky, you can click between the sub-applets and find an area which is bound
to the  Notification Area apple, and activate the panel-menu with "move" etc.

Suggestion, Give the Notification Area shell applet a visible "handle" of its own (like a visible separator).

#### MATE general version
1.16.2

#### Linux Distribution
Debian 10.

**Comment by lukefromdc** [comment]
The notification area does indeed have a clickable "handle" to its
left, same as the window list applet provided by wncklet. By default
(and in the MATE themes as well as themes like Adwaita with no MATE
support at all) three dots in a vertical row identify the handle. If
your theme removes the dots and does not set another contrasting
appearance for the handle, that is a significant usability issue with
that them.

**Comment by imcdgh** [comment]
Thanks, you are right: switching to different Theme  _sometimes_ reveals
the "handle" to the left -- three small stacked squares.
I'd request that the (Notification Area) "handle" contrast be enhanced significantly.
And/or open this issue against many of the "standard" Themes as they are incompatible with
applet color pallets design.

**Comment by imcdgh** [comment]
Okay, played with it some more.  Perhaps its an issue with the Mate Panel...
If you change  Mate Panel properties to use "Solid color" (so not "None", not "Background image"),
then you get issues with the (Notification Area) "handle" visibility -- it becomes invisible.
