### ISSUE TITLE
Icon woes: notification area disappearing icons, indicator applet

### ISSUE THREAD

**Issue by fpoto** [mate-desktop/mate-panel#1078]
#### Expected behaviour
One week ago I install a Debian testing system with Mate desktop. The bluetooth and volume icons are there, in the notification area, all is well. A printing icon appears while printing.

#### Actual behaviour
Three days ago the volume icon disappears. Maybe I touched it with the mouse by mistake, anyway I could not get it back. After trying to find info on the net, I give up and add the volume applet to the panel, which does the same job. It is less tidy than having it in the notification area, but it works.

Yesterday, after a reboot, the volume icon reappears. I don't reboot this box often, it is meant to be always on. So I remove the volume applet. So far so good (more or less). Today, the Bluetooth icon has disappeared. I kill mate-panel, but it restarts without change: still no Bluetooth icon. However, the volume icon is still there.

Next, I open the Bluetooth manager, and among the menu entries I fond a Plugin one. Apparently these are plugins of blueman. The first plugin is AppIndicator. If I disable it, the Bluetooth icon reappears in the notification area. This is reproducible at will.

So, first question: is there a configuration tool or file for the notification area?

Second question: what is the relationship between notification area and indicator applet?

#### MATE general version
1.24.0

#### Linux Distribution
Debian 10 (bullseye, current testing)

**Comment by rbuj** [comment]
You can use `mate-session-properties` to check/set  which applications are started at login.

![startup](https://user-images.githubusercontent.com/10171411/81176422-6d0a7880-8fa5-11ea-9128-b6cbdf395850.png)

**Comment by fpoto** [comment]
Thank you.  Three things follow.

First, I'll try to interpret your answer: are you saying that all applications started from mate-session have their icon shown in the notification area? If yes, that would answer my first question, but it is not clear to me that this is the case, can you please confirm and possibly elaborate?

Second, more in general, it would be useful to know what to do about icons mysteriously disappearing at random times, as described in my report, and that can not be recovered even by restarting mate-panel. It is not a real bug report, as I cannot reproduce it, but it happened to me more than once, and I can read that I am not the only one. It would be useful to have some instructions on how to check, debug and work around this kind of situations.

Third, my last question in the original post remains unanswered: what is the relationship between notification area and indicator applet?

Thank you for working on Mate
