### ISSUE TITLE
Clock applet crashing while setting up

### ISSUE THREAD

**Issue by artheduin** [mate-desktop/mate-panel#1094]
Date / time panel crashes after displaying seconds and setting location (for weather).

===================================================================
 Info                                                              
===================================================================
           PID: 1336 (clock-applet)
           UID: 1000 (artheduin)
           GID: 1000 (artheduin)
        Signal: 11 (SEGV)
     Timestamp: Fri 2020-06-19 15:24:37 CEST (2h 12min ago)
  Command Line: /usr/lib/mate-panel/clock-applet
    Executable: /usr/lib/mate-panel/clock-applet
 Control Group: /user.slice/user-1000.slice/user@1000.service/dbus.service
          Unit: user@1000.service
     User Unit: dbus.service
         Slice: user-1000.slice
     Owner UID: 1000 (artheduin)
       Boot ID: d3ff815eb80c49d79b9c316048fc5534
    Machine ID: c5757a64a19b4655bc899ddf43008524
      Hostname: nemesis
       Storage: /var/lib/systemd/coredump/core.clock-applet.1000.d3ff815eb80c49d79b9c316048fc5534.1336.1592573077000000000000.lz4
       Message: Process 1336 (clock-applet) of user 1000 dumped core.
                
                Stack trace of thread 1336:
                #0  0x00007fd68db78671 g_type_check_instance_is_fundamentally_a (libgobject-2.0.so.0 + 0x3c671)
                #1  0x00007fd68db55942 g_object_ref (libgobject-2.0.so.0 + 0x19942)
                #2  0x00007fd68e3db5de n/a (libgtk-3.so.0 + 0x3935de)
                #3  0x00007fd68db50a56 n/a (libgobject-2.0.so.0 + 0x14a56)
                #4  0x00007fd68db6fb28 g_signal_emit_valist (libgobject-2.0.so.0 + 0x33b28)
                #5  0x00007fd68db700d3 g_signal_emit (libgobject-2.0.so.0 + 0x340d3)
                #6  0x00007fd68df89ea7 n/a (libgdk-3.so.0 + 0x46ea7)
                #7  0x00007fd68df73f4d n/a (libgdk-3.so.0 + 0x30f4d)
                #8  0x00007fd68da65a28 n/a (libglib-2.0.so.0 + 0x52a28)
                #9  0x00007fd68da64e8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #10 0x00007fd68da65240 n/a (libglib-2.0.so.0 + 0x52240)
                #11 0x00007fd68da65533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #12 0x00007fd68e29630d gtk_main (libgtk-3.so.0 + 0x24e30d)
                #13 0x00007fd68ec6a3b8 n/a (libmate-panel-applet-4.so.1 + 0xa3b8)
                #14 0x0000560331eade16 n/a (clock-applet + 0xde16)
                #15 0x00007fd68d6f70b3 __libc_start_main (libc.so.6 + 0x270b3)
                #16 0x0000560331eade7e n/a (clock-applet + 0xde7e)
                
                Stack trace of thread 39981:
                #0  0x00007fd68da2fda4 n/a (libglib-2.0.so.0 + 0x1cda4)
                #1  0x00007fd68db4ff09 g_closure_unref (libgobject-2.0.so.0 + 0x13f09)
                #2  0x00007fd68db628ed n/a (libgobject-2.0.so.0 + 0x268ed)
                #3  0x00007fd68db6e1ab g_signal_handlers_disconnect_matched (libgobject-2.0.so.0 + 0x321ab)
                #4  0x00007fd68dc51ba8 n/a (libgio-2.0.so.0 + 0xb5ba8)
                #5  0x00007fd68dc51c6a n/a (libgio-2.0.so.0 + 0xb5c6a)
                #6  0x00007fd68da8f1d4 n/a (libglib-2.0.so.0 + 0x7c1d4)
                #7  0x00007fd68da8e931 n/a (libglib-2.0.so.0 + 0x7b931)
                #8  0x00007fd68d37e609 start_thread (libpthread.so.0 + 0x9609)
                #9  0x00007fd68d7f2103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1369:
                #0  0x00007fd68d7e596f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007fd68da651ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fd68da652e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007fd68da65331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007fd68da8e931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fd68d37e609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fd68d7f2103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1385:
                #0  0x00007fd68d7e596f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007fd68da651ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fd68da65533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007fd68dcbae9a n/a (libgio-2.0.so.0 + 0x11ee9a)
                #4  0x00007fd68da8e931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fd68d37e609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fd68d7f2103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1484:
                #0  0x00007fd68d7e596f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007fd68da651ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fd68da652e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007fd68836e99d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007fd68da8e931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fd68d37e609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fd68d7f2103 __clone (libc.so.6 + 0x122103)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1336]
[New LWP 39981]
[New LWP 1369]
[New LWP 1385]
[New LWP 1484]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/mate-panel/clock-applet'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd68db78671 in g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
[Current thread is 1 (Thread 0x7fd68a281c00 (LWP 1336))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1336]
[New LWP 39981]
[New LWP 1369]
[New LWP 1385]
[New LWP 1484]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/mate-panel/clock-applet'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd68db78671 in g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
[Current thread is 1 (Thread 0x7fd68a281c00 (LWP 1336))]
#0  0x00007fd68db78671 in g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007fd68db55942 in g_object_ref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007fd68e3db5de in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007fd68db50a56 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007fd68db6fb28 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007fd68db700d3 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007fd68df89ea7 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007fd68df73f4d in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#8  0x00007fd68da65a28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007fd68da64e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007fd68da65240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fd68da65533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007fd68e29630d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007fd68ec6a3b8 in ?? () from /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
#14 0x0000560331eade16 in ?? ()
#15 0x00007fd68d6f70b3 in __libc_start_main (main=0x560331eadcf0, argc=1, argv=0x7ffdce019958, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdce019948) at ../csu/libc-start.c:308
#16 0x0000560331eade7e in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1336]
[New LWP 39981]
[New LWP 1369]
[New LWP 1385]
[New LWP 1484]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/mate-panel/clock-applet'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd68db78671 in g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
[Current thread is 1 (Thread 0x7fd68a281c00 (LWP 1336))]

Thread 5 (Thread 0x7fd67bfff700 (LWP 1484)):
#0  0x00007fd68d7e596f in __GI___poll (fds=0x560333f69800, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd68da651ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd68da652e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd68836e99d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007fd68da8e931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd68d37e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140559180101376, -203238727028865295, 140728059660766, 140728059660767, 140728059660912, 140559180098304, 180430457439487729, 180400289779910385}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fd68d7f2103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7fd688c12700 (LWP 1385)):
#0  0x00007fd68d7e596f in __GI___poll (fds=0x7fd67c00ff90, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd68da651ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd68da65533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd68dcbae9a in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007fd68da8e931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd68d37e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140559394088704, -203238727028865295, 140559402477518, 140559402477519, 140559402477664, 140559394085632, 180393533068773105, 180400289779910385}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fd68d7f2103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7fd689c34700 (LWP 1369)):
#0  0x00007fd68d7e596f in __GI___poll (fds=0x560333eea520, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd68da651ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd68da652e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd68da65331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fd68da8e931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd68d37e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140559411005184, -203238727028865295, 140728059663246, 140728059663247, 140728059663392, 140559411002112, 180391315791906545, 180400289779910385}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fd68d7f2103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7fd689413700 (LWP 39981)):
#0  0x00007fd68da2fda4 in free@plt () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#1  0x00007fd68db4ff09 in g_closure_unref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#2  0x00007fd68db628ed in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#3  0x00007fd68db6e1ab in g_signal_handlers_disconnect_matched () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#4  0x00007fd68dc51ba8 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#5  0x00007fd68dc51c6a in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#6  0x00007fd68da8f1d4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007fd68da8e931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007fd68d37e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140559402481408, -203238727028865295, 140728059663070, 140728059663071, 140728059663216, 140559402478336, 180392431946532593, 180400289779910385}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#9  0x00007fd68d7f2103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7fd68a281c00 (LWP 1336)):
#0  0x00007fd68db78671 in g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#1  0x00007fd68db55942 in g_object_ref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#2  0x00007fd68e3db5de in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#3  0x00007fd68db50a56 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#4  0x00007fd68db6fb28 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#5  0x00007fd68db700d3 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#6  0x00007fd68df89ea7 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#7  0x00007fd68df73f4d in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#8  0x00007fd68da65a28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#9  0x00007fd68da64e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007fd68da65240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#11 0x00007fd68da65533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#12 0x00007fd68e29630d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#13 0x00007fd68ec6a3b8 in ?? () from /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
No symbol table info available.
#14 0x0000560331eade16 in ?? ()
No symbol table info available.
#15 0x00007fd68d6f70b3 in __libc_start_main (main=0x560331eadcf0, argc=1, argv=0x7ffdce019958, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdce019948) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94571722427376, -203238727028865295, 94571722366544, 140728059664720, 0, 0, 204473391832860401, 180400904637875953}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffdce019958}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#16 0x0000560331eade7e in ?? ()
No symbol table info available.
#0  0x00007fd68db78671 in g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007fd68db55942 in g_object_ref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007fd68e3db5de in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007fd68db50a56 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007fd68db6fb28 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007fd68db700d3 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007fd68df89ea7 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007fd68df73f4d in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#8  0x00007fd68da65a28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007fd68da64e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007fd68da65240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fd68da65533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007fd68e29630d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007fd68ec6a3b8 in ?? () from /usr/lib/x86_64-linux-gnu/libmate-panel-applet-4.so.1
#14 0x0000560331eade16 in ?? ()
#15 0x00007fd68d6f70b3 in __libc_start_main (main=0x560331eadcf0, argc=1, argv=0x7ffdce019958, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdce019948) at ../csu/libc-start.c:308
#16 0x0000560331eade7e in ?? ()

**Comment by raveit65** [comment]
Already fixed!
https://github.com/mate-desktop/libmateweather/commit/50aec09eae07b0c43c10d3212a5c0e0590db57b0
Please do not ignore our template!
