### ISSUE TITLE
Taskbar Icon Missing on Some Applications (MATE 1.6.0)

### ISSUE THREAD

**Issue by OatAndAbout** [mate-desktop/mate-panel#110]
The taskbar icons for the following (but not necessarily limited to) applications are missing:

brutalchess
dconf-editor
driconf
gnome-disks
google-earth
gtk-recordmydesktop
kazam
ltris
mate-calc
pinta

This problem also occurs in Debian, so it isn’t a Linux Mint-related issue. This problem was non-existent in previous releases. 

In the screenshot I have provided an example of four applications with working icons, and the four with missing icons.

![screenshot](https://f.cloud.github.com/assets/4564001/581769/898e1772-c8a7-11e2-9588-d9071cfe1a63.jpg)

**Comment by clort81** [comment]
Many linux programs don't provide icons.  

Which is why I don't use a DE that requires icons.

**Comment by lukefromdc** [comment]
1.6.0 is VERY old, though not sure if later changes such as the GTK 3 transition replaced "no icon" with "icon missing" GTK default icon given I am not at my desktop right now. That of course would probably be  worse than no icon, and the "spring" default launcher icon would not be appropriate for a window list icon.

At any rate, it's up to applications to ship an icon or not.
