### ISSUE TITLE
Closing last window with middle button leaves floating preview

### ISSUE THREAD

**Issue by viliaapro** [mate-desktop/mate-panel#1110]
#### Expected behaviour
Closing the last toplevel application window with the middle button should also close its preview window.

#### Actual behaviour
On the window list, when closing all windows with the middle mouse button, the last one's preview remains floating on screen until a new toplevel window is created and the window list's state is refreshed.

#### Steps to reproduce the behaviour
Close all windows from the window list with the middle button.

#### MATE general version
1.24

#### Package version
Package: mate-panel
Version: 1.24.0-2
Priority: optional
Section: universe/x11
Origin: Ubuntu

#### Linux Distribution
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian+Ubuntu MATE Packaging Team <debian-mate@lists.debian.org>

#### Link to downstream report of your Distribution
Bugs: https://bugs.launchpad.net/ubuntu/+filebug

**Comment by JohnVeness** [comment]
This also happens if you close windows using the keyboard, e.g. Ctrl+W, Ctrl+Q, or Alt+F4, while the preview thumbnail is showing.

**Comment by raveit65** [comment]
@vkareh ^^^^

Guys, try out https://github.com/mate-desktop/mate-panel/commit/df52ad594791bbc38237e373ba42556bb1c20306
or mate-panel-1.24.1

**Comment by Porrumentzio** [comment]
How could we try out that commit? I'll have to wait since the package is updated, but it's great to know that it's fixed :)

**Comment by lukefromdc** [comment]
One way to try out anything that has been merged to master is to build from source. I have all of MATE built that way and packed into one binary package per source package .debs, but you could install mate-common and the -dev packages for mate-desktop, mate-menus, and libmateweather and then build mate-panel locally using
```
autogen.sh
make
make install
```
to install it to /usr/local, then remove it to use your normal install with 
`make uninstall`

**Comment by viliaapro** [comment]
> [df52ad5](https://github.com/mate-desktop/mate-panel/commit/df52ad594791bbc38237e373ba42556bb1c20306)

The fix above shouldn't affect our issue here, as it's in the `applet_enter_notify_event` function, which shall be run whenever the window list gains focus; see [line 716](https://github.com/mate-desktop/mate-panel/blob/df52ad594791bbc38237e373ba42556bb1c20306/applets/wncklet/window-list.c#L716)

To properly address the issue at hand, I think the preview thumbnail should be destroyed whenever a window on the list is closed, or whenever the window list changes state however that may be; the exact desired semantics might not be clear.

The UI element closest in behavior to the preview thumbnail may be the tooltip. I notice now that GTK tooltips show a similar floating glitch when changing workspaces in MATE. Ultimately the Right Thing might be to meditate on the true essence of tooltips and see if the preview thumbnail could be implemented as a subclass of tooltip.

**Comment by viliaapro** [comment]
I'll close the issue again, as the fix seems like a decent solution
