### ISSUE TITLE
wnck-applet: constantly increasing memory consumption and crash

### ISSUE THREAD

**Issue by Experimenter** [mate-desktop/mate-panel#1120]
#### Expected behaviour
Should work with little or no increase in memory consumption and work without crashing

#### Actual behaviour
Mate edition: wnck-applet constantly increases in memory consumption going from 30 MB to over 100 MB and then crashes asking to reload the windows switcher, workspace switcher & show desktop.

#### Steps to reproduce the behaviour
Working over a long period of time (6-8 hrs) the problem presents without any user intervention

#### MATE general version
MATE 1.24.0

#### Linux Distribution
Linux Mint 20 & Manjaro

#### Link to downstream report of your Distribution

https://forums.linuxmint.com/viewtopic.php?f=47&t=324867&p=1846449&hilit=wnck#p1846449

https://forum.manjaro.org/t/mate-mate-panel-continuously-increasing-memory-consumption/155289

**Comment by mixmastamyk** [comment]
Ubuntu Mate 20.04.

wnck-applet uses up to 1GB !!! memory if I don't notice for a week.  I have to kill it and tell the panel to reload it about that often.

**Comment by raveit65** [comment]
Guys, all that is fixed with mate-panel-1.24.1. Your distro needs updating!
File out a report there asked for an update.

**Comment by mixmastamyk** [comment]
I moved up to Ubuntu 21.04.  Still a big problem here!

```
⏵ ps -e --sort rss -o rss,comm | grep wnck
693352 wnck-applet

# in megabytes:
677M  wnck-applet

⏵ dpkg-query --search /usr/lib/mate-panel/wnck-applet
mate-panel: /usr/lib/mate-panel/wnck-applet

⏵ apt-cache policy mate-panel
mate-panel:
  Installed: 1.24.2-0ubuntu1
  Candidate: 1.24.2-0ubuntu1
  Version table:
 *** 1.24.2-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
        100 /var/lib/dpkg/status
```

It also takes up a lot of shared memory so it and Xorg take up a gigabyte plus together.

**Comment by dedeibel** [comment]
Can confirm. Debian stable.

```
➜  ~ apt show mate-panel
Package: mate-panel
Version: 1.24.1-1
```

After start:

```
ps -e --sort rss -o rss,comm | grep wnck
27724 wnck-applet
```

After eight hours:

```
➜  ~ ps -e --sort rss -o rss,comm | grep wnck
135984 wnck-applet

➜  ~ uptime
 08:55:55 up 51 min,  1 user,  load average: 0,15, 0,37, 0,51
```
