### ISSUE TITLE
Window thumbnails sometimes show really glichy preview + 3 errors

### ISSUE THREAD

**Issue by Lagetta** [mate-desktop/mate-panel#1127]
#### Expected behaviour
Show a window thumbnail preview of a window when I point my cursor on the opened application.

#### Actual behaviour
As an example, I used Telegram. However it does happen with every application if I can recall it.
![Screenshot at 2020-08-04 15-44-26](https://user-images.githubusercontent.com/53313579/89296029-7f5e8600-d66a-11ea-9064-ca329b2b34cc.png)
![Screenshot at 2020-08-04 15-44-48](https://user-images.githubusercontent.com/53313579/89296031-808fb300-d66a-11ea-8f46-b3f56f263201.png)
![Screenshot at 2020-08-04 15-45-00](https://user-images.githubusercontent.com/53313579/89296033-81284980-d66a-11ea-854c-ff7a87df2fa1.png)

#### Steps to reproduce the behaviour
It happens always just by opening few tabs and switching to minimise window and stuff. I noticed that it does often happen on Firefox, MATE-Terminal, Konversation and Telegram.

#### MATE general version
1.24.0

#### Linux Distribution
Fedora 32

Sorry, I do not know how to fill other bars. And sorry if I repeat the same issue. I don't seem to find similar issue.

As I am writing this, I also encountered this error. I left the window list preference window open and put my mouse on the panel few times. Three errors at the same time.
![Screenshot at 2020-08-04 15-57-03](https://user-images.githubusercontent.com/53313579/89296741-70c49e80-d66b-11ea-8e16-54d3a76bb67b.png)

**Comment by raveit65** [comment]
@vkareh 
ping

**Comment by raveit65** [comment]
@Lagetta 
Are you able to test the pull request?
It fixes the issue for me with f32.
