### ISSUE TITLE
Panel objects schema inaccurate

### ISSUE THREAD

**Issue by ewangi** [mate-desktop/mate-panel#1132]
#### Expected behaviour
action-type key for panel object in schema should provide accurate description and enumerated list of available actions.

#### Actual behaviour
Enumerated list includes 'last' and 'suspend' which don't appear to be handled in the source code. In addition, the schema description for the action-type key states "Possible values are "lock", "logout", "run", "search" and "screenshot"", which is incomplete and inaccurate.

#### Steps to reproduce the behaviour
Navigate to an object using dconf-editor (org.mate.panel.objects._object_), select the action-type key.

#### MATE general version
1.24.0

#### Package version
mate-panel 1.24.0-2

#### Linux Distribution
Linux Mint 20 MATE

#### Link to downstream report of your Distribution
None.

#### Notes
My apologies that this Issue is phrased in terms of dconf-editor and not the schema itself, but I don't know where the schema is located. Given that dconf-editor derives its data from the mate-panel provided schema, I am hoping that this will be sufficient to pinpoint the inaccuracies in the schema. Many thanks.

**Comment by raveit65** [comment]
Does the issue still exists?
