### ISSUE TITLE
Minimum packages to enable all functionality on Arch Manjaro?

### ISSUE THREAD

**Issue by Hebgbs** [mate-desktop/mate-panel#1141]
MATE Tweak is a great tool for people who aren't that familiar with any open-source system running the MATE desktop, however unlike on Ubuntu MATE where _it just works_ I've been having issues with certain interface layouts like Mutiny, where the dock applet refuses to function, for instance (which is an entirely separate, but tangential issue presumably from missing a dependency which wasn't installed).

So I wonder, for _all_ of its functionality, with all of the panel layouts and such, what would be the minimum packages to install on my copy of Manjaro MATE?

**Comment by Hebgbs** [comment]
lol I thought markdown would work in the title. RIP.

**Comment by raveit65** [comment]
Mate tweak is ubuntu production, wrong repo.
https://github.com/ubuntu-mate/mate-tweak
