### ISSUE TITLE
Can remove the Preferences menu item

### ISSUE THREAD

**Issue by zhuyaliang** [mate-desktop/mate-panel#1144]
I suggest that you can remove the Preferences menu item This item is repeated with the control center item ，If can accept this suggestion, I can the work

**Comment by raveit65** [comment]
Please not, i prefer to use the preferences menu item.
Here you can open single applications directly from menu without opening m-c-c window first.

**Comment by zhuyaliang** [comment]
@raveit65 OK, I respect your opinion. I have added a new collection for mate menus. If you are interested, you can have a look.In fact, my idea is to use gtk_ tree_ view refactoring the applications menu,But I don't know if it's necessary

**Comment by lukefromdc** [comment]
I also vote for keeping this menu item-especially as someone might have mate-panel installed but not mate-control-center in another DE.
