### ISSUE TITLE
Russian translation quality dramatically decreased

### ISSUE THREAD

**Issue by ilya-fedin** [mate-desktop/mate-panel#1149]
Not sure where is the right place for such issue, but after upgrading to MATE 1.24.1 I observed that quality of the Russian translation is dramatically decreased.

For instance: "точек" -> "пиксела", "Места" -> "Точки входа", "О кнопке расчистки рабочего стола", "Фабрика демонстрационного апплета DBus", "Об апплете" -> "О программе", "О Рыбке", "О Часах"

And this is only a part of what I found in mate-panel, but I can see that the about dialog is affected as well:
![image](https://user-images.githubusercontent.com/17829319/94977620-1c258e80-0509-11eb-8dee-ff50ff85e63c.png)

**Comment by AlexKurisu** [comment]
Agreed. Previous translation was quite better. I suggest using older translation where applicable

**Comment by raveit65** [comment]
We are using transifex for our translation.
Please become a member of your language group and fix translation strings there.
Before we release a new package version we pull new translations from transifex server.
https://www.transifex.com/mate/MATE/dashboard/
The web-interface is easy to use, you only need to to honour string formatting from origin language (C).

**Comment by raveit65** [comment]
@monsta 
Problems with translations of your language

**Comment by raveit65** [comment]
no answer, closing
