### ISSUE TITLE
Window List manual sorting problems

### ISSUE THREAD

**Issue by ssrublev** [mate-desktop/mate-panel#1150]
#### Expected behaviour
Hello all and thank you for your work. There's Window List in the mate-panel. It has option to "Never group windows". When activated, I am able to sort windows manually in the list. I use this manual sorting and sort windows in the list as I want.

#### Actual behaviour
The sorting order that I set by myself is sometimes broken and window titles mix up. Not always, but sometimes, and I'm not sure what causes it. I. e. apps in the list that I manually sorted as 1, 2, 3, 4 may become 4, 2, 1, 3 or in other (random?) order. My own window order is not maintained as I ordered it.

#### Steps to reproduce the behaviour
May be reproduced using "Show Desktop Button" panel item. 
1) run some apps (3 or 4) 
2) press "Show Desktop Button" several times to minimize and restore windows of apps (maybe many times—no clear dependence, occurs "randomly"). 
3) watch the sorting order change "randomly" in the window list

I am not sure this is related only to "Show Desktop Button", sometimes order is changed unexpectedly during work.

#### MATE general version
1.24.1

#### Package version
mate-panel.x86_64 1.24.1-1.fc32 @updates

#### Linux Distribution
Fedora 32

#### Link to downstream report of your Distribution
not yet

**Comment by ssrublev** [comment]
![image](https://user-images.githubusercontent.com/6886166/100546868-a887cf80-3274-11eb-8ad2-a0aaf776a95d.png)

OK maybe someone may help me with icons at MATE-panel? Here is a picture explaining the questions. I am not sure if I should start new issue because of that

**Comment by raveit65** [comment]
You can change the icon of the compact-menu with dconf-editor.
In my case it's called object 26.
![Bildschirmfoto zu 2020-12-07 16-05-59](https://user-images.githubusercontent.com/961604/101367873-cd002f00-38a6-11eb-8b65-8f469206d03a.png)
I think you should disable the key `has-arrow` for fedora logo.

The icon of fusion-icon (compiz) you can't change. It's defined by your icon-theme. Icon name is fusion-icon

**Comment by ssrublev** [comment]
Thank you! In my case it is called object-0 and your instructions worked well. I use MATE-Faenza icon set and it's sad it is not in repos (it's much better than the default icon set). I download it from some websites to install and some icons could be updated.

**Comment by raveit65** [comment]
Does the issue still exists?

**Comment by ssrublev** [comment]
> Does the issue still exists?

I see this issue no more. Checked in Fedora 38 MATE 1.26.1

Thank you!
