### ISSUE TITLE
Network Icon vanishes when connected to a VPN

### ISSUE THREAD

**Issue by clifter1** [mate-desktop/mate-panel#1154]
#### Expected behaviour
Connect to Wifi, Connect to VPN, the Wifi and VPN icon displays for both (Wifi symbol with lock box).   
Functionality works as expected.  I can use the Wifi and resources through the VPN

#### Actual behaviour
Wifi symbol vanishes, but the lockbox displays

#### Steps to reproduce the behaviour
1) Connect to a Wifi network
2) Install VPNC "sudo apt install network-manager-vpnc-gnome"
3) Connect to a VPN using VPNC

#### MATE general version
System:    Kernel: 5.4.0-52-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: MATE 1.24.0 
         

#### Package version
ii  network-manager-vpnc        1.2.6-2           amd64        network management framework (VPNC plugin core)
ii  network-manager-vpnc-gnome      1.2.6-2     amd64        network management framework (VPNC plugin GNOME GUI)
ii  vpnc                                       0.5.3r550-3.1          amd64        Cisco-compatible VPN client
ii  vpnc-scripts                    0.1~git20190117-1         all          Network configuration scripts for VPNC and OpenConnect

#### Linux Distribution
wm: marco dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

![Wifi Only](https://user-images.githubusercontent.com/73201109/96648693-bce3be80-12fd-11eb-91af-9c5ec089efa3.png)
![Wifi and VPN](https://user-images.githubusercontent.com/73201109/96648748-d38a1580-12fd-11eb-9e2a-31c4141a6028.png)

**Comment by lukefromdc** [comment]
This might be an issue in network-manager-applet (which is a GNOME package) or in an icon theme that does not fall back to (inherit from) that packages's own icons. All we do in mate-panel is display it.

**Comment by raveit65** [comment]
Does the issue still exists?

**Comment by clifter1** [comment]
@raveit65 I am on the latest release of Linux Mint and confirm the issue does not exist any longer.   I verified the VPN icon worked from a Wifi and Ethernet connection.   System information below:

```
System:
  Kernel: 5.19.0-46-generic x86_64 bits: 64 compiler: N/A Desktop: MATE 1.26.0 wm: marco
    dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
```

**Comment by clifter1** [comment]
Verified resolved.
