### ISSUE TITLE
Workspace switcher: Change background color of workspaces

### ISSUE THREAD

**Issue by oratosquilla-oratoria** [mate-desktop/mate-panel#1176]
#### Expected behaviour
I'd like to change the color of workspaces in the applet like this:
![Screenshot at 2020-12-24 20-51-29](https://user-images.githubusercontent.com/15127577/103102214-f218cf80-4612-11eb-9920-9f8d40a28a46.png)

#### Actual behaviour
The background color of WS1, ... areas is dimmed:
![Screenshot at 2020-12-24 20-51-29](https://user-images.githubusercontent.com/15127577/103101919-a4e82e00-4611-11eb-8c8e-72cb7cec1aa2.png)

If I add to gtk.css this:

```
PanelApplet.wnck-applet .wnck-pager {
    background-color: white;
}
```

I get this (again WS1, WS2... are dimmed but the color between them **IS** white):
![Screenshot at 2020-12-24 20-52-46](https://user-images.githubusercontent.com/15127577/103102006-001a2080-4612-11eb-8bbd-fec8b9c88d2f.png)

Can I get pure color somehow? I know about `.wnck-pager:hover`, `.wnck-pager:selected` selectors but is there a 'normal' selector to change these dimmed areas' color?
These are not necessary when the 'show workspace names...' mode is used.

#### Steps to reproduce the behaviour
See above.

#### MATE general version
MATE 1.24.1

#### Package version
mate-panel 1.24.1-1

#### Linux Distribution
Manjaro (but any distribution, basically)

#### Link to bugreport of your Distribution (requirement)
Not bug?

**Comment by raveit65** [comment]
Try to work with a background-image for the `normal` state.
```
PanelApplet.wnck-applet .wnck-pager {
    background-image: linear-gradient(to bottom,
                                      shade (@theme_bg_color, 0.50),
                                      shade (@theme_bg_color, 0.50));
}
```
Btw. the selector `color` sets the edge open windows at the the workspace.
You can take a look here for more help https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L507
When both values of the gradient are the same than it is just a color.

**Comment by oratosquilla-oratoria** [comment]
I already tried all these variants from standard themes. `background-image`, `background-color` set to `none`, `transparent`, different colors, `linear-gradient`s and many other. Nothing works.

I have a feeling that there is some hardcoded semi-transparent layer on pager indicators. I've looked at the standard themes and they all have this dimmed background (except the space between the workspace indicators).

**Comment by raveit65** [comment]
Here it works like a charm.
Default with Blue-Menta theme:
![Bildschirmfoto zu 2020-12-26 20-04-48](https://user-images.githubusercontent.com/961604/103157698-0cd77980-47b6-11eb-8a10-b554df322bb0.png)
Dark background setup with gtk3-inspector:
![Bildschirmfoto zu 2020-12-26 20-03-14](https://user-images.githubusercontent.com/961604/103157711-3690a080-47b6-11eb-8c10-dd21a11cec10.png)

**Comment by oratosquilla-oratoria** [comment]
I think you misunderstood me a little. You've showed me that it does not work :) :
![103157698-0cd77980-47b6-11eb-8a10-b554df322bb0](https://user-images.githubusercontent.com/15127577/103158502-81121d00-47b6-11eb-9b4a-92cd80d243ca.png)
In the second screenshot you just made `not theme_bg_color (dimmed)` even darker by:

```
PanelApplet.wnck-applet .wnck-pager {
    background-image: linear-gradient(to bottom,
                                      shade (@theme_bg_color, 0.50),
                                      shade (@theme_bg_color, 0.50));
}
```
If I do either:
```
background-image: none;
```

or (to get a pure color without shades and other stuff):

```
background-image: linear-gradient(to bottom,
                                      shade (@theme_bg_color, 1),
                                      shade (@theme_bg_color, 1));
```
I get the same thing as in your first screenshot - nothing changes. But I'd like to have something like this:
![103157698-0cd77980-47b6-11eb-8a10-b554df322bb0](https://user-images.githubusercontent.com/15127577/103158612-6db38180-47b7-11eb-888f-c73137797151.png)

**Comment by raveit65** [comment]
Try `shade (@theme_bg_color, 1.00)`

**Comment by oratosquilla-oratoria** [comment]
> Try shade (@theme_bg_color, 1.00)
Does not work.

> Edit: You can replace @theme_bg_color with every color you want, this was only an example.
I understand that :). The point is that whatever color is used it's 'shady', not pure.

**Comment by lukefromdc** [comment]
Have you tried different GTK themes? This may be a theme issue. I checked all of wncklet's source for the string "shade" with mate-search-tool and came up empty

**Comment by oratosquilla-oratoria** [comment]
I have tested all the standard themes - all have this shady background. Also I tried to change a few standard themes, in particular, BlueMenta, Blue-Submarine, Matcha-azul, Matcha-light-azul, TraditionalGreen. Nothing works.

**Comment by lukefromdc** [comment]
I just looked at that code-and yes, draw_dark_rectangle is probably what is theming this. Note that a pixbuf (as in an IMAGE) background is the exception. In fact, some time back, I had played with this, testing changing my gtk theme to force use of a tiny version of my desktop background as the background of each of these rectangles. Cairo-dock can do that, which is where I got the idea. It worked fine. Downside of course is that's heavier code, but you could always make an image that just a rectangle the color you want, and force that as the pager background in your gtk theme or in ~/config/gtk-3.0/gtk.css

**Comment by oratosquilla-oratoria** [comment]
> but you could always make an image that just a rectangle the color you want, and force that as the pager background in your gtk theme or in ~/config/gtk-3.0/gtk.css

Do you mean using Cairo-dock or MATE panel? If the second one, won't I still get this shady thing?

**Comment by lukefromdc** [comment]
In mate-panel. That would invoke the pixbuf case and bypass the code to draw a dark rectangle.

**Comment by oratosquilla-oratoria** [comment]
Ok, so if I make an image and add this into `gtk.css`:

```
PanelApplet.wnck-applet .wnck-pager {
    background-image: url('/path/to/image.png');
}
```

I'll get rid of dark rectangles? If so, it does not work either. If not, then sorry, I am a little stupid :)

> use of a tiny version of my desktop background as the background of each of these rectangles

As you can see, there'd been the same feature before 2002 but it was [disabled](https://github.com/GNOME/libwnck/blob/master/libwnck/pager.c#L2903) (again, if I get it right).

**Comment by lukefromdc** [comment]
I just ran  test with this code in ~/config/gtk-3.0/gtk.css and a plain white image file on the desktop at 120x60px (forn hidpi):

```
/*WnckPager in both gnome-panel and mate-panel*/
wnck-pager,
.wnck-pager{
	border-color: transparent;
	border-width: 0px;
	border-style: none;
	background-image: url("/home/luke/Desktop/white.jpg");
}
```
And what I got was this: switcher workspace background is gray, but the individual windows are rendered in white. If an image is used, the image is darkened. If a black image (cannot be further darkened) is used, than windows on the workspaces can only be seen by their borders. If a theme sets these borders to that color too, than windows on the workspaces would be indistinguishable from the workspace rectangle. Thus a default of the chosen background for a non-focussed window, a tiny thumbnail of the window for the focussed window, and a dimmed/shaded version of the background for the overall workspace, to ensure there is always enough contrast to see it.

At any rate, if this is hardcoded in libwnck, we do not control it and cannot readily change it.  If we could, it might break the switcher in themes that don't support MATE. One thing we do NOT do: we don't hardcode a style element with the USER priority, so as to ensure that problematic theme defaults do get overriden, but user settings in  ~/config/gtk-3.0/gtk.css are NOT overriden. Use of the USER style provider priority in code is considered bad practice in the documentation.

**Comment by oratosquilla-oratoria** [comment]
> to ensure there is always enough contrast to see it

I totally understand why it's done this way for the 'default' mode but my original question was about the 'show workspace names...' mode (see my first post) where dimmed backgrounds are not necessary.

Anyway, thank you for your time and patience :) Should I close the issue?

**Comment by lukefromdc** [comment]
Yes, we don't control libwnck and that's where any change would have to be made.
