### ISSUE TITLE
Some tooltips don't show on bottom panel

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#1180]
#### Expected behaviour
Any applet showing a tooltip when hovered does so regardless of panel orientation: same on top panel, bottom panel, left panel,right panel

#### Actual behaviour
Some applets, notably netspeed and some (not all) items in the tray with tooltips will not display a tooltip when hovered over in a bottom panel

#### Steps to reproduce the behaviour
Put a mate-panel on the bottom of the display, add the netspeed applet. Hover on it. No tooltip appears. Move it to a top, left, or right panel. Tooltip appears on hover. No effect from restarting panel after move. Same behavior with xrandr tray icon

#### MATE general version
1.25

#### Package version
Locally built mate-panel 1.25.2+current git master commits as of Friday, Dec 25

#### Linux Distribution
Debian Unstable

#### Link to bugreport of your Distribution (requirement)
None as this is a locally built package rather than the version shipped by Debian.

**Comment by raveit65** [comment]
I see the tooltip of network applet at bottom panel.
![bottom-panel](https://user-images.githubusercontent.com/961604/103437459-51d13500-4c28-11eb-8e71-6bea5f58c6cd.jpg)

**Comment by lukefromdc** [comment]
If this works on your setup and not mine with the same applet (I tried it both in SNI and tray applet mode), than I wonder what is different and causing this. Maybe GTK or glib version(both local packages here)?

**Comment by raveit65** [comment]
As you can see my screenshot is about netspeed applet. I didn't test tray-applet because i use it on top panel.

**Comment by raveit65** [comment]
Tooltip with display-properties applet in tray at bottom-panel.
![bottom-panel-2](https://user-images.githubusercontent.com/961604/103461188-c9808c00-4d1c-11eb-8944-5e8da9efb9d9.jpg)

All tray applets which display tooltips at top panel, display their tooltips at bottom panel here. Which are display-properties, mega-sync, pulseaudio-appet and network-manager.
I am using HIDPI, normal panel size (24px) and panel from master is build with in-process applets.

**Comment by lukefromdc** [comment]
OK, works on your system, fails on mine and no clues yet. Rolling GTK3 all the way back to 3.24.0 had no effect whatsoever. I know this used to work on my machine as I saw those tooltips when developing my GTK theme.

I guess rolling back glib version (for a test) will be next

**Comment by allanlaal** [comment]
this happens in multimonitor setups when there are multiple monitors (X11 "panel"), the X11 screen forces itself to be rectangular, so there are areas of screen that are not shown in physical X11 panels:

see the black area below the Window List bar - its not shown in any physical form:
![Screenshot at 2021-02-06 09-07-40](https://user-images.githubusercontent.com/740826/107111725-eac42300-685a-11eb-87bf-1e9d42939160.png)

**Comment by raveit65** [comment]
@lukefromdc 
I forgot that i am using this PR of marco for fedora builds https://github.com/mate-desktop/marco/pull/625
Maybe this helps?

**Comment by lukefromdc** [comment]
My tests were on compiz-reloaded as I recall, but if that fixes it we are looking at the panel invoking a WM issue. That in turn will have to be fixed on every affected window manager.

Will try it out

**Comment by lukefromdc** [comment]
Oh yeah: https://github.com/mate-desktop/marco/pull/625 brings the bottom panel tooltips back, though they render slightly high they are now onscreen. Looks from this like this occurs only with hidpi or multimonitor setups(as indicated above in https://github.com/mate-desktop/mate-panel/issues/1180#issuecomment-774415656) , thus not everyone will be able to duplicate it.

**Comment by allanlaal** [comment]
I'll try to test out https://github.com/mate-desktop/marco/pull/625 ASAP
have to switch from a stable repo to nightly first, so it might take some time

**Comment by raveit65** [comment]
Closing as https://github.com/mate-desktop/marco/commit/a52f5c91c2fdc1a8f213f0ec322a46cf071eb277 is merged.

**Comment by lukefromdc** [comment]
compiz-reloaded has chosen for now not to support hidpi as it is extremely complex to do so. GTK is only used in the gtk-window-decorator and a number of plugins also have issues. I have a modified gtk window decorator that works for hidpi, though it was never merged due to the overall decision (as a legacy WM with wayland/wayfire the future) not to support hidpi unless someone manages to get support for it into the core. That would be tough to do without making compiz-core and probably the plugins as well as gtk-window-decorator depend on GTK.
