### ISSUE TITLE
Adding item "Command" to the panel

### ISSUE THREAD

**Issue by simonrodan** [mate-desktop/mate-panel#1198]
#### Expected behaviour
The output of a command window should be added to the panel 

#### Actual behaviour
A clock is added to the panel instead 

#### Steps to reproduce the behaviour
Right click on the panel
Select "Add to panel"
Click on "Command \n Shows the output of a command"
Click Add

#### MATE general version
RELEASE=20.1
CODENAME=ulyssa
EDITION="MATE"
DESCRIPTION="Linux Mint 20.1 Ulyssa"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=https://www.linuxmint.com/rel_ulyssa_mate_whatsnew.php
RELEASE_NOTES_URL=https://www.linuxmint.com/rel_ulyssa_mate.php
USER_GUIDE_URL=https://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 20.1 MATE

**Comment by lukefromdc** [comment]
This is because the default command to be run (changable from the applet preferences dialog) is
`date +%T` which displays the time. Changing this to "dmesg" or "ls /home" will display the (very, very truncated" output expected from those commands. This is the applet working as expected

**Comment by simonrodan** [comment]
Thanks likefromdc.
