### ISSUE TITLE
Network and Sound icons like to hang out in i3bar :)

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-panel#1199]
#### Expected behaviour
Network and Sound hangs out in mate panel

#### Actual behaviour
Network and sound icons hang out in i3bar

#### Steps to reproduce the behaviour
I guess install i3-gaps and set i3 as windows manager in dconf editor?

#### MATE general version
1.24

#### Package version
1.24

#### Linux Distribution
Guix System

#### Link to bugreport of your Distribution (requirement)
I didn't submit one :(

**Comment by raveit65** [comment]
Reporter leave github, closing.
