### ISSUE TITLE
Coding Issue in panel-addto.c

### ISSUE THREAD

**Issue by LaVerne-David** [mate-desktop/mate-panel#1201]
#### Expected behaviour
Consistent coding.

#### Actual behaviour
In mate-panel-1.24.0/mate-panel/panel-addto.c, line 1335-6
```
       g_signal_connect (dialog->addto_dialog, "destroy",
			  G_CALLBACK (panel_addto_dialog_destroy), dialog);
```
does not say 
```
                          G_OBJECT (dialog->addto_dialog)
```
as all the other calls to g_signal_connect do.
Probably an error.
#### Steps to reproduce the behaviour
Read the code.

#### MATE general version
1.24.0
#### Package version
none
#### Linux Distribution
Ubuntu-MATE 20.04.1

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu-mate/+bug/1914847

**Comment by lukefromdc** [comment]
Probably a good reason for that, and an error from this sort of thing will usually cause a build warning if not an outright build failure. 

NOT closing this yet, in case this is something the build system and cppcheck (which are not "glib aware) are not catching yet which affects the behavior in the linked bug report about panel menu items disappearing.  Someone better at the code than me should doublecheck this. Note that cppcheck-gui shows NO errors or warnings for this file, but I do not have it configured in such a way as to "understand" glib and gtk

**Comment by muktupavels** [comment]
`G_OBJECT` cast is not needed and definitely does not cause problems with disappearing menu items.
