### ISSUE TITLE
Unable to drag locked icon from mate panel and drop it to desktop

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-panel#1209]
#### Expected behaviour
even locked Firefox icon can be copied to desktop

#### Actual behaviour
locked Firefox icon is not copied to desktop

#### Steps to reproduce the behaviour
1. Have Ubuntu MATE 20.04 LTS installed
2. Minimize all windows to access the desktop
3. Drag default preinstalled Firefox icon from top MATE Panel and drop it to the Desktop area

#### MATE general version
MATE 1.24.0

#### Package version
mate-panel 1.24.0-2

#### Linux Distribution
Ubuntu MATE 20.04 LTS

#### Link to bugreport of your Distribution (requirement)
https://pad.lv/1917577

**Comment by N0rbert** [comment]
This issue does not exist for manually added application icons.
![drag](https://user-images.githubusercontent.com/309456/109770366-88b5ce00-7c0c-11eb-8580-e5339d3bc2f8.gif)

So something is unique with default Firefox icon on top panel.

**Comment by rbuj** [comment]
Failed to copy to desktop the icons that are locked to the panel after dragging them on the desktop.

**Comment by N0rbert** [comment]
Seems to be by design.
