### ISSUE TITLE
Unable to move MATE panel to second monitor

### ISSUE THREAD

**Issue by pkbarbiedoll** [mate-desktop/mate-panel#1224]
#### Expected behaviour
In a multiple-display system I should be able to right click a new panel and drag it to the second display

#### Actual behaviour
After creating a new panel, I am unable to move panel anywhere - not even on the same monitor.  I'm only allowed to change orientation of top/bottom/left/right.

#### Steps to reproduce the behaviour
Create new panel, attempt to drag to a new position on same or second monitor

#### MATE general version
1.24.0

#### Linux Distribution
Linux Mint 20

**Comment by TuxVinyards** [comment]
I am not a team member here but I am not seeing this as a bug.  This all looks like normal behaviour to me:

Select 'Preferences' from the main menu & then 'Display'.  On the left, select the monitor that you would like to see the panels appear on, then on the right select 'Choose as Primary' 

This should achieve what you are wanting to do.   You can move individual items on the panels by right clicking and selecting 'move'.  Afaik there is no drag and drop feature to the panels.  Something on my wish list would be the ability to extended the top & bottom panels right across the full spread of two or more monitors. But life is too short and the team put enough hours as it is....   This is my bit, hopefully to help them out.

**Comment by pkbarbiedoll** [comment]
I need apanels on both monitors, not just one.

**Comment by mbkma** [comment]
You can right click on any panel->preferences->untick the expand option. Than you can move the panel freely to any position by grabbing it on the left or right side.

**Comment by TuxVinyards** [comment]
@mbkma  Interesting.   I just tried that:  I dragged the bottom panel from the right monitor to the top on the left.  I then reselected 'expand' from the properties panel  (still left behind on the right monitor)  and found myself with a top panel on both screens.  Not quite a full stretch but pretty good nonetheless. Yay.

**Comment by pkbarbiedoll** [comment]
> You can right click on any panel->preferences->untick the expand option. Then you can move the panel freely to any position by grabbing it on the left or right side.

Excellent this works perfectly.  Thanks so much.

(obvs not a bug now - just didn't see how to do this with Mate Panels till you replied!)
