### ISSUE TITLE
Broken XEmbed tray icons

### ISSUE THREAD

**Issue by romildo** [mate-desktop/mate-panel#1225]
#### Expected behaviour

Notification area with icons correctly drawn.

#### Actual behaviour

Icons seems to be constantly redrawn at different positions.

#### Steps to reproduce the behaviour

Just run mate with some applets that are drawn to the notification area.

#### MATE general version

1.24.x

#### Package version

mate-panel-1.24.2

#### Linux Distribution

NixOS

#### Link to bugreport of your Distribution (requirement)

https://github.com/NixOS/nixpkgs/issues/122053

https://user-images.githubusercontent.com/1217934/117973273-8eade680-b302-11eb-8571-eb54b60fc961.mp4

**Comment by lukefromdc** [comment]
Not getting this error on Debian, not sure whether this is distro-specific or application-specific. If the application is constantly asking the icon to be redrawn this could happen. Looks like it's just one of your tray icons, for the sound. I'm guessing this video editor is constantly adding and subtracting the microphone, which is known to take a bit of time, and somehow adding more than one microphone device. Not sure this is a bug in mate-panel. Might be an issue with  your video editor (which one is it?), possibly mate-media (handles the sound icons) or even your sound setup not responding properly to the video editor's commands.

**Comment by ilya-fedin** [comment]
> Looks like it's just one of your tray icons, for the sound.

![image](https://user-images.githubusercontent.com/17829319/125694151-a072e6a4-23f3-4cc0-8f53-79be934a13d2.png)

I use sound applet, but if I activate tray icon instead of the applet, it will be broken as well. It's a pity that battery applet doesn't work (just doesn't show up when I add it to panel) and that layout indicator doesn't have an applet, only XEmbed tray icon.

**Comment by romildo** [comment]
After downgrading mate-panel, I have also encountered this issue with versions 1.22.2 and 1.24.2.

Considering that it worked before, it may be a problem with a library dependence that has been updated in the system. Does anyone have any idea of which library could it be?

**Comment by ilya-fedin** [comment]
This was due to gtk3 built without Xdamage
