### ISSUE TITLE
New panel crashes

### ISSUE THREAD

**Issue by MRF316** [mate-desktop/mate-panel#1232]
New panel disappears when I remove a separator

Customizing a newly created panel, the smallest tweak will cause it to crash like removing a separator

MATE 1.22.2

Linux Mint 19.3 Tricia

https://termbin.com/xn4c6

**Comment by zhuyaliang** [comment]
Can you explain in detail how to reproduce this problem

**Comment by MRF316** [comment]
I answered that in the OP

**Comment by raveit65** [comment]
Mate-1.22 reached EOL since 2 year in result we will never make new releases. Update your box to a supported version which is 1.26.
