### ISSUE TITLE
Alt+F2 or Run Application dialog incorrectly interprets ~ (tilde)

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-panel#1234]
#### Expected behaviour
Running commands like `pluma ~/somefile` opens Pluma text-editor which shows contents of `~/somefile`.

#### Actual behaviour
Running command like `pluma ~/somefile` opens strange file name `~/~` in Pluma. Saving file is not possible because of wrong path `/home/user/~/somefile` used.

#### Steps to reproduce the behaviour
1. Press <kbd>Alt</kbd>+<kbd>F2</kbd> to open Run Application dialog
1. Type command like `pluma ~/somefile`
1. Press <kbd>Enter</kbd> or click *Run*
1. Wait for Pluma window to be opened

#### MATE general version
1.24.1

#### Package version
1.24.2-0ubuntu1

#### Linux Distribution
Ubuntu MATE 21.04

#### Link to bugreport of your Distribution (requirement)

https://pad.lv/1933376

**Comment by zhuyaliang** [comment]
Sorry, this is a late reply. I have repeated this problem. I will fix it in the near future
