### ISSUE TITLE
Custom launcher in panel doesn't synchronise icon when menu entry changes

### ISSUE THREAD

**Issue by djmattyg007** [mate-desktop/mate-panel#1235]
I'm copying a launcher from the applications menu to my panel through this dialog:

![image](https://user-images.githubusercontent.com/489338/124370390-74690700-dcba-11eb-9bd2-dd81dd4e05e8.png)

This launcher triggers a script that updates the icon of the `.desktop` entry stored in my home directory for this launcher.

#### Expected behaviour

The icon in the panel should update automatically, like the icon inside the applications menu does.

#### Actual behaviour

Even though the icon inside the applications menu updates, the icon in the panel does not.

I've confirmed that I don't have any matching files stored in `~/.config/mate/panel2.d/default/launchers/`.

#### Steps to reproduce the behaviour

1. Copy an application launcher into the top panel by right-clicking on the panel, selecting "Add to Panel", and then selecting the relevant launcher.
1. Update the icon in the `.desktop` file for the launcher you've just added by using `desktop-file-install` to copy in an updated version of the file.
1. Observe that the icon has changed in the applications menu.
1. Observe that the icon does not change on the panel.

#### MATE general version

1.24.1

#### Package version

1.24.2-1

#### Linux Distribution

Arch Linux

#### Link to bugreport of your Distribution (requirement)

https://bugs.archlinux.org/task/71428

I don't really understand why it was necessary to file a bug report downstream first, given there are no custom patches applied to this package.

**Comment by zhuyaliang** [comment]
It should be the lack of ```g_file_monitor_file```  ```changed``` signal binding
Because restarting the panel can solve this problem，I can try to fix that

**Comment by zhuyaliang** [comment]
@djmattyg007 The specific reason has been found. Recently, I will upgrade the  ```mate-panel/launcher.c``` . I believe that the update can solve your problem
