### ISSUE TITLE
window list: wrong "Move to Workspace ..." context menu items

### ISSUE THREAD

**Issue by wpyoga** [mate-desktop/mate-panel#1239]
#### Expected behaviour

The window button context menu should have:
- on Workspace 1: only "Move to Workspace Right"
- on Workspace 2 & Workspace 3: "Move to Workspace Left" and "Move to Workspace Right"
- on Workspace 4: only "Move to Workspace Left"

#### Actual behaviour

The window button context menu actually has:
- on Workspace 1: only "Move to Workspace Right" option. (This is actually expected)
- on Workspace 2 & Workspace 3: "Move to Workspace Right", "Move to Workspace Up", and "Move to Workspace Down"
- on Workspace 4: only "Move to Workspace Down"

#### Steps to reproduce the behaviour

1. Boot into Linux Mint 20.2 MATE Live ISO.

2. When the desktop appears, open a Terminal window.

3. Right-click on the Terminal window button in the panel tasklist, it shows Move to Workspace Right. Click on it, the Terminal window will move to Workspace 2.

4. Press Ctrl-Alt-Right on the keyboard, the display will switch to Workspace 2.

5. Right-click on the Terminal window button in the panel tasklist, it shows Move to Workspace Right, Move to Workspace Up, and Move to Workspace Down. Click on Move to Workspace Right, the Terminal window will move to Workspace 3.

6. Press Ctrl-Alt-Right on the keyboard, the display will switch to Workspace 3.

7. Right-click on the Terminal window button in the panel tasklist, it shows Move to Workspace Right, Move to Workspace Up, and Move to Workspace Down. Click on Move to Workspace Right, the Terminal window will move to Workspace 4.

8. Press Ctrl-Alt-Right on the keyboard, the display will switch to Workspace 4.

9. Right-click on the Terminal window button in the panel tasklist, it shows Move to Workspace Down.

#### MATE general version

1.24

#### Package version

1.24.0-2

#### Linux Distribution

Linux Mint MATE 20.2

#### Link to bugreport of your Distribution (requirement)

I initially posted the bug on Linux Mint forums: https://forums.linuxmint.com/viewtopic.php?p=2040444#p2040444

On IRC, I was advised to report bugs to the corresponding package. However, if this is an error, please let me know and I will find another way to make a bug report for the distro (somewhere).

**Comment by vkareh** [comment]
These menu entries are handled by the wnck library: https://gitlab.gnome.org/GNOME/libwnck

However, based on your issue (and [the relevant libwnck code](https://gitlab.gnome.org/GNOME/libwnck/-/blob/master/libwnck/window-action-menu.c#L452-524)) it seems like something in your screen size versus viewport size calculation is off. Do you have a non-standard screen configuration by any chance?

**Comment by wpyoga** [comment]
@vkareh Wow, thank you for pointing me in the right direction! I didn't know it was due to a different package. Should I report this bug there?

As for screen configuration, I've reproduced this problem on two devices:
- laptop with Full HD screen (ThinkPad T450s), integrated intel graphics
- PC with Intel i6600K CPU, using a Full HD (1920x1080 also) TV as its monitor

I first noticed this problem on my laptop (on Linux Mint installed on the laptop), but then I confirmed it again using the Live ISO, both on my laptop and on my PC.

I should also add something:
- As soon as I add the workspace switcher onto the panel, the problem disappears. The context menu items become normal / as expected.
- If I reboot, it's still normal.
- If I remove the workspace switcher from the panel, it's still normal.
- But if I reboot now (without the workspace switcher on the panel), the problem reappears.

**Comment by mexsudo** [comment]
In my opinion Workspace Switcher is working exactly as intended.
please just put Workspace Switcher back on the panel.
if the single panel that Mint uses is too cluttered for your taste create a new panel for it to live on (and auto hide if you prefer)

BTW: we (Mate users) lack a comprehensive manual detailing how to use the myriad of tools. 
If something does exist please point it out to me.

**Comment by vkareh** [comment]
That's really interesting, sounds like adding the workspace switcher applet initializes something in the session. Looking at the mate-panel workspace-switcher applet code, it seems like it does: loading the applet sets all the gsettings from the applet as the initialization parameters of the wnck pager component. Which probably means that the default/empty settings for the wnck pager are not aligned with the expectations of the workspace switcher applet?

**Comment by mexsudo** [comment]
PS: https://ubuntu-mate.community/t/we-need-documentation-help-maintainers/17944

**Comment by vkareh** [comment]
@mexsudo yes, the workspace-switcher seems to be working correctly. However, the menu actions in the tasklist buttons expects a the wnck pager settings to be initialized (which happens through the workspace-switcher). If the workspace-switcher is not added, then the menu entries are based on some undefined/default configuration that's handled by the init code in wnck. This means that the current "correct" way to use workspaces involves having the applet active.

Some possible options to fix this:
- always load the wnck pager configuration on every package that needs it (workspace-switcher, window-list, marco)
- disable workspaces entirely if the workspace-switcher applet is not active
- have some global mate package load workspace configurations independent of the workspace switcher

Any other alternatives you can come up with?

**Comment by vkareh** [comment]
@wpyoga - in any case, the issue is _not_ in libwnck, as the workspace configuration is handled by the workspace-switcher applet. The real issue here is that _nothing_ is loading the wnck pager configuration in the first place.

**Comment by raveit65** [comment]
Can this issue be closed please?
For me this is an issue caused by linuxmint devs with shipping a wrong default panel config.
Default config by MATE is to use the workspace-switcher. See  https://github.com/mate-desktop/mate-panel/blob/master/data/default.layout#L47

**Comment by vkareh** [comment]
@raveit65 that's a really good point. I've never seen a distro ship without the workspace switcher applet by default. Seems like Linux Mint is the odd one out.

**Comment by wpyoga** [comment]
@vkareh Well, since workspace configuration is stored by marco:

```console
$ gsettings list-recursively | grep workspace
[...]
org.mate.Marco.general num-workspaces 16
```

I'm inclined to think that marco should be the one loading the workspace configuration.

@raveit65 With all due respect, I think the workspace switcher applet should help the user manage his/her workspaces (switch, show, configure), and nothing else. So even if the workspace switcher applet is not active, workspaces should work fine.

After all, when I switch workspaces using Ctrl-Alt-Left and Ctrl-Alt-Right, even without the workspace switcher active, there is a preview in the middle of the screen, showing the available workspaces.

Incidentally, I found that the workspace switcher applet does not retain the number of workspace rows:
1. add workspace switcher to panel, it shows 4 workspaces in a row
1. right click, then
    - add the Number of workspaces to 6
    - configure Show all workspaces in: 2 rows
1. The workspaces will be arranged as expected. However, if at this time we remove and re-add the workspace switcher to the panel, it will show 6 workspaces arranged in 1 row.

Some digging around led me to see that the number of workspace rows are stored in the current applet configuration:

```console
$ dconf dump / | grep row -A 2 -B 2
[...]
[org/mate/panel/objects/object-0/prefs]
num-rows=2
```

This couldn't be right, right...? I will open another issue for the workspace switcher row setting, since it's related but separate from this discussion.

Anyway, please let me know if I miss anything -- I'm not used to debugging the GUI parts of my desktop :) Also, I may be able to help implement any fix / feature, with some guidance.

**Comment by wpyoga** [comment]
Oops... I actually found that this issue is a duplicate of #159 
Should we continue discussion here (in this issue), or there (#159) ?

Btw @mexsudo , thank you for the Wiki, I've bookmarked it.

**Comment by lukefromdc** [comment]
If marco loads the workspace configuration, this breaks when using any other WM that is not also updated. We have two versions of compiz and lots.of other WM's to worry abouy here

**Comment by raveit65** [comment]
> With all due respect, I think the workspace switcher applet should help the user manage his/her workspaces (switch, show, configure), and nothing else. So even if the workspace switcher applet is not active, workspaces should work fine.

Well, i am using fedora with a perfect default panel config, i am so happy that i didn't run in `problems of other distros` 
:P 
Sorry, after maintaining Mate and helping users for for nearly 10 years i am focused on real problems.

**Comment by wpyoga** [comment]
@lukefromdc Did you mean, if marco loads the workspace configuration and workspace-switcher does not, then other window managers that don't load the workspace configuration will get this bug as well? I'm thinking we should then fix the other window managers, then, no...?

Btw, with the information I learned in this discussion, I'm deducing that xfwm4 also does not load the workspace configuration -- because Linux Mint XFCE exhibits the same bug as Linux Mint MATE does. But I'm not aware of how other window managers work...

@vkareh Alternatively, can the workspace configuration be loaded by a command instead? It would fit into this case:

> have some global mate package load workspace configurations independent of the workspace switcher

Just for the sake of brainstorming, I have another idea, hopefully this will not break too many things:
- graduate workspace-switcher into workspace-manager
- migrate workspace configuration from marco into workspace-manager
- add an option to workspace-manager to show or hide the workspace-manager applet
- add a workspace-manager-preferences utility to bring up the workspace-manager configuration interface

@raveit65 Well... I'm hoping I can contribute to this project, and improve MATE for my own use, as well :)

**Comment by raveit65** [comment]
Wow, i am providing repos as upstream since 10 years. please stop boring me... :)

**Comment by vkareh** [comment]
@lukefromdc Marco already tracks the number of workspaces, not the applet. In fact, if you toggle between `marco` and `metacity` you will notice that each WM has their own independent workspace configuration.

The workspace-switcher applet handles only some of the settings for the wnck pager. The rest are handled directly in marco, so fixing this in marco (to have it initialize the wnck pager configuration) will not affect the behavior of other WMs. You can see the workspace-switcher code using marco's settings here: https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/workspace-switcher.c#L990-L991 meaning that the right place to fix this is in marco.

That said, I'm wondering if this is just a large change with little benefit. All distros (except for Mint) ship with the workspace switcher by default. Most users don't switch away from the default, and I bet that most users concerned with workspaces make sure to have the applet active.

Seems like a very low probability use case that someone who wants to use workspaces deliberately removes the applet. I would advise @wpyoga to focus their energy on getting Mint to adopt a more sane default. Alternatively, feel free to submit a PR for marco to have it initialize the wnck pager settings.

I will close, as this issue does not belong in the mate-panel (or the wncklet)

**Comment by wpyoga** [comment]
Thank you for the pointers @vkareh  :) I will try to work on marco and submit a patch to fix this issue.

While I understand that most people who want to use workspaces might use the workspace switcher anyway, I can't help but think that the current behaviour is somehow incorrect -- because the workspace settings should be handled in marco. But that is just my opinion, and I hope I can contribute a good patch, later :)

**Comment by lukefromdc** [comment]
@wpyoga, that is EXACTLY what I mean. If we move this from the workspace switcher applet to marco, we will invoke this bug WITH the workspace switcher applet in the panel in every window manager other than marco, and we don't control any of them. I consider this a bad idea-especially to benefit one distro only.   Maybe having the applet check to see if these have been initialized and initialize them if the WM has not done so would allow this and mean the menus would work if either marco was running OR the workspace switcher applet was in the panel, but that's even more work.

**Comment by wpyoga** [comment]
@lukefromdc 
> If we move this from the workspace switcher applet to marco, we will invoke this bug WITH the workspace switcher applet in the panel in every window manager other than marco

Yes, because then the workspace switcher applet will then not initialize the workspace settings. I realized this a bit late, sorry. But please check my thoughts below.

> having the applet check to see if these have been initialized and initialize them if the WM has not done so

Yes, I agree and that's one way to implement this. Another (easier) alternative would be to let marco initialize the workspaces as a single row, although this would also mean the workspace switcher would still be managing the workspaces instead of just switching between them.

Again, I'm new on this desktop space, but somehow I think the current implementation does not handle the separation of concerns well enough. I'm sorry if I offended anyone with this remark :(

> that's even more work.

I'm planning to work on this, and submit the code to marco and mate-panel. I will do my best to make sure the code needs almost no maintenance in the future, I hope it's okay...

**Comment by muktupavels** [comment]
You can not move everything into WM:
https://specifications.freedesktop.org/wm-spec/1.3/ar01s03.html#idm45578527921280

And workspace number is already handled by WM:
https://github.com/mate-desktop/marco/blob/master/src/core/screen.c#L1100
