### ISSUE TITLE
workspace-switcher: number of rows is not preserved after removing and re-adding applet

### ISSUE THREAD

**Issue by wpyoga** [mate-desktop/mate-panel#1240]
#### Expected behaviour

When the workspace switcher is removed and re-added, the number of workspace rows is preserved.

#### Actual behaviour

When the workspace switcher is removed and re-added, the number of workspace rows is reset to 1.

#### Steps to reproduce the behaviour

1. Boot into Linux Mint 20.2 MATE Live ISO.
1. When the desktop appears, add the workspace-switcher applet to the panel.
1. Right-click on the workspace-switcher, modify the number of workspaces to 6, and modify the number of rows to 2.

    Now the workspaces are shown as 2 rows x 3 columns.

1. Right-click on the workspace-switcher and remove it from the panel.
1. Add the workspace-switcher applet to the panel again.

    Now the workspaces are shown as 1 row x 6 columns.

#### MATE general version

1.24

#### Package version

1.24.0-2

#### Linux Distribution

Linux Mint MATE 20.2

#### Link to bugreport of your Distribution (requirement)

(none)
This bug was discovered while discussing #1239

**Comment by wpyoga** [comment]
Additiional information:

- the number of workspaces are stored in GSettings:

    ```
    org.mate.Marco.general num-workspaces 6
    ```

- as long as the workspace-switcher applet is not removed from the panel, it is stored in dconf:

    ```
    [org/mate/panel/objects/object-0/prefs]
    num-rows=2
    ```

- if I add a new workspace-switcher applet, another config is stored in dconf:

    ```
    [org/mate/panel/objects/object-1/prefs]
    num-rows=1
    ```

**Comment by lukefromdc** [comment]
Removing an applet (ANY applet) and then adding it back always brings back the original configuration, the previously stored configuration is not used again. This is probably a design decision dating back to GNOME 2.0
