### ISSUE TITLE
mate-panel 1.26 update segmentation fault

### ISSUE THREAD

**Issue by bob-10598** [mate-desktop/mate-panel#1249]
#### Expected behaviour
Expect update from 1.24 to 1.26 to work properly

#### Actual behaviour
After updating to 1.26, mate-panel aborts with segmentation error.

#### Steps to reproduce the behaviour
Update 1.24 to 1.26 and reboot

#### MATE general version
1.26

#### Linux Distribution
Fedora 34

#### Link to bugreport of your Distribution (requirement)
https://bugzilla.redhat.com/show_bug.cgi?id=1997198

**Comment by mbkma** [comment]
Do you use Marco with compositing? Do you use a custom background for mate-panel, a custom color or the default theme?

**Comment by bob-10598** [comment]
Update-Problem essentially resolved. home/Bob/.config/dconf apparently contained settings which worked with 1.24 and all previous versions, but not with 1.26

Deleting dconf and restarting brought up a working mate desktop with default panels, however as previously noted there are differences. First, the panel size is 26 pixels, and cannot be set lower. Previously, it was 24 pixels and could be set lower.

Setting the Preferences->Hardware->Displays scaling setting to 100 from auto does decrease sizes, but the setting is not persistent. Logging out & back the desktop defaults to the larger scaling with 26 pixel min and larger bold "Applications Places System" header on the top right. So there seem to be some remaining quirks for my system using 1.26, but the root problem was caused by some incompatibility with the original dconf settings which worked under 1.24.

I don't use a custom mate-panel background color, and org.mate.Marco.general compositing-manager is set true.

**Comment by bob-10598** [comment]
Latent problem uncovered: selecting certain themes causes panel crash. The Traditional-Ok theme crashes panel, as does BlueMenta. The BlackMATE theme was selected for test and seems to work, as I'm writing this using that configuration, but there is an underlying problem. When dconf is deleted prior to a logout/login, which presents a "new" desktop, the theme reported is "custom", as apparently generated by some default initialization process.

**Comment by bob-10598** [comment]
After doing a complete MATE desktop uninstall, followed by a reinstall, could not get the desktop to recover like before by deleting the dconf user. Forced to downgrade back to 1.24, which works flawlessly, and was able to restore the original dconf user file. Checking the theme setting for that, it shows "TraditionalOk"! No wonder it couldn't start under 1.26, at least on this system. Keeping 1.24 for the foreseeable future, as for whatever reason it works perfectly here on this workstation.

**Comment by bob-10598** [comment]
Posted this to bugzilla report:
Source of problem has been isolated: nvidia/cuda driver

After many hours of trials and testing, ran two independent tests. First, an additional clean bootable F34-Mate partition was created on this workstation. No additional desktop environments were installed (e.g. no Gnome,XFCE,KDE, etc.) Install was completely updated including mate 1.26, using default nouveau drivers the desktop/panels were "perfect". Next the nvidia proprietary driver was installed, and the desktop changed format somewhat using larger fonts and panels which were set at 26pixels up from 24 and couldn't be set lower.

Next the original problem install was converted from nvidia back to nouveau video driver. Voila. Upgrading to 1.26 from 1.24 produced seamless results identical to the original 1.24 and earlier. At this point, leaving the nouveau driver intact until such time as the root cause of the incompatibility on this particular hardware is solved, if ever.

**Comment by raveit65** [comment]
Closing this as it is fixed with latest update in downstream report.
