### ISSUE TITLE
Menu item Properties dialog not appearing

### ISSUE THREAD

**Issue by adatum** [mate-desktop/mate-panel#1253]
#### Expected behaviour
It should be possible to edit the Properties of Menu items.

#### Actual behaviour
The Properties button is present but no dialog appears, as was previously the case. System log records a core dump.

#### Steps to reproduce the behaviour
Right click in the menu -> click Edit Menus -> highlight a menu and menu item -> click the Properties button or double click on the menu item -> instead of showing a dialog where the properties (eg. command for the item) can be edited, nothing happens

#### MATE general version
1.26.0

#### Package version
mate-panel-1.26.0-1.fc34.x86_64

#### Linux Distribution
Fedora 34

#### Link to bugreport of your Distribution (requirement)
https://bugzilla.redhat.com/show_bug.cgi?id=2000353

**Comment by raveit65** [comment]
I think this fixed by https://github.com/mate-desktop/mate-panel/commit/808032fcd41f10f8c794f9c8ea90a2aad30c76f7

**Comment by adatum** [comment]
@raveit65 What is the preferred way to test the build? I downloaded `mate-panel-1.26.0-2.fc34.x86_64.rpm` from the link above, but it does not install due to missing dependencies: 

```
$ sudo dnf install ./mate-panel-1.26.0-2.fc34.x86_64.rpm
Error: 
 Problem: conflicting requests
  - nothing provides mate-panel-libs(x86-64) = 1.26.0-2.fc34 needed by mate-panel-1.26.0-2.fc34.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by raveit65** [comment]
Ok, i can confirm that https://github.com/mate-desktop/mate-panel/commit/808032fcd41f10f8c794f9c8ea90a2aad30c76f7 included with mate-panel-1.26.0-2.fc34 fixes the issue.

**Comment by raveit65** [comment]
You need to download mate-panel-1.26.0-2.fc34 and mate-panel-libs

**Comment by raveit65** [comment]
Or wait for that the update is in update-testing repo.
Than execute `dnf update mate-panel* --enablerepo updates-testing`

**Comment by adatum** [comment]
I can also confirm that mate-panel-1.26.0-2.fc34 fixes the issue.

**Comment by raveit65** [comment]
Why not closing issue :)
