### ISSUE TITLE
mate-panel huge memory consumption

### ISSUE THREAD

**Issue by C4H7Cl2O4P** [mate-desktop/mate-panel#1255]
#### Expected behaviour
~100 Mb of RAM

#### Actual behaviour
~6Gb (51%) of RAM

#### Steps to reproduce the behaviour
~a week uptime

#### MATE general version
1.20.4
![Зняток екрану як 2021-09-14 02-29-40--](https://user-images.githubusercontent.com/44552111/133171641-5ef613db-3503-4714-a698-607763a74498.jpg)
![Зняток екрану як 2021-09-14 02-53-01---](https://user-images.githubusercontent.com/44552111/133171830-bdb21fcb-2a04-4da5-9581-9777ec741e6d.jpg)

#### Package version
mate-panel-common/stable,now 1.20.5-1 all [installed,automatic]
mate-panel/stable,now 1.20.5-1 amd64 [installed,automatic]

#### Linux Distribution
Debian 10
uname -a
Linux localhost 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

#### Link to bugreport of your Distribution (requirement)
https://www.debian.org/Bugs/Reporting
https://bugs.debian.org/

**Comment by lukefromdc** [comment]
That is a very old and unsupported version, and many memory leaks have been corked up since then.

**Comment by raveit65** [comment]
Closing, this is already fixed in mate-panel => 1.24.2.
Current supported version is 1.26 branch.
So please update your installation to a newer MATE version.
