### ISSUE TITLE
Window list applet cannot be set to "never group windows"

### ISSUE THREAD

**Issue by frankzen** [mate-desktop/mate-panel#1271]
#### Expected behaviour
Set applet to never group

#### Actual behaviour
Applet continues to group windows

#### Steps to reproduce the behaviour
Change applet to never group. Applet continues to group

#### MATE general version
1.26

#### Package version
mate-applets-1.26.0-1.fc35.x86_64

#### Linux Distribution
Fedora Rawhide

#### Link to bugreport of your Distribution (requirement)
Working on it. As soonas I figure out how!

**Comment by mbkma** [comment]
This issue should be already fixed in version 1.26 (see https://github.com/mate-desktop/mate-panel/issues/1250). Please test it with the newer version. If the issue still remains, you can reopen.

**Comment by mbkma** [comment]
What is your version of `mate-panel`?

**Comment by frankzen** [comment]
I replied via email but apparently it never made it here.


Name         : mate-panel
Version      : 1.26.1
Release      : 1.fc35
Architecture : x86_64
Size         : 13 M
Source       : mate-panel-1.26.1-1.fc35.src.rpm
Repository   : @System
From repo    : fedora
Summary      : MATE Desktop panel and app

![image](https://user-images.githubusercontent.com/717662/142731936-558f32b2-9717-44fe-9567-e7f758ecece3.png)

**Comment by raveit65** [comment]
Fedora-34/35 is using mate-panel-1.26.1 with https://github.com/mate-desktop/mate-panel/pull/1252
Setting applets to `never group` and `always group` are working in my f34, but it seems that `group if there is no place` is broken. This setting does not group when eg. many terminals windows are open.

**Comment by frankzen** [comment]
Certainly doesn't work on my machine .    what do you mean by "it seems that group if there is no place is broken" ???

**Comment by raveit65** [comment]
There is a third option, which calls` group if there is no space on the panel`

**Comment by frankzen** [comment]
Still not working on Fedora 35. Mate is v 1.26-0-1. Works fine on Debian Mate there is v 1.26-0-2. I guess it's Fedora's problem for not updating?

**Comment by raveit65** [comment]
There is no official mate-desktop tarball with 1.26-0-2 https://pub.mate-desktop.org/releases/1.26/
And fedora use latest mate-panel version which is 1.26.1

**Comment by mbkma** [comment]
> Setting applets to never group and always group are working in my f34, but it seems that group if there is no space is broken. This setting does not group when eg. many terminals windows are open.

@raveit65 the option `group windows when space is limited` works here on debian testing, mate-panel master branch:
![Peek 2022-01-05 20-50](https://user-images.githubusercontent.com/39454100/148280210-a4b6b326-f56b-4449-956a-01c8776337f3.gif)
The grouping only takes effect when there is very limited space. So maybe try to open a lot more terminal windows.

**Comment by frankzen** [comment]
> There is no official mate-desktop tarball with 1.26-0-2 https://pub.mate-desktop.org/releases/1.26/ And fedora use latest mate-panel version which is 1.26.1

frank@franklin:~$ apt show mate-panel 
Package: mate-panel Version: 1.26.1-2 
Priority: optional Section: x11 
Maintainer: Debian+Ubuntu MATE Packaging Team <debian-mate@lists.debian.org> 
Installed-Size: 1,738 kB

**Comment by mbkma** [comment]
@frankzen that is from debian. @raveit65  was referring to upstream MATE.
On my debian testing machine the `always group` and `never group` option also work fine (I have the same package version as you).

**Comment by raveit65** [comment]
@mbkma 
I have no idea which patches debian added to their builds.
Fedora use vanila 1.26.1, https://src.fedoraproject.org/rpms/mate-panel/commits/f35

@frankzen 
In 3 posts you posted 3 different versions. This is not helpful.

**Comment by mbkma** [comment]
@raveit65 I use mate-panel from master branch, self-compiled, without any patches and all options work fine.

**Comment by raveit65** [comment]
Good, but i can't push master to fedora stable :)
Is there a commit in master which has fixed the issue?
Can someone point me to debian git repos or what ever they use, to see what they did ?
Sorry, i am fedora maintainer and i have no clue about debian infrastructure :P

**Comment by mbkma** [comment]
https://salsa.debian.org/debian-mate-team/mate-panel/-/blob/master/debian/patches/series

It seems that they just apply rda-support patches.

**Comment by raveit65** [comment]
RDA support need to be reviewed  https://github.com/mate-desktop/mate-panel/pull/824
Beside from this fact rda support has no influence for windows-list applet.
As it is a wnck-applet, which libwnck version is used by debian?

**Comment by mbkma** [comment]
```
$ apt info libwnck-3-dev 
Package: libwnck-3-dev
Version: 40.0-2
```

**Comment by raveit65** [comment]
My ideas are running out, but at least i could never reproduce the issue with fedora see my comment https://github.com/mate-desktop/mate-panel/issues/1271#issuecomment-974669512

**Comment by frankzen** [comment]
I was looking at comparisons in dconf-editor and I noticed this in Fedora. I don't know whether it is significant. In Debian there is no "prefs' sub-section like in fedora.
![fedora-dconf](https://user-images.githubusercontent.com/717662/148448647-4530bd2b-e2af-426a-9726-79fcb5a5c3c0.png)

**Comment by raveit65** [comment]
> The grouping only takes effect when there is very limited space. So maybe try to open a lot more terminal windows.

Confirmed, it is working here when i open about 18-19 terminal windows. That's a lot.

**Comment by raveit65** [comment]
@frankzen 
Can you please test i with a new fresh user account?

**Comment by raveit65** [comment]
> I was looking at comparisons in dconf-editor and I noticed this in Fedora. I don't know whether it is significant. In Debian there is no "prefs' sub-section like in fedora.

I think this folder will only created when you change something

**Comment by mbkma** [comment]
> > The grouping only takes effect when there is very limited space. So maybe try to open a lot more terminal windows.
> 
> Confirmed, it is working when i open about 18-19 terminal windows. That's a lot. Edit: Maybe it counts the place of all workspace ? Though `show only windows from current workspace` is selected.

As you can see in my gif, the grouping happens earlier if the window-list applet has very little space, i.e. if it is near to another applet.

**Comment by raveit65** [comment]
Yes of course i did understand your gif before. But with normal Fedora panel layout i have enough space to open 8-9 terminal windows, so i would expect that it starts grouping with the tenth window and not after 19 windows.
Any way, not a problem for me as i don't use the feature. No need to open so much terminals or other applications for one workspace ;)

**Comment by frankzen** [comment]
> @frankzen Can you please test it with a new fresh user account?

Yes you are right. A newly created user does not have that problem. However the always group windows does not work with the new user. Is there a way to fix without a total re-install ?

**Comment by raveit65** [comment]
@frankzen 
I think you need fresh new dconf settings.
First you can try to reset the panel with `mate-panel --reset --replace`

Whole dconf settings are saved in /run/user/1000/dconf/user.
You can try to delete this file in non graphic mode and not logged in as user from your root account.
But than you loose all settings.
Or check dconf manual for reset.
```
[rave@mother ~]$ dconf help

Usage:
  dconf COMMAND [ARGS...]

Commands:
  help              Show this information
  read              Read the value of a key
  list              List the contents of a dir
  write             Change the value of a key
  reset             Reset the value of a key or dir
  compile           Compile a binary database from keyfiles
  update            Update the system databases
  watch             Watch a path for changes
  dump              Dump an entire subpath to stdout
  load              Populate a subpath from stdin

Use 'dconf help COMMAND' to get detailed help.
```
But panel is using dynamically dconf path, so it isn't trivial to use this tool.

**Comment by raveit65** [comment]
Or try gsettings
```
[rave@mother ~]$ gsettings help   
Usage:
  gsettings --version
  gsettings [--schemadir SCHEMADIR] COMMAND [ARGS?]

Commands:
  help                      Show this information
  list-schemas              List installed schemas
  list-relocatable-schemas  List relocatable schemas
  list-keys                 List keys in a schema
  list-children             List children of a schema
  list-recursively          List keys and values, recursively
  range                     Queries the range of a key
  describe                  Queries the description of a key
  get                       Get the value of a key
  set                       Set the value of a key
  reset                     Reset the value of a key
  reset-recursively         Reset all values in a given schema
  writable                  Check if a key is writable
  monitor                   Watch for changes

Use ?gsettings help COMMAND? to get detailed help.
```

**Comment by lukefromdc** [comment]
It is possible to reset everything in a user account by moving all hidden (.something) files and directories to a backup directory, logging out, and back in. You can then restore items one by one looking for the problem to recur to save things like browser customization.

In other works, you can nuke the settings while keeping both the install and the data.

**Comment by frankzen** [comment]
> It is possible to reset everything in a user account by moving all hidden (.something) files and directories to a backup directory, logging out, and back in. You can then restore items one by one looking for the problem to recur to save things like browser customization. In other works, you can nuke the settings while keeping both the install and the data.

This is the method I picked - took some time to sort it all out but I am largely back to normal now. I am curious as to how the whole thing happened.
Thanks to all for the advice.

**Comment by raveit65** [comment]
I am so happy that we could help you.
