### ISSUE TITLE
Icons in notification area disappeared

### ISSUE THREAD

**Issue by fpoto** [mate-desktop/mate-panel#1280]
#### Expected behaviour
Until yesterday, Indicator Applet Complete uses to display a computer icon and icons for Telegram, Skype and Slack.

#### Actual behaviour
The computer icon is still there, but the other three icons do not display

#### MATE general version
1.24.1

#### Package version
mate-desktop-environment (1.24.0+4)

#### Linux Distribution
Debian testing (bookworm)

#### Link to bugreport of your Distribution (requirement)
https://bugs.debian.org/1001798

**Comment by raveit65** [comment]
From debian report this is is debian libappindicator specific, closing.
