### ISSUE TITLE
[need help] about add mate-applets to mate-panel. 

### ISSUE THREAD

**Issue by tumashu** [mate-desktop/mate-panel#1299]
Hi:

I use guix system, the problem I have faced is that:  mate-panel can not find the mate-applets.
so I want to know:  how to find the installed mate-applets for mate-panel, by environment variable?

thanks.

**Comment by raveit65** [comment]
This is a Bug reporting tool not a help support line. Ask your distro or take a look at https://wiki.mate-desktop.org/introduction/installation/

**Comment by tumashu** [comment]
wow, I am try to improve guix's mate-panel and mate-applets packages, so I need to know this info, but seem to get useless info :-\
