### ISSUE TITLE
Improve Windows List Thumbnail Positioning

### ISSUE THREAD

**Issue by billyswong** [mate-desktop/mate-panel#1315]
#### Expected behaviour
Position the window thumbnails horizontally near the center or exactly the center of each window items, similar to how the text tooltips adjust their position so that they won't feel sitting right between 2 window list items.

#### Actual behaviour
Current window thumbnails, if enabled, put its horizontal position exactly the center of where the mouse cursor first touch the window list item unless the thumbnail would have overflown outside display surface. It is confusing as which window list item an thumbnail belongs may be visually unclear. The inconsistent positioning that cares too much where my mouse begins the hovering is frustrating. I end up disabling this feature after experimenting it a few while in Linux Mint, whereas I feel no problem keeping it on in Windows 10.

#### Steps to reproduce the behaviour
Enable Window Thumbnails in Window List Preferences

#### MATE general version
1.26

#### Package version
mate-panel
1.26.1.1mint1+una

#### Linux Distribution
Linux Mint 20.3 Una 64-bit

#### Link to bugreport of your Distribution (requirement)
https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/where.html#mate-bugs-github-mate-desktop said I should report it right here unless it "relates to mintmenu, mintdesktop or a mint theme in MATE", so... I hope I am law-abiding here.

**Comment by lukefromdc** [comment]
This behavior (show the window preview at the mouse) comes from this code in `preview_window_position`
in window-list.c:

	```
/* Set position at pointer, then re-adjust from there to just outside of the pointer */
	gtk_window_set_position (GTK_WINDOW (tasklist->preview), GTK_WIN_POS_MOUSE);
	gtk_window_get_position (GTK_WINDOW (tasklist->preview), &x_pos, &y_pos);
```

My guess is getting the position of the left edge of the button may not be so easy, thus the author's use of the easily obtained mouse position. For menus, I know gtk_menu_popup_at_rectangle is quite a bit more complex to use than its alternatives such as the pointer. In this case problem would be getting the coordinates,which can change with every window opened or closed. Not sure how hard that really is

**Comment by balazs-endresz** [comment]
I've made some progress on this: https://github.com/balazs-endresz/mate-panel/commit/ced8ab2aec1095e2b3b04c5d0a350be4e4947bbf
It keeps previews centered above each button even when moving the applet or opening/closing windows.

Btw, it's not as noticeable as the previews but the tooltips are also positioned inconsistently (at least on ubuntu).
