### ISSUE TITLE
notification-area spams journal with "GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty: No such property ('org.kde.StatusNotifierItem.IconPixmap')"

### ISSUE THREAD

**Issue by greenhorse-effect** [mate-desktop/mate-panel#1318]
#### Expected behaviour
no journal spamming

#### Actual behaviour
it spams the Systemd journal like below:

    # journalctl -e 
    ... (omitted for brevity)
    Jul 13 21:51:52 greenhorse notification-ar[1209]: GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty: No such property ('org.kde.StatusNotifierItem.IconPixmap')
    Jul 13 21:51:52 greenhorse notification-ar[1209]: GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty: No such property ('org.kde.StatusNotifierItem.IconPixmap')

#### Steps to reproduce the behaviour
use MATE without KDE environment.

#### MATE general version
1.26.0

#### Package version
mate-panel package 1.26.2-1

#### Linux Distribution
Arch GNU/Linux

**Comment by lukefromdc** [comment]
Not getting this on Debian Unstable with mate-panel from git master as of 11-10-2022

**Comment by yangzhenyu-123** [comment]
The same error occurs when I set 'enable-sn-support' to true
# gsettings set org.mate.panel enable-sni-support true

**Comment by raveit65** [comment]
I do not get this warnings in f38 ans SNI enabled.
```
[rave@mother ~]$ journalctl -b0 | grep GDBus.Error:org.freedesktop.DBus.Error.UnknownProperty
[rave@mother ~]$ gsettings get org.mate.panel enable-sni-support
true
[rave@mother ~]$```

**Comment by rilian-la-te** [comment]
@greenhorse-effect @raveit65 there is some SNI applications which does not send some properties. Issue reporters need to send all apps which uses SNI in their installations to debug such errors.

**Comment by greenhorse-effect** [comment]
@rilian-la-te how can I find out SNI enabled apps?

**Comment by greenhorse-effect** [comment]
I found out the culprit of the journal spammer.  it was fcitx.  a similar issue was reported on a different place: https://github.com/swaywm/sway/issues/6276

So I think it's an irrelevant issue with mate-panel or mate-desktop, I close this issue with this comment.

**Comment by lukefromdc** [comment]
One that is known to work is mate-polkit when built with SNI support. Seems to be well-behaved on my setup. Also nm-applet will start in SNI mode with --indicator if built with SNI support. Both are daily drivers on my setup
