### ISSUE TITLE
[weird bug] expand deactivates under certain conditions

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-panel#1321]
#### Expected behaviour
The panel should remain expanded.

#### Actual behaviour
The expand option gets deactivated under certain conditions.

#### Steps to reproduce the behaviour

It's a weird one:
fire mpv. close it. Move mouse pointer over the panel, press keyboard key down. The panel compacts.
To reverse, open properties of the panel, deactivate and reactivate the button for expand panel.

They are possibly other important parameters to reproduce. WM is marco, with no compositing. My graphics don't look buggy (a bit old opengl 3.1),  It's a laptop from 2014.

#### MATE general version

MATE 1.24.1

#### Package version

1.24.1-2

#### Linux Distribution
Debian 11, amd64

#### Link to bugreport of your Distribution (requirement)

This doesn't look like a Debian bug.

**Comment by lukefromdc** [comment]
I could not by any means duplicate this on Debian Unstable on a modern desktop, even with marco and compositing turned off
