### ISSUE TITLE
[Not sure if bug or normal behaviour] gvfsd-trash --spawner goes to 100% CPU usage

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/mate-panel#1333]
Hi,

I sometimes have "gvfsd-trash --spawner" in htop show up at 100% CPU usage.

I am not sure why or how.

I believe it should not reach this; but perhaps the overall structure could be made more transparent
and perhaps even have an option to disable it. It reminds me a bit of baloo on KDE which also
causes some problems. Or perhaps someone can come up with a simpler but faster daemon.

Either way I just wanted to report it. It is the only misbehaving mate-desktop program. Even caja
works quite ok-ish, does not go to that 100% CPU range. (I have a 12 core and 32 GB Ram so
this should not be an issue, so I suspect something in the code for gvfsd-trash is wrong or
not optimal. I don't even know where this is though.)

**Comment by lukefromdc** [comment]
This sounds like a GVFS bug rather than a bug in Caja or the trash applet.

**Comment by zhuyaliang** [comment]
```sudo rm -fr ～/.local/share/Trash/*```

**Comment by lukefromdc** [comment]
Closing as bug is in GVFS
