### ISSUE TITLE
mate-panel not showing after moving monitors from internal gpu to external gpu.

### ISSUE THREAD

**Issue by eriksl** [mate-desktop/mate-panel#1334]
#### Expected behaviour

- my nicely configured panel at the bottom of the screen

#### Actual behaviour

- depending on my actions. initially no panel at all, even though the space for it is kept free by the window manager, with the desktop showing through. With some tweaking I can make it appear when I double the size of it. Half of it is still off-screen though and many things still don't work.

#### Steps to reproduce the behaviour

- move both 4k monitors (fysically) from internal Intel GPU connectors to external AMD graphics card. That is all I did. All of the rest still works, it's just the panel.

#### MATE general version

- 1.26 (Fedora 36)

#### Package version

mate-panel-1.26.2-2.fc36.x86_64

#### Linux Distribution

Fedora 36

#### Link to bugreport of your Distribution (requirement)

I will do that as soon as anyone is willing to help me get relevant information to do so. Mate-panel doesn't log anything and strace doesn't give anything useful too.

I already cleared all panel config repeatedly using a.o. mate-panel --reset. I reinstalled all relevant packages.

**Comment by lukefromdc** [comment]
Have you tried restarting the panel? In a mate-session, killing the panel with `killall mate-panel` will cause it to automatically restart.

**Comment by raveit65** [comment]
Is one monitor marked as primary display in `mate-display-properties` ?

**Comment by eriksl** [comment]
> Have you tried restarting the panel? In a mate-session, killing the panel with `killall mate-panel` will cause it to automatically restart.

Yes I have. I also did `mate-panel --replace &` and `mate-panel --reset` and re-login and reboot, several times.

**Comment by eriksl** [comment]
> Is one monitor marked as primary display in `mate-display-properties` ?

Yes it is.

It seems like the panel is there, but it isn't drawn.

**Comment by raveit65** [comment]
Does the issue exists in a new fresh user account?
Maybe there is a bad config setting in your home dir.
Is the panel running?
```
rave@mother ~]$ ps aux | grep mate-panel
rave        3103  0.9  0.2 2205168 83012 ?       Sl   11:20   0:02 mate-panel
```
Scaling is on?
```
[rave@mother ~]$ gsettings get org.mate.interface window-scaling-factor
2
```

**Comment by eriksl** [comment]
Now with scaling and without the env variables, no change.

```
(mate-panel:53173): Gtk-WARNING **: 16:38:37.851: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner WnckButton)
```
This looks suspicous.

**Comment by raveit65** [comment]
> Yes believe me the panel is running ;-). I can see blank space (well actually, transparent...)

Sorry, i only ask to eliminate possible problems, I don't know you skill level :)
You mean there is transparent area where the panel should be?
Can you right click on it?
If yes, this sounds like a graphic driver issue.
Transparent issues with applications can cause by graphic drivers.


> Now with scaling and without the env variables, no change.
> 
> ```
> (mate-panel:53173): Gtk-WARNING **: 16:38:37.851: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner WnckButton)
> ```
> 
> This looks suspicous.

I think this is a warning from an applet (possible nm-applet) in notification_area. All basic applets are compiled in-process. This means you see only one process of the panel with all basic applets, like clock, workspace-switcher, notification_area, fish, windows-list and window-menu.

Did you check the behaviour with a new account, to be sure there is no old forgotten config in you home dir?
How did you arrange you displays? left to right or top to bottom?

**Comment by eriksl** [comment]
Sorry for sounding harsh, it wasn't meant this way and I really appreciate your help!

I think somewhere there is a bit of configuration that's messed up, but I can't think of anything remaining. I checked (and reset to defaults) all I could find with dconf-editor, department mate-panel (not much very interesting there). I used find and grep to find all files in my home directory that could be related but found none, actually. Where does mate-panel look for configuration items other than there? I even did an strace to find all the files it opens, but it really doesn't that, apparently. I am now trying ltrace.

What's interesting is that after the mate-panel --reset, I still some of my original items in the panel (occasionally, when I can see a part of the panel), which to suggests somewhere there is still some configuration left. Now, where is it ;-)

What I also did is an rpm check for checksum of all installed files. Who knows there is some corruption going on. It's still running.

So, about your questions:

- yes there is a transparent area where the panel is supposed to be and windows can't be placed there. So apparently that part is working.
- right clicking there is something I did, indeed, I was wondering too. The result is the menu of the desktop, not that of the panel (unfortunately)
- graphic drivers: I have been using this configuration before (AMD WX2100 GPU with two 4k monitors over DP). No problems then. No fundamental changes in the meantime. No other issues too.
- my monitors are left-right, where "left" is the "primary".

**Comment by raveit65** [comment]
So, this configuration did work some times before, you tested intel driver and switched back.

Easiest is to check with `dconf-editor` all gsettings key for the panel. It is all in org/mate/panel/ path.
But i recommend to test it first with a new fresh user account. If the issue isn't reproducible there than something is wrong in your home dir.

**Comment by raveit65** [comment]
Try `mate-panel  --reset --replace` in one command.
I recall both are needed otherwise reset doesn't work correctly.
I think the transparent background settings are not store in dconf, but i don't know where or if this is stored in home dir.
The hard way to clean up (all) dconf settings  is to rename (saving) and remove the dconf user config file from console without a user x11 session.
```
[rave@mother ~]$ ls -l ~/.config/dconf/user 
-rw-r--r-- 1 rave rave 239185 21. Sep 18:33 /home/rave/.config/dconf/user
```
and
```
[rave@mother ~]$ ls -l /run/user/1000/dconf/user 
-rw------- 1 rave rave 2 21. Sep 18:44 /run/user/1000/dconf/user
```
Than start x11 session again.
I am pretty sure it's a dconf setting.
Well, after this test you can restore old user dconf settings.
That's the way i would debug the issue.

Sorry, i searched my home dir for another panel config file but there isn't one

**Comment by eriksl** [comment]
Well, I seem to have touched something important now. I have set lots and lots of dconf settings to "default", just all of them, not just the panel ones and at a certain moment, it just appeared!

So I am now going to log out and log in and see if it still works...

Fingers crossed!

**Comment by eriksl** [comment]
Yep, remains working. Pfew!

Thanks for your help!
