### ISSUE TITLE
mate-panel Fedora 37

### ISSUE THREAD

**Issue by mattdrepo** [mate-desktop/mate-panel#1340]
Just a quick one:

Could anyone here give a quick run down as to what is needed (requirements wise) to install the latest mate-panel from source on Fedora 37?

I have run into a few requirements I cannot track down (due to references to Ubuntu deb packages).

I am *hoping* this will fix the current issue I have with running the available mate-panel in the Fedora repo that doesn't allow for a task bar or window manager under sway?

If this is still unresolved, I'll kindly delete this.

Thanks for all your efforts to date!

**Comment by balazs-endresz** [comment]
Have you tried these? https://github.com/mate-desktop/mate-panel/blob/master/.build.yml#L61-L82

**Comment by mattdrepo** [comment]
thanks that helped. I mistakenly earlier used the wrong terminology though - (probably lack of sleep!), sadly after getting it to install I still cant see options for a workspace switcher, window selector, or notification area.

Back to the drawing board!

**Comment by raveit65** [comment]
Why not using fedora configure options?
https://src.fedoraproject.org/rpms/mate-panel/blob/rawhide/f/mate-panel.spec#_97
`mate-panel --reset --replace` gives you the default applets.
Closing as it isn't a bug report.
