### ISSUE TITLE
[Feature Request] Display a separate clock for different time zone

### ISSUE THREAD

**Issue by u00101010** [mate-desktop/mate-panel#1345]
Hey there!

As of right now, I found no way to change the default clock applet to display a world clock instead of the system time zone. The only option is to add the city to a list that shows up when we click on the applet, under the calendar. The only other ways I found was to actually change the system clock to a different time zone but that's also not what I want. I would like to add a separate clock next to the local one that shows the time in an other city so I can see it at a glance and wouldn't have to click on a menu to see. Though personally I see that this might be an unusual use case, I believe it would help people who have relatives abroad or work remotely.

Is there an already existing solution somehow that I might have missed? 

Thank you so much in advance!

**Comment by lukefromdc** [comment]
The applet as currently designed shows only the "home" time zone, does not have an option to show another. The "home" time zone can be changed from the calendar when open with two or more locations showing, but that's it.

**Comment by raveit65** [comment]
Adding another city for another time zone should be enough.
We do not add a second clock.
