### ISSUE TITLE
"Reset All Panels" broken in Ubuntu 22.04, and Ubuntu 22.10

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/mate-panel#1365]
After spending 6 hours with virtual machine evaluation, I have finally submitted a bug report that should have sufficient with information to help us find the cause of the behavior: https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/2017319

If someone would like to help me to dig further, I'd be very grateful.

**Comment by davidhedlund** [comment]
Are you aware of this bug?: https://ubuntu-mate.community/t/window-list-applet-is-occasionally-unresponsive/23791

For me:

![Screenshot at 2023-04-24 00-08-43](https://user-images.githubusercontent.com/6416073/233869072-f67c8c12-bde6-4540-9dc2-eb9273b14f7a.png)

Entries listed by the Window List (Virtual Machine Manager, Control Center, LibreOffice-Calc, etc on the screenshot) sometimes they get unresponsive when I'm clicking on them.

**Comment by davidhedlund** [comment]
Is "Window List" part of the package `mate-window-menu-applet` or `mate-panel`?

**Comment by lukefromdc** [comment]
That's part of mate-panel, part of the wncklet applet which includes window-list, window selector, workspace switcher, and show desktop applets. Named for use of libwnck, which allows interaction with the window manager.

**Comment by lukefromdc** [comment]
Does this occur ONLY when you have the window buttons double-stacked (2-level)?

**Comment by lukefromdc** [comment]
Panels not coming back up on reset sounds like mate-panel somehow locking up. If it crashed the 
session manager would restart it and the panels would reappear.

Unfortunately, I have no landline and thus cannot download OS images to test for bugs in new installs

**Comment by davidhedlund** [comment]
> Panels not coming back up on reset sounds like mate-panel somehow locking up. If it crashed the session manager would restart it and the panels would reappear. 

Thanks, I added `Open another terminal with CTRL+ALT+F1. Sign in with your user and password. run "$ killall mate-session". Hit CTRL+ALT+F7, so log in with LightDM to MATE again.` to https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/2017319

Unfortunately, I have no landline and thus cannot download OS images to test for bugs in new installs

If you have ideas, just tell me and I'll try them. I'm very happy with your help!

**Comment by davidhedlund** [comment]
> 
Thank you! I can find it here: https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/window-list.c

**Comment by davidhedlund** [comment]
> That's part of mate-panel, part of the wncklet applet which includes window-list, window selector, workspace switcher, and show desktop applets. Named for use of libwnck, which allows interaction with the window manager.

Thank you! I can find it here: https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/window-list.c

**Comment by davidhedlund** [comment]
> That's part of mate-panel, part of the wncklet applet which includes window-list, window selector, workspace switcher, and show desktop applets. Named for use of libwnck, which allows interaction with the window manager.

I'm a bit confused. Look at my findings in https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/2017319
```
* ubuntu-22.10-desktop-amd64.iso (mate-panel 1.27.0-0ubuntu1, mate-window-menu-applet 21.04.0-1): Bug reproduced
* ubuntu-23.04-desktop-amd64.iso (mate-panel 1.27.0-0ubuntu1, mate-window-menu-applet 21.04.0-1): Bug NOT reproduced. 
```

**Comment by lukefromdc** [comment]
mate-window-menu-applet is part of
https://github.com/ubuntu-mate/mate-window-applets
which is maintained by Ubuntu not by us.

**Comment by lukefromdc** [comment]
"Reset all panels" is part of mate-panel itself.

**Comment by davidhedlund** [comment]
> "Reset all panels" is part of mate-panel itself.

Thanks.

**Comment by davidhedlund** [comment]
@lukefromdc I could not reproduce the bug in ubuntu-23.04-desktop-amd64.iso. Should I close this issue or should we keep it open?

**Comment by lukefromdc** [comment]
I think we can close this

**Comment by davidhedlund** [comment]
> I think we can close this

Sorry, I can still not reset the panels.

**Comment by davidhedlund** [comment]
![Screenshot at 2023-05-28 07-12-27](https://github.com/mate-desktop/mate-panel/assets/6416073/cfafe2c9-45c5-4cda-9cb1-45aeb785f43a)
