### ISSUE TITLE
panle clock 12-hour format

### ISSUE THREAD

**Issue by stephenboston** [mate-desktop/mate-panel#1367]
#### Expected behaviour
Preferences to offer option for 12-hour display

#### Actual behaviour
No such option

#### Steps to reproduce the behaviour

Open Clock preferences 
#### MATE general version
mate-common 1.26.01

#### Package version

mate-desktop-1.26.1-1
#### Linux Distribution

Linux 6.2.13-arch1-1

**Comment by lukefromdc** [comment]
Here is is, in mate-panel's clock applet from git master(1.27) as of this posting:
![clock_prefs](https://user-images.githubusercontent.com/14036792/235633776-058cc143-b3cc-40fb-a635-11988ab14a94.jpg)

**Comment by stephenboston** [comment]
I see now  this, in the clock help:

     `This option is not shown if your session language does not use the 12 hour clock.`

**Comment by lukefromdc** [comment]
No problem. That in fact is a MATE feature I just learned of, never seeing it because I only use one language and it didn't break on the GTK2->GTK3 transition
