### ISSUE TITLE
expanded callendar applet not visible when any app is full screen

### ISSUE THREAD

**Issue by Stormfinger** [mate-desktop/mate-panel#1368]
#### Expected behaviour
applets should always be on top of all applications even if applications are full screen.

#### Actual behaviour
sometimes i know there is expaned calender applet visible and on top but sometimes its behind an application ...it could be that inform7 somehow messes with panels couse sometimes inform7 makes my main panel invisible..it could be due low end graphic card im not sure. 

#### Steps to reproduce the behaviour
it seems like it happens sometimes i cant willingly repeat steps.

#### MATE general version
MATE 1.26.0

#### Package version
1.26.0-1

#### Linux Distribution
debian bookworm

**Comment by raveit65** [comment]
When an application is i full-screen mode it is always on top of all others. Normal behavior.

**Comment by lukefromdc** [comment]
Closing as this is intended/normal behavior and anything from the panel opening over a fullscreened app (e.g a video) would be considered a bug somewhere)
