### ISSUE TITLE
Build: org.mate.panel.TestApplet.mate-panel-applet generation fails with gettext 0.22

### ISSUE THREAD

**Issue by rezso** [mate-desktop/mate-panel#1373]
--desktop and -d options not allowed in gettext 0.22, so the generation of desktop file fails.
Because of this file (and the test applet) not installed, I currently simply removed the org.mate.panel.TestApplet.mate-panel-applet generation from Makefile.am, but this is an ugly workaround.

**Comment by jlocash2** [comment]
The actual error during build:
```
  GEN      org.mate.panel.TestApplet.mate-panel-applet
/usr/bin/msgfmt: no input file should be given if --desktop and -d are specified
Try '/usr/bin/msgfmt --help' for more information.
make[3]: *** [Makefile:1035: org.mate.panel.TestApplet.mate-panel-applet] Error 1
make[3]: Leaving directory '/tmp/build/mate-panel-1.26.3/libmate-panel-applet'


```
The error message is misleading. Here's a simple fix.  Before running configure, run
  sed -i 's/keyword /keyword=/g' libmate-panel-applet/Makefile.in

msgfmt changed in gettext-0.22.  See https://www.gnu.org/software/gettext/manual/html_node/msgfmt-Invocation.html#Desktop-Entry-mode-operations

**Comment by lukefromdc** [comment]
I don't know enough about the I18n stuff to work on this. It needs to be fixed though as this report is of build failures

**Comment by raveit65** [comment]
Fixed with https://github.com/mate-desktop/mate-panel/commit/5a7f770082568453f3a5f271a274156f08352101
