### ISSUE TITLE
[Feature Request] How to identify parallel panels 

### ISSUE THREAD

**Issue by stephenboston** [mate-desktop/mate-panel#1376]
#### Expected behaviour

If I have two top panels, one below the other, I want to be able to set properties for them through dconf or gsettings. For example I want to be able to 'hide them' via the CLI.

#### Actual behaviour
dconf does not distinguish between the two panels. 

     /org/mate/panel/toplevels/top/ 

   is all we have.

#### Steps to reproduce the behaviour
Given

#### MATE general version
mate-common 1.26.0-1

#### Package version

mate-panel 1.26.3-1

#### Linux Distribution
6.3.9-arch1-1

**Comment by cwendling** [comment]
Normally you should have the list of toplevels with `gsettings get org.mate.panel toplevel-id-list`  Then, you can use the corresponding relocatable schema to play with it, e.g. `gsettings set org.mate.panel.toplevel:/org/mate/panel/toplevels/bottom/ auto-hide false` (replace `bottom` with the toplevel ID you want).
Panel positions should have nothing to do with this, and I can indeed have as many top-oriented panels as I want and they'll appear just fine.
