### ISSUE TITLE
Fail to build using new gettext / gettext-tools 0.22

### ISSUE THREAD

**Issue by fulalas** [mate-desktop/mate-panel#1381]
Error: `/usr/bin/msgfmt: "no input file should be given if..."`

`eom` also fail to build with error: `/usr/bin/msgfmt: cannot locate ITS rules for eom.appdata.xml.in`

By reverting both gettext and gettext-tools to 0.21.1 everything works.

I'm using Slackware x64 current.

**Comment by raveit65** [comment]
Try https://github.com/mate-desktop/mate-panel/commit/5a7f770082568453f3a5f271a274156f08352101

**Comment by fulalas** [comment]
Thanks!

Any plans to release MATE 1.27.2 with this hotfix?

**Comment by raveit65** [comment]
Mate 1.27.x is a developer release. As developer you should able to use patches or build from master :)
Well, if enough commits are there for a new release we will make it.
I will make a new release for stable 1.26.

**Comment by fulalas** [comment]
Oh, I didn't know 1.27.x is a developer release. It makes sense now :)

Thanks!
