### ISSUE TITLE
wayland: tray icons does not appear in notification-area

### ISSUE THREAD

**Issue by Sunderland93** [mate-desktop/mate-panel#1382]
#### Expected behaviour
SNI-based tray should work, app icons (e.g. Telegram, QBitTorrent or nm-applet) should be displayed in `notification-area`

#### Actual behaviour
`notification-area` is empty in Wayland session, but works great on X11

#### Steps to reproduce the behaviour
1) build `mate-panel` with Wayland support and `--in-process-applets=all option`
2) run mate-panel on any wlroots based compositor (I use LabWC)
3) add `gtk-menu-images = true` and `gtk-button-images = true` lines in `~/.config/gtk-3.0/settings.ini`
4) relogin to session (or restart) and launch some application that uses SNI-based tray icon (e.g. Telegram)

#### MATE general version
1.26.0

#### Package version
"git master"

#### Linux Distribution
Debian 12 with MATE desktop (some packages built from git master with Wayland support)

#### Link to bugreport of your Distribution (requirement)
n/a

**Comment by Sunderland93** [comment]
I tried to launch LabWC with dbus-launch, but result is the same

**Comment by raveit65** [comment]
Only icons with sni are working ie. `nm-applet --indicator`, see https://github.com/mate-desktop/mate-panel/commit/e61dad01e852d7913f4c9b3dae508088e3e7b287
Legacy system tray in Wayland requires xembed.
So this is not an issue :)

**Comment by Sunderland93** [comment]
`nm-applet --indicator` does not work

**Comment by raveit65** [comment]
Here with fedora it is working. Is it compiled with sni support?

**Comment by Sunderland93** [comment]
mate-panel is compiled with` --enable-wayland and` `--in-process-applets=all`. Is there a separate option to enable SNI?

**Comment by lukefromdc** [comment]
SNI can be turned on and off by a gsettings preference in dconf-editor

**Comment by Sunderland93** [comment]
Thank you! I enable SNI in dconf-editor and now icons correctly displayed in notification-area!
