### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by stephenboston** [mate-desktop/mate-panel#1384]
#### Expected behaviour

Scrollbars are unnecesary in eom because we can already move the image with the mouse.  

They are undesireable in screenshots.

**Comment by raveit65** [comment]
I love scrollbars.....

**Comment by wmzart** [comment]
Scrollbars at least give an indication which areas are scrollable and how far can be scrolled. I think they are therefore useful.

**Comment by lukefromdc** [comment]
This would need to be moved to EOM if it was something we were going to change. Closing as we don't intend to change this anyway
