### ISSUE TITLE
Removed desktop files are not removed from the panel interactively after package removal

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/mate-panel#1396]
#### Expected behaviour
* In Ubuntu 23.04 Favorite (icons) are removed right away after a package has been removed (see Ubuntu-*.png) -- This bug also affects Ubuntu 22.04.

#### Actual behaviour
* In Ubuntu MATE 23.04 Panel (icons) are NOT removed right away after a package has been removed (see Ubuntu_MATE-*.png) -- This bug also affects Ubuntu MATE 22.04. This bug has nothing to do with snap that is related to the default installed firefox package. It affects any item. For example, you can
** right-click on the Panel and select "Add to Panel" -> "Application Launcher..." and click on "Accessories -> MATE Calculator", and then click on "Add"
** "apt-get remove mate-calc"

#### Steps to reproduce the behaviour
When you uninstall a package, that has an icon that is marked as extra visible:

#### MATE general version
1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu MATE 22.04, 23.04

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/2028577

**Comment by raveit65** [comment]
Ubuntu packaging bug. Not under our control.
