### ISSUE TITLE
The "Notification Area" cannot be removed

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/mate-panel#1398]
#### Expected behaviour
Add a "Remove" button to the "Add to Panel":
![image](https://github.com/mate-desktop/mate-panel/assets/6416073/320e98a8-a539-42cd-8d1a-3dec47b80ff5)

#### Actual behaviour
I could not remove the "Notification Area"

#### Steps to reproduce the behaviour
To remove "Indicator Applet Complete" you first mouse right-click it and select uncheck "Lock To Panel" to it, and then you mouse right-click it again and select "Remove From Panel". However, for the"Notification Area", this is not possible:
* Right mouse-click on program icons in the "Notification Area" is reserved for program options (for example this is how you quit programs, you can try this with the package _workrave_).
* Left-mouse click will open the programs in the  "Notification Area".

#### MATE general version
1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu MATE 23.04

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/+bug/2030265

**Comment by davidhedlund** [comment]
* https://github.com/mate-desktop/mate-panel/issues/1399

**Comment by lukefromdc** [comment]
The "Add to Panel" dialog does not include code to remove ANY applet, this is done from the right-click menu of each applet instead. Thus the name "Add to Panel" instead of "Manage Panel Applets" or something along those lines,

**Comment by davidhedlund** [comment]
> The "Add to Panel" dialog does not include code to remove ANY applet

I'm aware of that. It was my suggestion.

> this is done from the right-click menu of each applet instead

Unfortunately, that cannot be done for the "Notification Area".

**Comment by lukefromdc** [comment]
There is supposed to be a "handle" on the left edge of both the window list and the notification area, defaulting to a line of three dots vertically. Clicking on that raises the applet context menu. If you are not seeing the handle, open an issue against the theme you are using as that's where the problem would be.

**Comment by davidhedlund** [comment]
> There is supposed to be a "handle" on the left edge of both the window list and the notification area, defaulting to a line of three dots vertically. Clicking on that raises the applet context menu. If you are not seeing the handle, open an issue against the theme you are using as that's where the problem would be.

Cool! Can you please upload a screenshot?

**Comment by lukefromdc** [comment]
I circled the three dots in this image of mate-panel's tray with the Menta theme in use
![Three_Dots](https://github.com/mate-desktop/mate-panel/assets/14036792/dd097853-b735-486c-8881-53ea09eb6b13)

**Comment by davidhedlund** [comment]
> I circled the three dots in this image of mate-panel's tray with the Menta theme in use. Click on those, and the applet menu should come up. If your theme doesn't support them, the empty space might still be there and clickable 

We're almost there! But it's not visible in Ubuntu MATE 22.04, or Ubuntu MATE 23.04 (mate-panel 1.27.0). Here's an Ubuntu MATE 23.04 screenshot (with the workrave package installed):
![image](https://github.com/mate-desktop/mate-panel/assets/6416073/25f1a735-01ed-4c89-b6f2-c2054df70f4e)

**Comment by davidhedlund** [comment]
Same issues with the Menta that comes with Trisquel 11 (a distro based on Ubuntu MATE 22.04). Where did you download the Menta theme from (specific download link)?

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-themes
You may be dealing with an issue with an Ubuntu theme, and if Menta works you should file an issue against the Ubuntu theme in question

**Comment by davidhedlund** [comment]
> I circled the three dots in this image of mate-panel's tray with the Menta theme in use. Click on those, and the applet menu should come up. If your theme doesn't support them, the empty space might still be there and clickable ![Three_Dots](https://user-images.githubusercontent.com/14036792/258614132-dd097853-b735-486c-8881-53ea09eb6b13.jpg)

Finally I figured it out! I filed it:
* https://github.com/ubuntu/yaru/issues/3971

**Comment by davidhedlund** [comment]
> https://github.com/mate-desktop/mate-themes You may be dealing with an issue with an Ubuntu theme, and if Menta works you should file an issue against the Ubuntu theme in question

Finally, I figured it out! I filed it:
* https://github.com/ubuntu/yaru/issues/3971

**Comment by davidhedlund** [comment]
> I circled the three dots in this image of mate-panel's tray with the Menta theme in use. Click on those, and the applet menu should come up. If your theme doesn't support them, the empty space might still be there and clickable ![Three_Dots](https://user-images.githubusercontent.com/14036792/258614132-dd097853-b735-486c-8881-53ea09eb6b13.jpg)

You are correct, I could remove the notification area that way:

![image](https://github.com/mate-desktop/mate-panel/assets/6416073/6c385bb1-d75b-4812-b70e-a5fb189bb4cb)

**Comment by davidhedlund** [comment]
It should be noted mate-themes version 3.22.23-1 is packaged for both Ubuntu MATE 22.04 and Ubuntu MATE at this writing and still:
* The "handle" is not visible in _any_ theme in Ubuntu MATE 22.04.
* The "handle" is visible for _all_ themes in Ubuntu MATE 23.04.

**Comment by davidhedlund** [comment]
* https://github.com/mate-desktop/mate-panel/issues/1403
