### ISSUE TITLE
Panel Properties ->  Background [tab]: gsettings does not update the "Style" (transparent-opaque) knob

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/mate-panel#1408]
#### Expected behaviour
The "Style" knob should be placed in the center.

#### Actual behaviour
The "Color" is updated, but not the "Style" knob:

![Screenshot at 2023-10-05 20-34-12](https://github.com/mate-desktop/mate-panel/assets/6416073/c91b573d-a540-4a64-bd0b-02e314bf1a09)

#### Steps to reproduce the behaviour
Set solid color

![Screenshot at 2023-10-05 20-33-35](https://github.com/mate-desktop/mate-panel/assets/6416073/8d547ab8-71c4-4d0a-aa3a-aa9a4188e8d0)

* Run this from the terminal: `gsettings set org.mate.panel.toplevel.background:/org/mate/panel/toplevels/top/background/ color 'rgba(0,0,0,0.500)'`

#### MATE general version
1.26.0

#### Package version
1.26.2-1

#### Linux Distribution
Ubuntu MATE 22.04

**Comment by lukefromdc** [comment]
CONFIRMED here-and same behavior on wayland as well. The panel color and opacity are instantly updates, as is the shown color in the dialog but not the knob position. Note that this issue occurs ONLY if the dialog is showing while the gsettings value is being set from the command line. If the dialog is NOT showing, opening it brings it up with the correct knob position, meaning that widget and that widget alone is not being reset when the rest of the dialog listens for and reacts to a change

**Comment by davidhedlund** [comment]
Thank you very much guys!
