### ISSUE TITLE
Weather does not work anymore

### ISSUE THREAD

**Issue by CHJ85** [mate-desktop/mate-panel#1427]
The weather ain't showing in neither of the two panel applets. Not the time and date applet nor the separate weather applet. 
My distro is Ubuntu MATE. So Idk if this issue has been fixed but not pushed out yet.

**Comment by lukefromdc** [comment]
This is actually a libmateweather issue, not mate-panel and there have been updates to address the URL's the weather is fetched from changing. These are in the libmateweather 1.26.3 release, if Ubuntu-MATE hasn't picked that up you won't have it. Note that versions older than 1.26 are no longer supported as our team is too small to support multiple stable versions at this time.

**Comment by raveit65** [comment]
File out an report at ubuntu bug system and remember them to update their packages.

**Comment by CHJ85** [comment]
What's the name of the file within the package "libmateweather 1.26.3", so that I can simply replace the URL from the newer package? I found the package in question on packages.ubuntu.com. But upgrading the package would be a dependency hell. So I'm not going to do that.

**Comment by raveit65** [comment]
Simply download the source package from https://github.com/mate-desktop/libmateweather/releases/tag/v1.26.3
Again, please file out a report at ubuntu. That current LTS, 23.04 and 23.10 do not have the bugfix is not correct and user friendly.
I mean why we should spend our spare time to release a bugfix when maintainer from one of the biggest deb-based distro don't use them?
....sigh.
