### ISSUE TITLE
Clock applet fails to load on Wayland

### ISSUE THREAD

**Issue by DMJC** [mate-desktop/mate-panel#1428]
#### Expected behaviour
Clock applet appear in mate-panel and display the time

#### Actual behaviour
Clock applet fails to appear

#### Steps to reproduce the behaviour
Run wayland on Debian Trixie with mate-panel.

#### MATE general version
1.27

#### Package version
1.27.1-2

#### Linux Distribution
Debian 13 Trixie

**Comment by lukefromdc** [comment]
Found the problem by downloading and opening  Debian's mate-panel_1.27.1-2_amd64.deb:
They built the clock,fish, wncklet, and notification area out of process. Out of process applets use 
Xembed which cannot work on wayland so the applets cannot be loaded.

For wayland support these applets (and all others) need to be built in-process and with 
wayland support. You can ask Debian to build for wayland as well as x11, or if you don't
want to wait compile mate-panel, mate-applets, and mate-media yourself with the in-process and 
wayland options turned on as needed.

mate-utils also ships an applet (dictionary applet) to which the same considerations apply, as does
mate-notification daemon (do not disturb applet).
