### ISSUE TITLE
Regression: panel launcher position are not stored after moving the launcher

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-panel#1430]
#### Expected behaviour
Panel launcher position should be stored after moving the launcher and a panel restart.

#### Actual behaviour
Panel launcher position are not stored after moving the launcher and a panel restart.

#### Steps to reproduce the behavior
1. add much panel launcher in a row to the panel like eg. this
![mate-panel_launcher_row](https://github.com/mate-desktop/mate-panel/assets/961604/f819d76f-2049-4fc4-8663-9ec3503e057c)
2. move a launcher from the row to another position
3. Restart the panel with a `killall mate-panel` in terminal
4. Boom, the launcher isn't anymore at the new position

Sometimes it works better when moving the launcher to right direction, but not in all cases.
And it is very hard to select the new position during moving.
For me this is really a show stopper for a new major release, because moving a launcher will be done very often and it breaks the desktop appearance.

I could track down the issue to those commits
[Fix center- and right-sticking of expanding applets](https://github.com/mate-desktop/mate-panel/commit/7b1b00d5ddffc349ca117843bd0d015e9fb08a89)
[Add "center-stick" capability applets on the panel](https://github.com/mate-desktop/mate-panel/commit/38e00280e9d17282717595a05411736a308804c0)

Sadly simply reverting the commits is impossible, i had to revert some more unrelated commits to get this working :/
[Constify some pointer references in locals](https://github.com/mate-desktop/mate-panel/commit/b91376262abb56d95f9ec86993edaa8e9fb2cc1a)
[Reduce scope of more code](https://github.com/mate-desktop/mate-panel/commit/655a8f484598a07a210dc56f1662021f8be69737)
[Avoid a redundant NULL check](https://github.com/mate-desktop/mate-panel/commit/17b87e321bfca409c31ce4b4e0e3326eeef92b88)
[Reduce scope of variables](https://github.com/mate-desktop/mate-panel/commit/96c7ebc6dc9e8b8327db04a9570054ee78743353)

For better testing i created a branch with all those commits reverted.
https://github.com/mate-desktop/mate-panel/commits/revert-launcher-progress_real/
You will see that moving a launcher works well again. Same like with stable 1.26 branch
I know that reverting the unrelated commits isn't a solution and they have to add again.
So best solution might be to find a fix for this buggy behavior.

#### MATE general version

master
#### Package version
master

#### Linux Distribution
all

#### Link to bugreport of your Distribution (requirement)
Thanks god that this isn't released!

**Comment by lukefromdc** [comment]
With a row of 8-10 launchers between the menu and window list left side of a bottom panel, on Debian Unstable I've never had trouble with launcher positions not being saved.

When I get home tonight will test a 2nd panel many launchers and nothing else on it. If they stay put we need to find out what is different between my case and where the problem appeas

**Comment by raveit65** [comment]
Here is a small video (862,1 KB) with 5 panel launcher in the row. See what happens.
https://www.dropbox.com/scl/fi/k1fdbvadyev9vu2xvfvy4/panel_launcher-2024-01-28_17.44.08.mp4?rlkey=dm70h5ugzwgtp2g6wo63h90jw&dl=0
This is will collection menu enabled, but the issue still exists without collection menu.

**Comment by lukefromdc** [comment]
Just tested with a row of launchers on a top panel for testing. May have seen this issue once, then could not duplicate it (under wayland anyway) even under same conditions as the video. Will now try it in x11

**Comment by lukefromdc** [comment]
A little easier to invoke it under x11 (though sample size is small here), but was not consistant. Seems that it's when launchers are "spring loaded" against oneanother is when this is most likely to happen. The reason I've never seen this before then would be the fact that all of my normal launchers are part of a hand packed arrangement that avoids the "springy" condition entirely on the left side of the panel.

This part of the code (applet spacing) is not one I have much of an understanding of.

**Comment by raveit65** [comment]
@thesquash 
Huston we got a problem.
