### ISSUE TITLE
Some applets not showing on the panel (X11 session)

### ISSUE THREAD

**Issue by wiwyil2tr** [mate-desktop/mate-panel#1441]
#### Expected behaviour

All applets display normally on the panel
#### Actual behaviour
The panel only displays applications, places and system menus, and all other items (like system tray, window list)are not shown. Even after resetting the panel, it remains the same, and manually adding items also does not display them. But i can add custom launchers to the panel.

![image](https://github.com/mate-desktop/mate-panel/assets/108447154/e4394237-c2b1-440e-a33b-1334bbcec503)
![image](https://github.com/mate-desktop/mate-panel/assets/108447154/9a75a455-17ab-4f2a-b6b1-5b7a7c0981af)
![image](https://github.com/mate-desktop/mate-panel/assets/108447154/a923c125-6df0-4eb0-ac65-524bbf9d6c01)
#### Steps to reproduce the behaviour

Run mate-panel on X11

#### MATE general version
1.28.2

#### Package version
1.28.1-1

#### Linux Distribution
Arch Linux

#### Link to bugreport of your Distribution (requirement)

https://gitlab.archlinux.org/archlinux/packaging/packages

**Comment by lukefromdc** [comment]
This could be either a problem in your configuration (hidden) files, or a broken build. Create a new user, log into MATE as that new user and see what happens. If you get a fully loaded panel, your configuration files are the problem, and it's something where resetting the panel doesn't work (e.g. the offending directory accidently claimed by root while running something as root). In that case, move all of your hidden files to a backup directory, log out and back in and see if this is fixed. Otherwise an issue in the build is likely.

**Comment by wiwyil2tr** [comment]
> This could be either a problem in your configuration (hidden) files, or a broken build. Create a new user, log into MATE as that new user and see what happens. If you get a fully loaded panel, your configuration files are the problem, and it's something where resetting the panel doesn't work (e.g. the offending directory accidently claimed by root while running something as root). In that case, move all of your hidden files to a backup directory, log out and back in and see if this is fixed. Otherwise an issue in the build is likely.

It seems like there might have been an problem with my user account. It may be that the directory permissions are configured incorrectly. Even after moving the configuration files elsewhere and logging in again, the issue persisted. 
But when i logged in with a different user, the panel displayed normally and when i moved the configuration files to another user account, everything worked fine. Finally, switching to a different user account and moving all the files from the old user there resolved the issue. Thank you for your answer.
