### ISSUE TITLE
Where does Mate "Window List" get the summary application name from?

### ISSUE THREAD

**Issue by Betterbird** [mate-desktop/mate-panel#1449]
I'm the maintainer of Betterbird. On Mate, when grouping windows in the Windows list, this is displayed:
![image](https://github.com/user-attachments/assets/30dc006a-71e4-4fed-a4f6-057fc68e8f4b)

Can you please let us know where the "Thunderbird" string is taken from.

`xprop` shows no Thunderbird:
```
WM_CLIENT_MACHINE(STRING) = "betterbird-vm"
WM_CLASS(STRING) = "Mail", "betterbird"
WM_ICON_NAME(STRING) = "Inbox - Unified Folders - Betterbird"
_NET_WM_ICON_NAME(UTF8_STRING) = "Inbox - Unified Folders - Betterbird"
WM_NAME(STRING) = "Inbox - Unified Folders - Betterbird"
_NET_WM_NAME(UTF8_STRING) = "Inbox - Unified Folders - Betterbird"
```

Original complaint here:
https://www.reddit.com/r/Betterbird/comments/1e6k2xj/comment/leeo4w7/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by balazs-endresz** [comment]
I think those tooltips are handled by libwnck: https://gitlab.gnome.org/GNOME/libwnck/-/blob/master/libwnck/tasklist.c#L3806
This sounds relevant too: https://gitlab.gnome.org/GNOME/libwnck/-/blob/master/libwnck/class-group.c#L666-672

**Comment by Betterbird** [comment]
Hmm, this is twisted, they use `wnck_application_get_name()` and `wnck_window_get_name()`:
https://gitlab.gnome.org/GNOME/libwnck/-/blob/master/libwnck/class-group.c#L288
https://gitlab.gnome.org/GNOME/libwnck/-/blob/master/libwnck/class-group.c#L325
The former is here:
https://gitlab.gnome.org/GNOME/libwnck/-/blob/master/libwnck/application.c#L261
and the latter is here:
https://gitlab.gnome.org/GNOME/libwnck/-/blob/master/libwnck/window.c#L617
In both cases the name is obtained from `-priv->name`.

For example here
https://searchfox.org/mozilla-central/rev/de46cd99a7d1634058b511a3f546a970763e5048/widget/gtk/nsWindow.cpp#6396
the window is given a name from `gAppData->name`, and that is `thunderbird` for internal reasons. We'll check out this and other call sites to change the string where required.

Thanks for the pointer!
