### ISSUE TITLE
windows shortcut key to open menu overwrides other windows shortcut keys

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/mate-panel#160]
coming from windows, i'm very greatful that mate has activated the use of just the windows/super key to launch the menu, but unfortunately if the windows key is used with a combination of other keys, only the menu is opened. i've set the windows key similar to how i am use to windows, with Super+E for the file manager and Super+R for run, but these dont work unless i change the menu key back to how it used to be with Ctrl+Super. So maybe some checking needs to be done when the Super key is launching the menu to see it is exactly the same key as set in the menu preferences.
##

**Comment by monsta** [comment]
https://github.com/linuxmint/mintmenu/issues/98
