### ISSUE TITLE
clock applet seems to leak memory

### ISSUE THREAD

**Issue by juhp** [mate-desktop/mate-panel#163]
I think this is an old gnome2 bug...
(see https://bugzilla.redhat.com/show_bug.cgi?id=952763 ;)
The clock applet seems to leak quite a bit.
This might be related to the world-clocks or weather features I am not sure.

I am running mate-panel-1.6.1-4.fc20.x86_64 on Fedora 20.

Currently my clock applet is using about 2GB of VM:

    0  1000  1908     1  20   0 2134212 29260 poll_s Sl  ?         54:58 /usr/libexec/mate-panel/clock-applet

this is probably after about a week or two so the leak is not extreme but nevertheless noticeable and stands out.

After restarting the panel I see:

    0  1000 18197     1  20   0 853248 15100 poll_s Sl   ?          0:00 /usr/libexec/mate-panel/clock-applet

(I lost my clock config in the process so I will try running with default config for a while to see if that helps - I suspect it will.)

**Comment by monsta** [comment]
It seems to be in Gnome 3 panel as well:
https://bugzilla.gnome.org/show_bug.cgi?id=688967

**Comment by raveit65** [comment]
Does this issue still exists with Mate-1.12?

**Comment by juhp** [comment]
To be honest I am no longer using Mate... I finally caved into gnome-shell last year.
