### ISSUE TITLE
Wrong screen size at MATE startup

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-panel#178]
I install Linux MINT + MATE (or MANJARO + MATE) on 2 computers (SHUTTLE XS35 and SHUTTLE XS32 V2), with a live DVD. It works well. But after the first installation, when Linux starts for the first time on my computer, I only see the MATE screen background. There are no panel, no icons, no menu.
These computers work well with other desktops (KDE, old Gnome 2...). But with MATE, there's a problem with the detection of the screen size.
MATE detects a too wide screen and show only the background when MATE starts.

I click with the mouse right button on the empty background, then I choose "Open a terminal" in the menu. I type the command "sudo su" and "xrandr" and then, I see that the screen size is wrong (see added screenshot).
![captured](https://f.cloud.github.com/assets/3955499/2323835/b1bf51a2-a3c1-11e3-9d07-f34c25e4d926.png)

Then, I change the screen size, by exemple :
#xrandr --size 1920x1080
And then, I can see all the menus, icons...
But if I reboot the computer, it doesn't keep the right screen size. I must do it again and then, record it in the System-Preferences-Screens menu.

It's strange that the screen size is well detected when starting with the live DVD but not after installing Linux MINT + MATE or MANJARO + MATE.

**Comment by NiceandGently** [comment]
@Petrouchka 
Is the issue still exists?

**Comment by Petrouchka** [comment]
I don't know, I've changed my computer.

**Comment by NiceandGently** [comment]
@flexiondotorg 
Please close it, it's not reprodcible anymore
