### ISSUE TITLE
Multiple monitor panels hang mate-panel at startup

### ISSUE THREAD

**Issue by pwmarcz** [mate-desktop/mate-panel#188]
1. Connect 2 monitors to a laptop
2. Create two panels, one on one external monitor, one on another
3. Detach the monitors
4. Restart laptop and log in

Result: mate-panel hangs without ever displaying anything except a single empty panel.

I'll be happy to provide more details if necessary.

**Comment by NiceandGently** [comment]
@pwmarcz 
Is the issue still exists?
Which distro?
Which mate version?

**Comment by pwmarcz** [comment]
Sorry, I've long since moved to a different set-up so I cannot reproduce the issue.
If I recall correctly, this happened on Linux Mint 15 (Olivia) MATE version, 64-bit.
The computer was Lenovo ThinkPad x230, with one monitor connected by mini-DisplayPort, another by VGA cable.

**Comment by NiceandGently** [comment]
@flexiondotorg 
@stefano-k 
please close, it isn't reproducible anymore
