### ISSUE TITLE
Support icon-padding and icon-size for NotificationArea applet

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-panel#189]
I would be be nice to adopt the first 4 commits from those selection from gnome-panel.
https://git.gnome.org/browse/gnome-panel/log/?qt=grep&q=NATray
This is needed to crontrol the systry with a theme setting for GTK3, ie. like that
NaTrayApplet {
    -NaTrayApplet-icon-padding: 12;
    -NaTrayApplet-icon-size: 16;
}
I don't know if those commits also work for GTK2, but they end up in GTK3-3.0 and it should be possible to use cairo drawning in GTK2, maybe.
Currently i need a solution to control icon-size in themes for GTK3, otherwise the panel doesn't displayed well with default size (24 px).

**Comment by dnk** [comment]
https://github.com/dnk/mate-panel/commits/na-tray

**Comment by SamuelMiller** [comment]
I suggest adding custom icon size and show/hide options to the applet preferences accessible through the right-click context menu on the panel like the xfce indicator applet. Thanks.

**Comment by raveit65** [comment]
patch is applied.
