### ISSUE TITLE
Closing windows with middle click on windows list doesn't work anymore

### ISSUE THREAD

**Issue by DmitriyTrt** [mate-desktop/mate-panel#191]
On MATE 1.6 it was an amazing feature and now it seems broken on 1.8. Nothing happens after middle button click on the window. Does it happen for someone else? Upgraded to MATE 1.8 from Debian Testing.

**Comment by Keberdle** [comment]
Still not fixed, bad

**Comment by thonixx** [comment]
yup. bad, I miss the feature quite.

**Comment by glepretre** [comment]
Migrated to mate-panel 1.12 today. I do miss this feature too :disappointed: 

Is there something we can do? Any workaround?

**Comment by MightyPork** [comment]
Why is this closed if it's still broken?

**Comment by allanlaal** [comment]
This issue was fixed in a previous version of Mate Panel (1.08?), but no longer works in 1.12. Could someone confirm if this works in 1.14 or 1.16?

there's no hope getting this feature from libwnck devs:
https://bugzilla.gnome.org/show_bug.cgi?id=448036

**Comment by lukefromdc** [comment]
It works in 1.16 with GTK 3.22, that's for sure. This was something I learned about by accident before finding it was an intentional feature.

**Comment by wyatt8740** [comment]
I unfortunately discovered this when I accidentally hit the middle click button on my thinkpad while trying to switch to the terminal window I was compiling Wine in.

So it appears to work in 1.16 with GTK 3.23. Unfortunately, I can't seem to disable it, though.

**Comment by lukefromdc** [comment]
GTK 3.23? The current development (git master) version is a prequel to GTK4, and is listed as version 3.89 in configure.ac

**Comment by wyatt8740** [comment]
3.23 is the last "release" tarball.
