### ISSUE TITLE
weather not shown in clock applet (proxy issue?)

### ISSUE THREAD

**Issue by palosBA** [mate-desktop/mate-panel#200]
I have no direct connection and http proxy is already set correctly (Firefox is set to use system proxy settings and working). Display weather is checked in clock applet preferences and location is chosen (Bratislava, Europe/Bratislava).
Weather applet also displays only "--" (I know it is another component...)

mate-panel-1.8.0-1.fc21.x86_64 (installed Fedora 20 mate-compiz spin, upgraded to rawhide; never used other desktop type in this installation)

gnome-panel-2.32.0.2-2.fc14 works fine ;-)
##

**Comment by muesli4** [comment]
Works for me. Probably the same bug that has been in the *mate weather applet* which has been fixed.

**Comment by monsta** [comment]
With http proxy?

**Comment by raveit65** [comment]
Closing, no answer from reporter since years.
