### ISSUE TITLE
items removed from panel

### ISSUE THREAD

**Issue by MDykstra** [mate-desktop/mate-panel#202]
Browsing with Firefox to specific website pages (e.g. http://www.thermo.com.cn) causes the window list and workspace switcher to give error message boxes about failure loading. The items are thereafter removed from the panel. The system log shows "org.mate.panel.applet.WnckFactory[1352]: wnck-applet: cairo_saled_font.c: 459: _cairo_scaled_glyph_page_destroy: Assertion '!scaled_font->cache_frozen' failed." Just a guess; maybe Firefox blocks some font cache on the specific web page.

mate-panel 1.8.0-3 
cairo 1.12.16-2
firefox 30.0-1 on Arch Linux

**Comment by NiceandGently** [comment]
@MDykstra 
Is the issue still exists?

**Comment by raveit65** [comment]
no answer from reporter!
So i think the issue doesn't exists anymore.

**Comment by MDykstra** [comment]
Sorry lost track; this issue happens using Compiz 0.9.11.2-1 (does not happen with Marco). The window manager does not crash while showing Asian characters, but all window borders are lost. Subsequently many
panel applets are removed from panel and dialog boxes appear asking if I want to reload these items.

**Comment by raveit65** [comment]
Sounds like an compiz issue, anyways re-open.

**Comment by MDykstra** [comment]
Installed compiz-0.9.12.2. Compiz no longer drops window borders, while browsing to pages with Asian characters. Both with Compiz and  Marco are panel applets removed from panel with dialog boxes appearing, while earlier I thought it didn't happen with Marco. At least Marco never dropped window borders.

**Comment by monsta** [comment]
@MDykstra: does it happen with all themes?

**Comment by MDykstra** [comment]
It happens with Compiz-0.9.12.2 with Emerald window decorator. Also closed issue https://github.com/mate-desktop/mate-panel/issues/206 happens with Compiz. It is not only a Compiz issue; Mate panel applets should not just crash using another compositing manager.

**Comment by MDykstra** [comment]
Following #328. This issue can be closed.

**Comment by monsta** [comment]
Yes, looks like it's the same problem (especially given the same error message from cairo).
