### ISSUE TITLE
mate-panel: g_slist_remove_all(): mate-panel killed by SIGSEGV

### ISSUE THREAD

**Issue by samtygier** [mate-desktop/mate-panel#203]
I was notified of this crash in Fedora rawhide just after booting and logging in (though possibly it could have happened during logging out). Version mate-panel-1.8.0-1.fc21.

```
 #0 g_slist_remove_all at gslist.c:445
 #1 gtk_rc_clear_realized_style at gtkrc.c:1665
 #2 g_hash_table_foreach at ghash.c:1550
 #3 gtk_rc_reset_styles at gtkrc.c:1711
 #4 gtk_settings_notify at gtksettings.c:1423
 #10 g_object_notify_by_spec_internal at gobject.c:1147
 #11 g_object_notify at gobject.c:1194
 #12 _gtk_settings_handle_event at gtksettings.c:2151
 #13 gtk_main_do_event at gtkmain.c:1500
 #19 gtk_main at gtkmain.c:1257
```

There is a full backtrace attached to the fedora bug https://bugzilla.redhat.com/show_bug.cgi?id=1101919 it also looks like https://bugzilla.redhat.com/show_bug.cgi?id=1045835 with version mate-panel-1.6.1-4.fc19

I have not been able to reproduce it.

**Comment by monsta** [comment]
It seems to me that the panel hit some bug in GTK+2...

**Comment by samtygier** [comment]
Not seen this crash in a while, so closing

**Comment by monsta** [comment]
It really seems like some old bug in GTK+2. It crashes on [this line](https://git.gnome.org/browse/gtk+/tree/gtk/gtkrc.c?h=gtk-2-24#n1665), always with the same stacktrace.

https://bugzilla.redhat.com/1293096
https://bugzilla.redhat.com/1343807

Also https://bugs.launchpad.net/bugs/1555331 looks quite similar (even though the [stacktrace](https://launchpadlibrarian.net/247305076/Stacktrace.txt) isn't complete).

**Comment by raveit65** [comment]
I'm really in doubt that rc_style stuff will ever been fixed as this is replaced with GtkStyleProvider in gtk3.
We should check if we really need this with gtk2.
