### ISSUE TITLE
GTK3: Strange effect on drawer applet.

### ISSUE THREAD

**Issue by rilian-la-te** [mate-desktop/mate-panel#204]
Fix this may help fix #187.

Steps to reproduce (need latest mate-panel from master):

1.Make panel transparent via slider. (Solid color with 0% opacity)
2.Add drawer to panel
3. Click to it. 
4. Wait a second and click to it again.
5. After drawer will have closed, it will start flickering from transparency to system theme color. This will stop after a second and theme colored rectangle will stay on the panel until redraw (change color or opacity for it). Then drawer applet will be normal again... To another click.

**Comment by raveit65** [comment]
@rilian-la-te 
Is this issue still exists with 1.12 or master branch?
should be fixed with https://github.com/mate-desktop/mate-panel/commit/6f634c680fbc5ee5051253554f2710e39f9ea80a

**Comment by raveit65** [comment]
no answer from reporter!
