### ISSUE TITLE
container_child_background_set: Process /usr/bin/mate-panel was killed by signal 11 (SIGSEGV) 

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-panel#214]
orginal report at fedora bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=1023604
```
 satellit@bendbroadband.com 2013-10-25 18:20:51 EDT

Description of problem:
DVD install of TC5 Beta x86_64 to HD of Mate with updates block unchecked in software sources
doing test and added 2nd user and logged in then got error.

Version-Release number of selected component:
mate-panel-1.6.1-4.fc20

Additional info:
reporter:       libreport-2.1.8
backtrace_rating: 4
cmdline:        mate-panel
crash_function: container_child_background_set
executable:     /usr/bin/mate-panel
kernel:         3.11.5-302.fc20.x86_64
runlevel:       unknown
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 1 (8 frames)
 #1 container_child_background_set at mate-panel-applet-frame-dbus.c:240
 #2 g_simple_async_result_complete at gsimpleasyncresult.c:777
 #3 set_applet_property_cb at mate-panel-applet-container.c:556
 #4 g_simple_async_result_complete at gsimpleasyncresult.c:777
 #5 g_dbus_connection_call_done at gdbusconnection.c:5484
 #6 g_simple_async_result_complete at gsimpleasyncresult.c:777
 #7 complete_in_idle_cb at gsimpleasyncresult.c:789
 #12 gtk_main at gtkmain.c:1257
```
Note, there are about 10 users who are affected by this issue, latetest from 2014-06-20.
So i decided to forward it to github.
If you've questions to users pls asked at fedora bugzilla.
More Infos and descriptions you'll also find there.

**Comment by monsta** [comment]
@NiceandGently: here's the missing link to the PR - https://github.com/mate-desktop/mate-panel/pull/261 :)

**Comment by NiceandGently** [comment]
@stefano-k 
Can you please review this for 1.10.
I use the patch for several month in fedora and downstream report is closed since 2014-12-01.

**Comment by monsta** [comment]
@stefano-k: and the commit that fixes it (https://github.com/monnerat/mate-panel/commit/d02ce625ff7643df609f8911066c6a3304223d33) is very small, so maybe it should be applied to 1.8 branch as well.

**Comment by monsta** [comment]
@monnerat: check #701, it should fix the crash.

**Comment by lukefromdc** [comment]
I have never once seen this crash, but I will check the PR for any problems

**Comment by lukefromdc** [comment]
BTW, to quit the panel and stop automatic restarts so you can run it from terminal, run

mate-panel --replace 
from terminal, giving an instance which is disconnected from session management, then run
killall mate-panel
and then run 
mate-panel 
from the terminal. You now have complete control and get the messages, errors, etc

**Comment by monnerat** [comment]
@monsta: thanks for taking care of this. Unfortunately I have no access anymore to the failing configuration for 16 months and never experienced this problem since then.
