### ISSUE TITLE
Notification icons are invisible

### ISSUE THREAD

**Issue by danzpaim** [mate-desktop/mate-panel#215]
I am on Mate 1.8.0 in Linux Mint Qiana, Hardly ever I can see the notification icons on Linux Mint Qiana Mate edition. Now, I can't see... Why?
![captura_de_tela](https://cloud.githubusercontent.com/assets/8020150/3425582/59a15350-0008-11e4-866e-aeb025164581.png)

Screenshot here:http://forums.mate-desktop.org/viewtopic.php?f=2&t=3121

**Comment by monsta** [comment]
Well, since it seems to be a video card/driver problem, I'm closing it. There's nothing we can do about it.
