### ISSUE TITLE
Drawer bug

### ISSUE THREAD

**Issue by danzpaim** [mate-desktop/mate-panel#216]
When I reboot my system after put notification area inside a drawer, the drawer don't work fine. I can't use notification area inside a drawer after reboot.

http://forums.mate-desktop.org/viewtopic.php?f=2&t=3142

**Comment by monsta** [comment]
Do you have something like
```(mate-panel:14819): Gtk-CRITICAL **: IA__gtk_widget_map: assertion 'gtk_widget_get_visible (widget)' failed```
in your ```~/.xsession-errors``` file?

**Comment by monsta** [comment]
Should be fixed in https://github.com/mate-desktop/mate-panel/commit/5d5ba35a217735e272b406abfbffd07e64ded435 (1.10.1 release)
