### ISSUE TITLE
The Menu Bar panel applet inconsistently populates Places

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/mate-panel#225]
Hi,

The Places pop-out in the Menu Bar panel applet doesn't display the folders that are created by `xdg-user-dirs-update`. This is inconsistent with the Places shown in Caja, which does include the xdg folders.

Here is the original issue from the Ubuntu MATE bug tracker on Launchpad.

  * https://bugs.launchpad.net/ubuntu-mate/+bug/1341148

Regards, Martin.

**Comment by monsta** [comment]
Hmm, Caja shows these dirs for me, but I could only find a place in the code where it loads the old location - https://github.com/mate-desktop/caja/blob/master/src/caja-bookmark-list.c#L120...

**Comment by flexiondotorg** [comment]
@raveit65 @lukefromdc Given then recent update in https://github.com/mate-desktop/caja/pull/762, can you take a look at this for consistency?

**Comment by raveit65** [comment]
Indeed, menubar applet use old location

**Comment by raveit65** [comment]
@flexiondotorg 
All menus applets (Menubar, Main menu, mate-menu [mint-menu-fork)) uses the old location.
Maybe this is handled by mate-menu package?

**Comment by raveit65** [comment]
Found it it is defined here
```
mate-panel/panel-menu-items.c:60:#define BOOKMARKS_FILENAME      ".gtk-bookmarks"
```

**Comment by flexiondotorg** [comment]
Was just about to post that :-)

**Comment by monsta** [comment]
So it's fixed for the panel now, but I wonder where Caja gets the list of these places. Looks like they're hardcoded somewhere. You don't need to have them in the bookmarks file, Caja will show them anyway. :slightly_smiling_face:

**Comment by muesli4** [comment]
I just found out that Caja looks in `~/.gtk-bookmarks`. I will look at that.
