### ISSUE TITLE
Menu-bar applet resets gsettings changes on new session

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/mate-panel#245]
If you change the `dconf` settings for the menubar applet they are reset to defaults when you login to a new session. The following steps can reproduce the issue:
- Add the menu-bar applet (Applications Places System) to a panel
- Open `dconf-editor`
- Navigate to `/org/mate/panel/menubar`
- Untick `show-applications` and `show-desktop` so that only Places is stil displayed in the panel.
- Log out and then log back in. The menubar displays Applications Places System again.

The use case is for an XFCE user trying to recreate and panel layout similar to how he has used XFCE for many years. Basically by using the Main Menu applet in a bottom panel and just the Menu Bar showing Places next to it for one click access to common folders.

**Comment by monsta** [comment]
@stefano-k: please push that commit to 1.8 branch as well to fix https://github.com/mate-desktop/mate-panel/issues/294.
