### ISSUE TITLE
Searchbar in MATE menu

### ISSUE THREAD

**Issue by tranjeeshan** [mate-desktop/mate-panel#247]
A searchbar would be great in MATE menu for launching application fast. MintMenu or Whisker menu ffor Xfce has this feature. 
I can assign keyboard shortcuts for launching applications easily and fast but can't do that for all of them. A searchbar in the MATE menu would do the same easily.

**Comment by monsta** [comment]
I can't imagine both menus (single button menu and apps/places/system) with a searchbar. Where would you put it?

**Comment by tranjeeshan** [comment]
I'd put the Search Bar the first item in Applications Menu. Or, for more 'global' search, the search bar could be in the middle of the top panel!

**Comment by monsta** [comment]
"Middle of panel" would mean a separate applet then...

**Comment by tranjeeshan** [comment]
An 'applet' maybe, or built-in for panel?

**Comment by monsta** [comment]
It would be an applet anyway. Panel is just a container. Usually, when a "built-in" applet is mentioned, it means an applet packaged with mate-panel itself (clock, window list, notification area) as opposed to being packaged in [mate-applets](https://github.com/mate-desktop/mate-applets).
