### ISSUE TITLE
Icons in the panel are misalinged

### ISSUE THREAD

**Issue by rougin** [mate-desktop/mate-panel#255]
I just recently installed Ubuntu with MATE desktop, installed some applications and last thing I saw is that the icons (except the Network Manager and the Volume) are misaligned or they dont have enough space for each icon. Here is the screenshot for the issue: http://i.imgur.com/F4hZLd4.png

**Comment by NiceandGently** [comment]
Is this really mate-panel?

**Comment by rougin** [comment]
Yes. As far as I remember, it is ```mate-panel```.

**Comment by NiceandGently** [comment]
this is never in life mate-panel!
....looks like unity panel or gnome-s(hell)

**Comment by rougin** [comment]
Maybe I just an old version before? I install the Ubuntu core first then install the ```mate-desktop``` after. I think its from the themes I used but I really don't remember about it. It's been a long time :smile: :v:

**Comment by monsta** [comment]
Does it still happen in 1.12?

**Comment by raveit65** [comment]
no answer from reporter!
