### ISSUE TITLE
gnome-main-menu has quit unexpectedly

### ISSUE THREAD

**Issue by rezso** [mate-desktop/mate-panel#265]
After upgrading mate-panel to 1.9.4, the gnome-main-menu not works anymore: I always get an „gnome-main-menu has quit unexpectedly” message.
With previous version of mate-panel (1.9.3), the gnome-main-menu works as expected.

**Comment by monsta** [comment]
Try rebuilding gnome-main-menu, adding patches from https://github.com/GNOME/gnome-main-menu/pull/2 and https://github.com/GNOME/gnome-main-menu/pull/4 (other pull requests from there won't hurt as well).

**Comment by rezso** [comment]
Without libslab/libmate-slab renaming, the build fails with mate-panel 1.9.4, so it was done before this issue report.
But the https://github.com/GNOME/gnome-main-menu/pull/4 fixed the gnome-main-menu, it works now. Thanks.

**Comment by monsta** [comment]
Ok, you can close this issue then (the problem is in the outdated gnome-main-menu, not in the panel anyway).

**Comment by rezso** [comment]
Ok, I close it.
