### ISSUE TITLE
Workspaces limited to 4?

### ISSUE THREAD

**Issue by dslindsay73** [mate-desktop/mate-panel#267]
I installed CentOS 7 and noticed that I am limited to only 4 workspaces. Even the GUI has changed surrounding how to configure my workspaces. I am very accustomed to setting up 8 workspaces in 8 rows. I can no longer define 8 workspaces. I can define the 8 rows and the applet in the panel looks like it should support the 8 workspaces, but in reality there are only 4 that I can switch between.

This is bad. Is this a bug or some kind of feature regression?

**Comment by monsta** [comment]
Which MATE version do you use?

I can freely create up to 36 workspaces (this is the maximum) and up to 16 rows to display them:

![36_workspaces](https://cloud.githubusercontent.com/assets/5138986/5603053/2a7642ca-9383-11e4-8cc0-373a688034c4.png)

I'm running Debian Testing with mate-panel build from git master (1.9.x). Though the only recent change to the workspace applet was https://github.com/mate-desktop/mate-panel/commit/45f9dd1209ea5715b02d5d1a5e9e2dd51220da1e. Maybe you'll need this patch...

**Comment by NiceandGently** [comment]
No prob to setup up to 36 workspaces in CentOs7 from  workspaces context menu.with mate-panel-1.8.1-2.
Dear supporter, can you confirm?

Marked as can be closed
