### ISSUE TITLE
mate panel, orientation: top, does not 'block' the screen area

### ISSUE THREAD

**Issue by cerubim** [mate-desktop/mate-panel#271]
I have changed in Panel Properties, General, Orientation to 'Top', so the position is at the top of the screen. Now, most windows open in the top left corner, underneath the panel, with their title obscured by the panel. 
The workaround is to right-click and move them each time or use auto-hide.
I wonder if the panel should 'reserve' that area of the screen so that any windows open below it. 

Linux Mint 17.1
MATE 64-bit

**Comment by acidice-hun** [comment]
Exactly the same problem... :/

Ubuntu 14.04 (64-bit) & Mate

**Comment by rimbaum** [comment]
Same issue here, Mint 17.1 Mate 64-bit

**Comment by monsta** [comment]
By any chance, do you guys have compiz enabled? If yes, try switching to marco and see if the problem persists.

**Comment by monsta** [comment]
@flexiondotorg: did you encounter this issue?

**Comment by cerubim** [comment]
Since I opened this issue I have upgraded to:
Linux Mint 17.2, Mate 64-bit.
The windows now open a fair distance from the top; not in the top-left corner any more. 
So, I cannot reproduce it on this version.

**Comment by monsta** [comment]
That's probably because the new windows are placed in the center of the screen by default; you can change that in the Window Settings tool in the Control Center (or just run ```mate-window-properties```).

**Comment by monsta** [comment]
Of course, that only applies to the default window manager (marco). If you use Compiz, use the corresponding option in its settings.

**Comment by cerubim** [comment]
Thanks monsta. I have disabled to option for new windows to be placed in the center and I believe I have Compiz disabled. The new windows appeared in the top-left corner, but below the Mate panel. 
I have tried to move windows underneath the panel but I could not. It appears the issue is fixed.
