### ISSUE TITLE
clock applet doesn't receive TZ env variable

### ISSUE THREAD

**Issue by sketch242** [mate-desktop/mate-panel#279]
A little background: We use a standardized config with all systems set to UTC, then users can set the TZ variable as appropriate for their location.  mate-panel With gnome-panel-2.30 as delivered in CentOS 6, the clock applet does see the TZ env variable, and displays time in the correct user-specified timezone as expected.

I took a look at the code, and I see that the clock-applet does look for the TZ env variable, however, it doesn't appear to inherit the user's environment, so it's not actually set.  

With gnome-panel-2.30 as delivered in CentOS 6, the clock applet does see the TZ env variable, and displays time in the correct user-specified timezone as expected.  With mate-panel-1.8.1 as delivered in CentOS 7 (and the latest git as of yesterday), the clock applet does not see the TZ env variable, and displays it in the default system timezone.  I have verified this by looking at clock-applet's /proc/$PID/environ file.  I can also see in this file that the process's parent in CentOS 6 is gnome-session, while in 7 it is dbus-launch.  I'm not certain that this is actually caused by mate-panel, but seems to be caused by the way that the applet processes are launched.

Output of /proc/$PID/environ files follows:

centos7# cat /proc/15286/environ 
SHELL=/bin/bashMATE_DESKTOP_SESSION_ID=this-is-deprecatedDBUS_STARTER_ADDRESS=unix:abstract=/tmp/dbus-Ur6lFaUF82,guid=ca6fd930ee25ab3481f7f56554dcf595XDG_RUNTIME_DIR=/run/user/10001DISPLAY=:1DESKTOP_SESSION=mateSESSION_MANAGER=local/unix:@/tmp/.ICE-unix/14937,unix/unix:/tmp/.ICE-unix/14937WINDOWPATH=3PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbinGDMSESSION=mateXDG_VTNR=3USERNAME=testuserXDG_SESSION_ID=1632DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-Ur6lFaUF82,guid=ca6fd930ee25ab3481f7f56554dcf595XDG_SEAT=seat0XAUTHORITY=/run/gdm/auth-for-testuser-kW56gc/databaseUSER=testuserDBUS_STARTER_BUS_TYPE=sessionGNOME_KEYRING_PID=14927SHLVL=1PWD=/home/testuserGDM_LANG=en_US.utf8GNOME_KEYRING_CONTROL=/run/user/10001/keyring-DyjzziLANG=en_US.utf8_=/usr/bin/dbus-launchLOGNAME=testuserHOME=/home/testuser

centos6# cat /proc/18687/environ
DISPLAY=:0SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/18329,unix/unix:/tmp/.ICE-unix/18329XAUTHORITY=/var/run/gdm/auth-for-sysadmin-YJmnqm/databaseLANG=en_US.UTF-8MANPATH=HOSTNAME=monitoring-01.ad.mochotrading.comIMSETTINGS_INTEGRATE_DESKTOP=yesSHELL=/bin/bashTERM=dumbHISTSIZE=1000XDG_SESSION_COOKIE=02b7afda9e3a18d9b92784f30000003c-1423766501.156415-1475815437QTDIR=/usr/lib64/qt-3.3QTINC=/usr/lib64/qt-3.3/includeIMSETTINGS_MODULE=noneUSER=sysadminGNOME_KEYRING_SOCKET=/tmp/keyring-tN9MGb/socketUSERNAME=sysadminMAIL=/var/spool/mail/sysadminPATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/sysadmin/binDESKTOP_SESSION=gnomeQT_IM_MODULE=ximPWD=/home/sysadminXMODIFIERS=@im=noneGDM_KEYBOARD_LAYOUT=usGNOME_KEYRING_PID=18319MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/local/share/Modules/modulefiles:/opt/share/Modules/modulefilesGDM_LANG=en_US.UTF-8LOADEDMODULES=TZ=America/ChicagoGDMSESSION=gnomeSSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpassHISTCONTROL=ignoredupsKRB5CCNAME=FILE:/tmp/krb5cc_3000066_gvZYDBHOME=/home/sysadminSHLVL=1LOGNAME=sysadminQTLIB=/usr/lib64/qt-3.3/libCVS_RSH=sshDBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-otEmaINwJH,guid=396dbc0e9d0b821bf9d4f5c9000988bbMODULESHOME=/usr/share/ModulesLESSOPEN=|/usr/bin/lesspipe.sh %sWINDOWPATH=7G_BROKEN_FILENAMES=1BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
##

**Comment by NiceandGently** [comment]
Does this PR help?
https://github.com/mate-desktop/mate-panel/pull/261

**Comment by NiceandGently** [comment]
@sketch242 
Any news?

**Comment by raveit65** [comment]
no answer from reporter!

**Comment by sketch242** [comment]
Looks like I managed to miss the previous messages about PR #261.  However, it does not fix the problem.  As far as I can tell, it looks like it only affects /etc/localtime, which is not the issue here, as that worked properly before.  It's the lack of TZ environment variable that is the issue.  It's been months since I looked at this in detail, but I believe the problem is that dbus-launch starts the panel applets with a completely new environment, so existing environment variables are lost.

**Comment by raveit65** [comment]
Nice that i get an answer if i close a report ;)
With mate-1.12 we changed dbus name from mate-session to gnome-session.
Your description sounds like this will solve the issue.
Currently i'm waiting for Centos-7.2 update, than i will update epel7 repo to mate-1.12.
As Im using fedora and not Centos-7.2 every day, please notify me about when 7.2 update is done.
Thank you.

**Comment by raveit65** [comment]
Btw, https://github.com/mate-desktop/mate-panel/commit/6a71dd03e3d5c2eecdf6d6fcae50ab53656ff148
is in mate-panel-1.10.0.

**Comment by sketch242** [comment]
I just updated to CentOS 7.2 yesterday.  I'd love to see EPEL updated to 1.12..

**Comment by sketch242** [comment]
I just noticed EPEL was updated to 1.12.  Things look much the same.  dbus-launch is used to launch applets, so they don't inherit any environment variables.

centos7# cat /proc/xxx/environ 
SHELL=/bin/bashMATE_DESKTOP_SESSION_ID=this-is-deprecatedDBUS_STARTER_ADDRESS=unix:abstract=/tmp/dbus-qSwjB9ZiQY,guid=7f8f1440ac446eebb1b4906356d07019XDG_CURRENT_DESKTOP=MATEXDG_RUNTIME_DIR=/run/user/1000DISPLAY=:1DESKTOP_SESSION=mateSSH_AUTH_SOCK=/run/user/1000/keyring/sshSESSION_MANAGER=local/unix:@/tmp/.ICE-unix/951,unix/unix:/tmp/.ICE-unix/951GTK_OVERLAY_SCROLLING=0WINDOWPATH=1:1:2PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbinXDG_VTNR=2USERNAME=sysadminGDMSESSION=mateXDG_SESSION_ID=9948GPG_AGENT_INFO=/run/user/1000/keyring/gpg:0:1DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-qSwjB9ZiQY,guid=7f8f1440ac446eebb1b4906356d07019XDG_SEAT=seat0XAUTHORITY=/run/gdm/auth-for-sysadmin-w391nu/databaseUSER=sysadminDBUS_STARTER_BUS_TYPE=sessionPWD=/home/sysadminGDM_LANG=en_US.UTF-8SHLVL=1LANG=en_US.UTF-8_=/usr/bin/dbus-launchLOGNAME=sysadminXDG_SESSION_DESKTOP=mateHOME=/home/sysadmin

**Comment by besser82** [comment]
@raveit65 The build for epel7 with the patch applied already moved to regular updates repo.

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-session-manager/commit/8f84934b86f04eebb9d7aebf32321925e1764958
