### ISSUE TITLE
Light colored line appears in mate panel tray

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/mate-panel#281]
I installed Linux Mint Mate 17.1 and changed the panel to a dark color and then i noticed in the tray to the left of the volume icon was a light colored line (#d6d6d6) that i am unable to get rid of.

![mint taskbar line](https://cloud.githubusercontent.com/assets/4412114/6288356/d3537286-b931-11e4-93a0-b920a0909f72.png)

**Comment by pro100fed** [comment]
On my x64 Arch (MATE 1.8.1) this bug presented too.
![default](https://cloud.githubusercontent.com/assets/1312515/6530692/1819e7b6-c444-11e4-8235-96e41d24982e.png)

**Comment by NiceandGently** [comment]
Can you please use mate-icon-theme for testing?
This looks like an issue with the icon from your icon-theme.

**Comment by pro100fed** [comment]
Another icon theme aren't solved this problem.

**Comment by NiceandGently** [comment]
You did use mate-icon-theme?
This looks not like mate-icon-theme.

**Comment by pro100fed** [comment]
Yes, I try it.

**Comment by NiceandGently** [comment]
@flexiondotorg 
Can you reproduce this issue?

**Comment by pro100fed** [comment]
![cmp](https://cloud.githubusercontent.com/assets/1312515/9835541/56a84acc-5a12-11e5-9666-d45a39848dc7.png)

If you compare the two situations, you may notice a strange thing. The line takes a single pixel, but in the end the difference is two pixels. I think an error may occur when placing icon on the panel. Especially suspicious function "find_icon_position" in the file "na_tray.c".

**Comment by pro100fed** [comment]
![default](https://cloud.githubusercontent.com/assets/1312515/10222944/71f6e71a-6878-11e5-8733-d296287da7bf.png)
A unique phenomenon! The line can appear in other places!

**Comment by raveit65** [comment]
Can you do a right click on this line?

**Comment by pro100fed** [comment]
Unfortunately or fortunately, this line did not show himself more than a month. Perhaps it forever.

**Comment by raveit65** [comment]
fine,
if the line comes back, please post it here, than i will re-open the report.

**Comment by pro100fed** [comment]
Oh shi.
![screenshot at 2015-12-27 17 05 24](https://cloud.githubusercontent.com/assets/1312515/12010199/8cc65ae2-acc7-11e5-9502-d5bbaf41b01b.png)

Code that reproduces this error: http://pastebin.com/TVFpabFa
![screenshot at 2015-12-27 19 20 24](https://cloud.githubusercontent.com/assets/1312515/12010208/fac15cb8-acc7-11e5-826b-3059e5630d7a.png)
