### ISSUE TITLE
Problems with tray icons in mate panel

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/mate-panel#282]
I just installed Linux Mint Mate 17.1 and the default panel is 24 pixels in height. When i tried to adjust the height, the network and volume icons changed to icons that would look fine on a dark panel background.

![mint taskbar](https://cloud.githubusercontent.com/assets/4412114/6288363/e707b2b0-b931-11e4-900f-dbb0c22f5aa0.png)

**Comment by rilian-la-te** [comment]
Do you tried another icon theme?

**Comment by philipzae** [comment]
I just tested it with the Mate/Gnome icon theme and it behaves the same in the changing of the icon at these different sizes, though the icons are in color.

![mint taskbar with gnome](https://cloud.githubusercontent.com/assets/4412114/6289758/d8513c14-b93b-11e4-899b-f2d732942354.png)

**Comment by philipzae** [comment]
On my laptop, if the panel is 32px or more, the battery icon changes and the bluetooth icon which hadnt changed until 31px keeps the same icon but becomes blurry because its being stretched.

![tray icons](https://cloud.githubusercontent.com/assets/4412114/6313354/0ecc0796-b9bf-11e4-83ce-f3aebaa8f5ca.png)

**Comment by monsta** [comment]
These are issues with all the icon themes. The panel just displays the pictures.
Check all the subdirs in ```/usr/share/icons/Mint-X/status``` directory to see it for yourself.

**Comment by philipzae** [comment]
Yes i would presume it is related to the limited pictures available in the themes, which is why i'm bringing it to your attention so that the creators of the themes can be aware of the problem, primarily Mint-X which i'm assuming is being done by the Mint team.

**Comment by monsta** [comment]
Theme creators would be aware of it if you'd post it in the corresponding issue trackers:

https://github.com/mate-desktop/mate-icon-theme/issues
https://github.com/linuxmint/mint-x-icons/issues

**Comment by philipzae** [comment]
Thanks. Its been done.
