### ISSUE TITLE
clock, Menu button and Show desktop button cloned multiple times

### ISSUE THREAD

**Issue by ppolewicz** [mate-desktop/mate-panel#286]
It might be the same as #155.

I do not know how to trigger this. The cloning was first observed during reconfiguration of screens with nvidia-settings, which probably triggered --reset.

![screenshot](https://cloud.githubusercontent.com/assets/726553/6414670/69de308a-be99-11e4-9138-b3746d2c0868.png)

Linux Mint 17 Mate, mate-panel 1.8.0-0+qiana amd64.

In dconf-editor under org.mate.panel.general.object-id-list there is:
```python
['menu-bar', 'show-desktop', 'window-list', 'notification-area', 'clock', 'menu-bar', 'show-desktop', 'window-list', 'notification-area', 'clock', 'menu-bar', 'show-desktop', 'window-list', 'notification-area', 'clock', 'object_1']
```
object_1 is a widget added by the user.

**Comment by ppolewicz** [comment]
Removing duplicate entries from the list has (somewhat) resolved the issue for me at this time.

Whatever caused adding duplicate entries should not have done that though.

**Comment by monsta** [comment]
Ok, closing it for now. Feel free to reopen if you find a way to reproduce it.
