### ISSUE TITLE
Applications Menu does not handle custom entries in a compatible manner with other DEs

### ISSUE THREAD

**Issue by NP-Hardass** [mate-desktop/mate-panel#293]
Running MATE 1.8 with panel version 1.8.1

I'm the maintainer for the wine packages on Gentoo.  Wine generates its own desktop entries, creating a top level menu, "Wine" and then includes a "Programs" folder hierarchy for installed applications.  Wine's top level menu shows up okay, just not my local user's (see https://github.com/NP-Hardass/wine-desktop-common for how those are installed).  All applications installed by wine show up in the "Other" top level menu, and all related submenus are not to be found.  To confirm this wasn't a Gentoo specific issue, I installed the same wine version on mint mate, and it was missing from their menu as well.  To confirm this wasn't a wine issue, I installed the same wine version on ubuntu gnome3 with fallback mode and all wine entrees appeared as intended.  I have Gentoo users on KDE confirming that wine menus work fine for them. 
Now here's where things get interesting, I also have several custom submenus elsewhere that I created by right clicking "Applications" and clicking "Edit Menus".  I installed lxde, restarted X into lxde, and all of my wine entries were correct in the menu, and all of my custom entries in MATE are in the "Other" folder.  So, it would seem to appear that however MATE is handling custom entries (potentially just the local ones) it is being done in a manner inconsistent with other DEs (and the XDG spec, by chance) because menus on MATE appear incorrect relative to all others.

Let me know what if any other information I can provide.

**Comment by monsta** [comment]
I'm aware of this issue in mintMenu, but didn't know about MATE's own menu.
Can you please post the screenshots of MATE's menu and Gnome's fallback mode menu for comparison?

**Comment by raveit65** [comment]
ANY News?
Please answer on questions from us, otherwise i will close the issue.

**Comment by NP-Hardass** [comment]
Seems to be working as of 1.10
