### ISSUE TITLE
2 Displays above each other and panel in the midle bug. 

### ISSUE THREAD

**Issue by freed00m** [mate-desktop/mate-panel#295]
Hello :)

I want to report bug in mate 1.8 in latest mint 17.1

If a panel is set to sit at the top of the main screen, the above display is rendered useless. 

Every thing is ok when panel is set to sit at the botom.
##

**Comment by raveit65** [comment]
what  a weird configuration....

**Comment by freed00m** [comment]
Nobody cared and I don't use Mate anymore.
