### ISSUE TITLE
Run Application dialog: wrong reaction to show-program-list enabling

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-panel#296]
Steps to reproduce:
1. Have show-program-list property in org.mate.panel schema turned off.
2. Press Alt-F2 to invoke Run Application dialog. The program list will be hidden.
3. Enable show-program-list via dconf-editor.
4. See the empty space instead of the program list:

![run-dialog-wrong](https://cloud.githubusercontent.com/assets/5138986/7176879/051edc3c-e42b-11e4-966e-04eaf0d677d5.png)

It should be:

![run-dialog-right](https://cloud.githubusercontent.com/assets/5138986/7176884/14b8d5b2-e42b-11e4-8a72-8039bf1def34.png)

Tested in MATE 1.8 on two systems - LMDE 2 "Betsy" and Ubuntu MATE 15.04.

**Note:** this is not related to the known GLib 2.43 issue.
##

**Comment by NiceandGently** [comment]
With fedora 22 mate gtk3 version the list is enable.
![run-application-dialog](https://cloud.githubusercontent.com/assets/961604/9025837/2299229a-3917-11e5-99db-3e9412e4a323.png)
But as you see we have a UI issue with gtk3.
And it isn't relatet to glib issue, i've tested it with fixed glib2 version wrom Leigh Scott and with normal glib2 version.

**Comment by NiceandGently** [comment]
Hmm, it works here with 1.10.1 gtk2 version too.
PR for non displaying program-list is file out.

**Comment by monsta** [comment]
Unfortunately, https://github.com/mate-desktop/mate-panel/pull/333 only fixed the shrinked list in GTK+3...

**Comment by NiceandGently** [comment]
Are you shure, as you can see in my screenshot is the expander symbol open.
And i've same results with gtk2.

**Comment by monsta** [comment]
I can still reproduce the issue using the same steps in GTK+2 build.

**Comment by info-cppsp** [comment]
ARE YOU KIDDING ME??
Who would set gsettings while the run dialog is open?
Even if, what do you want? A callback?

That is what I wanted to write.
There is a callback.
![genius](https://user-images.githubusercontent.com/31438307/35628961-adaf06aa-069d-11e8-92a7-6e4ced102d76.jpg)

WAIT, that's not all!
Clicking the list expander sets the gsettings show-program-list key.
It does only that.
The callback sees this and changes the GUI accordingly.

BUT if you change the gsettings key yourself, this doesn't work.
OMG.

**Comment by lukefromdc** [comment]
This issue occurs only if you change the gsettings key while the run dialog is open in my testing here, thus is not obvious but is present
