### ISSUE TITLE
scrolling mouse wheel down really fast in a window causes to switch workspace

### ISSUE THREAD

**Issue by EvanDPoore** [mate-desktop/mate-panel#299]
If my mouse is positioned over a window and I'm scrolling rapidly and repeatedly down a page, the workspace switches to the one directly to the right of the current workspace.

**Comment by monsta** [comment]
mate-panel does not manage windows or workspaces :smile:

**Comment by infirit** [comment]
It only happens on certain distros and/or setups. I never had this on gentoo with the evdev driver.

**Comment by EvanDPoore** [comment]
Could you please direct me to the correct place to report this issue with the Workspace Switcher?
