### ISSUE TITLE
Mate Panel Not Responding

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-panel#301]
Mate Panel crashes, unable to close apps, unable to shutdown. 
system monitor displays frantic cpu usage
I apologize if this issue is already reported, if it is, I can't find it.
Using Debian 8.0, Mate 1.8.1 - was also happening with Debian 8-rc1,2
##

**Comment by monsta** [comment]
Can you reproduce this consistently?
If so, check which process eats CPU. It's faster to use the ```top``` utility in the terminal BTW.

**Comment by qoyote** [comment]
i have not found a consistant trigger yet, however, ...
when it does happen, the TOP utility reports that MATE-PANEL is using 
more than 100% of the CPU
and it mostly seems to happen when :
  - i try to change the desktop background
  - i add an item to the panel
  - i plug in a USB thumb or SDCard
when it does happen :
  - i may, or, may not be able to close apps
  - if the apps DO close, they leave the open-app-button on the panel
  - when i try to shutdown, PANEL NOT RESPONDING comes up as a reason 
that it can't
  - and of course, it won't shutdown, i need to hold the POWER button 
for 5 seconds

**Comment by monsta** [comment]
Check the ownership of ```/run/user/1000/dconf/user``` file when it happens.
Is it owned by you or by ```root:root```?

**Comment by qoyote** [comment]
well, ... right now, ... while the problem has not yet manifested itself 
at the moment, ...
i do not have a 'user' file in '/root/user/1000/dconf/'
the dconf directory is empty and it is currently owned be myuser:myuser

i will update this info when the bug rears it's ugly head

**Comment by NiceandGently** [comment]
> i do not have a 'user' file in '/root/user/1000/dconf/'
Pllease check the permissons as mentioned in previous post.
/run/user/1000/dconf/user

**Comment by qoyote** [comment]
i have the following folder structure

/run/user/1000/dconf/

there are NOT ANY files in the dconf folder
the dconf folder is empty

**Comment by CanadianJeff** [comment]
please look at issue #377 for a follow up

**Comment by monsta** [comment]
Closing - the author deleted his account, and 1.8 isn't supported anymore
