### ISSUE TITLE
The tooltips for sound and language indicator icons are not at its normal position

### ISSUE THREAD

**Issue by graywolf2** [mate-desktop/mate-panel#302]
When i move a mouse pointer to sound or language indicator icon, the tooltip appears at contrary side of the screen. You can see it at Screenshot-1.png and Screenshot-2.png.

The tooltips for other icons and applets have normal position. The Screenshot-3.png and Screenshot-4.png are an example.

My operating system is Fedora 21 32 bit with updates.

$ rpm -qi mate-panel|grep Version
Version     : 1.8.1

![screenshot-1](https://cloud.githubusercontent.com/assets/12239412/7460070/23c3df0c-f2a9-11e4-852c-1ac794cb768e.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/12239412/7460071/23c9861e-f2a9-11e4-8675-58b77d0f99e2.png)
![screenshot-3](https://cloud.githubusercontent.com/assets/12239412/7460072/23cc9e8a-f2a9-11e4-8dfd-f23cce3e874a.png)
![screenshot-4](https://cloud.githubusercontent.com/assets/12239412/7460073/23d17bb2-f2a9-11e4-8632-cc15c627263f.png)

**Comment by monsta** [comment]
I can't reproduce this in LMDE 2 Betsy with the same mate-panel version.
@NiceandGently: can you reproduce this in any Fedora release?

**Comment by graywolf2** [comment]
I have the computer with Fedora 21 64 bit also. There is no bug with
tooltips in this computer. It is strange.
The bugs with tooltips exists only on my notebook with Fedora 21 32 bit.
Thank you.

**Comment by NiceandGently** [comment]
I don't see that with x86_64 versions, sorry, i don't have a 32 bit box.
But you're using not the default fedora panel layout. There is a setting for that.
```
[rave@mother ~]$ gsettings get org.mate.panel default-layout
'fedora'
```
Imo, this should be empty in your case. Maybe there is a conflict.

**Comment by graywolf2** [comment]
I got the same setting.
[vovk@samsung ~]$ gsettings get org.mate.panel default-layout
'fedora'

**Comment by graywolf2** [comment]
I have the live Fedora 21 32 bit also that is installed to flash drive. The mate-panel settings at this live Fedora are default. This live Fedora has the same bug in icons tooltips. The bug exists in battery icon also.

The screenshots from live Fedora:
![screenshot5](https://cloud.githubusercontent.com/assets/12239412/7553729/a5e2f862-f711-11e4-9dd1-3ab9214b1b59.png)
![screenshot6](https://cloud.githubusercontent.com/assets/12239412/7553730/a5e722d4-f711-11e4-944f-65ad1f0163b0.png)

**Comment by NiceandGently** [comment]
Ok, i will try the 32 bit livecd in a VM

**Comment by graywolf2** [comment]
To reproduce this bug you may to do the following:
1) Download Fedora 21 32 bit image from http://ftp.colocall.net/pub/fedora/linux//releases/21/Live/i386/Fedora-Live-MATE_Compiz-i686-21-5.iso
2) Connect this image to VirtualBox or record it to DVD or flash drive.
3) Load this Live Fedora and check.

**Comment by NiceandGently** [comment]
Ok, i can reproduce it with latest 32 bit respin from http://alt.fedoraproject.org/pub/alt/live-respins/ in a quem-kvm VM.
But there is no differrent from packing between 32bit and 64 bit isos.
Is there a reason why you use a 32 bit iso?
I really can't remember that i had ever a system without 64 bit support.

**Comment by monsta** [comment]
Yes, I can try that.
Which version should I choose (to match the package versions in F21)?

**Comment by NiceandGently** [comment]
f21 has gtk-3.14 and glib2-2.42.2

**Comment by graywolf2** [comment]
> Is there a reason why you use a 32 bit iso?

My notebook Samsung R408 is very old and I do not know is it support
64 bit system.
Can I somehow check it?

> Which version should I choose (to match the package versions in F21)?

http://alt.fedoraproject.org/pub/alt/live-respins/F21-i686-MATE-20150501.iso

**Comment by NiceandGently** [comment]
it looks like you notebook supports 64 bit, btw. it depends on the cpu.
http://www.manualslib.com/manual/651953/Samsung-R408-Plus.html?page=80
If you have the -Core2-Duo-Processor-T6400 , than it supports 64 bit
http://ark.intel.com/products/40479/Intel-Core2-Duo-Processor-T6400-2M-Cache-2_00-GHz-800-MHz-FSB
> Can I somehow check it?

You can check for cpu with 'cpuid'
yum install cpuid

**Comment by graywolf2** [comment]
[vovk@samsung ~]$ cpuid
CPU 0:
   vendor_id = "GenuineIntel"
   version information (1/eax):
      processor type  = primary processor (0)
      family          = Intel Pentium Pro/II/III/Celeron/Core/Core 2/Atom, AMD Athlon/Duron, Cyrix M2, VIA C3 (6)
      model           = 0x6 (6)
      stepping id     = 0x1 (1)
      extended family = 0x0 (0)
      extended model  = 0x1 (1)
      (simple synth)  = Intel Core 2 Duo Mobile (Merom A1) / Celeron 200/400/500 (Conroe-L/Merom-L A1) / Celeron M (Merom-L A1), 65nm
   miscellaneous (1/ebx):
      process local APIC physical ID = 0x0 (0)
      cpu count                      = 0x1 (1)
      CLFLUSH line size              = 0x8 (8)
      brand index                    = 0x0 (0)
   brand id = 0x00 (0): unknown
   feature information (1/edx):
      x87 FPU on chip                        = true
      virtual-8086 mode enhancement          = true
      debugging extensions                   = true
      page size extensions                   = true
      time stamp counter                     = true
      RDMSR and WRMSR support                = true
      physical address extensions            = true
      machine check exception                = true
      CMPXCHG8B inst.                        = true
      APIC on chip                           = true
      SYSENTER and SYSEXIT                   = true
      memory type range registers            = true
      PTE global bit                         = true
      machine check architecture             = true
      conditional move/compare instruction   = true
      page attribute table                   = true
      page size extension                    = true
      processor serial number                = false
      CLFLUSH instruction                    = true
      debug store                            = true
      thermal monitor and clock ctrl         = true
      MMX Technology                         = true
      FXSAVE/FXRSTOR                         = true
      SSE extensions                         = true
      SSE2 extensions                        = true
      self snoop                             = true
      hyper-threading / multi-core supported = false
      therm. monitor                         = true
      IA64                                   = false
      pending break event                    = true
   feature information (1/ecx):
      PNI/SSE3: Prescott New Instructions     = true
      PCLMULDQ instruction                    = false
      64-bit debug store                      = true
      MONITOR/MWAIT                           = true
      CPL-qualified debug store               = true
      VMX: virtual machine extensions         = false
      SMX: safer mode extensions              = false
      Enhanced Intel SpeedStep Technology     = false
      thermal monitor 2                       = true
      SSSE3 extensions                        = true
      context ID: adaptive or shared L1 data  = false
      FMA instruction                         = false
      CMPXCHG16B instruction                  = true
      xTPR disable                            = true
      perfmon and debug                       = true
      process context identifiers             = false
      direct cache access                     = false
      SSE4.1 extensions                       = false
      SSE4.2 extensions                       = false
      extended xAPIC support                  = false
      MOVBE instruction                       = false
      POPCNT instruction                      = false
      time stamp counter deadline             = false
      AES instruction                         = false
      XSAVE/XSTOR states                      = false
      OS-enabled XSAVE/XSTOR                  = false
      AVX: advanced vector extensions         = false
      F16C half-precision convert instruction = false
      RDRAND instruction                      = false
      hypervisor guest status                 = false
   cache and TLB information (2):
      0xb1: instruction TLB: 2M/4M, 4-way, 4/8 entries
      0xb0: instruction TLB: 4K, 4-way, 128 entries
      0x05: data TLB: 4M pages, 4-way, 32 entries
      0xf0: 64 byte prefetching
      0x57: L1 data TLB: 4K pages, 4-way, 16 entries
      0x56: L1 data TLB: 4M pages, 4-way, 16 entries
      0x78: L2 cache: 1M, 4-way, 64 byte lines
      0x30: L1 cache: 32K, 8-way, 64 byte lines
      0xb4: data TLB: 4K, 4-way, 256 entries
      0x2c: L1 data cache: 32K, 8-way, 64 byte lines
   processor serial number: 0001-0661-0000-0000-0000-0000
   deterministic cache parameters (4):
      --- cache 0 ---
      cache type                           = data cache (1)
      cache level                          = 0x1 (1)
      self-initializing cache level        = true
      fully associative cache              = false
      extra threads sharing this cache     = 0x0 (0)
      extra processor cores on this die    = 0x0 (0)
      system coherency line size           = 0x3f (63)
      physical line partitions             = 0x0 (0)
      ways of associativity                = 0x7 (7)
      WBINVD/INVD behavior on lower caches = true
      inclusive to lower caches            = false
      complex cache indexing               = false
      number of sets - 1 (s)               = 63
      --- cache 1 ---
      cache type                           = instruction cache (2)
      cache level                          = 0x1 (1)
      self-initializing cache level        = true
      fully associative cache              = false
      extra threads sharing this cache     = 0x0 (0)
      extra processor cores on this die    = 0x0 (0)
      system coherency line size           = 0x3f (63)
      physical line partitions             = 0x0 (0)
      ways of associativity                = 0x7 (7)
      WBINVD/INVD behavior on lower caches = true
      inclusive to lower caches            = false
      complex cache indexing               = false
      number of sets - 1 (s)               = 63
      --- cache 2 ---
      cache type                           = unified cache (3)
      cache level                          = 0x2 (2)
      self-initializing cache level        = true
      fully associative cache              = false
      extra threads sharing this cache     = 0x0 (0)
      extra processor cores on this die    = 0x0 (0)
      system coherency line size           = 0x3f (63)
      physical line partitions             = 0x0 (0)
      ways of associativity                = 0x3 (3)
      WBINVD/INVD behavior on lower caches = true
      inclusive to lower caches            = false
      complex cache indexing               = false
      number of sets - 1 (s)               = 4095
   MONITOR/MWAIT (5):
      smallest monitor-line size (bytes)       = 0x40 (64)
      largest monitor-line size (bytes)        = 0x40 (64)
      enum of Monitor-MWAIT exts supported     = true
      supports intrs as break-event for MWAIT  = true
      number of C0 sub C-states using MWAIT    = 0x0 (0)
      number of C1 sub C-states using MWAIT    = 0x1 (1)
      number of C2 sub C-states using MWAIT    = 0x1 (1)
      number of C3 sub C-states using MWAIT    = 0x1 (1)
      number of C4 sub C-states using MWAIT    = 0x0 (0)
      number of C5 sub C-states using MWAIT    = 0x0 (0)
      number of C6 sub C-states using MWAIT    = 0x0 (0)
      number of C7 sub C-states using MWAIT    = 0x0 (0)
   Thermal and Power Management Features (6):
      digital thermometer                     = true
      Intel Turbo Boost Technology            = false
      ARAT always running APIC timer          = false
      PLN power limit notification            = false
      ECMD extended clock modulation duty     = false
      PTM package thermal management          = false
      digital thermometer thresholds          = 0x2 (2)
      ACNT/MCNT supported performance measure = true
      ACNT2 available                         = false
      performance-energy bias capability      = false
   extended feature flags (7):
      FSGSBASE instructions                    = false
      IA32_TSC_ADJUST MSR supported            = false
      BMI instruction                          = false
      HLE hardware lock elision                = false
      AVX2: advanced vector extensions 2       = false
      SMEP supervisor mode exec protection     = false
      BMI2 instructions                        = false
      enhanced REP MOVSB/STOSB                 = false
      INVPCID instruction                      = false
      RTM: restricted transactional memory     = false
      QM: quality of service monitoring        = false
      deprecated FPU CS/DS                     = false
      intel memory protection extensions       = false
      AVX512F: AVX-512 foundation instructions = false
      RDSEED instruction                       = false
      ADX instructions                         = false
      SMAP: supervisor mode access prevention  = false
      Intel processor trace                    = false
      AVX512PF: prefetch instructions          = false
      AVX512ER: exponent & reciprocal instrs   = false
      AVX512CD: conflict detection instrs      = false
      SHA instructions                         = false
      PREFETCHWT1                              = false
   Direct Cache Access Parameters (9):
      PLATFORM_DCA_CAP MSR bits = 0
   Architecture Performance Monitoring Features (0xa/eax):
      version ID                               = 0x2 (2)
      number of counters per logical processor = 0x2 (2)
      bit width of counter                     = 0x28 (40)
      length of EBX bit vector                 = 0x7 (7)
   Architecture Performance Monitoring Features (0xa/ebx):
      core cycle event not available           = false
      instruction retired event not available  = false
      reference cycles event not available     = false
      last-level cache ref event not available = false
      last-level cache miss event not avail    = false
      branch inst retired event not available  = false
      branch mispred retired event not avail   = false
   Architecture Performance Monitoring Features (0xa/edx):
      number of fixed counters    = 0x0 (0)
      bit width of fixed counters = 0x0 (0)
   extended feature flags (0x80000001/edx):
      SYSCALL and SYSRET instructions        = false
      execution disable                      = false
      1-GB large page support                = false
      RDTSCP                                 = false
      64-bit extensions technology available = true
   Intel feature flags (0x80000001/ecx):
      LAHF/SAHF supported in 64-bit mode     = true
      LZCNT advanced bit manipulation        = false
      3DNow! PREFETCH/PREFETCHW instructions = false
   brand = "Intel(R) Celeron(R) CPU          550  @ 2.00GHz"
   L1 TLB/cache information: 2M/4M pages & L1 TLB (0x80000005/eax):
      instruction # entries     = 0x0 (0)
      instruction associativity = 0x0 (0)
      data # entries            = 0x0 (0)
      data associativity        = 0x0 (0)
   L1 TLB/cache information: 4K pages & L1 TLB (0x80000005/ebx):
      instruction # entries     = 0x0 (0)
      instruction associativity = 0x0 (0)
      data # entries            = 0x0 (0)
      data associativity        = 0x0 (0)
   L1 data cache information (0x80000005/ecx):
      line size (bytes) = 0x0 (0)
      lines per tag     = 0x0 (0)
      associativity     = 0x0 (0)
      size (Kb)         = 0x0 (0)
   L1 instruction cache information (0x80000005/edx):
      line size (bytes) = 0x0 (0)
      lines per tag     = 0x0 (0)
      associativity     = 0x0 (0)
      size (Kb)         = 0x0 (0)
   L2 TLB/cache information: 2M/4M pages & L2 TLB (0x80000006/eax):
      instruction # entries     = 0x0 (0)
      instruction associativity = L2 off (0)
      data # entries            = 0x0 (0)
      data associativity        = L2 off (0)
   L2 TLB/cache information: 4K pages & L2 TLB (0x80000006/ebx):
      instruction # entries     = 0x0 (0)
      instruction associativity = L2 off (0)
      data # entries            = 0x0 (0)
      data associativity        = L2 off (0)
   L2 unified cache information (0x80000006/ecx):
      line size (bytes) = 0x40 (64)
      lines per tag     = 0x0 (0)
      associativity     = 4-way (4)
      size (Kb)         = 0x400 (1024)
   L3 cache information (0x80000006/edx):
      line size (bytes)     = 0x0 (0)
      lines per tag         = 0x0 (0)
      associativity         = L2 off (0)
      size (in 512Kb units) = 0x0 (0)
   Advanced Power Management Features (0x80000007/edx):
      temperature sensing diode      = false
      frequency ID (FID) control     = false
      voltage ID (VID) control       = false
      thermal trip (TTP)             = false
      thermal monitor (TM)           = false
      software thermal control (STC) = false
      100 MHz multiplier control     = false
      hardware P-State control       = false
      TscInvariant                   = false
   Physical Address and Linear Address Size (0x80000008/eax):
      maximum physical address bits         = 0x24 (36)
      maximum linear (virtual) address bits = 0x30 (48)
      maximum guest physical address bits   = 0x0 (0)
   Logical CPU cores (0x80000008/ecx):
      number of CPU cores - 1 = 0x0 (0)
      ApicIdCoreIdSize        = 0x0 (0)
   (multi-processing synth): none
   (multi-processing method): Intel leaf 1/4
   (APIC widths synth): CORE_width=0 SMT_width=0
   (APIC synth): PKG_ID=0 CORE_ID=0 SMT_ID=0
   (synth) = Intel Celeron M (Merom-L A1), 65nm

[vovk@samsung ~]$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 22
model name	: Intel(R) Celeron(R) CPU          550  @ 2.00GHz
stepping	: 1
microcode	: 0x44
cpu MHz		: 1995.088
cache size	: 1024 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss tm pbe lm constant_tsc arch_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm lahf_lm dtherm
bugs		:
bogomips	: 3990.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
---------------------------------------------------------------------------------------------------------------

By this information I can not determine exactly is my celeron processor 64 bit.

**Comment by graywolf2** [comment]
[vovk@samsung ~]$ sudo lshw -class cpu
  *-cpu                   
       description: CPU
       product: Intel(R) Celeron(R) CPU          550  @ 2.00GHz
       vendor: Intel Corp.
       physical id: 4
       bus info: cpu@0
       version: 6.6.1
       serial: 0001-0661-0000-0000-0000-0000
       slot: U2E1
       size: 1995MHz
       capacity: 2048MHz
       width: 64 bits
       capabilities: boot fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss tm pbe x86-64 constant_tsc arch_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm lahf_lm dtherm

Does "width: 64 bits" mean that my processor is 64 bit?

**Comment by NiceandGently** [comment]
>   64-bit extensions technology available = true
>   brand = "Intel(R) Celeron(R) CPU          550  @ 2.00GHz"

http://ark.intel.com/products/31727/Intel-Celeron-Processor-550-1M-Cache-2_00-GHz-533-MHz-FSB

yes, this smells like 64bit ;)

**Comment by graywolf2** [comment]
Thank you very much for explanation! :)

**Comment by graywolf2** [comment]
I had installed the Fedora 21 64 bit in my notebook. There is no bug with icons tooltips in this Fedora version.
![screenshot-5](https://cloud.githubusercontent.com/assets/12239412/7666878/649a5476-fbfe-11e4-875f-05dc156e582b.png)

**Comment by NiceandGently** [comment]
@monsta 
i think we can close the report, because there is nothing what we can do if i686 systems has issues with graphic drivers or xorg.

**Comment by graywolf2** [comment]
Okay. Close the report please. I dont use the i686 architecture more.
