### ISSUE TITLE
apps appearing behind the panel

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/mate-panel#306]
my son restarted my pc and when i logged back in the panel appears above fullscreen apps rather than the fullscreen app ending where the panel ends.

![screenshot-1](https://cloud.githubusercontent.com/assets/4412114/7899383/abf5e2a2-0731-11e5-99a7-3711a857afe8.png)

**Comment by monsta** [comment]
This is called "maximized", not "fullscreen". Fullscreen is what you see in your browser when you press F11 :smile: 

Anyway, this behavior is already reported in https://github.com/mate-desktop/mate-panel/issues/303.
