### ISSUE TITLE
Trash Applet 1.2.1 can't be opened properly in Mint 12

### ISSUE THREAD

**Issue by ludmilmm** [mate-desktop/mate-panel#31]
I added the Trash Applet 1.2.1 to the panel by: Right-click->Add to Panel. I can empty the trash but I cannot open it to view the files in my trash bin. When I click on "Open Trash", it gets opened by the gnome mplayer. If I use the main menu, then I can open it without any issues.

**Comment by kytsw** [comment]
Had a similar issue in Ubuntu using Mate, Where smplayer opened trash if launched from the panel. Fixed it by checking the default/preffered applications and switched the file manager from smplayer to caja/files.
