### ISSUE TITLE
An additional 1 pixel line to hidden panels...?

### ISSUE THREAD

**Issue by MarioMey** [mate-desktop/mate-panel#326]
EDIT: look the images in full-screen

As you can see my desktop, I have some icons in top and bottom panel:
![pantallazo-5](https://cloud.githubusercontent.com/assets/4954109/8722614/c289bf0e-2b9c-11e5-8c44-021d43f71cf4.png)

When these panels are hidden, the last line of pixels of the icons are shown:
![pantallazo-3](https://cloud.githubusercontent.com/assets/4954109/8722627/e51e6178-2b9c-11e5-9c93-7c283e06704c.png)

It is very annoying, because there is something strange "there". Sometimes, my eyes goes there, thinking there's something... and they are just the icons.

The solution should be one more line of pixels where the icons are not rendered. Or the panel completely hidden... nut I don't know how the mouse internally activate the panel. So, these are only suggestions.

Thanks!

**Comment by infirit** [comment]
Is this with Gtk2 or Gtk3?

In Gtk2 I see one pixel line for the whole panel not just the icons. This is more obvious when disable transparency so try that.

**Comment by MarioMey** [comment]
Thanks for the respond, infirit. I found what the problem was. I had configured the panels to be 32px height, the same as one of icon size (21, 22, 24, 32, 48). So, the icon is covering all the height. 

Now, I use 33px and there is one more line at the bottom. Just what I need.
