### ISSUE TITLE
Sometimes the drawer applet is not displayed after boot

### ISSUE THREAD

**Issue by graywolf2** [mate-desktop/mate-panel#327]
After 1 of 10 – 20 boots the drawer applet is not displayed.
Distribution: Fedora 21 64 bit with updates.
Notebook: Samsung R408. 2 mhz CPU, 2 mb RAM.
Mate panel version: 1.10.1.
This bug was in previous versions of mate panel and Fedora also.

Perhaps the bug reason is in read or write speed of notebook hard drive which may be slightly slow than in usual computer.
I have the fast computer with same mate panel configuration and this bug does not exist there.

To fix this bug I created ~/.config/autostart/reload-mate-panel.desktop file with the content:
[Desktop Entry]
Type=Application
Exec=mate-panel --replace
StartupNotify=false
Hidden=false
X-MATE-Autostart-enabled=true
X-MATE-Autostart-Delay=15
X-MATE-Autostart-Notify=false
Name=Reload mate panel

But this fix is not perfect because I must wait some time after boot before mate panel using.
Note: if X-MATE-Autostart-Delay is less than 15, sometimes the drawer applet is not displayed after mate panel reloading.

I have the firefox and skype in autostart also but I don't think it is the bug reason.
For the check some time ago I made start delay of these programs by 10 – 15 seconds using X-MATE-Autostart-Delay parameter. The bug was not solved.

I don't know how you can reproduce this bug. Maybe some of programs like virtualbox has the ability to slow down the read or write speed of virtual hard drive.

The drawer applet bug:
![bug_screenshot2](https://cloud.githubusercontent.com/assets/12239412/8755282/61d6855c-2cd2-11e5-9b79-3cfe25f51a5d.png)

The normal drawer applet:
![drawer_applet1](https://cloud.githubusercontent.com/assets/12239412/8755326/b8034dac-2cd2-11e5-901b-aa6ed2b42c53.png)
![drawer_applet2](https://cloud.githubusercontent.com/assets/12239412/8755327/b8043bb8-2cd2-11e5-92b5-170687072cc8.png)
##

**Comment by monsta** [comment]
Is the drawer still accessible while it's invisible? E.g. opening it, or right-clicking to show the menu, etc.

**Comment by graywolf2** [comment]
> Is the drawer still accessible while it's invisible? E.g. opening it, or right-clicking to show the menu, etc.

No. If I click on empty space (where the drawer must be) by left or
right button, there is no reaction from the invisible drawer.

I found the better way to fix this bug.
I think that this problem exists due to high processor load during
system boot. So I decided to delay the mate panel load.
I had copied /usr/share/applications/mate-panel.desktop to
~/.local/share/applications/mate-panel.desktop.
Then in ~/.local/share/applications/mate-panel.desktop I specified:
X-MATE-Autostart-Phase=Applications
X-MATE-Autostart-Delay=6

I also delayed the auto start of firefox and skype by 10 seconds.

This solution is not perfect. Approximately 1 time per 2 weeks the
drawer is invisible after boot and I press alt + F2 and run mate-panel
--replace.

Thank you very much for your message.

**Comment by monsta** [comment]
That's weird...
When it happens again, can you check ```~/.xsession-errors``` for any warnings from mate-panel or drawer itself? They can also be in the system journal (```journalctl -b0```).

**Comment by graywolf2** [comment]
> That's weird...
> When it happens again, can you check ~/.xsession-errors for any warnings from mate-panel or drawer itself? They can also be in the system journal (journalctl -b0).

I know about .xsession-errors and system log well. And in the past I
found nothing there when the bug happened. In the past I also tried to
do redirect the mate panel output to file but I did not find
suspicious things.

I even wanted create the script that will reload the mate panel when
the bug happens. But I could not because it is impossible to determine
when the bug happens.

Ok, I will check it again.
It is strange: during last 3 weeks I did not see the bug. The mate
panel works fine. It is seem like the delay of mate panel load is
helped.

**Comment by monsta** [comment]
Well, we've applied some fixes to drawer code in 1.12.2. I'm not really sure, but that might fix this bug as well.

**Comment by graywolf2** [comment]
Thank you very much for the great work!

Is it possible to update the drawer applet in Fedora 21?

**Comment by monsta** [comment]
F21 reached [EOL](https://fedoraproject.org/wiki/End_of_life) a few months ago, so @raveit65 won't do it.
He has enough work maintaining the supported Fedora releases and RHEL...

**Comment by raveit65** [comment]
Sorry, it's not the question if i won't or not, i can't build for f21 anymore, the branch is closed by fedora.
But you can use rhel7.2/centos7.2 which base of f21.
Or you need to rebuild latest SRPM from f21 with patches from 1.12 branch.
I'm not sure if they will apply on 1.10.1 package.
The SRPM you find here.
http://koji.fedoraproject.org/koji/buildinfo?buildID=668065

**Comment by info-cppsp** [comment]
@monsta 
I suggest closing this.
I have tested my old laptop - it is from 2006, this is from 2008 based on a manual I have found on the net - reloading the mate panel with prime 95 about 30 times. Granted, p95 doesn't effect hdd use, so I can't be certain, but I guess, I should have seen the error anyway.
(mint 17.3 mate-panel 1.12.1)

I suggest using memtest to test the memory and badblocks to test the hdd.
Maybe it would be a good idea to buy an ssd.
Also, please try the newest mate-panel version.

**Comment by monsta** [comment]
Ok. If it's reproduced again, we can reopen it.
