### ISSUE TITLE
Gtk3: Main menu improperly configured near bottom of side panel or in bottom panel

### ISSUE THREAD

**Issue by usdanskys** [mate-desktop/mate-panel#330]
Running 64-bit Fedora 23 branched with Gtk3-based Mate desktop. When a Main Menu applet is added to a panel, if that panel is a bottom panel, the menu displays approximately 20 blank lines above the actual menu contents, forcing me to scroll down to see the menu contents. When a Main Menu applet is placed in a side panel, this problem occurs to varying degrees, depending on how close the applet is positioned to the base of the screen. Screenshot.png show effect using MainMenu applet in bottom panel; Screenshot-1.png uses applet in right panel 
![screenshot](https://cloud.githubusercontent.com/assets/1627462/8892093/3d180b9e-330a-11e5-900d-8f1e3fc82a44.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/1627462/8892094/3d1dcd86-330a-11e5-86ed-392aba7cb43c.png)

**Comment by NiceandGently** [comment]
Confirmed with f23 + gtk+-3.17.5, but i can this also reproduce with stable f22 + gtk+-3.16.6.
So, i guess this is independent from gtk3 version. I do not have a mate gtk+3.14 installation anymore to confirm.
I see that scroll effect with rigtht click contexmenu too.
Also the contextmenu of the default menubar is affected.

**Comment by NiceandGently** [comment]
@usdanskys 
Can you please add GTK3: to header?

**Comment by NiceandGently** [comment]
confirmed, that fixes the issue.
@usdanskys 
I have updated fedora's gtk3 repo

**Comment by usdanskys** [comment]
Fixed the menu problem, but my Clock applet no longer shows. Creating a new panel and adding a Clock Applet, the clock does not show up until I add a Command Applet to the panel. Adding multiple command applets just adds more clocks. Interesting, but not expected behavior.

**Comment by usdanskys** [comment]
Overwriting the clock applet with the old clock applet from mate-panel-1.10.1-11.fc23.x86_64.rpm gives me a working clock applet in my panel. Creating a new panel and adding a clock applet to the new panel now works properly, too.

**Comment by NiceandGently** [comment]
mate-panel-1.10.2-10.2.git20150714.59c66fd.fc23.x86_64
was built from git snapshot from http://git.mate-desktop.org/mate-panel/commit/?id=59c66fd
+ 
http://git.mate-desktop.org/mate-panel/commit/?id=5d04731
+
http://git.mate-desktop.org/mate-panel/commit/?id=3fc68b4

I can confirm that i can't add the clock applet anymore with gtk+-3.17.x
But this works in f22 with gtk+-3.16.x
Sorry, i tested the build only with f22 :-/
I will try to build from 1.10.1 tarball + 5d04731 and 3fc68b4,
but without any other commit from master branch.

I noticed also several crashes/abrt alarms if i remove an applet from panel with that build.

**Comment by NiceandGently** [comment]
Looks like i did a build issue, btw. a prob with creating the git snapshot tarball.
@usdanskys 
Can you please test https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/SOURCE/mate-panel-1.10.2-10.3.git20150714.59c66fd.tar.xz
before i upload a broken build again?
This build fix the issue and has no **collateral damage**

**Comment by usdanskys** [comment]
Looks good
