### ISSUE TITLE
GTK3: cairo_pattern_t is NULL when change_background signal handler is invoked

### ISSUE THREAD

**Issue by assen-totin** [mate-desktop/mate-panel#331]
Tested with MATE 1.10 on Fedora 22 (GTK 3.16). My applets have a signal handler for the 'change_background' signal. According to mate-panel-applet.h, the signal handler will be invoked as: 
```
void (*change_background) (MatePanelApplet *applet, MatePanelAppletBackgroundType type, GdkRGBA* color, cairo_pattern_t *pattern);
```
However, `*pattern` is always  NULL. Normally, the pattern should be supplied and then there is no need to provide neither `type` nor `color`, since both can (and normally should) be extract from `pattern`. Worst of all, however, when the background is an image, we have no way of extracting it since the `pattern` is NULL.

**Comment by infirit** [comment]
I may not understand it depends on MatePanelAppletBackgroundType. We only use NULL in the first case where there is no panel background. There are two more cases where we use the colour or pattern, see https://github.com/mate-desktop/mate-panel/blob/master/libmate-panel-applet/mate-panel-applet.c#L1777

**Comment by infirit** [comment]
btw, you could use ```mate_panel_applet_set_background_widget``` and it will handle the background for you, example [here](https://github.com/mate-desktop/mate-sensors-applet/blob/master/sensors-applet/sensors-applet.c#L1310) and stop worying. Works on both gtk2 and gtk3.

**Comment by assen-totin** [comment]
Thanks, I'll check this. Still, I believe panel should always return a valid `pattern` and the colour + type should be extracted from it. 

WWell,

Assen

**Comment by infirit** [comment]
Ok, I see. But why would it return a background pattern when the panel has a background colour set. What is it that you want to do?

Regardless, if you don't need to modify your applet's background use mate_panel_applet_set_background_widget and stop listening for the background changed signal. There is a similar function for [gnome-panel](https://git.gnome.org/browse/gnome-panel/tree/libpanel-applet/panel-applet.c?h=gnome-2-32#n2291) >= 2.32.
