### ISSUE TITLE
removing the drawer crashes the panel sometimes

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-panel#334]
origin downstream report.
https://bugzilla.redhat.com/show_bug.cgi?id=1208991#c14
mate-panel-1.10.1-1.fc21
stacktrace: https://bugzilla.redhat.com/attachment.cgi?id=1010968
```
Thread 1 (Thread 0xb775e900 (LWP 9959)):
#0  0x420e6983 in g_type_check_instance_cast (type_instance=0x51b, iface_type=140473872) at gtype.c:4008
#1  0x08074c7b in panel_drawer_use_custom_icon_changed (settings=0x8654d58 [GSettings], key=0x850d8a0 "use-custom-icon", drawer=0x8653e98) at drawer.c:432
        use_custom_icon = <optimized out>
        custom_icon = 0x0
#2  0x420c2fb3 in g_cclosure_marshal_VOID__STRINGv (closure=0x8656198, return_value=0x0, instance=0x8654d58, args=0xbff4b69c "\240\330P\b\367\375\vB", marshal_data=0x0, n_params=1, param_types=0x84cdee0) at gmarshal.c:1004
        cc = 0x8656198
        data1 = <optimized out>
        data2 = <optimized out>
        callback = <optimized out>
        arg0 = 0x850d8a0
        args_copy = 0xbff4b6a0 "\367\375\vB"

cut
```
btw. it happens on my boxes too......sometimes

**Comment by monsta** [comment]
Oh, another drawer bug. Well, bugs like to live in drawers... :smile:

**Comment by raveit65** [comment]
@ monsta
f21 is EOL and downstream report is closed.
I like to remove broken and buggy drawer too, or to have a configure option to remove this broken stuff from build.

**Comment by monsta** [comment]
I wouldn't like to remove it - at least now. There was a lot of complaints when gnome guys did that (and didn't provide any replacement). People still use it in MATE as well.

**Comment by monsta** [comment]
Try https://github.com/mate-desktop/mate-panel/commit/c19a21e8dfeb7b72ff18ff63954130456dd2cdc7 - it might fix it...

**Comment by monsta** [comment]
Well, a few months passed... I guess it can be considered fixed?
