### ISSUE TITLE
Under Places the name 

### ISSUE THREAD

**Issue by theking2** [mate-desktop/mate-panel#335]
Under the Places section in the main menu the location "Wastebasket" is called "Trash"

Consistant naming helps usability

1) LinxuMint Mate version 17
2) Open main menu
3) Under Places the name of the wastebasket is Trash
4) The name of the specific place is consistent with Nautlius
5) Problem happens always

**Comment by infirit** [comment]
I suspect you are using the [mintmenu](https://github.com/linuxmint/mintmenu) which is not part of MATE. In both the menu's provided by mate-panel, main menu and menubar, I have no trash icon.

**Comment by monsta** [comment]
Yes it definitely looks so - and the bug should be reported in https://github.com/linuxmint/mintmenu/issues then.
