### ISSUE TITLE
Gtk3: na-tray applet lost transparency when using icon-padding

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/mate-panel#336]
![na-tray](https://cloud.githubusercontent.com/assets/961604/9111330/4d32dd5c-3c46-11e5-920e-376bb6e3d8a7.png)
This screenshot is with gtk+-3.17.x, for some reasons the new feature doesn't work with gtk+-3.16.
I used this setting in mate-applictions.css (green-submarine)
```
NaTrayApplet {
    -NaTrayApplet-icon-padding: 6px;
    -NaTrayApplet-icon-size: 16;
}
```
Here you see that the padding background left and right from the icon use the default bg from the theme. This is bad if a theme use a dark bg for the panel which differs from default theme bg, or using a transparency panel.
I tried to fix that with set background-color=transparent or border-color=transparent in theme settings, but all of this will be ignored.
You will see this also if you use a custom bg-color for the panel.
The only soution is to use
```
NaTrayApplet {
    -NaTrayApplet-icon-padding: 0px;
    -NaTrayApplet-icon-size: 16;
}
```
in themes. But than we don't need this new feature ;)
See also:
http://forums.mate-desktop.org/viewtopic.php?f=16&t=3668

**Comment by monsta** [comment]
Did it happen after @dnk's commits were merged?

**Comment by NiceandGently** [comment]
> Did it happen after @dnk's commits were merged?

Of course, without this commit you don't have a padding ---> no background of the padding area :)

**Comment by monsta** [comment]
Ah :smile:

**Comment by infirit** [comment]
I don't have this problem with 3.16.4 and green submarine.

**Comment by monsta** [comment]
Might be a problem in 3.17 which @NiceandGently is using?

**Comment by NiceandGently** [comment]
The prob is that those setting don't work with 3.16.
Try something like this

NaTrayApplet {
    -NaTrayApplet-icon-padding: 20px;
    -NaTrayApplet-icon-size: 16;
}
You will see any different to

NaTrayApplet {
    -NaTrayApplet-icon-padding: 0px;
    -NaTrayApplet-icon-size: 16;
}

**Comment by NiceandGently** [comment]
I found a setting to make the bg transparent.
```
/* no background for icon-padding area */
GtkTrayIcon.background {
    background-color: transparent;
}
```

**Comment by NiceandGently** [comment]
This can easily fix in a theme, so i will close the issue.
