### ISSUE TITLE
[bug?] GTK3 panels are hidden beyond the edge of the screen, except for one row of pixels.

### ISSUE THREAD

**Issue by trusktr** [mate-desktop/mate-panel#338]
I just switched to the GTK3 version of everything in Arch Linux (`pacman -S mate-gtk3 mate-extra-gtk3`), and the inertial scroll is quite pleasing, but I can't access my panels. They're hidden beyond the edges of the screen, except for a single row of pixels.

See the very top row of pixels of the screenshot (you'll need a dark background to see the light colors within this single row of pixels):

![hidden panels](https://cloud.githubusercontent.com/assets/297678/9153566/5c46e2fa-3e14-11e5-9807-f906b9284206.png)
##

**Comment by trusktr** [comment]
Here's a zoom shot of the top left:

![zoom](https://cloud.githubusercontent.com/assets/297678/9153574/f6614ab0-3e14-11e5-8f02-2f943a67f322.png)

**Comment by trusktr** [comment]
I tried looking in dconf, but I don't see anything relevant:

![screenshot-dconf editor](https://cloud.githubusercontent.com/assets/297678/9153768/d69b9a88-3e22-11e5-84e7-1c1a2cd1de46.png)

**Comment by NiceandGently** [comment]
I can't confirm that with fedora's mate gtk3 version.
Can access the top panel via right-click menu?
Try to set a larger value for the size via gesettings, maybe 50 px for testing

**Comment by raveit65** [comment]
@trusktr 
check this gsettings key
```
[rave@mother ~]$ gsettings get org.mate.Marco.general disable-workarounds
false
```
and set it to false.

**Comment by monsta** [comment]
I think it was something during upgrade to GTK+3 version in Arch. Since we can't reproduce this, and there was no additional feedback for almost a year, I'm closing this.
