### ISSUE TITLE
Feature Request: Transparency for elements of mate-panel

### ISSUE THREAD

**Issue by synthakai** [mate-desktop/mate-panel#341]
In mate-panel properties in the background tab when the "Solid color" option is chosen the transparency can be set with the "Style" slider. However, currently not all elements of mate-panel follow this setting.
I would like the following components of mate-panel to be transparent:
1. Mate-panel edges (those used to move the panel around).
2. Hide buttons (which can be enabled in General tab with "Show hide buttons") both with and without arrows.
3. Hovered and pressed clock applet button. Currently when the clock applet button is mouse-hovered, it is highlighted, but the solid colour without transparency is being used to display it.
If it is possible I would like to ask the transparency to be true transparency, not only showing the desktop wallpaper behind the panel but windows as well.
Sorry for the long post; pictures below
![screenshot-2](https://cloud.githubusercontent.com/assets/8536190/9379724/ece95cca-4733-11e5-906e-30fd6f6375e8.png) 
mate-panel edges and hovered calendar applet button are not transparent
![screenshot-1](https://cloud.githubusercontent.com/assets/8536190/9379827/ac6b6ee4-4734-11e5-8aec-734124bf5227.png) 
mate-panel is not transparent to windows

**Comment by monsta** [comment]
> If it is possible I would like to ask the transparency to be true transparency, not only showing the desktop wallpaper behind the panel but windows as well.

Only possible with GTK+3.

**Comment by raveit65** [comment]
all done with gtk3
