### ISSUE TITLE
Gtk3: use GdkAppLaunchContext for panel_run_dialog_launch_command

### ISSUE THREAD

**Issue by infirit** [mate-desktop/mate-panel#342]
We need to spawn on a specific screen, g_spawn_async does handle this afaics

**Comment by monsta** [comment]
Can we use [this function](https://github.com/mate-desktop/mate-desktop/blob/master/libmate-desktop/mate-desktop-utils.c#L185) (with some possible modifications if needed)?

**Comment by infirit** [comment]
Things seem to work fine with 3c21f66bf30810fcb25dfe8c3c0960df270dc416
