### ISSUE TITLE
Gtk3: replace GtkTable with GtkGrid?

### ISSUE THREAD

**Issue by yetist** [mate-desktop/mate-panel#343]
GtkTable has been deprecated since version 3.4 and should not be used in newly-written code, we should use GtkGrid. 

But gtk2 has no GtkGrid, and mate-panel use GtkTable in some ui files, so, if we change to GtkGrid, mate-panel could not build with gtk2.

these ui files are:
applets/clock/clock.ui
applets/fish/fish.ui
mate-panel/panel-properties-dialog.ui
mate-panel/panel-test-applets.ui

**Comment by monsta** [comment]
UI files are a problem here - you can't use ```#ifdef```s there :smile:

**Comment by infirit** [comment]
A couple of options..

Create two versions and install based on GTK_API_VERSION.
Have autoconf create the file (file.ui.in) and use some magic based on the same GTK_API_VERSION

**Comment by monsta** [comment]
Yes, ```.in``` files are a common thing, we might use it here as well...
Not sure if it's worth it though. Until that deprecated property makes loading ui files actually fail, we can still use it.

@NiceandGently: thoughts?

**Comment by NiceandGently** [comment]
Different UI files will help us with other deprecation too.

**Comment by monsta** [comment]
Done in https://github.com/mate-desktop/mate-panel/pull/462.
