### ISSUE TITLE
New feature : locking the panels

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-panel#345]
I install Linux Mint MATE in associations. I've got a big problem : some people in the associations sometimes remove the panels !
It is very problematic. Would it be possible to add an option that asks the admin password to remove an applet ? (using the right-click and red cross)

**Comment by infirit** [comment]
Use the "locked-down" key in ``org.mate.panel``. To lockdown dconf see https://wiki.gnome.org/action/show/Projects/dconf/SystemAdministrators?action=show&redirect=dconf%2FSystemAdministrators

**Comment by Petrouchka** [comment]
It would be interesting to ask admin password only for panel removing. It's impossible to remove panels on others systems (Windows, Mac OS X, ReactOS...) and it's normal. In MATE, a normal user can easily remove it.
