### ISSUE TITLE
Open with.. taskbar item stays longer than needed

### ISSUE THREAD

**Issue by Smile4ever** [mate-desktop/mate-panel#346]
When I open files or software, the "Opening..." or "Open with..." item stays in the taskbar longer (~10 seconds) than needed:
![openwith](https://cloud.githubusercontent.com/assets/544411/9581838/0f2fee30-5002-11e5-93fc-d9627cb96a13.png)
I observed this with GNOME2 in the past. This is using MATE 1.10.1.

As a workaround, is there a way to turn off these "ghost" windows?

**Comment by infirit** [comment]
This is called startup notification. What happens is that while starting a place holder is created until the real program is done starting. The program is then supposed to signal it is done starting which it seams is not happening here. Can you provide more info how vlc is started and with what arguments, iow your use case?

**Comment by Smile4ever** [comment]
This one for VLC. (Has the same effect whether StartupNotify is true or false)
[Desktop Entry]
Version=1.0
Name=VLC media player
GenericName=Media player
Comment=Read, capture, broadcast your multimedia streams
Exec=/usr/bin/vlc --started-from-file %U
TryExec=/usr/bin/vlc
Icon=vlc
Terminal=false
Type=Application
Categories=AudioVideo;Player;Recorder;
MimeType=video/dv;video/mpeg;video/x-mpeg;video/msvideo;video/quicktime;video/x-anim;video/x-avi;video/x-ms-asf;video/x-ms-wmv;video/x-msvideo;video/x-nsv;video/x-flc;video/x-fli;video/x-flv;video/vnd.rn-realvideo;video/mp4;video/mp4v-es;video/mp2t;application/ogg;application/x-ogg;video/x-ogm+ogg;audio/x-vorbis+ogg;audio/ogg;video/ogg;application/x-matroska;audio/x-matroska;video/x-matroska;video/webm;audio/webm;audio/x-mp3;audio/x-mpeg;audio/mpeg;audio/x-wav;audio/x-mpegurl;audio/x-scpls;audio/x-m4a;audio/x-ms-asf;audio/x-ms-asx;audio/x-ms-wax;application/vnd.rn-realmedia;audio/x-real-audio;audio/x-pn-realaudio;application/x-flac;audio/x-flac;application/x-shockwave-flash;misc/ultravox;audio/vnd.rn-realaudio;audio/x-pn-aiff;audio/x-pn-au;audio/x-pn-wav;audio/x-pn-windows-acm;image/vnd.rn-realpix;audio/x-pn-realaudio-plugin;application/x-extension-mp4;audio/mp4;audio/amr;audio/amr-wb;x-content/video-vcd;x-content/video-svcd;x-content/video-dvd;x-content/audio-cdda;x-content/audio-player;application/xspf+xml;x-scheme-handler/mms;x-scheme-handler/rtmp;x-scheme-handler/rtsp;
X-KDE-Protocols=ftp,http,https,mms,rtmp,rtsp,sftp,smb
Keywords=Player;Capture;DVD;Audio;Video;Server;Broadcast;
StartupNotify=false

Second desktop file, same problem:

[geoffrey@msi-laptop ~]$ cat /usr/local/share/applications/vlc-newinstance.desktop
[Desktop Entry]
Version=1.0
Name=VLC media player (new instance)
GenericName=Media player
Comment=Read, capture, broadcast your multimedia streams
Exec=env LANG=nl_BE.utf8 /usr/local/bin/vlc
TryExec=/usr/local/bin/vlc
Icon=vlc
Terminal=false
Type=Application
Categories=AudioVideo;Player;Recorder;
MimeType=video/dv;video/mpeg;video/x-mpeg;video/msvideo;video/quicktime;video/x-anim;video/x-avi;video/x-ms-asf;video/x-ms-wmv;video/x-msvideo;video/x-nsv;video/x-flc;video/x-fli;video/x-flv;video/vnd.rn-realvideo;video/mp4;video/mp4v-es;video/mp2t;application/ogg;application/x-ogg;video/x-ogm+ogg;audio/x-vorbis+ogg;audio/ogg;video/ogg;application/x-matroska;audio/x-matroska;video/x-matroska;video/webm;audio/webm;audio/x-mp3;audio/x-mpeg;audio/mpeg;audio/x-wav;audio/x-mpegurl;audio/x-scpls;audio/x-m4a;audio/x-ms-asf;audio/x-ms-asx;audio/x-ms-wax;application/vnd.rn-realmedia;audio/x-real-audio;audio/x-pn-realaudio;application/x-flac;audio/x-flac;application/x-shockwave-flash;misc/ultravox;audio/vnd.rn-realaudio;audio/x-pn-aiff;audio/x-pn-au;audio/x-pn-wav;audio/x-pn-windows-acm;image/vnd.rn-realpix;audio/x-pn-realaudio-plugin;application/x-extension-mp4;audio/mp4;audio/amr;audio/amr-wb;x-content/video-vcd;x-content/video-svcd;x-content/video-dvd;x-content/audio-cdda;x-content/audio-player;application/xspf+xml;x-scheme-handler/mms;x-scheme-handler/rtmp;x-scheme-handler/rtsp;
X-KDE-Protocols=ftp,http,https,mms,rtmp,rtsp,sftp,smb
Keywords=VLC;Player;Capture;DVD;Audio;Video;Server;Broadcast;

It seems like it's VLC Media Player (2.2.1) that is causing issues.

Also, mp4 files opened from PCManFM 1.2.3 in VLC Media Player have this issue. This isn't the case when using Caja.

xdg-open anyfile.mp4 (with VLC as the default video player) causes this same issue to appear.

Is there a way to disable all startup notifications in MATE for all programs?

**Comment by Smile4ever** [comment]
Caja has this issue too when I choose to open the file (Open with..) with VLC (new instance), the second desktop file.

**Comment by infirit** [comment]
I can't reproduce his with vlc 2.2.1. I tried from caja, mate-terminal and xdg-open all work perfectly fine and only briefly show the startup notification. But PCmanFM does show this problem which indicates to me it does not support startup notification.

I did notice the second desktop file points to ``/usr/local``, was this one build yourself? If so does the distro's prebuild one show the same problem?

Most toolkits these days support this out of the box and I do not know of a way to disable this except to set it accordingly in the desktop file.

**Comment by Smile4ever** [comment]
[geoffrey@msi-laptop /usr/local/bin]$ ls -l
lrwxrwxrwx 1 root root     12 02.06.2015 19:23 vlc -> /usr/bin/vlc*
It's a symlink. It once was a self-built VLC Media Player, but now it's simply a symlink.

I set VLC (new instance) as the default and the issue disappeared with xdg-open, VLC Media Player and PCManFM. I think this means VLC Media Player does not properly support StartupNotify when it is used with parameters. I've reported it here: https://trac.videolan.org/vlc/ticket/15386

> Most toolkits these days support this out of the box and I do not know of a way to disable this except to set it accordingly in the desktop file."

mate-panel could provide a setting (dconf or GUI) to hide the startup notification from the panel.

**Comment by Smile4ever** [comment]
I finally fixed it by:
- changing my default video player to VLC (new instance)
- editing the desktop file vlc.desktop and adding (again, I tried this before!) StartupNotify=false
- changing my default video player back to VLC

Thank you for all your efforts. I hope my fix/workaround will help others with the same problem.
