### ISSUE TITLE
Alt+F2 command run-application from panel hangs everything.

### ISSUE THREAD

**Issue by 133794m3r** [mate-desktop/mate-panel#348]
I'm on debian jessie with the default mate desktop isntall except I added system-tools to the default list and without question it acts like it's going to bring it up and then sits there hanging.

**Comment by 133794m3r** [comment]
Sep 16 08:20:12 sager-laptop org.mate.panel.applet.SensorsAppletFactory[1271]: (mate-sensors-applet:1453): dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.

here's some information from the panel's page that i think is what caused the crash/hangup of panel. Ituses 110% of cputime an this was was not hapening with previous versions of the panel. It's something new that's going on with the panel. If anyone can give me help with further debugging for the issue I'll provide the logs.

**Comment by monsta** [comment]
```
dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': Permission denied. dconf will not work properly.
```

Say hello to the old systemd bug that Debian maintainers still don't want to fix:
- https://bugs.debian.org/732209
- https://bugs.debian.org/766464
- https://bugs.debian.org/769889
- https://bugs.debian.org/767173
- https://bugs.debian.org/772910

Temporary fix: change ownership of ```/run/user/1000/dconf/user``` from root to yourself.
Works until the next usage of ```gksu``` (e.g. with pluma).

Closing as it's not mate-panel issue - it's a lot deeper.

**Comment by 133794m3r** [comment]
Where should I report an issue with the mimeapps list not being udpatged.
