### ISSUE TITLE
Mate panel won't load when 2 panels are in the same location

### ISSUE THREAD

**Issue by KwisatzHaderach** [mate-desktop/mate-panel#356]
I have usually 2 monitor setup with 2 panels, one up and one down, on monitor 2 and 1 panel down on monitor 1 (I had it left but wanted to avoid another bug with window list). But when I disconnect the ext monitor whole desktop goes funky and I can't do anything with it. If I reboot, the panels won't load properly at all, they just blink somehow and won't allow me to change anything. Also I would like to note that the panel on monitor 1 has autohide option set.

I have Fedora 21 with mate-panel-1.10.1-1.fc21.x86_64
##

**Comment by raveit65** [comment]
Does this issue still exists with actual f38 ?

**Comment by KwisatzHaderach** [comment]
I have no idea, haven't used mate for over 7 years.
