### ISSUE TITLE
Vertical centering of icons in notification area

### ISSUE THREAD

**Issue by sasht77** [mate-desktop/mate-panel#357]
Hello!

I have a problem with the location of the icons in Notification Area Applet. I am with Linux Mint 17.2 MATE. I use Linux Mint MATE from about two years and I am very happy from it. But I have one problem that I can't resolve. This is it:
The size of my bottom panel is 32 pixels and when I start some program, the icon in the notification area goes to the top of the applet and this is too unpleasantly. Here is the picture:

![viu1400400037r](https://cloud.githubusercontent.com/assets/15244070/10659226/e6037f40-78a6-11e5-8181-0d37e6ae4dca.png)

I want after program's launch, the icons to go at the middle of the notification area. I want it seems like this:

![viu1400400037r-2](https://cloud.githubusercontent.com/assets/15244070/10659250/0f904a3c-78a7-11e5-9581-e62ca8590b06.png)

Thank you!

PS: the icons that usually goes to the top of the panel are the icons of Skype and QBitTorrent.
##

**Comment by monsta** [comment]
Confirmed, I can reproduce it with Skype in Mint 17.2 and LMDE 2.
BTW, if I resize the panel *after* Skype is launched, the icon becomes centered. Might be related to https://github.com/mate-desktop/mate-panel/issues/50 as well.

**Comment by monsta** [comment]
Same as #50, fixed with migration to GTK+3.
