### ISSUE TITLE
Two stacked panels and autohide

### ISSUE THREAD

**Issue by randomguyeatspotato** [mate-desktop/mate-panel#358]
When I have two panels at the top of the screen and I set the bottom one to autohide, the whole desktop becomes unresponsive. The bottom panel autohides behind the top one and then everything goes wrong. The two overlapping panels flicker, the mouse cursor changes to a spinning wheel, and the keyboard and mouse buttons stop working. I can still move the mouse cursor, but I can't click on anything.
##

**Comment by randomguyeatspotato** [comment]
Issue #356 describes a similar issue.

**Comment by randomguyeatspotato** [comment]
Here is a video demonstration: https://youtu.be/gXL67AR3VOE

**Comment by dnord** [comment]
confirm this, this terribly broked my mate configuration, when i tried to configure another panel with applets. this is dangerous, as it can ocasionally totally break your mate session and it can be fixed only with manual editing of dconf configuration.

**Comment by Yasen6275** [comment]
Not blocking the desctop, but autohide dosent work corectly. No mater which one is set to auto hide, the older panel is hiding,

Debian testing, Mate 1.12.1

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-panel/issues/356
