### ISSUE TITLE
[1.11] crash on dragging applet from one panel to another

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#360]
If I add a second panel, add an applet to it, and try to drag it to the other panel, mate-panel crashes, leaving this error in dmesg. This began with the yetist gtk3 deprecation fixes and did not exist before. 

traps: mate-panel[1701] general protection ip:7ff77c5c336b sp:7fff858c78b0 error:0 in libgobject-2.0.so.0.4600.1[7ff77c58f000+52000]

Workaround is to always add applets to the panel on which they will be used, but this could be a nuisance for a new user setting up a non default panel layout.

**Comment by raveit65** [comment]
confirmed, moving an applet does not work anymore.
For some reasons fedoras abrt-tool don't give me a alarm about.
Can you create a stacktrace with gdb please?
see  http://fedoraproject.org/wiki/StackTraces#gdb

**Comment by lukefromdc** [comment]
OK, I got these two results from gdb, hope they help. The only available
debugging symbols were from a "make-install" of mate-panel to get the
debugging symbols for it (not in my Debian packages) installed for this
test:

From "run" and trying to drag an applet from a top to a bottom panel,
showing a segfault:

Starting program: /usr/bin/mate-panel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffebedc700 (LWP 17549)]
[New Thread 0x7fffeb6db700 (LWP 17550)]
Cannot register the panel shell: there is already one running.
[Thread 0x7fffeb6db700 (LWP 17550) exited]
[Thread 0x7ffff7f28a40 (LWP 17545) exited]
[Inferior 1 (process 17545) exited with code 0377]
(gdb) run
`/usr/bin/mate-panel' has changed; re-reading symbols.
Starting program: /usr/bin/mate-panel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffebedc700 (LWP 20840)]
[New Thread 0x7fffeb6db700 (LWP 20841)]
[New Thread 0x7fffeaccd700 (LWP 20842)]
[New Thread 0x7fffd9ce7700 (LWP 20843)]
[New Thread 0x7fffd92d7700 (LWP 20848)]

(mate-panel:20839): GLib-GObject-WARNING **: /build/glib2.0-l3js1a/glib2.0-2.46.1/./gobject/gsignal.c:2516: signal 'size_request' is invalid for instance '0xb0eac0' of type 'GtkLabel'
[Thread 0x7fffd9ce7700 (LWP 20843) exited]
[Thread 0x7fffd92d7700 (LWP 20848) exited]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffd92d7700 (LWP 21147)]
[New Thread 0x7fffd9ce7700 (LWP 21219)]

(mate-panel:20839): Gtk-CRITICAL **: gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed

(mate-panel:20839): Gtk-CRITICAL **: gtk_widget_get_can_focus: assertion 'GTK_IS_WIDGET (widget)' failed

(mate-panel:20839): Gtk-CRITICAL **: gtk_widget_set_can_focus: assertion 'GTK_IS_WIDGET (widget)' failed

(mate-panel:20839): Gtk-CRITICAL **: gtk_widget_grab_focus: assertion 'GTK_IS_WIDGET (widget)' failed

(mate-panel:20839): Gtk-CRITICAL **: gtk_widget_set_can_focus: assertion 'GTK_IS_WIDGET (widget)' failed

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff475b36b in g_type_check_instance_is_a ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) 

from 

thread apply all bt full:

Thread 8 (Thread 0x7fffd9ce7700 (LWP 21219)):
#0  0x00007ffff34dc52d in poll () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff44621dc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff44622ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff4d0356d in ?? () from /usr/lib/x86_64-linux-gnu/libdconf.so.1
No symbol table info available.
#4  0x00007ffff4488955 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff37b00a4 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#6  0x00007ffff34e506d in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 7 (Thread 0x7fffd92d7700 (LWP 21147)):
#0  0x00007ffff34e0ff9 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff44a6ada in g_cond_wait_until ()
---Type <return> to continue, or q <return> to quit---
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff4436a59 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff443707b in g_async_queue_timeout_pop ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ffff44893aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff4488955 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007ffff37b00a4 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#7  0x00007ffff34e506d in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 4 (Thread 0x7fffeaccd700 (LWP 20842)):
#0  0x00007ffff34dc52d in poll () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff44621dc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff44622ec in g_main_context_iteration ()
---Type <return> to continue, or q <return> to quit---
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fffeacd528d in ?? ()
   from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007ffff4488955 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff37b00a4 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#6  0x00007ffff34e506d in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7fffeb6db700 (LWP 20841)):
#0  0x00007ffff34dc52d in poll () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff44621dc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff4462562 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff4a5a4c6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#4  0x00007ffff4488955 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff37b00a4 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#6  0x00007ffff34e506d in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7fffebedc700 (LWP 20840)):
#0  0x00007ffff34dc52d in poll () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff44621dc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff44622ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff4462329 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ffff4488955 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff37b00a4 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#6  0x00007ffff34e506d in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7ffff7f28a40 (LWP 20839)):
#0  0x00007ffff475b36b in g_type_check_instance_is_a ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#1  0x00007ffff676766a in gtk_widget_queue_draw ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#2  0x0000000000422c14 in emit_applet_moved (panel_widget=0x876130, 
    applet=<optimized out>) at panel-widget.c:134
No locals.
#3  0x00000000004260e2 in panel_widget_reparent (
    old_panel=old_panel@entry=0x876390, new_panel=new_panel@entry=0x876130, 
    applet=applet@entry=0xca6170, pos=pos@entry=865) at panel-widget.c:2843
        ad = 0xc90940
        focus_widget = 0xbf82b0
        info = 0xc8a7f0
        __func__ = "panel_widget_reparent"
#4  0x000000000042647f in panel_widget_applet_move_to_cursor (
    panel=panel@entry=0x876390) at panel-widget.c:2300
        new_panel = 0x876130
---Type <return> to continue, or q <return> to quit---
        list = 0x7dcb30
        moveby = <optimized out>
        pos = 865
        movement = <optimized out>
        applet = 0xca6170
        device = <optimized out>
        forb = 0x0
        mods = 0
        ad = 0xc90940
        __func__ = "panel_widget_applet_move_to_cursor"
#5  0x0000000000426b2f in move_timeout_handler (data=0x876390)
    at panel-widget.c:2363
        panel = 0x876390
#6  0x00007ffff4462903 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#7  0x00007ffff4461e9a in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#8  0x00007ffff4462240 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#9  0x00007ffff4462562 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#10 0x00007ffff661d745 in gtk_main ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#11 0x0000000000421c3c in main (argc=1, argv=0x7fffffffe7f8) at main.c:170
        desktopfile = <optimized out>
        context = <optimized out>
        error = 0x0
(gdb)

**Comment by raveit65** [comment]
OH,
You have reference old reports, and we can't delete that.   :-/
se PM in forum.

**Comment by monsta** [comment]
The backtrace isn't useful without GLib and GTK+ debug packages anyway :smile:

As for the issue itself, it's not related to GTK+3: I just reproduced it here with GTK+2 build of MATE 1.11.
It's reproducible with two top panels or a top and bottom ones, doesn't matter. I'll try getting complete backtrace later.

**Comment by lukefromdc** [comment]
I can confirm that dragging applets between panels now works fine. I suppose when reparent is actually removed from GTK3 this will come up again-but will that be before GTK4?

**Comment by monsta** [comment]
It's too early to worry about that. :smile:
