### ISSUE TITLE
How to make a panel applet?

### ISSUE THREAD

**Issue by ArsenShnurkov** [mate-desktop/mate-panel#364]
http://unix.stackexchange.com/questions/241439/how-mate-panel-applets-is-better-than-icons-with-system-tray-protocol?
http://unix.stackexchange.com/questions/241435/why-to-write-applet-config-for-dbus?
http://unix.stackexchange.com/questions/241445/where-dbus-interface-for-mate-panel-applets-is-documented?
##

**Comment by raveit65** [comment]
@monsta 
can you please answer?
Reporter want's to write a panel applet.

**Comment by info-cppsp** [comment]
@ArsenShnurkov 
Please look at:
https://github.com/mate-desktop/mate-university
I am in the process of updating it.

@raveit65 
Please rename to 'How to make a panel applet?'
Please close.

**Comment by info-cppsp** [comment]
Well, links 1 & 3 are dead, so...
I guess you just have to check exiting applets / code for the DBus stuff.
I think normally an applet developer shouldn't be concerned about DBus things for applets.
Kinda inner workings.
But if you have other questions, feel free to ask.
