### ISSUE TITLE
mate-panel is not visible

### ISSUE THREAD

**Issue by XzK** [mate-desktop/mate-panel#365]
Hi there!

Today I installed Ubuntu Mate 15.10 64 bit on Dell Vostro A860. After installation was successful and I reboot the system, not even a trace from mate-panel. I tried with mate-panel in Terminal, but I received this note: "(...) there is already one running". Both old and new xsession-error files:
https://www.dropbox.com/s/z0whcn47uezsmfz/xsession-errors.old.txt?dl=0
https://www.dropbox.com/s/6fg6ra7foqsx6g9/xsession-errors.txt?dl=0

I kill this process from Terminal and it worked. I received these lines in xsession-errors:

Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1c00003 (Authentica)
meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed

Thanks in advance!

**Comment by raveit65** [comment]
Did you file out a report at ubuntu?
Only as a note, this is a bug reborting platform not a installation helpline ;)
A good place for getting first-aid is https://ubuntu-mate.community/ :smile:

**Comment by raveit65** [comment]
see https://bugzilla.redhat.com/show_bug.cgi?id=1288309#c16
and comment 17.
The user could solve the issue by resetting **all** dconf settings.
@XzK Try
For saving you settings use.
```
dconf dump / > user.txt
```
For re-setting **all** to default use.
```
dconf reset -f /
```

**Comment by raveit65** [comment]
btw. the culprit gsettings key is
< [org/mate/marco/general]
< disable-workarounds=true
see https://github.com/mate-desktop/mate-panel/issues/381

**Comment by monsta** [comment]
Looks like we aren't gonna receive any more info. So if there won't be any more feedback on this, I'm closing it as a distro-specific issue.

**Comment by raveit65** [comment]
well, #381 is the real report
