### ISSUE TITLE
gtk3: custom panel backgrounds only partially applied if theme also sets a bg

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#375]
When a custom panel background is selected on a gtk3 build of mate-panel, images and solid colors with 100% opacity are applied only to some panel widgets, not the panel itself on starting or restarting the panel. Altering the selection in any way from the panel properties dialog will re-read the custom background and apply it to the panel. If the panel background is a custom color with an alpha value other than full opaque applied it will work properly. Backgrounds applied by the panel theme (e.g. .mate-panel-menu-bar) work fine when system theme selected.

The widgets getting the background are all buttons in the panel, the na-tray, and applet backgrounds. The background set by the system theme, if any or else a transparent background is applied to the panel itself between the widgets.

WORKS:
background set by gtk theme with or without an alpha value
custom color background with non 100% alpha value, any theme
image background with Raleigh or some other themes not setting panel background
opaque color background with Raleigh or some other themes not setting panel background

DOES NOT WORK: 
image background with gtk theme setting panel bg or with Adwaita
custom color background with 100% opaque color with gtk theme setting panel bg or with Adwaita

Adwaita seems to be a special case: it does not set a mate or gnome panel background, yet behaves with custom themes as though it explicitly set the background transparent, not sure why.

Tested with both the current mate-panel and an old 1.9 build from before my theme support work, exactly the same behavior in a gtk3.18 system.

**Comment by lukefromdc** [comment]
UPDATE-I have just confirmed that this is a gtk3.18 only issue, does not affect gtk3.14 or gtk3.16

**Comment by raveit65** [comment]
I found out that
```
PanelToplevel.background.horizontal {
    background-color: transparent;
}
```
eliminate the background color from general theme settings.
And with 'PanelToplevel.background .button' you can style the 'hide panel buttons'.

The only damage in my themes which i see after 'Don't set the panel transparent by default' commit, is that this setting does not work if 'background-color' or 'background image' is choosen.
```
/* the grid left from wnckpager and wncktasklist */
MatePanelAppletFrameDBus {
    background-image: -gtk-scaled(url("assets/panel-grid.svg"));
    background-color: transparent;
    background-repeat: no-repeat;
    background-position: left;
}
```
But this isn't a drama for me ;)

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-panel/pull/384 fixes this in my testing with gtk3.19.5, more testing needed with gtk3.18

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-panel/commit/410de37dad6f46c6d28a3ebaf832efa1f31e3141
