### ISSUE TITLE
GTK3: Adding shortcut in panel and panel becomes unresponsive

### ISSUE THREAD

**Issue by willysr** [mate-desktop/mate-panel#376]
Adding application shortcut to panel will make the panel unresponsive until logged out or after being killed and it respawn

Tested in Slackware-Current
GTK+3-3.18.5
GCC-5.2.0
MATE 1.12.0

**Comment by monsta** [comment]
How did you add it? If you used right-click menu of an item in Applications menu... then it's https://github.com/mate-desktop/mate-panel/issues/305 :smile:

**Comment by willysr** [comment]
yes, i think it's a duplicate of that bug report. 
Closing
