### ISSUE TITLE
[URGENT] Consumes 110% cpu and memory leaks

### ISSUE THREAD

**Issue by CanadianJeff** [mate-desktop/mate-panel#377]
I hit a rather interesting 'feature' in systemd recently where doing an ` su - ` and then running a GUI application before switching back and executing one as your normal user will cause desktop to lock-up.

Examining /var/log/messages I found a series of messages similar to:

CRITICAL: unable to create file '/run/user/1000/dconf/user': 
Permission denied. dconf will not work properly.

It turns out that this is 'by design' in systemd... Yep, Lennart strikes again.

What in effect happens, is that the file /run/user/1000/dconf/user becomes owned by the root user

`
-rw------- 1 root root 2 Dec  1 15:31 /run/user/1000/dconf/user
`

[RANT] I get that some old paradigms need to die for various, valid, reasons. However, it should never, ever, ever, cause the whole desktop to crash. Ever! It's just hostile towards your user base. Period! [/RANT]

Fortunately a temp workaround is quite easy.

switch to tty1 with CTRL+ALT+F1 and login as root and delete the file

A suggested workaround which has not been confirmed to work is

Simply add this to the root users .bash_profile :

export XDG_RUNTIME_DIR=/run/user/0

**Comment by monsta** [comment]
What is the point of this report in regards to ```mate-panel```?

**Comment by flexiondotorg** [comment]
What distro? What version of MATE?

**Comment by monsta** [comment]
@flexiondotorg: any distro except Mint, any version of MATE... it's not fixable at this level anyway.
One needs to patch systemd with https://github.com/linuxmint/systemd-betsy/commit/f7ab85f1e1169ac1598dfc1fba1c01063840b3c5 to fix it.

**Comment by CanadianJeff** [comment]
they did not accept this change upstream

**Comment by CanadianJeff** [comment]
see: https://github.com/systemd/systemd/pull/2130

**Comment by monsta** [comment]
It's known. You're not the first one to try. This has to be patched in distros.
