### ISSUE TITLE
Panel too big, minimum size available: 34

### ISSUE THREAD

**Issue by Ubiquitous-X** [mate-desktop/mate-panel#378]
I am running 1.12.0 on Arch, with one panel at the bottom, which is a bit too big for my liking and when I went to properties to change the size, it seems like I cannot lower the size below 34, the down arrow greys out at 34.

**Comment by flexiondotorg** [comment]
GTK2 or GTK3 version of MATE?

**Comment by Ubiquitous-X** [comment]
It is the GTK2 version.

**Comment by flexiondotorg** [comment]
What font and font size do you have configured?

**Comment by Ubiquitous-X** [comment]
Silly me. I had Cantarell 11 configured and when I tried a smaller font
size I could lower the size on the panel.

Sorry Whimpy for wasting your time with such simple mistake by me. Keep up
the good work with MATE!

2015-12-06 1:07 GMT+01:00 Martin Wimpress <notifications@github.com>:

**Comment by flexiondotorg** [comment]
No problem.
