### ISSUE TITLE
1.12.0-12, 1.12.1 on Fedora (GTK3) using 100% cpu time

### ISSUE THREAD

**Issue by 6wl** [mate-desktop/mate-panel#379]
Updating mate-panel-libs and mate-panel to 1.12.0-12, or 1.12.1 from the GTK3 repo results in panel taking 100% cpu time on a single core.

Reverting back to 1.12.0-11 fixed the issue.

Anything else that would be helpful?

**Comment by raveit65** [comment]
Do you use f21, f22 or f23 ?
On baremetal or VM?

1.12.0-12 is build from 1.12.0 tarball + 2 commits from master/1.12 branch
https://github.com/mate-desktop/mate-panel/commit/ad3464d
https://github.com/mate-desktop/mate-panel/commit/0e477da

1.12.1 has this commits in tarball, see
https://github.com/mate-desktop/mate-panel/commits/1.12

Well, i never noticed this here on baremetal and on f22/f23 VMs.
0e477da is a huge change how to handle the background color of the panel.
I suspect that a setting or a applet causes the issue.
Can you reset the panel please with 'mate-panel --reset', to get a fresh panel configuration?
Note, you will lost all customizations, you can also create another fresh account to see if it happens there too.

**Comment by 6wl** [comment]
Fedora 23, baremetal.

The issue didn't occur with a new user.  So the suggestion its something config does sound likely.

Want me to dig further? Any merit in getting a copy of dconf for mate-panel?

**Comment by 6wl** [comment]
Tried changing a few settings within dconf and couldn't get it to drop CPU time.  Tried a reset, still same.  So then changed GTK3 theme from Ubuntu's Radiance, to Adwaita.

This fixed the issue.  Selecting Radiance or Ambiance from Ubuntu caused the high CPU usage again.

ubuntu-themes_14.04+16.04.20151127  is the one I'm using I think.

Thanks

**Comment by raveit65** [comment]
Well, is it allowed to use ubuntu themes in fedora :)
I suggest to use one of our mate themes. They are adjusted for the panel or other mate apps if using gtk3.
Adwaita has no adjustments for mate.
Ok, closing this because it isn't a panel issue.
