### ISSUE TITLE
Moving a panel to secondary monitor

### ISSUE THREAD

**Issue by ianunruh** [mate-desktop/mate-panel#38]
A feature that was in Gnome 2 seems to be unsupported in MATE. If I create a new panel, I have no way of moving it to a secondary monitor. It used to be that you just held ALT and dragged the panel wherever you wanted.

Maybe I'm missing something, but I've read the manual and asked in the IRC channel. Other people seem to have this problem as well.

**Comment by pandruszkow** [comment]
Update: as of 2019, this setting has been moved from `/apps/panel/toplevels/panel_0` to `/org/mate/panel/toplevels/top`.

I also recommend installing dconf-editor instead, as mateconf-editor appears to be gone from the packaged that replaces `mate-conf-editor`.
