### ISSUE TITLE
Window List applet ignores applications on second screen.

### ISSUE THREAD

**Issue by abickerton** [mate-desktop/mate-panel#380]
Version : 1.10.1+gfdl1-1 (Debian Sid)

Symptom: 
When an application is opened on the second screen, the application is not shown in the window list applet. When the same application on screen 0, it is correctly shown. 

All opened applications are available using Alt-Tab.

**Comment by monsta** [comment]
Sorry, stupid question... but did you try setting "Show windows from all workspaces" in the applet preferences first?

**Comment by abickerton** [comment]
Yes, I tried both. I'm only using one workspace though, so it shouldn't matter.

**Comment by monsta** [comment]
Ok, I see. Can you post the output of ```echo $DISPLAY``` from both screens?

**Comment by abickerton** [comment]
? 
$echo $DISPLAY
:0

Nvidia driver (340.96) shows a single screen 
3840x1080 pixels (1060x301 millimeters)

**Comment by monsta** [comment]
Ah, so you have two 1920x1080 screens as a single screen? Ok, I see. Then the panel should span both screens?

**Comment by abickerton** [comment]
That's what I would expect. The fact it only shows only on one screen is fine for me. I just expect applications opened on the second monitor be listed as it's the same workspace. Right now they aren't, hence the reason for this issue.

**Comment by abickerton** [comment]
Doh!, Wrong button...

**Comment by davidfraser** [comment]
+1

**Comment by abickerton** [comment]
It seems to be fixed in the latest Ubuntu as of today, so I'll close this issue.
