### ISSUE TITLE
gtk3.19 now breaks calendar window position

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#386]
On 12-22-2015, GTK3.19 received this commit which causes both the calendar window and the panel properties dialog to always come up at the top left of the screen, ignoring the functions that normally position them:

https://git.gnome.org/browse/gtk+/commit/?id=2438a06d54636e5074c29bd696e3e81e90288b8dRevert "window: Remove suspicious branch"
This reverts commit 67ab00e01ec06d7b05a82c3d80b235ac6c4abfd2.

See https://bugzilla.gnome.org/show_bug.cgi?id=759705
for a case where this makes a difference.

If I read that right, the features they removed were meant to support  gtk_widget_realize , which only is used in na-tray-applet.c but that is not where the problems are. I send an email to the author of this commit with no response, it appears this will NOT be reverted, so barring some later change before GTK 3.20 fixing this we will have to find a way to work around this. Menus position fine, that code might offer clues. I have not been able to fix this in initial experiments, so for now I am locally reverting the offending commit in my gk3 buiids. Needless to say, MATE cannot depend on a patched version of GTK3 a year from now.

**Comment by lukefromdc** [comment]
This function was added to gtkwindow.c

+  if (need_resize)
+    {
+      GtkWindowGeometryInfo *info = gtk_window_get_geometry_info (window, TRUE);
+      GtkAllocation allocation = { 0, 0 };
+      GdkRectangle configure_request;
+      GdkGeometry new_geometry;
+      guint new_flags;
+      gboolean was_realized;
+
+      /* We are going to go ahead and perform this configure request
+       * and then emulate a configure notify by going ahead and
+       * doing a size allocate. Sort of a synchronous
+       * mini-copy of gtk_window_move_resize() here.
+       */
+      gtk_window_compute_configure_request (window,
+                                            &configure_request,
+                                            &new_geometry,
+                                            &new_flags);
+      
+      /* We update this because we are going to go ahead
+       * and gdk_window_resize() below, rather than
+       * queuing it.
+       */
+      info->last.configure_request = configure_request;
+      
+      /* and allocate the window - this is normally done
+       * in move_resize in response to configure notify
+       */
+      allocation.width  = configure_request.width;
+      allocation.height = configure_request.height;
+      gtk_widget_size_allocate (widget, &allocation);
 
+      /* Then we guarantee we have a realize */
+      was_realized = FALSE;
+      if (!_gtk_widget_get_realized (widget))
+	{
+	  gtk_widget_realize (widget);
+	  was_realized = TRUE;
+	}
+
+      /* We only send configure request if we didn't just finish
+       * creating the window; if we just created the window
+       * then we created it with widget->allocation anyhow.
+       */
+      if (!was_realized)
+        gdk_window_move_resize (_gtk_widget_get_window (widget),
+				configure_request.x,
+				configure_request.y,
+				configure_request.width,
+				configure_request.height);
+    }

**Comment by raveit65** [comment]
here is another breakage https://bugzilla.redhat.com/show_bug.cgi?id=1294319
....does using 3.19 makes sense in this state?
I'm pretty sure damage, inc company will break and revert a lot of thins during development ;)

**Comment by lukefromdc** [comment]
I'm just trying to keep up with all the changes as I don't want to stew for months about
getting an utterly broken theme and broken MATE install months down the road. It's a
moving target right now but unless everyone wants to permanently blacklist everything 
later than gtk3.18 we will be stuck with this down the road. If we use only older versions
of gtk3 we would end up having to fork them-and THAT would mean loading three toolkit
libraries on any system with MATE, a gtk2 app, and a gtk3 app loaded.  Alternate would
be to port gtk2 to wayland...

We can wait to see if they revert this one, but I would not bet in it as it fixed a broken
(well sort-of) sidenbar in gnome-disks. GNOME is not known as a listerer, though in the
3.10 cycle they DID revert the hard-removal of menu icons from GTK, simply making them
a deprecated option instead.

**Comment by lukefromdc** [comment]
Found a fix for this:
https://github.com/mate-desktop/mate-panel/pull/387

**Comment by lukefromdc** [comment]
it is possible to use the compiz "put" window management plugin to force the dialog windows made by applications like Caja, Pluma, and so many others to roughly (but not exactly) the center of the screen. GNOME will be under a lot of pressure to revert this ugly mess or fix it elsewhere in gtk. Perhaps they could fix this in gtkdialog.c  and not have to revert their "fix" for the gnome-disks sidebar. We shall see, it might pay to put these PR's on hold until this shakes out. If I have to find and fix all this in Caja, Pluma, etc it will be a lot of hard work. Experimenting with Caja I was able to quickly fix the file-conflct dialog but the rest of them (in eel) were too complex for an easy fix.

**Comment by lukefromdc** [comment]
Caja fixes now at 
https://github.com/lukefromdc/caja/tree/gtk3.19-bugfixes ,
pluma fixes except for print dialog(whole mess internal to gtk?) at
https://github.com/lukefromdc/pluma/tree/gtk3.19-bugfixes

Keeping these "parked" but merging them into my continuously updated branches for local use. If GTK fixes this upstream it call all be reverted, if gtk3.20 gets released with this issue it can be fast-forwarded and merged. 

A note concerning Pluma: I get 
"Gtk-WARNING **: Theme parsing error: <data>:5:22: The :focused pseudo-class is deprecated. Use :focus instead." 
with any version built with gtk3.19 but cannot find that pseudo-class loaded anywhere in the Pluma code, nor in mate-desktop.

**Comment by raveit65** [comment]
> A note concerning Pluma: I get
"Gtk-WARNING **: Theme parsing error: :5:22: The :focused pseudo-class is deprecated. Use :focus instead."
with any version built with gtk3.19 but cannot find that pseudo-class loaded anywhere in the Pluma code, nor in mate-desktop.

Simply change that in your theme.
Theme parsing errors can always fixed by the theme itself.

**Comment by raveit65** [comment]
Btw. i need to finish the port to 3.20 for BlueMenta theme first, than i can test all you fixes for 3.20.
Thank you

**Comment by lukefromdc** [comment]
Thanks.  Given that I will park my fixes for everything else I find on my own 
branches but not submit PR's yet. These branches are split out from my 
continously updates ones that fork from them, then merge upstream commits
as they arrive plus any other bugfixes I have for my own use.

Hopefully GTK3.19 will settle down now. I haven't had any new theming issues
except the occasional new deprecation warning for weeks. A bigger problem is
deprecation warnings for theme elements GTK says are loaded from data but
which I cannot find in the code.

**Comment by lukefromdc** [comment]
The problem is lots of these have <data>in them are are not found in my theme
as I replace them as soon as they come up. The string :focussed is not in any 
file of the gtk3.20 version of my theme, yet I get this on opening pluma or even
gedit 3.18

**Comment by lukefromdc** [comment]
As of Jan 3, 2015 window positions in GTK3.19 got fixed in GTK3 with this commit

https://git.gnome.org/browse/gtk+/commit/?id=e93d64e4c3cdc71972bc92106763f29bfdc0abbf

reverting the commit that created all these problems. Let's hope it stays this way.
The gnome-disks sidebar this was aimed at is now fixed some other way. Looks like
we just caught a break.

I will update the caja branch I build from to reflect this and revert the rest of my debian
packages to mate-desktop/master. I'll leave these branches in existance but close
the PR's as they would now just add several lines of unneeded code. Leaving the
branches up covers for any future return of this problem, I would not want to have to redo
days of work in that event.

**Comment by flexiondotorg** [comment]
@lukefromdc Thanks for your diligence on these matters. Just posting here so you know your efforts are appreciated and being read ☺

**Comment by lukefromdc** [comment]
Closing as this is fixed in gtk3
