### ISSUE TITLE
Unified panel as in Linux Mint Mate edition.

### ISSUE THREAD

**Issue by bharat226g** [mate-desktop/mate-panel#390]
It will be great if main panel and window list panel are unified as in Linux Mint Mate edition.

![](http://www.linuxmint.com/pictures/screenshots/qiana/gallery/mate4.jpg)

Enhances user experience greatly for desktop users.  
The old top and bottom panel style is too obsolete, i think.

Thanks :)

**Comment by flexiondotorg** [comment]
The dual panel layout is simply the default. MATE Tweak can be used, in the distros that ship it, to chose alternative panel layouts.

**Comment by raveit65** [comment]
Or via gsettings.
[rave@mother ~]$ gsettings get org.mate.panel default-layout
'fedora'
