### ISSUE TITLE
Opened window preview

### ISSUE THREAD

**Issue by clagiordano** [mate-desktop/mate-panel#391]
Hi,

there is a way to enable window preview on mouse hover for window list applet?

Best regards

**Comment by raveit65** [comment]
You need to install compiz and enable the preview plugin.
Btw. not a bug!

**Comment by clagiordano** [comment]
It was not a bug but an information request or a feature request... 
anyway as for the window shadow or window preview on Alt-tab key combination where for that is used automatically compiz for the "compositing window manager"  (I suppose), I was hoping there was a way for enable  windows previews in the same way on mate-panel/mate-applet/marco window manager.

Thank you,
best regards
