### ISSUE TITLE
na-tray icon image corruption on slow machine only

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#394]
Beginning with the Jan 6 build of mate-panel build with/run on gtk3.19, I noticed corruption of icon images in the tray only on my slowest machine, an Intel Atom netbook. Interacting with any icon in the corrupted area reloads the image and it then renders correctly. On my faster AMD FX machine there is no sign at all of this problem.

**Comment by lukefromdc** [comment]
Looks like this is specific to Marco, appearing only with Marco 1.13, not with any 1.12 version (I rebuilt after every commit and the very last version of 1.12 from Jan 2  was OK), and not with compiz. Opening a new issue there

**Comment by lukefromdc** [comment]
All versions of Marco 1.12 or 1.13 show this problem, the last version of 1.10 is clean. Never saw this before a few days ago, possibly an interaction between recent background changes in the panel and the "extents" or "crashfix" branches merged during Marco 1.11?

**Comment by monsta** [comment]
I'm yet to reproduce this... it doesn't happen to me - though it's a VM and GTK+ is 3.18.6.
Can you try ```git bisect``` to find the commit that possibly caused it?

**Comment by lukefromdc** [comment]
No I cannot. I've never once done something like that and in fact the only 
things I have ever made work from the command line in GIT are "clone"
and "pull," that's it. 

I did however have saved Debian packages from every version of Marco 
I built in that time period, looks like the only things I didn't save as separate
packages were updates to NEWS. Here's what I got, from the comment on
the Marco issue report:

K,I just tested the 1.11 versions I saved as Debian packages. The version I built on Oct 25, whose last commit was
eceb8d7
window: initialize custom_frame_extents

was good. The next version I has was an Oct 31 build of 1.11.1. The only actual code changes there (as opposed to NEWS updates) was the combined merge of the "extents" branch from which the previous good commit and those that led to it came and the "window-move crash fix" branch. One way of invoking the panel corruption is in fact to move the tray on the panel, which is moving a window.

The only commit still shown on the timeline after those branches were merged between the 1.11.1 release and the last good one is
0303e70

window: initialize fullscreen to FALSE

Not sure if that had anything to do with the window move bugfix referred to in my changelogs and in the NEWS file

**Comment by lukefromdc** [comment]
One more test I will run is to try the laptop with current marco and gtk3.18, to see if this is a gtk3.19/20 specific bug

**Comment by lukefromdc** [comment]
Just tested with gtk3.18.0, same results. On the other hand, this might be platform-specific in some way. Never saw it in anything except that Atom netbook, so no surprise it doesn't appear in a VM. Could video driver 2d code be affecting this?

**Comment by monsta** [comment]
Well, I heard of some screen artifacts on Intel videocards in LMDE 2 (based on Debian Jessie). People seem to solve it only by installing Liquorix kernel, see http://forums.linuxmint.com/viewtopic.php?f=239&t=196272.

**Comment by lukefromdc** [comment]
I would rather have screen artifacts than risk compromising security on
that particular laptop.  BTW, I realized today that I still have all the 
Debian packages for the panel for many months, so I will try them one
after another to see if some older version of the panel works right with
newer Marco. Those packages are granular almost to individual commits
and often only one commit between them. Thus I might be able to find
the exact change that made the panel do this unless of course ALL versions
do this back to the first 1.10 version.

**Comment by lukefromdc** [comment]
It looks like this is indeed a screen actifact bug, probably caused by a 
very recent driver or Xorg update. The Mesa code (from an ubuntu PPA)
should not be a factor in Marco but that Intel xorg driver update I got on
Jan 2 from the same PPS could very well be a factor.

I also found a workaround, though since the bug is erratic and does not
appear every time it wil take some testing to know for sure: set an image
background. All solid color backgrounds whether theme or user are affected
but so far I have been unable to reproduce the bug when using an image
background.

I tested multiple versions of mate-panel all the way back to 1.10.0 initial
release without my theme work, all were affected exactly the same way.
Since the Marco version that is not affected far predates the bug showing 
up, and since I never saw it during my gtk3.18 days yet still got it when I
rolled back to gtk3.18, that leaves the X driver issue.

Maybe marco hits the driver a little different since that 1.11 version but it
seems to me that the driver must be the culprit as it's the only recent change
that cooincides with the bug showing up, and all recent panel and marco
changes have no effect.

**Comment by monsta** [comment]
Maybe try drivers from Debian repos instead of PPA?

**Comment by lukefromdc** [comment]
Those drivers are used to get maximum video card performance on other
machines which share root file system images with the laptop. Not practical
to use reverted drivers on one machine only, and a test revert would require
a manual download of every replacement package from Debian's website. 
Keeping that would cause the laptop and desktop filesystems to diverge, so
no longer would they be functional backups for each other.

Much easier to set an image as the panel bg on the laptop.

If the Ubuntu PPA's break I will just end up building Mesa and probably X locally
 as well.

**Comment by lukefromdc** [comment]
Closing this, haven't seen this happen in a while-probably due to driver updates. Also DID see similar corruption in Iceweasel scrollbars for a while, further suggesting video drivers were at fault
