### ISSUE TITLE
Windows in the Window List always group together, no matter the setting.

### ISSUE THREAD

**Issue by Cloaky** [mate-desktop/mate-panel#395]
The Window List groups windows 2 by 2 when the panel is enlarged to 50+ pixels, even when the Window Grouping setting in the Window List Preferences is set to 'Never group windows'. 

This does not occur if the panel is set to a size below 50 pixels.

This is occurring on MATE 1.10.2

**Comment by monsta** [comment]
That setting actually means "Group windows of the same application into a single tasklist item". You can open several terminals to test this.
