### ISSUE TITLE
Feature request: Don't show tooltip in clock applet

### ISSUE THREAD

**Issue by zaps166** [mate-desktop/mate-panel#397]
One more option to not show the tool tip with a date.

Currently this is annoying: scrolling something down by scroll bar, mouse is over the clock applet and then scrolling up and then tooltip is displayed somewhere on the screen.

**Comment by zaps166** [comment]
Updating a tooltip also causes problems on on fullscreen applications on nvidia proprietary drivers when VSync and AllowFlipping are enabled (example: show seconds on clock applet, run 'glxgears -fullscreen' and if the mate-panel is visible - set 'always on top' for the glxgears. The gears animation will stop on every second).
Disabling ```gtk_widget_set_tooltip_text()``` function in mate clock applet fixes the problem.
I think that tooltip which displays current date or "Click to hide month calendar" shouldn't be updated on every second :smile:
The same problem with OpenGL is on temperature applet (so I thing that is also caused by tooltip).

**Comment by zaps166** [comment]
The PR #423 accidentally fixes the problem with described problem in first comment (with annoying tooltip somewhere on screen) :)

**Comment by raveit65** [comment]
merged 299fd12061be8eec8cdb97b7b0afb0307ef86944
