### ISSUE TITLE
ADD Window List: Feature: ability to set custom titles

### ISSUE THREAD

**Issue by allanlaal** [mate-desktop/mate-panel#400]
ADD Window List: Feature: ability to set custom title (prefixes) for windows in right click menu

use case:
this would improve workflow UX greatly. I could add UTF-8 icons or short tags as window titles when there are many many windows open. It's much better than seing a generic icon or the first few letters of a long title

**Comment by monsta** [comment]
Please discuss this with the developers of libwnck, the library which is used in window list applet.
