### ISSUE TITLE
ADD Window List: Feature: disable appending ... to shortened titles

### ISSUE THREAD

**Issue by allanlaal** [mate-desktop/mate-panel#401]
show letters instead, makes no sense to use up valuable space to show generic dots that mean nothing

this could be a separate option or preferably the new default behaviour (needs discussion)

**Comment by monsta** [comment]
Please discuss this with the developers of libwnck, the library which is used in window list applet.

**Comment by allanlaal** [comment]
filed as: https://bugzilla.gnome.org/show_bug.cgi?id=773502

**Comment by allanlaal** [comment]
I'm actively trying to solve this upstream. libwnck uses GTK's method gtk_label_set_ellipsize(), which adds the "⋯" character at the end of the text, if it doesnt fit its GTKLabel (window title in this case)
