### ISSUE TITLE
The volume monitor complains about not finding BDMV index filealways with all external devices.

### ISSUE THREAD

**Issue by 133794m3r** [mate-desktop/mate-panel#402]

**Comment by 133794m3r** [comment]
I cannot edit my original issue but anyway here's the log in the file manager.

Jan 29 10:58:23 das-home org.gtk.Private.UDisks2VolumeMonitor[1574]: index_parse.c:191: indx_parse(): error opening /media/wiiext4/BDMV/index.bdmv
Jan 29 10:58:23 das-home org.gtk.Private.UDisks2VolumeMonitor[1574]: index_parse.c:191: indx_parse(): error opening /media/wiiext4/BDMV/BACKUP/index.bdmv
Jan 29 10:58:23 das-home org.gtk.Private.UDisks2VolumeMonitor[1574]: index_parse.c:191: indx_parse(): error opening /media/wiifat32/BDMV/index.bdmv
Jan 29 10:58:23 das-home org.gtk.Private.UDisks2VolumeMonitor[1574]: index_parse.c:191: indx_parse(): error opening /media/wiifat32/BDMV/BACKUP/index.bdmv


It's done that ever since I played a blu-ray from an external drie and it'snever been fixed, and fills up the log pointlessly.

**Comment by 133794m3r** [comment]
I cannot remove libbluray which is apparently the source of this issue since apparently now mate requires it for whatever the hell reason. And doing so will destroy all of mate so it's something with maet I guess now.

**Comment by flexiondotorg** [comment]
The issue appear to be in UDisks2, which is not a MATE component. Are you running Ubuntu MATE?

**Comment by monsta** [comment]
Please contact UDisks2 maintainers or developers about this.
