### ISSUE TITLE
mate-panel 1.13.0 release doesn't include up-to-date translations

### ISSUE THREAD

**Issue by tarakbumba** [mate-desktop/mate-panel#404]
"Computer" string in menubar > Places is shown in English on a Turkish locale system.(../mate-panel/panel-menu-items.c:1080) sitll.Altough translation is completed 3 months ago and it is translated in Tx, latest release doesn't include these.

**Comment by monsta** [comment]
Well it's ok for development version. We'll update all the translations before releasing MATE 1.14.

**Comment by monsta** [comment]
All translations are updated now.
