### ISSUE TITLE
places as part of the menu-bar not configureable

### ISSUE THREAD

**Issue by FreeInMind** [mate-desktop/mate-panel#408]
Places as part of the menu-bar is not configureable, but in the mint-menu it is (in mintmenu.plugins.places )
##

**Comment by info-cppsp** [comment]
@FreeInMind 
![screenshot at 2018-01-28 21-30-43](https://user-images.githubusercontent.com/31438307/35487023-23222f94-0477-11e8-9a73-128fbad23963.png)

If you right click on one of 3 menus, after adding it to the mate-panel, you can click 'Edit Menus'.
(mint 18.3 mate-panel 1.18.6)
Is this the issue?

**Comment by info-cppsp** [comment]
Let me learn how to read...

https://askubuntu.com/questions/29103/how-to-customize-places-menu
Does this help?
![screenshot at 2018-01-28 22-09-52](https://user-images.githubusercontent.com/31438307/35487103-3ad11906-0478-11e8-8f8e-c65a51dbb65d.png)

You can set up places with bookmarks in mint too.

**Comment by info-cppsp** [comment]
nvm, now I know what you mean.
feature request.

**Comment by info-cppsp** [comment]
@FreeInMind 
updated comment.
I kinda know what to do, maybe I get back to doing it later...
