### ISSUE TITLE
Minimizing an app using mate-panel switches keyboard layout.

### ISSUE THREAD

**Issue by omusil24** [mate-desktop/mate-panel#409]
When I minimize an application by clicking on it in the mate-panel taskbar, keyboard layout switches from Czech to the "system-default" (en_US) one. It doesn't happen with every application, only with some specific ones like Mate Terminal, Pluma or Google Chrome for example. Happens at about 90% of times.
Minimizing using the buttons in the corner of the window doesn't trigger this.

Regarding my keyboard layout setup, I'm using Czech as the first one, English (US) is second. I'm also running iBus with "Czech - Czech" first and "Korean - Hangul" second.
Locales:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
```

The system is latest Fedora 23 x86_64. Versions of MATE packages:

```
libmatekbd.x86_64                     1.12.1-1.fc23
mate-applets.x86_64                   1.12.1-1.fc23
mate-control-center.x86_64            1.12.1-2.fc23
mate-desktop.x86_64                   1.12.1-1.fc23
mate-desktop-libs.x86_64              1.12.1-1.fc23
mate-menus.x86_64                     1.12.0-3.fc23
mate-menus-libs.x86_64                1.12.0-3.fc23
mate-notification-daemon.x86_64       1.12.1-1.fc23
mate-panel.x86_64                     1.12.1-1.fc23
mate-panel-libs.x86_64                1.12.1-1.fc23
mate-polkit.x86_64                    1.12.0-1.fc23
mate-power-manager.x86_64             1.12.1-1.fc23
mate-search-tool.x86_64               1.12.0-1.fc23
mate-session-manager.x86_64           1.12.1-1.fc23
mate-settings-daemon.x86_64           1.12.1-1.fc23
mate-system-log.x86_64                1.12.0-1.fc23
mate-system-monitor.x86_64            1.12.1-1.fc23
mate-terminal.x86_64                  1.12.1-1.fc23
mate-themes.noarch                    3.18.0-1.fc23
mate-user-guide.noarch                1.12.0-1.fc23
mate-utils-common.noarch              1.12.0-1.fc23
```
##

**Comment by raveit65** [comment]
I recall a similar issue (not with panel, more general) from a guy who use english and bulgarian keyboard layout in the beginning of f23.
In the end he could solve the issue with removing and re-adding the us layout after a restart.

**Comment by omusil24** [comment]
Yeah, that works. But after a restart it's not working properly again. And I don't want to do this everytime I start my computer. And I don't know if it's connected to the panel or not, it just seemed like the most appropriate place.

**Comment by raveit65** [comment]
I'm pretty sure that is a fedora issue, maybe im-settings. You can try to disable im-settings-mate from autostart.
@assen-totin
Sorry that i bother you.
Do you remember how do solve the issue with different keyboard layouts in the beginning of f23?
Looks like we have here the same issue.

**Comment by assen-totin** [comment]
It was a bit weird - I removed the second layout I had added during installation and added it again. No idea what was wrong (or missing?), but this fixed the case. Hope this helps:
https://bugzilla.redhat.com/show_bug.cgi?id=1279074#c6

**Comment by omusil24** [comment]
There's no im-settings-mate running or even in autostart. There was only ```imsettings-switch -n -q -x``` being autorun but disabling that made no difference. There was also ```/usr/libexec/imsettings-daemon``` running but killing it also made no difference.

And as I said, removing and adding the second (en_US) layout fixes the problem but only until the next start of the computer.

**Comment by raveit65** [comment]
I can't reproduce this with f23, here i have 2 languages installed, english (us) and german installed by anaconda during installation.
German is the default language.
But i see no switching to english layout if i minimize Mate Terminal, or Pluma.
I do not use Google chrome.

**Comment by omusil24** [comment]
With Google Chrome it happens the most, pretty much everytime. With the other apps, it depends. It seems like there are different "states" depending on in which order I opened or focused all the windows, so sometimes minimizing Pluma or terminal does nothing, sometimes it behaves exactly like Chrome.
