### ISSUE TITLE
Some applets are missing and there are three strange icons

### ISSUE THREAD

**Issue by ubunteroz** [mate-desktop/mate-panel#410]
![mate-panel](https://cloud.githubusercontent.com/assets/1107652/13370930/2bd4197c-dd4b-11e5-8d89-5b4a9b1a88ae.png)

**mate-panel v1.12.2** from Debian testing repository

Update to v1.12 is causing many issues for mate-panel. NetworkManager and Dropbox icons are missing. If I launch an application which have an icon in panel, the icons will not show up. There are also three strange icons in notification area.

**Comment by raveit65** [comment]
Looks like an downstrean issue.
Debian report?

**Comment by flexiondotorg** [comment]
Those are the Keyboard LED indicators that can be enabled by changing a key with dconf-editor. If you install `mate-tweak` you can toggle the Keyboard LED with it.
