### ISSUE TITLE
GTK+-3.20: panel crashed if removing an applet

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-panel#414]
This is reproducible with every applet.
```
Thread 1 (Thread 0x7f68eae77a80 (LWP 24494)):
#0  0x000055a596b33bdf in mate_panel_applet_locked_change_notify (settings=0x55a597512300 [GSettings], key=0x7f68e79b733a "locked", applet=0x55a5972001f0) at applet.c:186
        __inst = 0x55a5972001f0
        __t = 94169690598512
        __r = <optimized out>
#1  0x00007f68e763dfac in g_cclosure_marshal_VOID__STRINGv (closure=0x55a5971c8630, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x55a596f8a1e0) at gmarshal.c:1794
        cc = 0x55a5971c8630
        data1 = <optimized out>
        data2 = <optimized out>
        callback = <optimized out>
        arg0 = 0x7f68e79b733a
```
full stacktrace at
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/backtrace-applet-remove

**Comment by lukefromdc** [comment]
For some reason this does not occur on my system. I am using gtk3.19.10 from GIT master current as of Feb 26 at the moment. Wonder if this is gtk3.19 version specific?

**Comment by raveit65** [comment]
It looks like this is unreleated to gtk+ toolkit version.
I see this crash also in fedora 24 Mate gtk+-2 environment test with tarball from #/419 PR.
Need to test this more.

**Comment by raveit65** [comment]
@lukefromdc 
which glib2 version are you using?

**Comment by lukefromdc** [comment]
I've got 2.46.2-3 from Debian Unstable

**Comment by raveit65** [comment]
It is an glib (probably debugging issue),
Fedora's bug reporting tool pointed me to an old an closed report from mate-panel.
https://bugzilla.redhat.com/show_bug.cgi?id=1068968
our upstream report:
https://github.com/mate-desktop/mate-panel/issues/166
After installing stable glib2-2.48.0 the issue is gone in gtk2 and gtk3 environment.
Same with crashing of some applications if closing, ie. caja-actions.
I'm so so bored about their debbuging stuff during during development.
Every year the same.
Ok, i will leave the report 1 or 2 days open to be sure.
