### ISSUE TITLE
Bug in the menu when using Compiz

### ISSUE THREAD

**Issue by gabrielsbarros** [mate-desktop/mate-panel#416]
There is a bug in the menu when using the following settings of MATE Tweak:

Window Manager: Compiz
Panel layout: Redmond
Panel Features: ☑ Enable advanced menu

When you click the menu, sometimes it appears suspended. This doesn't happen when using Marco as Windows Manager.

Tested with Ubuntu MATE 15.10 and 16.04 beta.

![img](https://cloud.githubusercontent.com/assets/3298817/13801189/5b1c43dc-eb0e-11e5-834d-204d7d700e49.png)

**Comment by flexiondotorg** [comment]
This is not a mate-panel bug. It is a compiz issue, with no general purpose solution. 

https://bugs.launchpad.net/ubuntu-mate/+bug/1419346
