### ISSUE TITLE
Mate 1.12.1: Mate-Panel: Issue with  focussing elements on the panel using the keyboard

### ISSUE THREAD

**Issue by domasofan** [mate-desktop/mate-panel#422]
Hi all,

I just noticed that i have some problems focussing some elements on the panel using the keyboard.

I navigate using the cursor keys.

i wonder if it is just me but i got reports from other people who are blind and use screen readers.
so this seems not to be something i just seem to experience.

basically how it feels like is when you move to the panel and start wandering through it that it seems to be blank and the screen reader seems to report nothing.

would be nice if someone could have a look at this.

greetings,
simon

**Comment by raveit65** [comment]
This is fixed with mate-panel-1.14.1
https://github.com/mate-desktop/mate-panel/commit/e14d3305b6ea36bb68db6c410494824e3c64ab5d
You should update to Mate 1.14.x

**Comment by domasofan** [comment]
did that.
thanks very much.

greetings,
simon

Am 18.06.2016 um 13:49 schrieb raveit65:
> This is fixed with mate-panel-1.14.1
> https://github.com/mate-desktop/mate-panel/commit/e14d3305b6ea36bb68db6c410494824e3c64ab5d
> You should update to Mate 1.14.x
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mate-desktop/mate-panel/issues/422#issuecomment-226937420
>

-- 
Simon Eigeldinger
Follow me on Twitter: http://www.twitter.com/domasofan/
E-Mail: simon.eigeldinger@vol.at
MSN: simon_eigeldinger@hotmail.com
ICQ: 121823966
Jabber: domasofan@andrelouis.com

---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by raveit65** [comment]
Ok, fine :)
closing.
