### ISSUE TITLE
Need an option for adding border to the panel

### ISSUE THREAD

**Issue by thachngopl** [mate-desktop/mate-panel#424]
VirtualBox  5.0.16
LinuxMint Mate Debian 2
Theme:
- Control: Redmond
- Window Border: WinMe

Mate panel version 1.8.1:
![1 8 1](https://cloud.githubusercontent.com/assets/16706272/14276864/c30ae506-fb4a-11e5-8aa3-ba72c1547c6a.PNG)
Mate panel version 1.12.2:
![1 12 2](https://cloud.githubusercontent.com/assets/16706272/14276989/5a7b1794-fb4b-11e5-9fc9-17a3a8f56419.PNG)

Thanks
##

**Comment by info-cppsp** [comment]
@monsta 
If I could bother you to close this issue in favor of https://github.com/mate-desktop/mate-panel/issues/344.
Thanks.
