### ISSUE TITLE
FIX neither the Power Management battery/charge icon nor the Battery Charge Monitor panel applet update/refresh

### ISSUE THREAD

**Issue by allanlaal** [mate-desktop/mate-panel#425]
system: Lenovo Thinkpad W541 with a Lenovo stock 9 cell battery
OS: Ubuntu 14.04 LTS
mate-desktop: 1.10.2-1~trusty1.0

steps to reproduce:
A.1: select "Always display an icon" in Power Management. unplug laptop.
Expected behaviour: Power Management Notification Area icon changes from being plugged in to a battery
Actual behaviour: icon does not change

A.2:
I wait 15 minutes to see if the battery % changes
Expected behaviour: battery % drops from the last value seen
Actual behaviour: % value does not change

B.1: Add 2x Battery Charge Monitors applets to panel:
- one with "show time"
- the other with "show percentage"
  wait 15min
  Expected behaviour: battery % and time drops from the last value seen
  Actual behaviour: neither values change

Facts:
when I killall mate-panel to restart mate-panel, all applets load new values, but do not update.
this works fine: upower -i /org/freedesktop/UPower/devices/battery_BAT0
##

**Comment by allanlaal** [comment]
extra info:

$ cat /sys/class/power_supply/BAT0/uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=10800000
POWER_SUPPLY_VOLTAGE_NOW=10222000
POWER_SUPPLY_POWER_NOW=61056000
POWER_SUPPLY_ENERGY_FULL_DESIGN=99470000
POWER_SUPPLY_ENERGY_FULL=96640000
POWER_SUPPLY_ENERGY_NOW=35570000
POWER_SUPPLY_CAPACITY=36
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=45N1779
POWER_SUPPLY_MANUFACTURER=SANYO
POWER_SUPPLY_SERIAL_NUMBER= 2422

$ acpi -V
Battery 0: Discharging, 37%, 00:38:49 remaining
Battery 0: design capacity 9587 mAh, last full capacity 9314 mAh = 97%
Adapter 0: off-line
Thermal 0: ok, 77.0 degrees C
Thermal 0: trip point 0 switches to mode critical at temperature 200.0 degrees C
Cooling 0: x86_pkg_temp no state information available
Cooling 1: intel_powerclamp no state information available
Cooling 2: Processor 0 of 10
Cooling 3: Processor 0 of 10
Cooling 4: Processor 0 of 10
Cooling 5: Processor 0 of 10
Cooling 6: Processor 0 of 10
Cooling 7: Processor 0 of 10
Cooling 8: Processor 0 of 10
Cooling 9: Processor 0 of 10

$ upower -i /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               SANYO
  model:                45N1779
  serial:               2422
  power supply:         yes
  updated:              R 08 apr   2016 10:59:03 EEST (9 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              36,81 Wh
    energy-empty:        0 Wh
    energy-full:         96,98 Wh
    energy-full-design:  99,47 Wh
    energy-rate:         61,043 W
    voltage:             10,268 V
    time to empty:       36,2 minutes
    percentage:          38%
    capacity:            97,4967%
    technology:          lithium-ion
    icon-name:          'battery-good-symbolic'
  History (charge):
    1460102343	38,000	discharging
  History (rate):
    1460102343	61,043	discharging


P.S. my laptop does not have support for 2 batteries, this used to work at some point in time between last July and this year with this laptop (can't remember when exactly it stopped working)

**Comment by raveit65** [comment]
Does this issue still exists?

**Comment by allanlaal** [comment]
prolly ok now
