### ISSUE TITLE
Feature Request: ‘Sticky-Center’ property for panel items  [$120]

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/mate-panel#426]
It would be nice to be able to "snap" panel items to a relative position at the center of an horizontal panel layout.
I have no clue how hard such a feature would be to implement and I understand this might not seem like something very important, but I feel like it would add quality to the overall interface.
Not having the "sticky-center" makes it dicey to locate items, especially variable width items such as clocks at the dead center of the screen.

I've described further what I mean in the Ubuntu MATE forums [here](https://ubuntu-mate.community/t/mate-panel-feature-request-sticky-center-property-for-panel-items/4913).

And here's a couple of screenshots showing what's doable under the old "fallback" desktop:
http://i.imgur.com/doQF6KE.jpg
http://i.imgur.com/8mevJG4.jpg

In this layout the two system monitors, the two network folders and the clock are all "Sticky-Center".

Cheers

Edit: a downstream bug report for this issue:

https://bugs.launchpad.net/ubuntu-mate/+bug/1708649

##

**Comment by FennFelis** [comment]
U find a way to center items in mate-panel?
I have this trouble:
[http://imgur.com/xzhYWyR](url)
[http://imgur.com/xzhYWyR](url)

The clock are moved when I resize my screen. I want to put in the center of screen independently of screen size, there is any solution?

**Comment by epgfm** [comment]
Not really. You can set the position of an item via gsettings but you have to know the exact width and it's of no help for variable-width items.
I've just posted a [50$ bounty on this](https://www.bountysource.com/issues/32817997-feature-request-sticky-center-property-for-panel-items), feel free to add to it.

**Comment by Michael-AU** [comment]
This has been reported before as early as 2012 (https://github.com/mate-desktop/mate-panel/issues/62) and 2014 (https://github.com/mate-desktop/mate-panel/issues/183). Note in the 2014 report the then main developer had an offer of help but suggested it would not be incorporated. Now the developers want money to do it. I know Mate is a small project with very few devs but to ignore an offer of help and then 2-3 years later ask for money to do what would have been done  for free is a [gobsmack](https://www.urbandictionary.com/define.php?term=gobsmack) moment for FOSS.

**Comment by DoktorStein** [comment]
Surely a very sad moment for **FOSS**.

**Comment by Toromino** [comment]
Is there anyone working on this? :)

**Comment by thesquash** [comment]
There absolutely is.  I actually have a patch for this that (as far as I can tell) works (https://raw.githubusercontent.com/thesquash/patches/master/mate-panel_Center_stick_applets.patch), and at this very moment I'm working on a pull request to get this issue solved once and for all after these years.

I know, however, that my code will have some flaw or shortcoming or somebody'll have a bone to pick with it somehow, and that's fine.  But that means the PR will take time to be applied (if it's accepted at all -- but that's probable), and this'll drain resources away from me.

I don't want to sound selfish, but if anyone wants to **ensure** that I'll go through with this feature addition and I'll go through any hoops and contortions needed to get this pull request merged, please drop another bounty.  Thanks in advance, for support and for patience.

**Comment by Toromino** [comment]
Very nice work, mate

**Comment by lukefromdc** [comment]
Note that the current PR as of May 7 segfaulted when I tried it on Debian Unstable w locally compiled MATE from git master and a highly customized panel layout

**Comment by thesquash** [comment]
I fixed the PR.  The PR has way, way more details about what went wrong.

**Comment by lukefromdc** [comment]
Just retested, segfaults gone, last two applets on my layout(farthest right) were gone too, one showing up almost all the way to the left and one missing. This sort of thing is easily fixed on a one-time update but would no doubt generate bug reports. We could do this anyway and document that as a known issue if there is a good enough reason of course
