### ISSUE TITLE
[GTK3 Version] Panel becomes unresponsive to mouse after adding an icon to the panel.

### ISSUE THREAD

**Issue by Ufeldraku** [mate-desktop/mate-panel#427]
As the title says the "applications", "places", and "system" menus and notification area become unresposive to the mouse, the "Clock" applet is fine, though.

**Comment by monsta** [comment]
Yes, it's very annoying bug. Already reported at https://github.com/mate-desktop/mate-panel/issues/305 though, so closing this one.
