### ISSUE TITLE
Feature request: new option for panel/animation-speed: instant

### ISSUE THREAD

**Issue by anton-z-s** [mate-desktop/mate-panel#428]
It would be great to have the ability to make hidden panel appear instantly. To get rid of the need to wait for the panel to appear.
Since almost every other DE have the ability to disable panels hide/unhide animation, i thought that this feature may be useful.
##

**Comment by Azarien** [comment]
I remember this was possible in GNOME 2.
This is super annoying, I like to disable all animations and there's no option to disable this one.

**Comment by kn00tcn** [comment]
according to the arch wiki https://wiki.archlinux.org/index.php/MATE#Panel_speed_settings

i am confirming that i made it instantly popup when the mouse goes to the bottom of the screen & i even tried making 1sec delay for it to hide after the cursor leaves to see that the values are doing something useful

this setting has probably been around for years if not always, unfortunately i wasnt around to notice in april

i will probably attempt to add a visual setting in the panel properties so nobody has to deal with lame dconf settings (what kind of dconf editor cant add a new key!? then i cant figure out the syntax in terminal to create a new string for the animation speed... why is that even hardcoded as words)

**Comment by anton-z-s** [comment]
To disable bottom panel popup animation just run `dconf write /org/mate/panel/toplevels/bottom/enable-animations false`.
