### ISSUE TITLE
GTK2: Panel default style doesn't have borders anymore

### ISSUE THREAD

**Issue by Exalm** [mate-desktop/mate-panel#430]
Panel should draw borders when default style (as opposed to a fill color or an image background) is used. In MATE 1.12.2 is doesn't anymore.

Comparison (left MATE, right GNOME 2.28, but it looked the same in MATE 1.10):
Clearlooks:
![clearlooks](https://cloud.githubusercontent.com/assets/1510457/14856324/6b4c8b14-0cb9-11e6-825f-74fc0eec08e8.png)

Clearlooks-Classic:
![clearlooks-classic](https://cloud.githubusercontent.com/assets/1510457/14856325/6b4ed9d2-0cb9-11e6-8fc6-16fab6a0fe69.png)

Simple:
![simple](https://cloud.githubusercontent.com/assets/1510457/14856326/6b518484-0cb9-11e6-9490-2171a32745f5.png)

Raleigh:
![raleigh](https://cloud.githubusercontent.com/assets/1510457/14856327/6b566030-0cb9-11e6-8f8d-91dc980ab400.png)

Distro: Debian Sid

**Comment by raveit65** [comment]
Please use Mate themes, all those themes don't support mate-panel.

**Comment by Exalm** [comment]
Ok. Same results with TraditionalOk, TraditionalOkGreen, TraditionalOkTest. No idea about other themes, since I don't know how they're supposed to look.

**Comment by monsta** [comment]
Wasn't it already reported in https://github.com/mate-desktop/mate-panel/issues/344?

**Comment by Exalm** [comment]
Oops. Yes, it was.
