### ISSUE TITLE
Taking screenshots doesn't work while any mate-panel menu is opened

### ISSUE THREAD

**Issue by drws** [mate-desktop/mate-panel#433]
If a certain menu is opened from the mate-panel (for example I consider "Places" a menu), an user is unable to take a screenshot **neither** with keyboard (the designated hotkey doesn't do anything in this case) **nor** with the "Take Screenshot" application from mate-utils (a click in its window closes the aforementioned mate-panel menu).

While I don't consider the second way as a bug I think the first one should be considered as such. Also the volume or brightness "dropdowns" produce the same result - no screenshot is taken.

**Comment by raveit65** [comment]
You've to use a timing in m-s-s gui if you want to shoot an image from any menu.

**Comment by monsta** [comment]
IIRC it's a limitation in GTK+ itself.

**Comment by raveit65** [comment]
A menu type window can never been focused if mate-screenshot dialog window have the focus.
How should that work? :smile:

**Comment by flexiondotorg** [comment]
As mentioned, use the timer in the screenshot application, the expose the menu you want and wait for the screenshot to be captured.

**Comment by drws** [comment]
@raveit65 The point of my bug report is the fact that **global** hotkey for taking screenshots does not work as expected - it works in any application, but not while any menu in mate-panel is opened. @flexiondotorg Is this expected behaviour?

I propose reopening of the bug with the focus on the hotkey bug report, not the second one which I already dismantle in the OP ("While I don't consider the second way as a bug...").

**Comment by monsta** [comment]
It's not just the panel. Open a menubar item or a right-click menu in some other GTK+ app and you'll get the same behavior.

**Comment by drws** [comment]
@monsta do you maybe know if this bug is already reported on GTK bugtracker?

**Comment by raveit65** [comment]
:smile: 
I promised you that gtk+ dev will say ' use a GtkPopoverMenu', which stays always open until you click somewhere in another area.

**Comment by raveit65** [comment]
Btw. you can add keyboard shortcut with 'mate-keybinding-properties'
1. click on add button
2. choose a name , ie. Sceenshot with delay
3. set command, ie. mate-screenshot --delay=5
4. close the window
5. click on shortcut
6. type a shortcut, ie alt+Rolling or what ever you want
That's it ;)

**Comment by monsta** [comment]
I don't remember if it had been reported... and their search isn't very good, though googling with ```site:``` keyword should help a bit.
