### ISSUE TITLE
Panels disappearing after "mate-panel --reset"

### ISSUE THREAD

**Issue by seamus-45** [mate-desktop/mate-panel#436]
| Package | Version |
| --- | --- |
| OS | Ubuntu Xenial 16.04 |
| MATE | 1.12 |
| GTK | 2.24.30 |
| GLIB2 | 2.48.0 |
### Steps to reproduce

1) launch `mate-panel --reset`
### Result

Layout is resetted, but panels is disappear while still in processes, until `mate-panel --replace` do not runned.
### Expected result

Panels should be reloaded with new layout.
##

**Comment by flexiondotorg** [comment]
You should run `mate-panel --reset --replace`

**Comment by raveit65** [comment]
nice trick, i never known that :)

**Comment by seamus-45** [comment]
I have tried --replace command line switch, but still get same behavior :(

**Comment by pellcorp** [comment]
I actually habe same issue.  I can switch layouts which use same menu bar but switching to a layout which uses the new style menu results in all panels disappearing.  I can switch back to an old style to recover

Tweak works fine.  So what else is tweak calling other than mate-panel --reset --replace --layout somelayout

**Comment by pellcorp** [comment]
It seems to work randomly.  A restart does however apply the change

**Comment by pellcorp** [comment]
Run the same command twice works and it works successfully second time.  Seems consistent.  But it only seems to work when you have --reset --layout and --replace on both commands

**Comment by pellcorp** [comment]
OK so I narrowed if down.

You can call --reset --layout somelayout

And theb call --reset by itself second time and the panel changes apply perfectly every time

**Comment by monsta** [comment]
I can't reproduce it with 1.18.

**Comment by monsta** [comment]
So I was able to reproduce it in a few Ubuntu MATE systems which have GTK+ 3.22.

We have two problems here.
First, some callbacks connected to GSettings might still be invoked while the panel is being deleted. This causes random crashes on `mate-panel --reset`.
Second, if that crash doesn't happen, and all the panels are deleted, we have the next problem. Reloading the default layout after the panel reset might start too early, while the previous layout isn't completely deleted yet. In this case the reloading function doesn't do its work, so the new panels don't appear.

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/mate-panel/commit/5e2b2a876e481ef98ed8ebd75bfa656a60253571 and https://github.com/mate-desktop/mate-panel/commit/8dd8eaa8252ed2627b5e9a384d6c58d0a74c22be. Commits will be picked for 1.22 and 1.20 branches too.
