### ISSUE TITLE
tray: possible mis-sized icons

### ISSUE THREAD

**Issue by MingcongBai** [mate-desktop/mate-panel#437]
This is a GTK+ 3 (3.20) build of MATE 1.14.0, and I am seeing some weirdly sized tray icons on the panel...

![2016-05-21 20-30-02](https://cloud.githubusercontent.com/assets/5006263/15451811/1d38e138-1f93-11e6-81b7-b4f7c5b715de.png)

As you can see, the "Telegram Desktop" and "NetworkManager Applet" icons are showing up fine... not so much for the audio mixer (`mate-media`) and power gauge (`mate-power-manager`) though. The "charging battery" icon are certainly oversized.

This happens on both the theme I use (Arc Darker) and the default Menta theme.

**Comment by raveit65** [comment]
I can't reproduce this with Menta gtk theme and mate icon theme here in fedora with gtk+-3.20.
![bildschirmfoto zu 2016-05-22 11-01-06](https://cloud.githubusercontent.com/assets/961604/15453196/d8b48cb8-200c-11e6-9520-e7d6c012b7a6.png)
Which icon theme are you using?
Anyway, you can try to add this code below this line.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L428
```
/* control icon size */
na-tray-applet > widget > box {
    margin: 3px 3px 3px 0px;
}
```
And reload the theme.

**Comment by monsta** [comment]
Well, looks like there's no more feedback.
