### ISSUE TITLE
clock and weather disappears from mate-panel other issues with power manager

### ISSUE THREAD

**Issue by frankzen** [mate-desktop/mate-panel#442]
Running Debian Stretch. A bunch of Mate applications were updated this morning, now the clock and weather applets don't show on the panel. The versions running are 1.12 I believe.

Extracted from xsessions-error.

 
mate-session[1603]: WARNING: Unable to find provider '' of required component 'dock'

(mate-power-manager:1667): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

**Comment by swyngaard** [comment]
I can confirm for mate-panel version 1.12.2-1 on Debian Stretch.

Syslog errors:
`Jun  2 14:57:32 peanut org.mate.panel.applet.ClockAppletFactory[3701]: (clock-applet:5614): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Jun  2 14:57:32 peanut kernel: [ 1804.275974] traps: clock-applet[5614] trap int3 ip:7f93b48e2a6b sp:7ffea7fb4bb0 error:0
Jun  2 14:57:42 peanut org.mate.panel.applet.MateWeatherAppletFactory[3701]: (mateweather-applet:5627): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Jun  2 14:57:42 peanut kernel: [ 1813.657936] traps: mateweather-app[5627] trap int3 ip:7f40eb831a6b sp:7ffee25833d0 error:0`

**Comment by raveit65** [comment]
This is a debian packager issue, please file out a report there.

**Comment by alexarnaud** [comment]
Dear @frankzen,

I have also experienced this issue without finding any related bug on a search engine. Have you already reported something about this issue on the Debian BTS ? Have you found a work around ?

Best regards.

**Comment by frankzen** [comment]
This was a problem  which happened during the transsition from GTK 2.0 to 3.0. Debian packages had not been updated by the packager. The problem now has been resolved. Which flavour of Debian are you running ? The Sid packages were updated sometime ago and I no longer have the problem.

**Comment by alexarnaud** [comment]
Le 06/12/2016 à 15:50, Frank a écrit :
> This was a problem which happened during the transsition from GTK 2.0 to
> 3.0. Debian packages had not been updated by the packager. The problem
> now has been resolved. Which flavour of Debian are you running ? The Sid
> packages were updated sometime ago and I no longer have the problem.

I use Debian 8.6 "Jessie". The issue is just a breakage when mate-panel 
displays applets. If I change the size of the panel, the hidden applets 
reappear.
It seems if I unchecked the weather checkbox the problem appear less often.

@raveit65: I understand it could or it is a debian-related bug but if 
you have any idea to help us to fix it it will be really great. At this 
time I don't have any idea.

Do you think is it relative to the weather and the clock applet? What 
change has been made? How to debug such mate-panel related issue ? 
Debian has not updated Mate panel since 2014.

Best regards.
-- 
Alex ARNAUD

**Comment by raveit65** [comment]
This is a typical issue if a package is compiled with wrong dependencies.
Beside from working on Mate upstream i am fedora Mate packager.
I always use latest versions for fedora and rhel7/centos7 and if i do an packager error i fix it very fast.
With this distros i don't have restrictions like in debian and believe me, those distros with MATE  are 'stable as fuck '  ;-) .
Try out Centos7.....

**Comment by lukefromdc** [comment]
Looks like you've got libmateweather compiled with GTK2 and mate-panel compiled with GTK3, meaning the clock(depends on libmateweather) and weather applet(same) cannot run.  Also mate-power-manager compiled with GTK2.  Debian should have either made all the GTK3 versions depend on the GTK3 versions of all their dependencies or held the uploads until all of them were ready.

**Comment by frankzen** [comment]
The debian site show Jessie has version 1.81 + for all mate packages. Should not be a problem if your system has the 1.81 packages. Have you run aptitude update + aptitude full-upgrade as root ?

**Comment by raveit65** [comment]
Or maybe a mix from stable and sid repo?
As far i know only in sid are the packages compiled with gtk3.
A installed package list with versions of libmate*, mate-*, atril, caja, engrampa, eom and pluma can give us a hint.

**Comment by alexarnaud** [comment]
Le 11/12/2016 à 10:18, raveit65 a écrit :
> Or maybe a mix from stable and sid repo?

THe only package I use from testing is caja-dropbox.

Best regards.
-- 
Alex ARNAUD

**Comment by frankzen** [comment]
Have you checked the buglist on Debian.org for Jessie ?

**Comment by alexarnaud** [comment]
Le 11/12/2016 à 17:11, Frank a écrit :
> Have you checked the buglist on Debian.org for Jessie ?

Yes, I don't find anything related to this issue. I suspect caja-dropbox 
to produce strange behavior. I have switched caja-dropbox from 1.16 to 1.12.
I'll check if the problem continues to appear.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"
