### ISSUE TITLE
GTK+3: window list icons hidden/overlap with text when switching workspaces

### ISSUE THREAD

**Issue by paravoid** [mate-desktop/mate-panel#443]
The following seems to happen to me with MATE 1.14 on Debian stretch/sid (i.e. using GTK+3). This did not happen before this week's upgrades (i.e. with 1.12/GTK+2). If it matters, the theme I'm using is BlueMenta, although I've tried with other themes as well, just in case, but to no avail.

Sometimes, the window list layout seems to corrupt itself, with many icons being hidden, or overlapping with text. Sometimes even the text gets hidden entirely. You can then recover by either hovering on each of the windows on the list, or by opening a new window, or closing one of the existing windows.  See the attached screenshots:

Bad: ![mate-appswitch-bad](https://cloud.githubusercontent.com/assets/1330796/15784269/73b3eaa4-29ba-11e6-8ad1-a127a7976adb.png)
Good: ![mate-appswitch-good](https://cloud.githubusercontent.com/assets/1330796/15784267/71c50c14-29ba-11e6-9b97-5cb0bc7920cd.png)

I've noticed it especially under the following conditions:
- Set up a workspace with enough windows to fill the window list in the panel (at the point where the length of each window in the list is getting compressed)
- Switch to an adjacent workspace, then switch back. The adjacent workspace needs to be empty or have 1-2 windows (with 2, the effect is a little bit different). When the adjacent workspace has >= 3 windows, everything seems to be normal.

As you can imagine, it's a pretty annoying issue, bordering on making my desktop unusable.

**Comment by raveit65** [comment]
Where is the debian downstream report?
Debian Mate maintainers needs first confirm this issue before you file out an report here.
Because debian packages are not our responsibility.
Btw. i use fedora 24 with gtk+-3.20.x (Mate gtk3) and i don't see this issue.

**Comment by paravoid** [comment]
There isn't one yet. Happy to file it on the Debian BTS too, although I don't see what Debian packagers can do for what it looks like an upstream bug rather than a system integration bug (I think the most likely outcome is that it will end up in this bug tracker anyway). I'm a Debian Developer myself and on my own packages I tend to encourage bug reporters to file upstream bugs directly with upstream, as it avoids the game of telephone which only introduces delays and misunderstandings.

**Comment by sc0w** [comment]
I can confirm the issue with debian testing

Anyway all packages of mate 1.14 is not in testing, we must wait

**Comment by paravoid** [comment]
For what it's worth, I'm not running what's in testing — I've explicitly upgraded the rest of MATE to 1.14, there are no MATE 1.12 components in my system.

**Comment by paravoid** [comment]
Anything I can do to help you folks troubleshoot this and move it along?

**Comment by monsta** [comment]
> - Set up a workspace with enough windows to fill the window list in the panel (at the point where the length of each window in the list is getting compressed)
- Switch to an adjacent workspace, then switch back. The adjacent workspace needs to be empty or have 1-2 windows (with 2, the effect is a little bit different). When the adjacent workspace has >= 3 windows, everything seems to be normal.

Hmm, I missed this report before - now I can confirm it, using the mentioned steps to reproduce. I can reproduce it a few times in a row here (a VM with Debian Testing, GTK+ 3.20).
I also noticed that clicking on the "show desktop / minimize all windows" applet a couple of times brings the window list back to sanity.

I can't tell if this is something in GTK+3 build of mate-panel, or something in GTK+3 version of libwnck (which is used by the window list applet). :confused:

**Comment by monsta** [comment]
Guess what... I just got an update of libwnck to 3.20.1 and now I can't reproduce this. Then I looked at upstream commits and saw [this one](https://git.gnome.org/browse/libwnck/commit/?id=0bcc8b46ce15130003d17be6113b4a0aa3243b02). The mentioned [bug report](https://bugzilla.gnome.org/show_bug.cgi?id=658106) also looks relevant.

Can you check if it still happens with libwnck 3.20.1 in your system?

**Comment by monsta** [comment]
Oops - accidentally clicked on close button

**Comment by paravoid** [comment]
Indeed, I can't reproduce this anymore! Good catch — thanks for the solid investigative work :)

**Comment by monsta** [comment]
Glad it's solved :smile:
