### ISSUE TITLE
Focus and keyboard

### ISSUE THREAD

**Issue by Texou-** [mate-desktop/mate-panel#444]
Hi,

Just to have a trace of what we experiencec yesterday. When pressing alt-ctrl-tab, the focus should go to panels, and it does but randomly. Once on a panel, tab should move the focus on various icons (applets, etc). Actually, this behavior works randomly. It should be stabilized in next releases.

Regards,

**Comment by monsta** [comment]
I confirm this and confirm that #446 fixes that. I can actually move between applets with Tab/Shift-Tab and use Enter to invoke left-click action on an applet.

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/mate-panel/commit/e14d3305b6ea36bb68db6c410494824e3c64ab5d
