### ISSUE TITLE
Add option to close windows middle clicking on them

### ISSUE THREAD

**Issue by Yanpas** [mate-desktop/mate-panel#448]
Add support for closing window by clicking middle mouse button on them
##

**Comment by monsta** [comment]
It's in libwnck, not in mate-panel. See https://github.com/mate-desktop/mate-panel/issues/191.
It will work here when we move mate-panel to GTK+3 by default.

**Comment by monsta** [comment]
Ok, mate-panel is GTK+3 only as of version 1.17, so this feature now works.
