### ISSUE TITLE
clock applet uses 24hr, C and m/s units instead of regional defaults

### ISSUE THREAD

**Issue by chrstphrchvz** [mate-desktop/mate-panel#450]
I live in the US, so I set the clock to 12-hour display and weather units to F and mph. Ideally, the applet to choose defaults based on what I set in Language Support, or at least have an option for "Region defaults" and let me change specific options in the applet as needed (e.g. for 24-hour display or non-default units for my region). Related: issue #95 and pull request #123.

**Comment by raveit65** [comment]
Well, we need to set a default and the metric system is used all over the world.
Only the US lacks of updating since 100 years ;)
But you can set your local settings in preferences.

**Comment by chrstphrchvz** [comment]
As much as I and government agencies like NIST would like for the US to adopt metric, I think that goal is beyond the scope of MATE. In the mean time, I don't think it would be counterproductive to have MATE attempt to use regional defaults instead of making it the user's problem. Would it be helpful to use some APIs or libraries, like `GWEATHER_*_UNIT_DEFAULT` from libgweather and `LC_TIME` from glibc?

**Comment by raveit65** [comment]
Well, we are a small team........patches are welcome for that the clock applet read  local settings.
