### ISSUE TITLE
[Request] Dynamic Panel Transparency

### ISSUE THREAD

**Issue by TrendaFet** [mate-desktop/mate-panel#452]
I would like to make a feature request for the MATE panel to have Dynamic Transparency based on window state. Similar to this [Gnome Extension](https://github.com/rockon999/dynamic-panel-transparency) and Pantheon Desktop default panel.

**Logic:**
If window maximized, then set transparency to null, else set transparency to XX.

**Possible options:**

- Enable/Disable Dynamic Panel.
- If enabled 
 - Maximum Transparency value
 - Minimum Transparency value.

Thank you and I hope you consider this feature, though I understand it's not remotely important but it would make all minimalists' desktop perfect.

Keep up the great work.

**Comment by lukefromdc** [comment]
Setting the panel to autohide will get it out of the way of maximized windows, and some windows such as browsers and video players can be fullscreened, which normally renders them over the panel.

**Comment by TrendaFet** [comment]
@lukefromdc Thank you for the suggestion. Though my feature request was a cosmetic change (transparency) based on window state, the panel is always there.

Though like I said, I completely understand that this is not essential, so I understand if it weren't implemented.

I hope one day it would be a feature.
