### ISSUE TITLE
Window list context menu "not translated" - regression

### ISSUE THREAD

**Issue by rogue-spectre** [mate-desktop/mate-panel#453]
Hi i noticed that in

linuxmint mate beta 18 64bits : mate-panel 1.14.0.1
ubuntu-mate 32bits : mate-panel 1.12.2-1

the context menu of Window list is not translated… but in a previous version linuxmint mate 17 32bit mate-panel 1.10.1it's already translated.

**Comment by monsta** [comment]
@flexiondotorg: I can reproduce this in 16.04 but not in 16.10. Also it's not reproducible in LMDE or Debian Testing. Any idea what's going on...? :confused:

**Comment by monsta** [comment]
Ok, I found out what's going on. These context menus are from libwnck, and the translations are missing in Ubuntu 16.04: https://bugs.launchpad.net/bugs/1587287.

I'm closing this as it's an issue in another library which we can't fix.
Please leave further comments at that bug report at LP.
