### ISSUE TITLE
Window List refuses to restore unfocused windows after clicking on Mint Menu.

### ISSUE THREAD

**Issue by cyber-doug** [mate-desktop/mate-panel#454]
This is a tricky issue to describe, but I'll try to write it as detailed as possible.

I'm running Linux Mint 18 MATE edition, that was released earlier today. It's a clean install, with all updates and nothing else. The issue is present even before installing to disk, while using the Live USB. In fact, it was present in older versions of Linux Mint MATE.

To reproduce: run any application and leave it **minimized**. Click on the Mint Menu (Advanced MATE menu), close it (again with **mouse**, not super key) and then click on a **Window List button**. It will make that button twinkle forever and become unresponsive to Alt + Tab or clicks, although any currently focused window will not be affected whatsoever.

The workaround is to open and close the MATE menu with the super key and then click on the unresponsive button. It will stop twinkling and restore its functionality.

I appreciate any guidance on collecting more information on this, if needed.
![tela copiada como 2016-06-30 23-41-13](https://cloud.githubusercontent.com/assets/20234673/16510421/3419cfa4-3f1c-11e6-8c79-e3202331b118.png)

**Comment by raveit65** [comment]
Mintmenu is from LinuxMint, please report it there.

**Comment by monsta** [comment]
Yes, https://github.com/linuxmint/mintmenu/issues/155.
