### ISSUE TITLE
the panel does not display the icon on the mouse when I try to move them

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/mate-panel#457]
debian testing mate 1.14.1
mate-themes 3.20.8
mate-panel 1.14.1
gtk 3.20.6
theme: traditional ok

![arrastrariconospanel](https://cloud.githubusercontent.com/assets/7734191/16816684/5c1ab46e-493f-11e6-896f-0da90cef5813.png)
##

**Comment by monsta** [comment]
Do you mean a tooltip over an icon? I have tooltips shown here in similar system (Debian Testing, TraditionalGreen theme, etc.) - only mate-panel is the latest build from git master.

**Comment by sc0w** [comment]
@monsta you can see the video:

[out.zip](https://github.com/mate-desktop/mate-panel/files/363707/out.zip)

**Comment by raveit65** [comment]
panel is gtk2?
It works here with gtk3 version.

**Comment by sc0w** [comment]
gtk3 , all packages on debian testing are in gtk3

I can see --with-gtk=3.0 in debian rules

**Comment by raveit65** [comment]
well, i'm using 1.15.x here and all gtk3 VMs use 1.15.x

**Comment by raveit65** [comment]
complete weird that stupid debian politics prevent updating to working version in testing.
For what is testing good for than?

**Comment by monsta** [comment]
Hmm how do I move launchers with a click like it's shown in the video...? :confused:

**Comment by sc0w** [comment]
Same problem with the latest version of mate-panel in the master branch

I have tested with various themes

@monsta holding left click and dragging

**Comment by sc0w** [comment]
@monsta If you can't, you can verify with right button if the icon are locked

**Comment by monsta** [comment]
Ah... how I didn't figure this out :smile:

**Comment by monsta** [comment]
So I've tried both methods... the icon isn't displayed indeed, but I also don't see that blank square at the mouse cursor.

**Comment by monsta** [comment]
Aha, I see the difference now, tried GTK+2 build as well... So the icon isn't shown when you move the launcher via menu item from right-click menu, but it's shown when using click-and-hold method. Ok, counting this as GTK+3 issue then.

**Comment by monsta** [comment]
Interesting... I also tried it in Ubuntu 16.10 where GTK+ is 3.18 and MATE is also built for GTK+3. Well, the icon is shown at the mouse pointer.

**Comment by raveit65** [comment]
weird btw. good , that it works here, debian issue?
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/out.ogv.tar.xz

**Comment by raveit65** [comment]
with drag and hold function it works here with session icons (logout, etc.)

**Comment by monsta** [comment]
Confirmed, logout and shutdown buttons are fine, even with GTK+ 3.20. The icon is shown at the mouse pointer for them. Looks like only app launchers are affected.

**Comment by sc0w** [comment]
**[ right button -> move ]** works for me, the problem is when I hold the left mouse button and I drag

**Comment by sc0w** [comment]
@monsta 

> Looks like only app launchers are affected.

aha, this icon isn't affected:

![icon](https://cloud.githubusercontent.com/assets/7734191/16846034/37c32c5c-49eb-11e6-83b1-0db024af7a31.png)

anyway, when I'm moving this icon, I dont see the black squares over the others

**Comment by monsta** [comment]
@lukefromdc: maybe you could help us with this? It's not a major issue, but we've been wondering if any 3.20-specific commits might be related... because it's not reproducible with 3.18.

**Comment by lukefromdc** [comment]
What I get with ALL this icons in the panel is that the icon itself moves with the mouse. The behavior here is that the icon continues to be rendered in the panel, moving with the mouse position. It is not re-rendered diagonally moved like in the video where it becomes a blank square. To put it another way, when you select it for moving the pointer takes the "hand" form indicating dnd but the icon stays where it is until you move the mouse. Then it follows the mouse until you anchor it. 

There is one exception: No panel icon can follow the mouse to another panel, instead staying in the panel it came from until the mouse reaches the new panel. Then it appears in the new  panel-and removing it from the old panel crashes the panel and it restarts. This is https://github.com/mate-desktop/mate-panel/issues/447 and comments there say glib issues are to blacme

**Comment by sc0w** [comment]
@lukefromdc 

> It is not re-rendered diagonally moved like in the video where it becomes a blank square.

with ![icon](https://cloud.githubusercontent.com/assets/7734191/16854139/ed059536-4a0f-11e6-904f-51c97dce5b99.png) works, see the video:

[out.zip](https://github.com/mate-desktop/mate-panel/files/364705/out.zip)

**Comment by lukefromdc** [comment]
In every GTK 3 build I have ever used it stays inside the boundaries of the panel
and "slides" with the mouse, it does NOT become "attached" to the pointer like
what you showed. You have it rendering slightly larger and outside the panel
boundaries, presumably with GTK 2 which behaves differently.

**Comment by sc0w** [comment]
another video in a virtual machine with debian jessie with mate 1.8.1 gtk2:

[out.zip](https://github.com/mate-desktop/mate-panel/files/364749/out.zip)

seems it must be the same icon for all app launchers

@lukefromdc I understand you, but I am using gtk3, this is odd, thanks for your explanations :)

**Comment by sc0w** [comment]
more info:

after I unlock the icon, it works

and after the drop to the panel, it doesn't work

Video:

https://mega.nz/#!9dJnFDBL!qJnPOwlEZrhNS0drnO768M5LWGsSEgSbhY7UU92VF_c

**Comment by lukefromdc** [comment]
A locked icon cannot be moved, so of course it must be unlocked. On my system with GTK 3.22.4, icons "slide" within the panel rather than "sticking" to the mouse cursor. The only possible "drop" is to move it to a different panel, where I get a new issue: the icon disappears until the panel is restarted. Sometimes a narrow rectangle in the theme bg color will appear but usually nothing at all.

Again a video on Mega where I cannot get it, I am relying on descriptions as a result.

**Comment by monsta** [comment]
> The only possible "drop" is to move it to a different panel, where I get a new issue: the icon disappears until the panel is restarted. 

Yes, I confirm that. I accidentally found that some time ago in Debian Testing. It's worth a new report I think (if we don't have one already).

**Comment by lukefromdc** [comment]
Window list, tray rendered incompletely until restart after moving to another panel
https://github.com/mate-desktop/mate-panel/issues/504
