### ISSUE TITLE
Window List : Icons rapidly flicker/resize when panel is on vertical right position

### ISSUE THREAD

**Issue by nwodb** [mate-desktop/mate-panel#458]
When ever the panel is on the right hand side of my screen (vertical position) and I then click a window icon that is not grouped with like icons they will all grow/shrink in rapid manner several times, with the result of the window clicked on may or may not gain focus in the main user area.

![window icon flicker](https://cloud.githubusercontent.com/assets/9101530/16934715/a4caa81c-4d1e-11e6-8db8-0d45c2a52254.png)

**Comment by monsta** [comment]
An old issue in the old and unmaintained GTK+2 version of ```libwnck```, already mentioned in https://github.com/mate-desktop/mate-panel/issues/157 and https://github.com/mate-desktop/mate-panel/issues/277. Will probably be solved only when mate-panel is switched to GTK+3, as ```libwnck3``` (GTK+3 version) will be used there.
