### ISSUE TITLE
can't place any applet to the right of volume-control indicator

### ISSUE THREAD

**Issue by black77** [mate-desktop/mate-panel#459]
Having once moved Clock applet to the left of volume indicator, I can't move it back to initial location (to the right of volume control). I.e. once volume indicator took the most right position, nothing can be placed to the right of it.
![panel](https://cloud.githubusercontent.com/assets/364128/17081952/a1d3bb3c-517c-11e6-8f14-b65a0e3267ab.png)

**Comment by monsta** [comment]
Volume control "indicator" is a tray icon. Check if the tray area applet is locked.

**Comment by black77** [comment]
It's a shame for me. Thanks alot, monsta. Am closing the issue
