### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fennectech** [mate-desktop/mate-panel#460]
I have been a verry happy mate user for a long time   but i stil have a coupple little gripes with the DE    I would like to request a feature like XFCE's expanding seperator that would push the icons arround for when some objects (like the notification tray) change size my things will move arround with them   i would also like to get  the ability to in startup applications to "wait until system tray starts" for a coupple applications that do not take well to launching before the system tray C:  _thank you_  id be willing to donate a few dollars into the project for something like this  _cheers_  I hope i did that correctly C:
##

**Comment by kn00tcn** [comment]
there are ways to delay startup of apps that dont depend on having settings of the DE https://askubuntu.com/questions/28685/how-can-i-delay-a-specific-program-on-startup

**Comment by raveit65** [comment]
With mate-session-properties you can add delays to application when starting the session.
