### ISSUE TITLE
Right-click on panel menus makes panel unresponsive

### ISSUE THREAD

**Issue by mspaulding06** [mate-desktop/mate-panel#467]
To Reproduce:
1. Click on Applications menu
2. Right-click on any application in the menu

Expected Result:
Nothing strange happens

Actual Result:
Most panel items like the menus cannot be clicked anymore

Build Details:
Ubuntu MATE 16.04.1
Mate Panel v1.15.x built from master with Gtk3 support

**Comment by raveit65** [comment]
Looks like you reported  a detail of https://github.com/mate-desktop/mate-panel/issues/305
I guess you mean gtk3 version.
Your PR is for this issue?

**Comment by raveit65** [comment]
Ahh, i see PR is for another issue.

**Comment by raveit65** [comment]
for reference https://git.gnome.org/browse/gnome-panel/commit/?h=gnome-3-0&id=c1ab7e84f6478a826a746d5999d95f2fcbe13d4f

**Comment by mspaulding06** [comment]
Thanks for the link.  So does that mean the best solution is just to remove the functionality altogether?  I noticed that if I remove the signal for deactivate to the `restore_grabs` function that this partially fixes the problem.  The panel doesn't become unresponsive but the menu will not close if you click off of the menu like usual.  You have to click the Applications button on the panel to make the menu close.

**Comment by raveit65** [comment]
Well, this code is the problem and i will remove it for next fedora (25) release, as i switched to gtk3 here. And adding a launcher via drag&drop to panel or desktop works well. I just tested this.
Also the drawer function can be done with the drawer itself, and mozo can started via menu entry.
So i don't see a real regression.
As fedora Mate maintainer i don't like bug reports about stuff which don't work, and switching to gtk3 is a huge change and ppl can't expect that everything works as before.........imo.
Well, i don't know what the other guys thinks and maybe someone want to fix it, but this is my solution for next fedora.

**Comment by raveit65** [comment]
>  I noticed that if I remove the signal for deactivate to the restore_grabs function that this partially fixes the problem. The panel doesn't become unresponsive but the menu will not close if you click off of the menu like usual.

Btw. this is exactly how it works with gtk+-3.20, see my comment and followers.
https://github.com/mate-desktop/mate-panel/issues/305#issuecomment-189911471

**Comment by monsta** [comment]
Well, it's same as https://github.com/mate-desktop/mate-panel/issues/305. Happens with GTK+3.18, but doesn't with 3.20 :confused:
