### ISSUE TITLE
Two panels at the top - after login black screen with grey panel

### ISSUE THREAD

**Issue by rappelkiste** [mate-desktop/mate-panel#470]
I have using two panels ... one on the top, the other at the bottom.
After applying the panel from the bottom to the top, so that I have two panels at the top, everything seems O.K..
After a reboot and a normally login, I get a black screen with on grey panel at the top.
No icons on the panel or desktop. Nothing to click on.
By pressing Strg + Alt + DEL, the Screen flashes (I can see my background wallpaper for a second), then the login-screen appears. After the login ... the same black screen with the grey panel.

I'm not using the Auto-Hide-Modus of the panel.

I have this problem on my desktop-PC and laptop.
Im running Linux Mint 18 (sarah) 64bit.

A Question: How can I reset or delete the panels from recovery-mode?

**\* edit ***
I could restore my system with a backup file from yesterday. I copy back the file /.config/dconf/user.
So the panels are back on the "old" place at top and bottom.
##

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-panel/issues/356
