### ISSUE TITLE
Caja thumbnails slow loading

### ISSUE THREAD

**Issue by jaimejimbo** [mate-desktop/mate-panel#471]
Comparing to windows system, thumbnail loading time is much bigger. As I'm using SSD I expected thumbnails to show up quite fast, but it takes ~1 minute to load 1000 thumbnails (in windows just seconds). I don't know if it's a kernel's problem or a caja's.

**Comment by monsta** [comment]
How does it affect mate-panel?

**Comment by jaimejimbo** [comment]
I missclicked
