### ISSUE TITLE
Bottom panel ocasionally disappears when returning from suspension

### ISSUE THREAD

**Issue by apnegrao** [mate-desktop/mate-panel#472]
![Here's a screenshot.](https://cloud.githubusercontent.com/assets/12966082/17681527/34c14d74-633e-11e6-988f-bb66cf3dacc1.png) I'm using Ubuntu Mate 16.04.

I can't deterministically reproduce this error, sometimes it takes only a few suspensions in a day, other times a couple of days (even a week) of suspensions. But after it first happens, it keeps happening after each suspension until reboot.

Changing workspaces makes the panel appear again until the next suspension. Hovering the mouse over the panel also makes the icon below the mouse pointer appear (and, as a result, sliding the mouse from one end of the panel to the other makes the panel reaper, one item at a time).
##

**Comment by kn00tcn** [comment]
which compositor?

**Comment by raveit65** [comment]
No answer from reporter since years.
