### ISSUE TITLE
panel applets crashing randomly

### ISSUE THREAD

**Issue by gothmog123** [mate-desktop/mate-panel#476]
Is this a known issue? Sorry if it is. My panel applets inlcuding the notification area, clock and window list are crashing randomly at startup.

I would appreciate any help, thank you.

Arch+Mate from the community repo
##

**Comment by gothmog123** [comment]
I think the culprit was fake transparency without compositing. Don't know why.

**Comment by monsta** [comment]
I assume Arch should have MATE 1.14 by now, but I don't know how they build it, with GTK+2 or 3.

**Comment by monsta** [comment]
Well, we need more info on that.
Does it still happen in 1.16 (it should be in Arch by now)?
Is that GTK+2 or 3 build? If it's GTK+3, then which GTK+3 version is used in Arch now?

**Comment by lukefromdc** [comment]
I am not getting any applet crashes at all with GTK 3.22 and didn't with
GTK 3.20 either, using anything after or including the 1.14 release. The
panel background changes for GTK 3.18 or later seemed to make a huge
difference for me.

**Comment by monsta** [comment]
I guess it's already fixed since we didn't get any more info about crashes from anyone.

**Comment by lukefromdc** [comment]
I just had a trash applet crash on session start with an image custom panel background. Nothing in dmesg, so no segfault or anything like that. Five test panel restarts did not crash it again.

 I never, ever get applet crashes with the system background. Using GTK 3.22.6 and glib 2.50.2.

**Comment by monsta** [comment]
So it's only on session start?

**Comment by lukefromdc** [comment]
Can't tell for sure yet, as I am in the middle of a session that cannot be interrupted. Does require custom background it seems or applets never crash

**Comment by lukefromdc** [comment]
OK, just did several session starts, the trash applet and only the trash applet crashed about half the time with the custom image background in use.

**Comment by monsta** [comment]
I did some session restarts and system restarts, but couldn't make the trash applet crash with the custom image background. This is in a VM though, so I'm not surprised.

A crash without any info in dmesg might indicate a failed g_assert (which aborts the app). Check the journal with ```journalctl -b0```, maybe something is there. Any warnings from the applets also get there. For example, I have this one there:

```
trashapplet[949]: Allocating size to GtkImage 0x564f62522140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```
It appears with the default panel background as well, so I'm not sure it's related to a custom image background.

**Comment by lukefromdc** [comment]
Today the trash applet did not crash in a sequence of restarts but the inhibit applet did after about a half dozen restarts with a custom .png background. Got this set of errors in journalctl:

Jan 07 14:26:18 ubuntu clock-applet[13344]: gsignal.c:2523: signal 'size_request' is invalid for instance '0x55d1f016ddf0' of type 'GtkLabel'
Jan 07 14:26:18 ubuntu kernel: traps: mate-inhibit-ap[13329] trap int3 ip:7fb41cad5ad1 sp:7fff9f20f260 error:0
Jan 07 14:26:18 ubuntu kernel:  in libglib-2.0.so.0.5000.2[7fb41ca87000+10f000]
Jan 07 14:26:18 ubuntu clock-applet[13344]: Failed to get pattern 27263164,-1,-1
Jan 07 14:26:18 ubuntu trashapplet[13345]: Allocating size to GtkImage 0x55fe4ae40140 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Jan 07 14:26:18 ubuntu clock-applet[13344]: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkToggleButton)
``

**Comment by jonathonf** [comment]
I can replicate applet crashes (MATE 1.18, Ubuntu 17.10 packages backported to 16.04) with a transparent panel but accessing the desktop using x2go.

**Comment by lukefromdc** [comment]
When did you last update? As of now Ubuntu Artful(17.10) includes 
https://github.com/mate-desktop/mate-panel/pull/612  which fixed a severe chain of applet crashes on opening the panel with an image background or with  a transparent panel used with a non-compositing window manager. 

Also, packages for 17.10 are built with gtk 3.22 and mate-panel built with gtk 3.22 won't run with Ubuntu 16.04's gtk 3.18. Are you updating gtk3 to 3.22, or building from source for 16.04. The latter should work, as the changes to applet code apply to gtk 3.18 or later

**Comment by jonathonf** [comment]
mate-panel is version 1.18.4 built against GTK 3.22.15 (also backported to 16.04); I'll try my backport built against 16.04's GTK 3.18.

All of my backports are built from source against 16.04 libraries (apart from this set; I think I did that to fix some older issues when it was built against GTK 3.18); I don't know when this might have started happening as I haven't connected via x2go for a while.

**Comment by lukefromdc** [comment]
I don't know anything about x2go but if this is the onlty way you see applet crashes it might be a totally separate issue. Here's an example of how that could work: Any application that works in X should also work in Xwayland, but some do not and cannot. Some make direct calls to X that Xwayland should support and maybe does not, but others simply use X in a way that segfaults on Xwayland due to a long-unfixed bug in Xwayland itself. 

You might be hitting a similar issue in X2go if you can't duplicate the crashes on a local connection. In fact, if you can't crash the applets on a local session with marco as the window manager with or without compositing enabled, this is the first suspect. 

On the other hand, it you get the same crashes both with a (assuming non-compositing capable) remote access or with marco and no compositing, you have found another bug in pseudotransparency code in  mate-panel itself, and one I can't duplicate.

**Comment by flexiondotorg** [comment]
Also the MATE 1.18 backported packages for 16.04 don't come from the Ubuntu MATE team and are not supported.

**Comment by jonathonf** [comment]
The intention was to provide another data point rather than look for support.

**Comment by monsta** [comment]
@jonathonf: if you see crashes like in https://github.com/mate-desktop/mate-panel/issues/604, try adding the patch from https://github.com/mate-desktop/mate-panel/pull/612.

**Comment by BenSmyth** [comment]
> Got this set of errors in journalctl:
> 
> Jan 07 14:26:18 ubuntu clock-applet[13344]: Negative content width -7 (allocation 1, extents 4x4) while allocating gadget (node button, owner GtkToggleButton) ``

Here's a minimal example creating that error on mate-panel 1.27.1.

**test-applet.c**:

```
#include "mate-panel-applet.h"

static gboolean init(MatePanelApplet *applet)
{
  GtkWidget *button = gtk_button_new();

  gtk_container_add(GTK_CONTAINER(applet), button);

  gtk_widget_show_all(GTK_WIDGET(applet));

  return TRUE;
}

static gboolean applet_factory(MatePanelApplet *applet, const gchar *iid, gpointer data) {
	return (!strcmp(iid, "TestApplet")) ? init(applet) : FALSE;
}

MATE_PANEL_APPLET_OUT_PROCESS_FACTORY("TestAppletFactory", PANEL_TYPE_APPLET, "Testing", applet_factory, NULL)
```

**org.mate.panel.TestApplet.mate-panel-applet**:

```
[Applet Factory]
Id=TestAppletFactory
Location=/home/abc/share/mate-panel-cmd-applet/tmp/test-applet
Name=Test Applet Factory
Description=Factory for Cmd Applet

[TestApplet]
Name=Test Applet
Description=Test Applet
Icon=utilities-terminal
```

**org.mate.panel.applet.TestAppletFactory.service**:

```
[D-BUS Service]
Name=org.mate.panel.applet.TestAppletFactory
Exec=/home/bas/share/mate-panel-cmd-applet/tmp/test-applet
```
