### ISSUE TITLE
notifications incorrectly displays icon

### ISSUE THREAD

**Issue by ewangi** [mate-desktop/mate-panel#477]
Mint 18 MATE

On startup, the notifications section of mate-panel always displays the icon for the CopyQ application at the top of the panel, displaying a black rectangle beneath it.

This can be solved by increasing the panel size (from 32px to 33px) - the refresh caused by this causes the icon to be displayed correctly, vertically centred on the panel, even when the panel size is then decreased back to 32.

I have also noticed this behaviour with the icons from two more applications, and will add this info once I can put together more evidence.

Problem:
![screenshot1](https://cloud.githubusercontent.com/assets/21488893/18159382/44171b2a-7020-11e6-960b-4240aaa12b6a.png)

How it should look (and how it looks after panel resize):
![screenshot2](https://cloud.githubusercontent.com/assets/21488893/18159392/591e5272-7020-11e6-87b4-bc648e220eff.png)

**Comment by ewangi** [comment]
Another example, opening Skype:

![screenshot3](https://cloud.githubusercontent.com/assets/21488893/18159982/0ad24b0c-7023-11e6-8fbb-01416fb56fe2.png)

After screen resize, displaying normally now:

![screenshot4](https://cloud.githubusercontent.com/assets/21488893/18160001/282404c0-7023-11e6-8ad5-eb2ba5404c07.png)

**Comment by ewangi** [comment]
Accidentally closed - apologies. Now re-opened.

**Comment by raveit65** [comment]
Can you please be careful with reopen or adding new stuff?
We all received email notification from MATE. And your action causes 4 mails about the same issue.
And i'm missing an link from an existing downstream report from your distro.
It is useful that linuxmint maintainer can check a report first before you write it here.

**Comment by ewangi** [comment]
Thank you for your reply raveit65.

As you can see, I am new to this particular bug reporting page. I accidentally clicked on "Close and comment", thinking that this meant it would close or finish the comment I was making, not close the whole thread. I subsequently apologised, which I thought was the correct thing to do. I apologise that this caused you unnecessary stress.

In addition, I initially intended to report this bug on Linux Mint but during that process the Mint reporting page specifically requested me not to log the bug there but to log the bug with MATE as the issue was MATE-related, which I duly did. I will also, as you request, log it with Mint.

**Comment by ewangi** [comment]
Now registered as Linux Mint bug #1619224 (https://bugs.launchpad.net/linuxmint/+bug/1619224).

To provide further information on Mint asking me to report this bug here rather than with them, the page in question (https://bugs.launchpad.net/linuxmint/+filebug) reads as follows:

> ***** IMPORTANT *****
> If this is a desktop-related issue (i.e. Cinnamon, Mate or a related package, please open an issue in Github instead.
> see https://github.com/linuxmint
> or https://github.com/mate-desktop

So, if raveit65's concern about reporting such bugs with Mint first is shared by the other maintainers, I would suggest that you contact Mint and ask them to modify the wording on that page.

My apologies to raveit65 for the email notification generated by this message.

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-panel/issues/92 & https://github.com/mate-desktop/mate-panel/issues/50
