### ISSUE TITLE
mate-panel-1.16: switch monitor output: shrink resolution width, panel will not shrink

### ISSUE THREAD

**Issue by geki-yaba** [mate-desktop/mate-panel#486]
Update 1.14.2 to 1.16.0 regression:

Switch laptop monitor output from internal LVDS(1366x768) to external HDMI(HDTV - 1920x1080) streches mate-panel fine.

Switch laptop monitor output back from HDMI to LVDS does not stretch mate-panel back to fit screen resolution width.

Right now, I lose the virtual desktops and power/user-switch applets off screen. :-)
##

**Comment by lukefromdc** [comment]
Confirmed with mate-panel 1.16 and GTK 3.22. Restart the panel to work around this, and expect problems around locked panel applets. If this is something you do a lot consider unlocking applets near the right side of the panel so they can move as needed.

**Comment by monsta** [comment]
There are a few upstream commits that might be relevant:
https://git.gnome.org/browse/gnome-panel/commit/?id=4511f4466df0b163906794b4a32196226ccf90f3
https://git.gnome.org/browse/gnome-panel/commit/?id=0021c4741af748b634989ac0829d7aab8b103e80
https://git.gnome.org/browse/gnome-panel/commit/?id=fc24d8fa623c4cf841eb5168cb1c250b4a84d4da

The last one mentions this issue, and the previous ones need to be applied before it (as it seems to me). I didn't test them yet.

**Comment by monsta** [comment]
I forgot about this one. Now it's fixed along with https://github.com/mate-desktop/mate-panel/issues/552.

**Comment by lukefromdc** [comment]
Sweet

**Comment by MartinX3** [comment]
Using Ubuntu Mate x64 17.04 with Mate-Panel Version 1.18.1-0ubuntu2.

This Problem still happen.

Please Reopen this Issue.

**Comment by monsta** [comment]
It was fixed in 1.18.2

**Comment by MartinX3** [comment]
I'm using Linux Mint Mate x64 18.2 and Ubuntu Mate x64 17.04.
Update isn't rolled out.

When will it be rolled out?
