### ISSUE TITLE
Sound preferences hitbox too small in notification area.

### ISSUE THREAD

**Issue by psypherium** [mate-desktop/mate-panel#487]
Sound preferences hitbox too small in notification area/notification area cannot be moved to the very edge of a panel. I'm looking to be able to simply move my mouse into the very edge/corner of the screen and scroll my mouse wheel to change the volume. It is very close, it misses just a few pixels in the extreme corner of the screen.
##

**Comment by kn00tcn** [comment]
this very likely depends on the (gtk aka settings>appearance>theme>customize>controls) theme you're using, i saw a border in xfce's notification area when i was trying out some themes

right now i am trying arc theme on mate, i moved the notification area to the right, & the network tooltip shows up when i move the mouse hard right, but i can see how the icon moves further left with no more tooltip when i switch to bluementa theme

you can try editing your theme files, i dont know where to edit, but i dont expect it to be hard to find

**Comment by raveit65** [comment]
No answer from reporter since years.
