### ISSUE TITLE
The Mate Panel 1.15.1 unusable

### ISSUE THREAD

**Issue by apolitech** [mate-desktop/mate-panel#488]
The Mate Panel 1.15.1 is unusable, it will kill the app that is intrgated with the applet. 

See the video https://youtu.be/tKd3R9MYpZA

I am using Ubuntu MATE 16.10 daily with MATE 1.15.1 latest

Bug reported on ubuntu mate launchpad https://bugs.launchpad.net/ubuntu-mate/+bug/1630515
I did another report with the logs from caja after the crash (i dont know how to merge the apport logs in this bug report) https://bugs.launchpad.net/ubuntu-mate/+bug/1630517

**Comment by lukefromdc** [comment]
More information needed.

Which applet and which app or apps? I have never seen this sort of thing happen
on Debian Unstable with GTK3. I am on limited bandwidth-and only access anything
Google over Tor.

**Comment by monsta** [comment]
Just in case:
http://mate-desktop.org/blog/2016-09-21-mate-1-16-released/

**Comment by flexiondotorg** [comment]
This is a bug in topmenu-gtk, specifically when built against GTK3+, not mate-panel.
