### ISSUE TITLE
workspace-switcher: feature: change background color when window has urgency hint

### ISSUE THREAD

**Issue by quite** [mate-desktop/mate-panel#489]
Would be great if the background color of a button in the workspace switcher could change to reflect that a window on that workspace has a notification/urgency hint.
##

**Comment by muesli4** [comment]
**mate-panel** uses `WnckPager` from **libwnck** to switch workspaces (as does **marco** for its key-based switching). There is no easy way to come up with an easy solution within only **mate-panel**, without replacing the pager widget. Hence the easiest solution is to add this behavior to **libwnck** itself. See https://github.com/GNOME/libwnck/blob/master/libwnck/pager.c#L958 where the active window is drawn differently one could easily check the window state and to the same on the desired states (see https://github.com/GNOME/libwnck/blob/master/libwnck/window.h#L65).

I had a quick look at **libwcnk** and it should be relatively easy to add it. There is one downside however: Their source code changes go through bugzilla and they are very unresponsive (e.g., my last addition hasn't even gotten an answer after a month, neither did emails to responsible persons change anything).
