### ISSUE TITLE
Trash applet interacts with XFCE while in mate session

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#490]
After fixing a Caja bug affecting GtkApplication builds running in XFCE, I ran into a nuisance issue when back in a MATE session: The spinning busy cursor was back when opening the trash. I wanted to see if some change in Debian did this to Nemo and Nautilus,  but the setting for system file manager in mate-control-center was ignored by the trash applet. Finally I tried removing Caja temporarily and clicking on the trash applet. Both the MATE and the XFCE error dialogs for selecting another file manager popped up!  On reinstalling Caja, the trash applet could not find it and again the system file manager could not be changed, at least so far as the trash applet was concerned.

I then uninstalled all of XFCE, and expected behavior was back. No spinning cursor on opening the trash from the applet, and the applet respected the system file manager setting,

Not sure if this can be fixed in MATE at all or is an XFCE issue but figured I'd better report this
##

**Comment by raveit65** [comment]
I noticed that the busy cursor was back in a VM where i tested caja in xfce.
I think not so much people use both desktops, except a server installation with several user accounts.

**Comment by lukefromdc** [comment]
That probably means something in XFCE is setting StartupNotify=true

**Comment by kn00tcn** [comment]
if this still exists, how do i test this? i need to use xfce's trash applet on the xfce panel then switch to mate?

i use file managers to access the trash, i have no problem switching between mate & xfce in f25, it works with no weird cursor in caja/thunar/pcmanfm in both DEs, could it be debian specific?

the only other possibility is that i manually installed xfce in a minimal way (without all themes & applets, not from the complete group that contains everything), though i do have xfconfd still running in mate for whatever reason

**Comment by lukefromdc** [comment]
Install a full XFCE environment with MATE already installed, run an XFCE session, then switch back toi a MATE session and open the trash. If you get a busy spinning cursor, that's the issue.

**Comment by monsta** [comment]
Does this problem still exist?

**Comment by lukefromdc** [comment]
I have no idea, I do not now have XFCE installed. We've not had any other reports of this however, so we can probably close it and reopen if we get any other reports

**Comment by kn00tcn** [comment]
i'm feeling too lazy to test this, nor am i going to install a full xfce compared to my minimal one

i think it would be very rare for someone to be flipping between the DEs outside of testing (testing which is itself more rare than loading the individual spins/flavors from a livedvd)

**Comment by lukefromdc** [comment]
OK, I just pulled in a full XFCE session from Debian Unstable, tested it, and found this issue was all the way gone. Cursor now fine on opening the trash. Then removed all of XFCE. Closing this as it appears the issue was somewhere in XFCE and has been fixed.

**Comment by kn00tcn** [comment]
or GVFS even
