### ISSUE TITLE
MATE Panel displayed at the top of the screen when using the Redmond panel layout and Compiz

### ISSUE THREAD

**Issue by bedfojo** [mate-desktop/mate-panel#495]
Ubuntu MATE 16.10 (also present in previous versions).

See https://bugs.launchpad.net/ubuntu-mate/+bug/1579421 - MATE Panel (inc. Menu) displayed at the top of the screen when using the Redmond panel layout and Compiz.

This looks like a resurfacing of bug #249 here which was closed as it was believed "the issue has been fixed in Mint 17.1 Rebecca". If so, what was that fix? Can it be generalised?

**Comment by monsta** [comment]
Fixed in Compiz, as stated in the Ubuntu report, so closing this one.
