### ISSUE TITLE
CentOS 7 - mate-panel killed by SIGSEGV

### ISSUE THREAD

**Issue by hanzer** [mate-desktop/mate-panel#498]
This sigsegv type of event happens about once a week.

```
[root@galileo7 etc]# abrt-cli list --since 1467852448
id e6d25a998e8e4acc9bc193f199f3df47547c420f
reason:         mate-panel killed by SIGSEGV
time:           Wed 23 Nov 2016 02:19:59 PM EST
cmdline:        mate-panel
uid:            1000
Directory:      /var/spool/abrt/ccpp-2016-11-23-14:19:59-1863
Reported:       cannot be reported
```

**Comment by raveit65** [comment]
Please post a description, steps to reproduce, mate-panel version, and attach the backtrace which is in /var/spool/abrt/ccpp-2016-11-23-14:19:59-1863 
Sorry, we can't work on such report like this. i will re-open it if you provide this infos.
