### ISSUE TITLE
Keyboard focus locked after keyboard interaction with the menubar (GTK2)

### ISSUE THREAD

**Issue by b4n** [mate-desktop/mate-panel#505]
The keyboard input is totally locked up inside the panel after opening one of the main menus.  This issue is apparently restricted to GTK2, but exists in most if not all mate-panel versions otherwise: the same problem happens in 1.8 and 1.16 alike.

To reproduce:
- Focus the panel (<kbd>Ctrl+Alt+Tab</kbd>)
- Use the arrows to move in the panel, until it focuses the main menu and opens one of the menus
- See that none of the global shortcuts work anymore (<kbd>Alt+Tab</kbd>, <kbd>Alt+F1</kbd>, <kbd>Alt+F2</kbd>, …), rendering it impossible to move the focus to anything else than the panel with the keyboard.  A mouse click on something else restores proper input handling.

The same do not lock input in a GTK3 build, neither with mate-panel version 1.8 or 1.16.

---
I'd like to work on that issue, but I'm having a hard time figuring out where I should try and poke, so any direction on that would be highly welcome.

**Comment by cwendling** [comment]
Okay, it's not actually a bug in mate-panel but in GTK2.  It has been corrected very early in the GTK3 days, but never backported to GTK2.  I did such a backport, which can be found on the original GNOME's bugzilla report at https://bugzilla.gnome.org/show_bug.cgi?id=554057#c18

Whether the backport will be accepted or not is not yet very clear, but I'm hopeful.  If it's not, I'll investigate whether I can come up with a workaround on mate-panel's side until I can drop GTK2 on my side.

**Comment by monsta** [comment]
Should we close it then, as it can't be fixed at our side?

**Comment by cwendling** [comment]
@monsta yes indeed.  BTW, Debian just patched its GTK2 package in Unstable (not that it affects much there as MATE is built against GTK3 in Unstable, bu well): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847438#17
GTK didn't answer on the issue yet.

**Comment by monsta** [comment]
Oh, that's already good (about Debian). As for upstream, I don't think we can expect much.

**Comment by monsta** [comment]
Debian also has a strict policy about patches, you need to prove that a bug is already fixed in current Testing and Unstable, then they might consider it for current Stable release. And what's confusing is that bugs are closed once the fix hits Unstable, so for Stable you'll need to file a new one.

**Comment by monsta** [comment]
P.s. it's confusing that you use two accounts :smile:

**Comment by cwendling** [comment]
> Debian also has a strict policy about patches, you need to prove that a bug is already fixed in current Testing and Unstable, then they might consider it for current Stable release.

Yeah I know.  Rough road ahead ^^

> P.s. it's confusing that you use two accounts :smile:

I know, sorry ^^  I shouldn't have opened this with my other account, but as it was that way I had to use that one to close it too.
