### ISSUE TITLE
notification area: Some app icons break keyboard navigation

### ISSUE THREAD

**Issue by cwendling** [mate-desktop/mate-panel#506]
When navigating with the keyboard over the notification area, focus disappears when passing over some applications, including *Mumble* and *ownCloud*.  Tested with 1.8 and 1.16, both GTK2 and GTK3, all the same.

Steps to reproduce:
* Open *Mumble* or *ownCloud* (probably more apps are triggering this though)
* Focus the panel (with <kbd>Ctrl+Alt+Tab</kbd>)
* Move the focus to the focus around with either <kbd>Tab</kbd> or the arrow keys

What you'll see is that focus works fine over some icons (like NetworkManager's, the sound volume, keyboard layout and some apps too like *RedShift* or *Gajim*), but once you reach *Mumble* or *ownCloud*'s icons, keyboard interaction is lost.  <kbd>Tab</kbd>, arrows, space, return: nothing has any effect.

My guess is that it is related to Qt application's icons somehow (as all non-working apps I mention are Qt-based, and none of the working ones are), but for now that's a mere guess.

I believe @raveit65 mentioned the same issue in https://github.com/mate-desktop/mate-panel/issues/441#issuecomment-224087627

**Comment by cwendling** [comment]
Ah, I forgot to mention that this is a fairly major accessibility problem, as it basically breaks keyboard navigation in the panel.

**Comment by cwendling** [comment]
I'm trying to debug this, but can't make much sense out of it yet.

Looking at the events `GtkSocket`'s `gtk_socket_filter_func()` receives, I see working ones get `ClientMessage` (33), and non-working ones don't.  However, they all receive event type 91, but I can't make sense out of it as it doesn't seem like a valid X event type.

I'm wondering if this might be a problem with XEmbed in either side, GtkSocket's or Qt's? (assuming it's indeed Qt tray icons that cause trouble).

Anyhow, I'd really appreciate any pointer or help with that, if anybody got any idea.

**Comment by lukefromdc** [comment]
OK, I see this is about tray icons. Is this with the notification area built in process out out of process? Most distros build the applets out of process, and with GTK 3.22 that avoids https://github.com/mate-desktop/mate-panel/issues/468 , which is a rather nasty rendering bug with custom backgrounds and GTK 3.22.  Try builidng in-process and see if this still occurs. Let that rendering bug go if using GTK 3.22, just see if the focus can be kept.

**Comment by cwendling** [comment]
> Is this with the notification area built in process out out of process?

I just tested in-process applets, and it's the same, so both.  This is also reproducible with the `testtray` sample program from the notification area applet.

**Comment by cwendling** [comment]
FWIW, I found out that Mumble icon creates a [`_NET_WM_USER_TIME_WINDOW`](https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html#idm139870829927952) *PropertyNotify* event which others don't seem to… but that seems irrelevant.  And it's fired after the *first* key press after focusing the icon.

**Comment by cwendling** [comment]
Okay, so apparently any Qt tray icon trigger the problem.  Sample app, buildable both with Qt4 and Qt5, both exposing the problem:

*qttrayicon.cxx*:
```C++
#include <QtGui>
#include <QApplication>
#include <QSystemTrayIcon>

int main(int argc, char **argv)
{
  QApplication app(argc, argv);
  
  if (! QSystemTrayIcon::isSystemTrayAvailable()) {
    return 1;
  }
  
  // or whichever image you like
  QIcon icon("/usr/share/pixmaps/qtconfig-qt4.png");
  QSystemTrayIcon trayicon(icon);
  trayicon.show();
  
  return app.exec();
}
```

*qttrayicon.pro*:
```qMake
TEMPLATE = app
TARGET = qttrayicon
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += qttrayicon.cxx
```

**Comment by cwendling** [comment]
Looks more and more like either a *GtkSocket*/*GtkPlug* issue, or a Qt one.  The same problem occurs with *gnome-panel*'s notification area (unsurprising I guess), but also with LXPanel's.  I hacked out lxpanel's tray as a standalone app for testing purpose, see https://gist.github.com/cwendling/a21b3312e455481b3db46d078fc60ae9.

**Comment by monsta** [comment]
Since SNI support addresses this issue in 1.18, it's time to close it.
