### ISSUE TITLE
Setting white font in mate-panel 

### ISSUE THREAD

**Issue by tonyabc** [mate-desktop/mate-panel#507]
I have just setup a new machine under F25 and Compiz/Mate.

Historically you've been able to set the font on the panel to white by installing a .gtkrc-2.0 file in your home directory with some keys.

However under the latest F25 versions this method is no longer working.

I would guess this is related to how themes are now working on the latest release but as I don't hack around inside themeing I'm a bit out of my comfort zone so would appreciate some pointers if possible.

Also I've noticed in the F25 version right clicking on an app selected from the menu no longer gives you a context menu to do things such as add a shortcut on the panel, instead it just opens the app and would appreciate some guidance here if possible.

Keep up the good work guys, Mate makes my life a heck of a lot easier as I frankly don't want to have to relearn my desktop every couple of years.

**Comment by lukefromdc** [comment]
When mate-panel is built with GTK3 as on many distros using 1.16, no GTK2 setting has any effect. The GTK3 theme controls it,  could be overrriden by code in ~/.config/gtk-3.0/gtk.css. The code below is taken from my UbuntuStudio_Legacy theme and should do it if saved to ~/.config/gtk-3.0/gtk.css 

```
panel-toplevel.background.horizontal,
.mate-panel-menu-bar,
#clock-applet-button,
#clock-applet-button:hover  {
	color: white;
}
```

**Comment by raveit65** [comment]
> Also I've noticed in the F25 version right clicking on an app selected from the menu no longer gives you a context menu to do things such as add a shortcut on the panel, instead it just opens the app and would appreciate some guidance here if possible.

We switched to gtk3 with f25 and adding application links from menus to the panel does not work very well. It freezes the panel.
https://github.com/mate-desktop/mate-panel/issues/305
For this reason i have disabled this for fedora builds.
http://pkgs.fedoraproject.org/cgit/rpms/mate-panel.git/tree/mate-panel.spec?h=f25#n35
http://pkgs.fedoraproject.org/cgit/rpms/mate-panel.git/tree/mate-panel_0023-panel-Remove-popup-menu-for-items-in-applications-me.patch?h=f25
You can use drag&drop for adding a started to the panel, so the context menu isn't really needed, imo.
Of course i will remove the patch if this feature is working again for gtk3.

Ok this isn't really a issue so i will close this report.
Hit me if you don't agree ;-)

**Comment by lukefromdc** [comment]
On my setup with GTK 3.22 and mate-panel 1.17, adding a launcher to the panel from a main menu item's right-click menu works, and does not freeze the panel.

**Comment by raveit65** [comment]
> On my setup with GTK 3.22 and mate-panel 1.17, adding a launcher to the panel from a main menu item's right-click menu works, and does not freeze the panel.

Yes, the panel does not freeze anymore with gtk+-3.20/22, but the menu does not close without this workaround.
See https://github.com/mate-desktop/mate-panel/issues/305#issuecomment-189911471
I received enough rhbz reports with f25 and i can live pretty well w/o stuff which does not work correctly.

**Comment by tonyabc** [comment]
Luke

Thank you so much, with your permission I'm going to post this on a number
of forums (with credit back to you of course) so that other users can use
your elegant solution.

Have a great Christmas and if you could come up with a solution to the lack
of ability to right click on apps in menu and get a context menu (with
options such as add to panel, etc...) instead of just opening the app that
would be incredibly useful.

Regards

Tony

**Comment by lukefromdc** [comment]
Feel free to repost the code anywhere you want.

**Comment by raveit65** [comment]
offtopic
@lukefromdc 
I tried to advised a user for another report to use ~/.config/gtk-3.0/gtk.css
with a change for TOK themes, but this doesn't have any effect here, see 
https://bugzilla.redhat.com/show_bug.cgi?id=1405819
