### ISSUE TITLE
Cannot disable scroll between opened apps in taskbar

### ISSUE THREAD

**Issue by ChaossAdept7** [mate-desktop/mate-panel#508]
It enabled by default, but i cannot find option to disable it(Of course, i've googled the solution and didn't found anything). But that option is present on Cinnamon or on Xfce(I can go to behavior and disable it).

**Comment by kn00tcn** [comment]
cinnamon & xfce are two different environments that happened to have created such an option/feature

mate would need the feature to be added if it doesnt have it

i might try to attempt this at some point, but probably not very soon

**Comment by muesli4** [comment]
**mate-panel** uses `WnckTasklist` from **libwnck**. The toggle buttons which represent windows and groups fire those scroll events. To inhibit those scroll events a change to **libwnck** is necessary first.

**Comment by muesli4** [comment]
I finished this feature and will open a pull request. However, I'm not sure how to handle version constraints of **libwnck** (I need `3.20.2`). Since I cannot wrap the xml files in macros I will have to raise the version of it. Or is this possible with **autoconf**? Any guidance or advice appreciated!

**Comment by monsta** [comment]
Note: we can't require libwnck 3.20, some distros that we support still have 3.14.

**Comment by raveit65** [comment]
Currently it is undecided if i ever will update epel7 repo for rhel7/centos7 (3.14) with Mate-1.18, as this means a switch to gtk+-3 during a release cycle.
Some people ask me for doing that , but as always if something goes wrong ppl will start whining "Where is my old good Mate gtk2.......".
Personal i prefer not to update rhel7 to Mate gtk3 and wait for a new enterprise release for that.
In this this case we can change our requirement.
Anyway, beside from that open/freebsd use gtk+-3.18 as far i know.

In the past we used different UI files for gtk2 and 3 in some packages, maybe this is the solution?

**Comment by monsta** [comment]
Mint is stuck with 3.14 as well due to Ubuntu 16.04 having it in the repos. There is GTK+ 3.18, but libwnck is 3.14.

**Comment by muesli4** [comment]
I have a branch with my patches applied, which I use for *mate-panel*. In case anyone is interested: https://github.com/muesli4/mate-panel/tree/libwnck-additions

**Comment by raveit65** [comment]
> Mint is stuck with 3.14 as well due to Ubuntu 16.04 having it in the repos. There is GTK+ 3.18, but libwnck is 3.14.

But the question is more if those distros  will ever update to to Mate-1.20?
I mean such a change is for future mate-1.20, so why we shouldn't add this feature if older distos will never update?

**Comment by raveit65** [comment]
> I have a (temporary) branch with my patches applied, which I use for mate-panel. In case anyone is interested: https://github.com/muesli4/mate-panel/tree/libwnck-additions

Why using deprecated widgets like GtkVBox and GtkAlignment to window-list.ui nowadays?

**Comment by muesli4** [comment]
> Why using deprecated widgets like GtkVBox and GtkAlignment to window-list.ui nowadays?
I just needed some GUI controls and used copy & paste in the ui file. Maybe there is someone interested in updating the file? ;)

**Comment by raveit65** [comment]
@muesli4 
Well, i am thinking about to use this fedora as patch, as we use gtk+-3.22 and libwnck is updated

**Comment by raveit65** [comment]
Btw. rhel7 is upgraded to gtk+-3.22

**Comment by raveit65** [comment]
It seems to be fixed or not?

**Comment by muesli4** [comment]
> It seems to be fixed or not?

I had a look, and yes.  Someone duplicated the work (they used the functionality I provided to libwnck at least).  See https://github.com/mate-desktop/mate-panel/commit/8245b0e9dadb7c8be534301bf0060227199e79d6

That is why work or review requests should be organized by issues.

**Comment by raveit65** [comment]
ok, closing
