### ISSUE TITLE
mate-panel still using deprecated focus-line-width and focus-padding

### ISSUE THREAD

**Issue by claurita** [mate-desktop/mate-panel#509]
mate-panel is still using deprecated focus-line-width and focus-padding and this causes lots of warning in journals and .xsession-errors:
wnck-applet[1505]: Theme parsing error: <data>:3:27: The style property GtkWidget:focus-padding is deprecated and shouldn't be used 
wnck-applet[1505]: Theme parsing error: <data>:3:27: The style property GtkWidget:focus-padding is deprecated and shouldn't be used 

Please switch to outline-width

Regards
Claudio Laurita

**Comment by raveit65** [comment]
Closing this anoying report as reporter doesn't provide any infos like theme, theme-version, gtk3 version, panel version and distro version.
....my crystal ball is dead....

**Comment by claurita** [comment]
I'm very sad for your crystal ball...
And, sure, I didn't want to annoy you, just tried to help making mate 
bug free.
But, despite your unfriendly answer, you are perfectly right.

Anyway...
Debian unstable, gtk 3.22, mate 1.16, mate-themes 3.22. Tried all themes 
from the package, same result. No evidence of the offending properties 
grepping the themes.
I felt the problem was in the code, but I saw you put every instance of 
the offending properties inside an #ifdef (but why you check against 
3.19, or 3.20 in master? Shouldn't it be against 3.14, when the 
deprecation started?). Maybe a Debian package problem, I'll try to 
recompile from source.

Again, accept my apologies.
Have an happy new year.
Claudio


Il 29/12/2016 20:25, raveit65 ha scritto:

**Comment by lukefromdc** [comment]
Lots of things broke outright on the GTK 3.20 and 3.22 transitions. Fixes for those were intentionally limited to those versions.

**Comment by monsta** [comment]
I'd check ```~/.config/gtk-3.0/``` folder for any related settings.

**Comment by claurita** [comment]
Really thank you for your attention.
@monsta: accurately checked before the first post, I can exclude any explicit css related problem.
@lukefromdc: I know, and, sure, it's not the first time gtk devels play a bit rudely. 

Recompiling the debian package from source solved the problem, but, after that, reinstalling the same package from repository did NOT break things again. Absurd!
So I still don't understand where those warnings came from.

But, just for the sake of completeness, at least in mate-applets/drivemount/drive-button.c (drive_button_class_init) the hard-coded focus setting is still there, and the related warnings too.
 If you find some time...

Claudio

**Comment by monsta** [comment]
@lukefromdc: hmm, we still have a place where these two properties are used for all GTK+3 versions...
It's in ```calculate_minimum_height``` function in ```applets/clock/clock.c```. Should we do something about it?

Another thing, in most places these two properties are used with GTK+ < 3.20, but in ```libmate-panel-applet/mate-panel-applet.c``` they're restricted to GTK+ < 3.18. Which one is more appropriate?

**Comment by monsta** [comment]
@lukefromdc: about mate-applets - indeed, these two properties are used without ```GTK_CHECK_VERSION``` in charpick and drivemount applets.

**Comment by lukefromdc** [comment]
At the moment I am facing an emergency here and can
do little.

**Comment by lukefromdc** [comment]
It should probably come all the way out, as we now handle focus in the
themes using GTK specific code

**Comment by monsta** [comment]
I can patch all the mentioned sources, just need to know if it's 3.18 or 3.20 that should be used in version checks.
