### ISSUE TITLE
Mate-panel errors in .xsession-errors

### ISSUE THREAD

**Issue by frankzen** [mate-desktop/mate-panel#510]
Running Mate under Mint v 18.2. No background image is set for the panel, but my .xsession-errors is filled with complaints from the panel that it could not find the background image.

** (mate-panel:12078): WARNING **: couldn't get background pixmap

**Comment by lukefromdc** [comment]
What theme are you using? A theme that sets a background image but then does not provide it (e.g.broken link/url/path to an image) could do this. Try another theme and start a new session, see if you still get this.

**Comment by frankzen** [comment]
I am using an oldish theme -Windows 7-aero but it does not set a background for the panel. In any event I went into the panel, right click and made sure ONLY a color was set. The panel still complains it can't find background pixmap. Its not a big deal - there are a lot of other Mate errors in .xsessions-errors, which are undoubtedly the themes fault :)

**Comment by lukefromdc** [comment]
I assume this is MATE-panel built with GTK2?  As of today 18.1 is the most recent release listed on Linuxmint's web site, and that only builds a few MATE components with GTK3, not all of it like Ubuntu MATE 16.10 does.

**Comment by monsta** [comment]
It should be 18.1, it's the latest release. It's still GTK+2 build, yes.

**Comment by frankzen** [comment]
Obviously the transition from GTK2 to 3 is behind the errors. I
I'll close this now.
