### ISSUE TITLE
Analogue clock in time applet stretched when hovering over set button

### ISSUE THREAD

**Issue by mrferda** [mate-desktop/mate-panel#520]
I have set up multiple locations in the clock applet.
When you hover over one of the locations to change to it, the analogue clock is stretched when the button appears (see attached screenshot).
![clock](https://cloud.githubusercontent.com/assets/24938498/22389154/8c93be42-e4e4-11e6-85dd-2d86a641ca98.png)

**Comment by bcv** [comment]
[me too!](https://www.bountysource.com/issues/41407980-analogue-clock-in-time-applet-stretched-when-hovering-over-set-button?utm_campaign=plugin&utm_content=tracker%2F314880&utm_medium=issues&utm_source=github)

**Comment by raveit65** [comment]
i saw that too, but i was too lazy to file out a report ;-)

**Comment by phillip-white-sociomantic** [comment]
Same for me

**Comment by lukefromdc** [comment]
I just found this is theme-sensitive, the issue does not appear in my UbuntuStudio_Legacy theme but did appear in a test in green-submarine

**Comment by ekotoyants** [comment]
Its still [stretching](https://kotoyants.com/public/img_20170620105521.gif) but in different direction.

**Comment by raveit65** [comment]
Not here ;-)

**Comment by lukefromdc** [comment]
That's  a different problem: the entire calendar window being stretched by the "set" button appearing on hover. What theme are you using?
