### ISSUE TITLE
blueman: tray icon too small, and whithout icons with right button

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/mate-panel#521]
see the differences, the blueman icon, and the order of the network and sound icons

mate panel 1.16

![beforematepanel](https://cloud.githubusercontent.com/assets/7734191/22400743/bfb76150-e5bd-11e6-9016-aa36581a07f0.png)

mate panel with the latest changes on the master branch ( I have tested with https://github.com/mate-desktop/mate-panel/commit/3edb41ee3e632cec5fcda70d34f4a613e24adf52 as latest commit)

![latermatepanel](https://cloud.githubusercontent.com/assets/7734191/22400756/26f509e4-e5be-11e6-91da-9de8e2944f59.png)

------------------------------------------------------------------------

and now, see the differences, right click on blueman: (with icons)

mate panel 1.16

![bluemanbefore](https://cloud.githubusercontent.com/assets/7734191/22400790/f191bc2e-e5be-11e6-9e7d-9d4c48dae8d9.png)

mate panel with the latest changes on the master branch: (where is the icons?)

![bluemanlater](https://cloud.githubusercontent.com/assets/7734191/22400793/f776c684-e5be-11e6-97e1-d0230c919796.png)

**EDIT:** This commit makes the issue: 7d39b2e (PR https://github.com/mate-desktop/mate-panel/pull/517 )

-------------------------------------------------------------------------------------

**Comment by cwendling** [comment]
> see the differences, the blueman icon

My guess here would be that before the icon was stretched, and since 195c2a8d155cac5bd10d59a481259c161cea6c57 and 3edb41ee3e632cec5fcda70d34f4a613e24adf52 we decided not to scale raster icons.
Would be interesting to know which sizes are available for that icon on your system.

> and the order of the network and sound icons

Oops, that was an overlok on my part.  Actually all the fixed-place tray icons are now reversed, I'll provide a patch.

> mate panel with the latest changes on the master branch: (where is the icons?)

Does you apps menu have icons?  There is an (in)famous GTK setting for showing icons in menus or not, and it defaults not to on recent versions.  This new menu should follow that setting, I'm not sure about the previous one.

BTW, the previous menu has an odd blank space on the left.

Lastly… how was the Bluetooth icon displayed before?  'cause it's weirdly placed in 1.16, as in theory if the previous code worked for it it should have been placed between volume and network icons.  But maybe it just didn't work, not sure.

**Comment by sc0w** [comment]
> Would be interesting to know which sizes are available for that icon on your system.

how can I know?

> Does you apps menu have icons?

yes, only the icons are missing on right click over blueman

**I have tested:**

- I have the problem: with the master branch with latest commit https://github.com/mate-desktop/mate-panel/commit/3edb41ee3e632cec5fcda70d34f4a613e24adf52

- All is ok: with the master branch with https://github.com/mate-desktop/mate-panel/commit/a506150684ad2e71b1f70190ee70fe9eda7a4ba9 as latest commit

so, the problem is some commit after https://github.com/mate-desktop/mate-panel/commit/a506150684ad2e71b1f70190ee70fe9eda7a4ba9

> Lastly… how was the Bluetooth icon displayed before? 'cause it's weirdly placed in 1.16, as in theory if the previous code worked for it it should have been placed between volume and network icons. But maybe it just didn't work, not sure.

before 1.16, I am not sure, I think on the same place, but I can confirm, with gnome 2 it was to the right

I have an old capture of that icon on debian squeeze with gnome 2:

![squeezytray](https://cloud.githubusercontent.com/assets/7734191/22419338/5759458a-e6dd-11e6-8aa1-d7219be0cb79.png)

**Comment by sc0w** [comment]
without https://github.com/mate-desktop/mate-panel/commit/195c2a8d155cac5bd10d59a481259c161cea6c57 and without https://github.com/mate-desktop/mate-panel/commit/3edb41ee3e632cec5fcda70d34f4a613e24adf52 have same problem

**Comment by cwendling** [comment]
> how can I know? [the size of the icons]

Good question.  I'm not sure how to be sure short of adding debugging code like that to the applet:
```diff
diff --git a/applets/notification_area/status-notifier/sn-item-v0.c b/applets/notification_area/status-notifier/sn-item-v0.c
index 871f794..4b01035 100644
--- a/applets/notification_area/status-notifier/sn-item-v0.c
+++ b/applets/notification_area/status-notifier/sn-item-v0.c
@@ -221,11 +221,23 @@ get_icon_by_name (const gchar *icon_name,
       else if (sizes[i] < requested_size && sizes[i] > chosen_size)
         chosen_size = sizes[i];
     }
+
+  for (i = 0; sizes[i] != 0; i++)
+    {
+      if (sizes[i] == -1)
+        fprintf (stderr, "%s is available scalable (SVG)\n", icon_name);
+      else
+        fprintf (stderr, "%s is available at size %d\n", icon_name, sizes[i]);
+    }
+
   g_free (sizes);
 
   if (chosen_size == 0)
     chosen_size = requested_size;
 
+  fprintf (stderr, "icon-name %s: requested %d, chosen %d\n", icon_name,
+           requested_size, chosen_size);
+
   return gtk_icon_theme_load_icon (icon_theme, icon_name,
                                    chosen_size, GTK_ICON_LOOKUP_FORCE_SIZE,
                                    NULL);
```

The output should appear either through *journald* or in *~/.xsession-errors*.

> without 195c2a8 and without 3edb41e have same problem

Which one?  The menus not having icons, the icon being smaller, or both?

Could you test at 352600f12126c2f974a2510dfb744ba4f562da3f for the menu icons?

> before 1.16, I am not sure, I think on the same place

Apparently yeah it was off before that anyway.  Probably it changed its name and the panel didn't catch up or something.

**Comment by cwendling** [comment]
BTW, I can't easily test on a recent setup as I don't have any actual bluetooth device and recent applet/daemon don't seem to be runnable without that, but under a Debian 8 install (ok, inside a 1.8 panel, but that shouldn't be too related as it's out of process) I don't reproduce either issue.  The menu have proper icons, and the icon is displayed correctly (admittedly, I have various icon sizes on the system, and a scalable one).

**Comment by cwendling** [comment]
> The menu have proper icons

And it follows the *org.mate.desktop.interface* *menus-have-icons* setting. (still on Debian 8 that is)

**Comment by sc0w** [comment]
this is the guilty: https://github.com/mate-desktop/mate-panel/commit/7d39b2e82f46777efa67224f078c1cec9e827654

I have debian testing

**Comment by cwendling** [comment]
> this is the guilty: 7d39b2e

For all of the above?  It's the one that initially introduced SNI, so changed what the bluetooth applet used, but it definitely shouldn't look the same as current master, that'd be odd.

**Comment by cwendling** [comment]
For the menu icons, what does `gsettings get org.mate.interface menus-have-icons` give you?

**Comment by sc0w** [comment]
@cwendling 

> For the menu icons, what does gsettings get org.mate.interface menus-have-icons give you?

true

@cwendling @lukefromdc 

I think you can install blueman without bluetooth devices, only to see the icons with right click

btw, I see blueman have the dependencie gnome-icon-theme

**Comment by lukefromdc** [comment]
I was able to install Blueman easily enough but it would not start without detecting any Bluetooth devices. I am on Debian Unstable. I've seen it run in Ubuntu before without Bluetooth devices active but not working on my setup.

**Comment by cwendling** [comment]
> > For the menu icons, what does gsettings get org.mate.interface menus-have-icons give you?
>
> true

OK, so that should indeed be fine.  No idea yet.  @XRevan86 any idea/way to test?

> I think you can install blueman without bluetooth devices, only to see the icons with right click

As @lukefromdc says, I have blueman just fine, but it refuses to do anything because the blueman daemon is not running, and it seems not to accept starting because I have no bluetooth devices.  I guess it's because of all the DBus auto-activation, in which case it makes sense not to run an unneeded daemon if it can start automatically when needed…

As said on Debian Jessie (stable) I see the blueman applet, and it works fine there.  But I don't have all of MATE 1.16/17, so maybe there's some difference.

**Comment by raveit65** [comment]
I can confirm that some icons are smaller with building from master (pre vers 1.17.2), ie. blueman or fusion-icon from compiz-reloaded. @XRevan86 should see that too.
https://github.com/compiz-reloaded/fusion-icon
And i confirm that menu icons are gone from blueman (i have only a bluetooth dongle).

**Comment by raveit65** [comment]
Reverting https://github.com/mate-desktop/mate-panel/commit/7d39b2e82f46777efa67224f078c1cec9e827654 for testing is a bit hard because it is the first commit of the status notifier stuff.
Well i will drop the whole stuff for testing.

**Comment by raveit65** [comment]
Btw. For me the icons are to small in na-try, i am sure this will cause issues by other users.

**Comment by raveit65** [comment]
dropbox icon from caja-dropbox is also affected.
icon is too small and the menu is broken with right click.
Note here left and right click does show the same regular.

**Comment by XRevan86** [comment]
```diff
--- a/applets/notification_area/status-notifier/sn-item-v0.c
+++ b/applets/notification_area/status-notifier/sn-item-v0.c
@@ -218,7 +218,7 @@ get_icon_by_name (const gchar *icon_name,
           chosen_size = requested_size;
           break;
         }
-      else if (sizes[i] < requested_size && sizes[i] > chosen_size)
+      else if (sizes[i] <= requested_size && sizes[i] > chosen_size)
         chosen_size = sizes[i];
     }
   g_free (sizes);
```
Does this handle the size issue?

**Comment by b4n** [comment]
@XRevan86 it shouldn't change anything, as the `if` part handles quality already.
I think we first need to know what icon sizes there is, and the panel size, so we can figure out whether the code is actually not doing what we think it should, or if the result doesn't please everyone.

BTW, I myself think that from the examples, the best one is the GNOME2 one, then the SNI one (small), and finally the Systray one (too tall IMO to fit nicely visually).  But apparently YMMV :)

**Comment by XRevan86** [comment]
@b4n, ah, right, you're right.
I guess it's the padding in the theme then.

**Comment by b4n** [comment]
@raveit65 @sc0w does this fix the missing images in the menu?:
```diff
--- a/applets/notification_area/status-notifier/sn-dbus-menu-item.c
+++ b/applets/notification_area/status-notifier/sn-dbus-menu-item.c
@@ -197,6 +197,8 @@ sn_dbus_menu_item_new (GVariant *props)
             }
 
           item->item = gtk_image_menu_item_new ();
+          gtk_image_menu_item_set_always_show_image (GTK_IMAGE_MENU_ITEM (item->item),
+                                                     TRUE);
           gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (item->item),
                                          image);
         }
```

**Comment by b4n** [comment]
@raveit65 If the above doesn't help, what about reverting 017323dd4f8337ec91dd18f13955ab2e9df26cff?

**Comment by cwendling** [comment]
BTW @raveit65 

> Btw. For me the icons are to small in na-try

what do you mean by that?  The changes shouldn't affect the system tray part (only thing using the `na-tray` name), but only items that can be displayed through SNI.

**Comment by raveit65** [comment]
> > Btw. For me the icons are to small in na-try

> what do you mean by that?  The changes shouldn't affect the system tray part (only thing using the 
> `na-tray` name), but only items that can be displayed through SNI.

![na-tray](https://cloud.githubusercontent.com/assets/961604/22480897/4b53f016-e7f3-11e6-93d5-0f27c3643d89.png)
Here you see 5 icons in tray, from left to right, dropbox, fusion-icon, kaffeine, volume applet, nm-applet.
dropbox, fusion-icon and kaffeine are smaller with your merged PR and they are smaller than volume applet and nm-applet.
The last 2 ones have the same size as before.
And you see that those 3 icons displays smaller like normal applets now like shutdown applet.

Note, this is with Blue-Submarine theme and full transparency.

**Comment by raveit65** [comment]
For me all icons in na-tray applet should have the same size.

**Comment by lukefromdc** [comment]
If some icons get padding and others do not, this will certainly force down the size of those icons that get the padding

**Comment by raveit65** [comment]
> @raveit65 @sc0w does this fix the missing images in the menu?:
>```diff
>--- a/applets/notification_area/status-notifier/sn-dbus-menu-item.c
>+++ b/applets/notification_area/status-notifier/sn-dbus-menu-item.c
>@@ -197,6 +197,8 @@ sn_dbus_menu_item_new (GVariant *props)
>             }
> 
>           item->item = gtk_image_menu_item_new ();
>+          gtk_image_menu_item_set_always_show_image (GTK_IMAGE_MENU_ITEM (item->item),
>+                                                     TRUE);
>           gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (item->item),
>                                          image);
>         }
> ```

Nope, this does nothing.

Reverting https://github.com/mate-desktop/mate-panel/commit/017323dd4f8337ec91dd18f13955ab2e9df26cff
gives me a build issue.
...please test before you post......

```
libtool: link: gcc -Wall -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wno-sign-compare -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wl,-z -Wl,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o testtray testtray.o  ./.libs/libtray.a -lm -lX11 -lXau -lmate-desktop-2 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lstartup-notification-1
libtool: link: gcc -Wall -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wno-sign-compare -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wl,-z -Wl,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o .libs/notification-area-applet notification_area_applet-main.o  ../../libmate-panel-applet/.libs/libmate-panel-applet-4.so ./.libs/libtray.a -lm -lX11 -lXau -lmate-desktop-2 -lstartup-notification-1 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
./.libs/libtray.a(sn-dbus-menu-item.o): In function `sn_dbus_menu_item_new':
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:192: undefined reference to `sn_image_menu_item_new'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:193: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:197: undefined reference to `sn_image_menu_item_set_image_from_icon_name'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:202: undefined reference to `sn_image_menu_item_set_image_from_icon_pixbuf'
./.libs/libtray.a(sn-dbus-menu-item.o): In function `sn_dbus_menu_item_update_props':
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:313: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:317: undefined reference to `sn_image_menu_item_set_image_from_icon_name'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:332: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:336: undefined reference to `sn_image_menu_item_set_image_from_icon_pixbuf'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:341: undefined reference to `sn_image_menu_item_unset_image'
./.libs/libtray.a(sn-dbus-menu-item.o): In function `sn_dbus_menu_item_remove_props':
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:437: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:438: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:438: undefined reference to `sn_image_menu_item_unset_image'
collect2: error: ld returned 1 exit status
Makefile:731: recipe for target 'testtray' failed
make[4]: *** [testtray] Error 1
make[4]: *** Waiting for unfinished jobs....
./.libs/libtray.a(sn-dbus-menu-item.o): In function `sn_dbus_menu_item_new':
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:192: undefined reference to `sn_image_menu_item_new'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:193: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:197: undefined reference to `sn_image_menu_item_set_image_from_icon_name'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:202: undefined reference to `sn_image_menu_item_set_image_from_icon_pixbuf'
./.libs/libtray.a(sn-dbus-menu-item.o): In function `sn_dbus_menu_item_update_props':
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:313: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:317: undefined reference to `sn_image_menu_item_set_image_from_icon_name'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:332: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:336: undefined reference to `sn_image_menu_item_set_image_from_icon_pixbuf'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:341: undefined reference to `sn_image_menu_item_unset_image'
./.libs/libtray.a(sn-dbus-menu-item.o): In function `sn_dbus_menu_item_remove_props':
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:437: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:438: undefined reference to `sn_image_menu_item_get_type'
/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area/status-notifier/sn-dbus-menu-item.c:438: undefined reference to `sn_image_menu_item_unset_image'
collect2: error: ld returned 1 exit status
Makefile:727: recipe for target 'notification-area-applet' failed
make[4]: Leaving directory '/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area'
make[4]: *** [notification-area-applet] Error 1
make[3]: *** [all-recursive] Error 1
Makefile:865: recipe for target 'all-recursive' failed
make[3]: Leaving directory '/builddir/build/BUILD/mate-panel-1.17.2/applets/notification_area'
Makefile:449: recipe for target 'all-recursive' failed
make[2]: Leaving directory '/builddir/build/BUILD/mate-panel-1.17.2/applets'
Makefile:532: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/builddir/build/BUILD/mate-panel-1.17.2'
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.DVm3hg (%build)
    Fehler-Status beim Beenden von /var/tmp/rpm-tmp.DVm3hg (%build)
Makefile:464: recipe for target 'all' failed
```

**Comment by cwendling** [comment]
> Reverting 017323d
> gives me a build issue.

Works just fine for me.  As this updates a *Makefile.am*, are you sure the *Makefile* was properly updated?  Normally it should have been automatic unless you ran *configure* manually, but maybe Autotools failed for some reason.  Re-running autogen should fix it.

**Comment by cwendling** [comment]
> how can I know? [the size of the icons]

Please give last commit on https://github.com/cwendling/mate-panel/commits/debug/i521 a try and report the contents of */tmp/sn.log*.

**Comment by raveit65** [comment]
>> Reverting 017323d
>> gives me a build issue.

>Works just fine for me.  As this updates a *Makefile.am*, are you sure the *Makefile* was properly updated?  Normally it should have been automatic unless you ran *configure* manually, but maybe Autotools failed for some reason.  Re-running autogen should fix it.

Opps, i didn't take a look in the commit,
Ok, building works but no icons in menu of blueman.
Btw. i am thinking of switching from blueman to blueberry from cinnamon for fedora 26 with Mate-1.18.
Than buggy blueman is history for me.

**Comment by raveit65** [comment]
> About icon sizes, please give last commit on https://github.com/cwendling/mate-panel/commits/debug/i521 a try and report the contents of /tmp/sn.log.

Here's the log
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/sn.log

**Comment by cwendling** [comment]
> Ok, building works but no icons in menu of blueman.

Damned.  OK, let's see.  I pushed additional debugging into the debug/i521 branch, could you try that and report the result?

> Here's the log
>https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/sn.log

Hum. The code selecting the icon seems to do its job just fine.  The thing is it gets asked for a 16x16 icon (which it gives), which is fairly smaller than your panel (26px tall if I'm correctly view the image).  I'm suspecting the theme specifying an icon size of 16 for the panel (panel has an `icon-size` style property), or some padding/margin (through `icon-padding` or `margin`).  For that too I added additional debugging printers, so could you try them again?

**Comment by raveit65** [comment]
> Hum. The code selecting the icon seems to do its job just fine. The thing is it gets asked for a 16x16 icon (which it gives), which is fairly smaller than your panel (26px tall if I'm correctly reading the image). I'm suspecting the theme specifying an icon size of 16 for the panel (panel has an icon-size style property), or some padding/margin (through icon-padding or margin). For that too I added additional debugging printers, so could you try them again?

Good hint, all our themes forced the icon to use 16px, ie. BlueMenta
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L507
Commenting out that line fixes the issue for me.
```
na-tray-applet {
    -NaTrayApplet-icon-padding: 1px; /*any more and outlines get cut off*/
/*    -NaTrayApplet-icon-size: 16;*/
}
```
That means that this setting was never working before, btw. that this has no influence on applets like nm-applet or our volume-control applet.
@sc0w @lukefromdc 
Can you please confirm before i commit that to all our themes?

**Comment by sc0w** [comment]
@raveit65 yes, thanks, it works here on TOK

but the problem with icons on right click over blueman persists

**Comment by raveit65** [comment]
New sn.log with fixed theme
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/sn.log
Looks like blueman applet doesn't find the icons for menu  items.

**Comment by lukefromdc** [comment]
Any way to test this when Blueman won't run on my systems due to the no bluetooth device issue?

**Comment by raveit65** [comment]
@lukefromdc 
You can install fusion-icon from https://github.com/compiz-reloaded/fusion-icon
which should work with compiz-0.9 too.
Another applet is dropbox from caja-dropbox, but here you need to sign in for a free account with first running.
...i don't think you like that :-)

**Comment by raveit65** [comment]
...and start fusion-icon with 'fusion-icon -n".
-n starts only the applet.....

**Comment by lukefromdc** [comment]
Will try that later today after other business

**Comment by cwendling** [comment]
> Good hint, all our themes forced the icon to use 16px, ie. BlueMenta […]
>
> That means that this setting was never working before, btw. that this has no influence on applets like nm-applet or our volume-control applet.

Hum.  Do we want to honor it properly in the SNI icons then?
I possibly could try and see if it's easy to fix for the System Tray part, but I'm afraid I don't understand all its arcane internals well enough.

> https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/sn.log
> Looks like blueman applet doesn't find the icons for menu items.

Do you see icons in *fusion-icon*?

As I see this, blueman simply does not report any icon for its menu items, neither an icon name nor an icon pixmap.  Possibly there's a setting somewhere in it to have icons in the menus, maybe in the *AppIndicator* plugin?

**Comment by raveit65** [comment]
> Do you see icons in fusion-icon?

Yes, fusion-icon have icons in menuitems.

> As I see this, blueman simply does not report any icon for its menu items, neither an icon name nor an icon pixmap. Possibly there's a setting somewhere in it to have icons in the menus, maybe in the AppIndicator plugin?
I dunno...

**Comment by sc0w** [comment]
some icons on blueman code are here:

https://github.com/blueman-project/blueman/blob/master/blueman/plugins/applet/StandardItems.py

`get_icon(..........)`

**Comment by cwendling** [comment]
Hum, looking at the code, I see that they [dropped icons in menus](https://github.com/blueman-project/blueman/commit/4ca1cc94d641d47cf53d91af6f7f80bc0f2a4df8#diff-dde3c81b7bdb89782ed24e69cf244703R272) (because *"Effective GTK 3.10 Menu Items no Longer Support Icons/Images so we ignore images passed in here"*) and later [re-introduced them a hacky way](https://github.com/blueman-project/blueman/commit/0aa9344099f0031aef6eba0a059c9cd8fe9303d9).  The version I have working on Debian Jessie still has the `Gtk.ImageMenuItem` code, so I suspect that [the AppIndicator menu](https://github.com/blueman-project/blueman/blob/master/blueman/plugins/applet/AppIndicator.py#L31) doesn't catch those custom icons.

I'll try to find some time to switch it back to `Gtk.ImageMenuItem` and see if it helps, but apparently it's not as trivial as just changing `create_menuitem()`, because some other code poke into the widget hierarchy.

@lukefromdc I found a way to test Blueman without having actual Bluetooth device: edit the `bluetooth.service` *systemd* unit (*/lib/systemd/system/bluetooth.service*) and comment-out `ConditionPathIsDirectory=/sys/class/bluetooth`, so that it starts anyway whether or not */sys/class/bluetooth* exists.

**Comment by lukefromdc** [comment]
Just got it running, and can see the icon using the full available space in my setup and with my "UbuntuStudio_Legacy" icon-theme. I checked the size of the bluetooth icons in my theme and all of them are correct, and they are in sizes 16, 22, 24, and 48(did not check larger than that). These icons use all of the available height of the image file. 

By comparison, preferences-system-bluetooth.png in the "mate" icon theme is padded down 3px on the top and 2px on the bottom, for 5px out of 24 vertical pixils not used. Thus, in the MATE themes the bluetooth icon appears tiny. Difference is quite profound, not sure if all of it is the icon size but some of it sure as hell is

**Comment by sc0w** [comment]
@infirit @cschramm @walmis @stefano-k @rworkman (blueman contributors)

please, can you help us?

(right click on the blueman tray icon, shows no icons)

**Comment by infirit** [comment]
Before commit x in panel things were fine, after it broke and somehow this became a blueman problem? Sound more like panel broke GtkStatusIcon/AppIndicator. If you can reproduce this on Xfce for example please open an issue on blueman.

As for the hacky reimplementation, this is what the gtkimagemenuitem documentation says is functionally equivalent and that is what I did (just providing a pixbuf instead of an icon name). Feel free to send patches if you think you can do better __and not break other desktops__.

**Comment by raveit65** [comment]
@lukefromdc 
```
na-tray-applet {
    -NaTrayApplet-icon-padding: 1px; /*any more and outlines get cut off*/
/*    -NaTrayApplet-icon-size: 16;*/
}
```
Should i do that for BlackMATE too?

**Comment by sc0w** [comment]
@infirit is only a question to solve this, I know this isn't a blueman issue

about the PR https://github.com/mate-desktop/mate-panel/pull/517

+6,077 additions −367 deletions, and merged in three days

obviously that wasn't tested enough

and probably, more applications must be affected, sure

I suggest revert all the https://github.com/mate-desktop/mate-panel/pull/517 commits and the next commits affected, if we can't solve this

**Comment by raveit65** [comment]
> I suggest revert all the #517 commits and the next commits affected, if we can't solve this

And why this isn't a problem with fusion-icon which is written in python and use AppIndicator too?

**Comment by muktupavels** [comment]
https://code.launchpad.net/~dbusmenu-team/libdbusmenu/trunk.16.10
Check 479. revision. Either it does not work or blueman use too old appindicator/libdbusmenu version that does not know how to extract image!?

It is not problem with fusion-icon most likely because it still use deprecated GtkImageMenuItem!?

**Comment by sc0w** [comment]
@raveit65  good question, If it works with gtkimagemenuitem on ifusion-icon, it ca be adapted to blueman, I think

**Comment by infirit** [comment]
Muting this discussion, if you have specific questions or bugs for blueman open and issue with us. Good luck with solving this.

**Comment by sc0w** [comment]
more info: with blueman 1.99~alpha1 I can see the icons

**Comment by raveit65** [comment]
As the culprit is blueman itself we can close the issue?

**Comment by sc0w** [comment]
@raveit65 of course

**Comment by infirit** [comment]
Sigh it seems I can't avoid this issues and I have to spend more time on this 😢. Firstly the fix is not a fix. blueman has plugins and by reverting that commit it throws an exception for the AppIndicator plugin whichs skips loading it. You can accomplish the same by just disabling the plugin through the dialog

Second, blueman sets the icon_name for the StatusIcon and the Appindicator gets the icon_name from it. It does not force a size or anything special. Also it only sets the icon on which one clicks and has nothing to do with any of the icons displayed in the menuitems. The menuitems can come from all plugins but mostly from the StandardItems plugin.

And last, the core problem is that Appindicator/DBusMenu only looked for icons in the GtkImageMenuItem objects and does not search the GtkMenuItem children. And in release 16.04.0 it added that it also searches GtkMenuItems, as Albert already pointed out to you. However this has most likely not ended up in many distributions, it hasn't in Gentoo which is at 12.10.2 (previous release).

Now, do everyone a favour and make sure to update libdbusmenu to the latest release before doing anything else with other projects. And if your distro has updated send the bug report to the libdbusmenu folks as their changes appears to not work.

**Comment by infirit** [comment]
Just build 16.04 version of libdbusmenu and icons show up in the menu. The icon in the notification area still is a bit smaller but as I explained we do not enforce any size so you will have to do some work in mate-panel to figure that out.

Now, can you please stop blaming blueman for this?? Thanks!

**Comment by cwendling** [comment]
@muktupavels @infirit thanks for the info and effort.  Indeed I have an older version on Debian Sid.

So I guess it's nobody's fault but libdbusmenu's latest version not being spread enough into various distros.

And IIUC the icon size issue is related to padding in the theme (https://github.com/mate-desktop/mate-panel/issues/521#issuecomment-277512835), and for me it's good anyway (using Adwaita currently).

> Now, can you please stop blaming blueman for this?? Thanks!

I easily can, I blame GTK for deprecating `GtkImageMenuItem` :)

**Comment by lukefromdc** [comment]
No objection to stripping  
` -NaTrayApplet-icon-size: 16;`
out of BlackMATE, I've just been overwhelmed with other things lately

**Comment by raveit65** [comment]
Done in themes b64a6c90a982a67a4a74d38dc60c6f0b57d3478d

**Comment by lukefromdc** [comment]
Now I know why my theme did not have this problem: it never specified the icon size for the tray
