### ISSUE TITLE
Change text when switching between panels with the keyboard

### ISSUE THREAD

**Issue by alexarnaud** [mate-desktop/mate-panel#530]
When you switch between panels with the keyboard, the strings are long so it reduces the productivity for the blinds persons that need to listen to the whole string to determine if the panel is the top or the bottom one.
In English, it's not a big issue because "top" is the first announced element, but in French the top ("supérieur") ends up at the end of the sentence, and thus is read last by the Orca screen reader.

At this time there are 4 detailed elements for the top bar (the same for the bottom, left and rieght bars):
* "Top Expanded Edge Panel"
* "Top Centered Panel"
* "Top Floating Panel"
* "Top Edge Panel"

Would it be possible to reduce it to only one string "Top bar" due the low usefulness of the "extended", "edge" or "floating" information for a sighted person?

Best regards.

**Comment by monsta** [comment]
@cwendling: what do you think about it?

**Comment by cwendling** [comment]
I agree with @alexarnaud that the current situation is highly suboptimal when used with a screen reader, and the proposition sounds reasonable to me.  Announcing how the panel expands seems useless to everyone, and ATs can know the real screen position and size anyway -- so can sighted users visually.

I'm not totally sure about the "panel" vs "bar" suggestion as I'm not a native English speaker, but it doesn't sound bad, and doesn't seem to be the most critical change to this either.

**Comment by alexarnaud** [comment]
@flexiondotorg @monsta could you give us your opinion for this change ? If it's OK for you we could made the change.

Best regards.

**Comment by monsta** [comment]
If it only affects a11y, I'm fine with the change. However, it will take some time for the translators on Transifex to update the translations for all the languages. So I think we will wait a bit before releasing the change in version 1.18.1 (for example).

**Comment by raveit65** [comment]
> So I think we will wait a bit before releasing the change in version 1.18.1 (for example).

@monsta 
I will start with branching if you agree, i prefer cherry-pick commits from master to 1.18.1 if needed.
Please give me a info, especially m-p have to much new commit and open PRs.
