### ISSUE TITLE
Black Squares On Notification Area Applet Panel.

### ISSUE THREAD

**Issue by javashin** [mate-desktop/mate-panel#532]
hello i need  some help with this problem im having never happen before on My gentoo installations
this is a fresh install of gentoo . please can someone tellme why is this happening what exactly may cause this. :
![screenshot at 2017-03-12 23-27-22](https://cloud.githubusercontent.com/assets/15115613/23844875/4a20b28e-079b-11e7-96cc-55e82d2b090d.png)

**Comment by javashin** [comment]
mate-panel 1.16.0

**Comment by javashin** [comment]
the icons are there but are black squares everything works fine on xfce , gnome . lxde all of them have systray even on fluxbox

**Comment by biergaizi** [comment]
1.16, Same problem here on Gentoo, what are all the icons?!

**Comment by biergaizi** [comment]
Don't install Mate from the Gentoo Portage main tree, 1.16 is a pretty old release! Install 1.18 from `gentoo-mate` overlay solves all the problems!
