### ISSUE TITLE
Don't suppress the shutdown menu on LTSP clients

### ISSUE THREAD

**Issue by alkisg** [mate-desktop/mate-panel#535]
[This commit](https://github.com/mate-desktop/mate-panel/commit/8c25e1bdd328a8712735c0b00cf4aede7993da1d), 9 years ago, aimed at hiding the shutdown menu on LTSP clients, because they were remote sessions to the LTSP server, and we didn't want remote users to shut down the server by accident.

Nowadays it prevents LTSP fat clients from shutting down. Fat clients is the recommended LTSP setup, and they run the session locally on the client, so having a shutdown button there is required.
As for thin clients, preventing server shutdown is taken care of by policykit, there's no need to check for an environment variable in the MATE code (btw I'm an LTSP developer).

So, I'd like to ask you to please revert commit https://github.com/mate-desktop/mate-panel/commit/8c25e1bdd328a8712735c0b00cf4aede7993da1d.

**Comment by raveit65** [comment]
@lukefromdc 
@monsta 
@XRevan86 
Can we do that?

@alkisg 
What is a LTSP client?

**Comment by alkisg** [comment]
@raveit65, LTSP (ltsp.org, Linux Terminal Server Project) is a collection of packages that helps sysadmins set up DHCP, TFTP, NBD, SSHFS etc, so that diskless clients can be booted from the network.
One way to test the problem is to manually set that environment variable, e.g.:
LTSP_CLIENT=1.2.3.4 mate-panel --replace
You'll see then that
1) Initially, the shutdown menu item is hidden, and
2) After reverting that 9 year old commit, the shutdown menu item is properly shown again.

I'm testing with mate-panel's redmond layout, because the ubuntu-mate layout doesn't include the shutdown menu item anyway.

**Comment by sbalneav** [comment]
I support reverting this; it won't affect anyone other than LTSP clients, and we don't need that in there anymore.

**Comment by lukefromdc** [comment]
I can confirm that mate-panel in master as of today suppresses the shutdown item in the main menu (shutdown applet from mate-applets unaffected) when restarted with 
`LTSP_CLIENT=1.2.3.4 mate-panel --replace`
though I have never worked with a diskless client that I controlled.
