### ISSUE TITLE
[Feature request] Hide window titlebar on maximized windows and move "close minimize maximize" buttons to panel

### ISSUE THREAD

**Issue by Sunderland93** [mate-desktop/mate-panel#554]
Just like in Unity 7. MATE has an option to hide titlebar's on maximized windows, but buttons "close minimize maximize" are dissapear.

![6wasb](https://cloud.githubusercontent.com/assets/11344982/24786405/2fa69d28-1b9c-11e7-80c3-b0d6caf6a5b6.png)

**Comment by monsta** [comment]
This won't/can't be implemented in panel itself, it should be done in some applet. It probably will be useful only in Ubuntu MATE too. I suggest looking here:

https://ubuntu-mate.community/t/developing-a-window-buttons-applet-for-mate/8637

**Comment by flexiondotorg** [comment]
This feature has been implemented in the Mutiny layout for Ubuntu MATE 18.04
