### ISSUE TITLE
mate-panel: gtk_image_definition_unref(): mate-panel killed by SIGSEGV

### ISSUE THREAD

**Issue by smoge** [mate-desktop/mate-panel#555]
https://bugzilla.redhat.com/show_bug.cgi?id=1409226

**Comment by lukefromdc** [comment]
I have not seen this on Debian Unstable with GTK 3.22 and any version of mate-panel compatable with it.  Wonder what is different. Could one of the many build time warnings point to something that Federa's core library build options or kernel configuration are stricter about? This is not the first time I've seen a bug report of segfaults that could not be duplicated on Debian against a package-and I think but am not sure last time around was also on Fedora.

Also, can this be duplicated with mate-panel 1.18 or (git master) 1.19? Also, might something have gotten updated since mate-panel was last built in Fedora that caused this?

**Comment by lukefromdc** [comment]
There was mention in the Fedora report of someone first seeing the crash after a Chrome update, I don't have Chrome installed. One user was using Xnomad, another was not, yet another said Fedora 26 did not have this and called Fedora 25 "buggy."  Also need to know exactly what applets are being used, and if any were built in-process. A crashing in-process applet takes down the panel, an out of process applet usually does not.

**Comment by raveit65** [comment]
I can't reproduce that in fedora.
Updating the system with 'dnf update' does not have any influence on the panel.
But i only use package from fedora and not packages from external 'google repos` like chrome.

**Comment by monsta** [comment]
Might be the same as https://github.com/mate-desktop/mate-panel/issues/494 because the backtraces are similar (not exactly the same though).

**Comment by smoge** [comment]
It happens with me all the time on Fedora 25. I use XMonad as the WM, but other people reported having this problem without XMonad as well. A few other people reported this problem, but it seems to happen with just a few of us for some reason. The maintainer thinks it might be related to Chrome because it's from a third-party repo. I can't confirm this. Fedora's maintainer couldn't help much. Let me know if I can provide more information.

**Comment by raveit65** [comment]
>  Fedora's maintainer couldn't help much.

Fedora mantainer asked for a new stacktrace and you didn't provide this info.
How/Why should a volunteers help you if you ignore questions?

**Comment by raveit65** [comment]
Btw. in this stacktrace is ktelnet mentioned at the end of Thread 1
https://bugzilla.redhat.com/attachment.cgi?id=1270253
```
#59 0x00007f04fa10524f in invoke_notifies (path=0x56168b2275c0 "/usr/share/applications/ktelnetservice5.desktop", event=MENU_MONITOR_EVENT_CREATED, monitor=0x56168b3ebb80) at menu-monitor.c:79
```
```
[root@mother rave]# dnf provides */ktelnetservice5.desktop
Letzte Prüfung auf abgelaufene Metadaten: vor 0:31:15 am Wed Apr 12 13:13:18 2017 CEST.
kf5-kio-core-5.33.0-1.fc26.x86_64 : Core components of the KIO Framework
```
As always i installed this package but i don't get a abrt alarm or crash at my box if using
'dnf update'.

As Fedora maintainer says: try removing those packages (ie chrome, chromium, kde crap) which causes the issue. To find out which package is the real culprit.

**Comment by smoge** [comment]
This has already been tried here. If there is a list of actions you want to suggest, you can do it here. The other bugracker was a little abstruse by the tone of the conversation.

**Comment by smoge** [comment]
Why "unconfirmed"?

**Comment by raveit65** [comment]
@smoge 
Scratch builds for f25 or f26, Are they helpful?
f26 with 1.18.1:
https://koji.fedoraproject.org/koji/taskinfo?taskID=19004755
f25 with 1.16.2:
https://koji.fedoraproject.org/koji/taskinfo?taskID=19004911

**Comment by raveit65** [comment]
@smoge 
see and read this comment and followers
https://github.com/mate-desktop/mate-panel/issues/494#issuecomment-303175502
Please check **all** desktop files in /usr/share/applications/ and remove all lines like
```Icon=```
(icon is declared without a value)
Don't forget kde dirs there.
Hopefully this **workaround** helps for the moment.

**Comment by raveit65** [comment]
Ok, i was able to duplicate the issue with using 'dnf update', if i install ggz-gtk-client with the culprit desktop file.
Now i will test if https://github.com/mate-desktop/mate-panel/pull/581 helps.

**Comment by raveit65** [comment]
The commit fixes the problem for me, tested with mate-panel-1.19.0 / 1.18.2 and 1.16.2.

**Comment by raveit65** [comment]
I will update fedora branches soon.

**Comment by raveit65** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2017-d536f592bc
Done!
