### ISSUE TITLE
Launchers description text doesn't appear in locale language

### ISSUE THREAD

**Issue by fblais** [mate-desktop/mate-panel#572]
Howering the mouse over the launchers on the panel shows the text in english instead of my locale, which is french.
French-canada has already been configured as system-wide.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-session-manager/pull/138

**Comment by fblais** [comment]
Forgot to say it's with MATE 1.18.

**Comment by monsta** [comment]
Hmm... why we didn't have this issue in 1.16?

**Comment by alexarnaud** [comment]
Le 15/05/2017 à 14:48, monsta a écrit :
> Hmm... why we didn't have this issue in 1.16?

Is it related to the bug #530 ? It could be just a matter of translation.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by raveit65** [comment]
> Hmm... why we didn't have this issue in 1.16?

We have :-)
I can reproduce that with all mate versions if system default language differs to user language.

**Comment by raveit65** [comment]
Btw. at least it depends on systemd and dbus.
For rhel7 i don't need this PR but it won't hurt.
I use that for all fedora/rhel versions.

**Comment by monsta** [comment]
> Is it related to the bug #530 ? It could be just a matter of translation.

I doubt that... it was about a11y name of panel itself, and this one affects only panel launchers (icons).

>  I can reproduce that with all mate versions if system default language differs to user language.

Then it's a different issue... this one can be seen without modifying any locale settings.

**Comment by monsta** [comment]
@dnk: can you please look at this? It seems like migration from GKeyFile to GDesktopAppInfo in https://github.com/mate-desktop/mate-panel/commit/7ee450758e4f2bee13aa8ff967a5795a6dcdc91f removed locale support for launcher name and comment.

**Comment by monsta** [comment]
Ok, we have a fix in https://github.com/mate-desktop/mate-panel/pull/575.

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/mate-panel/commit/cf3155349a163f1be2bba99539ff234bf56b6a38. We'll make a new 1.18.x release soon.

**Comment by monsta** [comment]
Version 1.18.3 is now released with the fix.
