### ISSUE TITLE
Calendar time not set to the correct time on laptop after suspend

### ISSUE THREAD

**Issue by orion40** [mate-desktop/mate-panel#576]
When you close the lid of your laptop, then open it again after some time, the calendar time stay as it was when you closed the lid, instead of correctly updating to the current time.

Clicking on it fix the issue, as well as waiting for a minute to pass, in which case the time update itself.

**Comment by monsta** [comment]
Yes, known issue: https://github.com/mate-desktop/mate-panel/issues/481
