### ISSUE TITLE
[1.18] menubar/menu-button: can't launch mozo when menulibre isn't installed

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-panel#586]
@flexiondotorg: please take a look at this. I have a feeling it's caused by https://github.com/mate-desktop/mate-panel/commit/a506150684ad2e71b1f70190ee70fe9eda7a4ba9.

I can reproduce it with menubar and menu-button, and there's a couple of reports about the advanced menu at https://github.com/mate-desktop/mate-menus/issues/49.

**Comment by Kallestofeles** [comment]
For the same issue, only using Advanced mate menu, I have created a bug report also on ubuntu-mate bug-tracker:
https://bitbucket.org/ubuntu-mate/mate-menu/issues/22/cannot-launch-mozo-when-menulibre-isnt

**Comment by lukefromdc** [comment]
I can confirm that "edit menus" from right-clicking the menu button does not work here onMATE 1.19 from git master built with  GTK 3.22 over Debian Unstable.

Mozo will launch fine from system>preferences>look and feel>main menu but not from the "edit menus" right-click menu on the menu button. That would be a far faster way to it if only it was working, I had  somehow not noticed its existance until now.

**Comment by raveit65** [comment]
@flexiondotorg 
From my point of view we should prefer mozo as it is our own app, and menulibre is a csd app.
Why not simply reverting the commit if it doesn't work properly?

**Comment by raveit65** [comment]
Confirmed, reverting https://github.com/mate-desktop/mate-panel/commit/a506150684ad2e71b1f70190ee70fe9eda7a4ba9 fixes the issue.
