### ISSUE TITLE
1.18 - Privilige Escalation icon corrupt

### ISSUE THREAD

**Issue by Rahtgaz** [mate-desktop/mate-panel#587]
With 1.18 an old problem fixed in 1.17 has resurfaced. The Privilege Escalation icon on the notification area of the panel is showing again corrupt.

Can't take a screenshot right now as I'm on a different partition distro, but advise if you need more information.

**Comment by raveit65** [comment]
ZZZZzzzz.....
...as always, distro, version of the package and a screenshot won't hurt.

**Comment by Rahtgaz** [comment]
Zzzz....
Package 1.18.2 on Arch linux.

Zzzz....
As I said, no screenshot possible right now. Icon corrupt is too complicated for you? You are going to see a corrupt icon. Meaning, the image of the icon is being rendered incorrectly.

**Comment by lukefromdc** [comment]
Question, maybe one of us will have the answer: Does mate-polkit (source of this icon) build with or without appindicator support? If with, than a bugfix applied to the original icon code might also be needed for the new code used with appindicator (status notifier) support. The status notifier is new in mate-panel 1.18 and mate-polkit will build to support it unless explicitly disabled.

**Comment by lukefromdc** [comment]
Question, maybe one of us will have the answer: Does mate-polkit (source of this icon) build with or without appindicator support? If with, than a bugfix applied to the original icon code might also be needed for the new code used with appindicator (status notifier) support. The status notifier is new in mate-panel 1.18 and mate-polkit will build to support it unless explicitly disabled.

**Comment by Rahtgaz** [comment]
According to the Arch sources (https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/mate-polkit), it is built from the sources available at http://pub.mate-desktop.org/sources/mate-polkit/1.18/mate-polkit-1.18.1.tar.xz

The answer could be on those makefiles? I can't move past this stage since I don't understand the syntax.

**Comment by lukefromdc** [comment]
That looks like it will enable appindicator support, which if detected is used by default. I didn't see any use of the option to disable it, so it will be detected from mate-panel 1.18 and used.  There is also the issue of this icon not disappearing when elevated priviliges are dropped
https://github.com/mate-desktop/mate-polkit/issues/35
which also related to that same icon, so my guess is the code for displaying that icon needs some work. This is thus is probably an issue in mate-polkit and not mate-panel's status notifier, but I don't know enough about the status notifier to be 100% sure of that.

Thus I suggest opening an issue against mate-polkit for this

**Comment by Rahtgaz** [comment]
Ok, will do. Thank you.

**Comment by raveit65** [comment]
> Or perhaps you think I care. Is that it? Maybe you think I'm so desperate and out of options, that I will just bend over to your jerk attitude.

80 % of bug reports here have incomplete informations. And i am tired of saying every time the same, as it it is my free time that i spend here to ask you for this.
As you getting personal you're in my blacklist.
