### ISSUE TITLE
[1.18] panel can't load launchers for files/folders [$25]

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-panel#590]
@dnk: we have another regression from https://github.com/mate-desktop/mate-panel/commit/7ee450758e4f2bee13aa8ff967a5795a6dcdc91f...

Steps to reproduce:
1. Launch Caja.
2. Drag some folder to the panel. I used a folder called "mate".
3. Launcher for that folder will be created, but won't be loaded. In `~/.xsession-errors` there will be an error message: "Unable to open desktop file mate.desktop for panel launcher".

The launcher is stored in `~/.config/mate/panel2.d/default/launchers` dir, but for some reason `g_desktop_app_info_new_from_filename` function (called from `create_launcher`) can't load it. I don't know the exact reason because that function doesn't have a way to set GError.

Here's the contents of that launcher:
```
$ cat ~/.config/mate/panel2.d/default/launchers/mate.desktop
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Name=mate
Comment=Открыть «/home/monsta/mate»
Icon=folder
Name[ru_RU]=mate
Comment[ru_RU]=Открыть «/home/monsta/mate»
Icon[ru_RU]=folder
URL=file:///home/monsta/mate
Type=Link
```

**Comment by lukefromdc** [comment]
Confirmed here on Debian Unstable with GTK 3.22.15

**Comment by AshleyYakeley** [comment]
Ubuntu Launchpad downstream bug: https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/1690517

**Comment by raveit65** [comment]
It seems to be very popular to create launchers from folders in the panel.
I can confirm that it doesn't work to drag a folder from caja window, but it works to drag the home folder from the desktop for some reasons here.

**Comment by raveit65** [comment]
@dnk 
Can you please take a look in it?

**Comment by AshleyYakeley** [comment]
I downgraded to 1.16 to avoid this.

**Comment by monsta** [comment]
> I can confirm that it doesn't work to drag a folder from caja window, but it works to drag the home folder from the desktop for some reasons here.

I know why it works. It creates an app launcher with `caja --no-desktop`, not a folder link launcher. It's also is saved in dconf as all the app launchers, not in the config directory.

**Comment by mexsudo** [comment]
Good morning.
Using LMDE.  I have been trying daily. Updated again, two different computers. Not fixed. Played with various repos, nothing new to update with.
Is this an issue with Mint not adopting the fix? 
thanks

**Comment by lukefromdc** [comment]
My guess is Mint won't pick up the fix until the next 1.18 point release.

**Comment by raveit65** [comment]
> Is this an issue with Mint not adopting the fix?

This you have to ask linuxmint devs.
We are MATE, not linuxmint ;-)

**Comment by monsta** [comment]
Fix is now released in version 1.18.5.

**Comment by raveit65** [comment]
@monsta 
Don't forget to claim the bounty 
https://www.bountysource.com/issues/45980902-1-18-panel-can-t-load-launchers-for-files-folders

**Comment by monsta** [comment]
I didn't even notice there was a bounty... Ok, I submitted a claim there.
