### ISSUE TITLE
Mate Panel Transparency not working correctly

### ISSUE THREAD

**Issue by Isakku** [mate-desktop/mate-panel#591]
I just downloaded the Linux Mint Mate 18.2 beta and found a bug with the panel applet. 
#### Expected behaviour
Panel transparency working the way it worked before in former versions of Linux Mint.

#### Actual behaviour
Only the corners become transparent instead of the entire panel.

Here's a screenshot.

![Image](https://lh3.googleusercontent.com/EdP2CKxIi8zrknr8a0Xxmp8D14c3Zxsp3wFP85rYBKxAd3xuckS_k9dZfQKWTjGfubOCEh0IwV9Nz6GXyrprW4b6TS9l26KAQP5q7SD3Phi0cIeTy_q5AabeQJp3tbzmD0ASjQlsCOHWT191xzFvF8egLgLUOGcJOPgND3xFdzw_s8fNkjaipfQHjsg2ZTzD0Y2wEx6gqf-TkDRI4rBIGWDTL_hVdWP-kKO-L_Hqk8HnqptyZj2P-aluKnJo2o1B77HIp5p0Aa8np5EF8VPPel-gh5PeXC99_CKGGN4XYL58HPsj7N2yvRFgJ-4Zb8iJ-F86nvu97_dAhjbpF0b8xy0Kl0uXSbDjjAwmJIE-IFc12iErwpcajTAfxhkgZkJEpZ-hx0Ulykh-nQg3cf3Os6iZZHwGvv2akAplUh-5XBf4Lhy6Lg3W2wus_Y0mbT8FcX0pz91MzGR58-oaOHQUbR7BWOGKwlJUnxDOefzmDYp8lv3z7ptQ3RYa_hdaZCOZC5SoHRcJ1gFt0jHAC5GWscxiZzTS6nzSQvQKBzuLDMHugIzy6lqNqDl2f9zvM6Uqd99Cp4muAPx8QrtVFdSeTfxdpZlbSPK4qpOFSnqbfWPJ528BzRQjkCvCSfSniBt6-32R0L5ZQIUON7Hu_1Zir8_4gWj_m-oGXhM=w949-h536-no)

#### Steps to reproduce the behaviour
Right click and choose properties, background, solid color (choose a color) and set a transparency level. Close.

#### MATE general version
Mate 1.18

#### Package version
Mate Panel 1.18.2

#### Linux Distribution
Linux Mint Mate

**Comment by raveit65** [comment]
This works great in fedora with all themes from mate-themes.
Looks like a mint-X theme issue.
I suggest to contact linuxmint directly.
@clefebvre @JosephMcc
Can you please take a look into it?

**Comment by raveit65** [comment]
@Isakku 
Did you file out a report against Linuxmint?
......to be sure it isn't a distro issue.

**Comment by JosephMcc** [comment]
I'll take a look. Users need to realize that this functionality won't work with all theme though. Supporting puts some limitations on what a theme is allowed to do. Last time I checked, at least, if you use any sort of image based assets they are unaffected by that setting.

**Comment by raveit65** [comment]
@JosephMcc
I suggest to add something like this add the beginning of panel settings to clean all garbage from general settings. This is what i do with our default themes (Menta).
```
/* first make all transparent */
.mate-panel-menu-bar,
.mate-panel-menu-bar menubar,
.mate-panel-menu-bar menuitem,
#PanelPlug,
#PanelApplet button,
PanelToplevel.background,
#PanelApplet-window-menu-applet-button {
    background-color: transparent;
    border-image: none;
    background-image: none;
    background-color: transparent;
    box-shadow: none;
}
```
see here for details https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L281

**Comment by JosephMcc** [comment]
@raveit65 thanks. Useful info.

**Comment by JosephMcc** [comment]
@raveit65 Feel free to close this. It is a limitation of our theme at the moment.

@Isakku This is being looked into. I won't promise it will work exactly the way you expect with Mint-X but I'll see what I can do. A serious limitation of this feature is that it doesn't work well with image based assets and we do currently use some for the panel.

**Comment by lukefromdc** [comment]
This has never worked with every applet in the panel and every theme even in Gtk2. In the old days the original circa 2007-2008 UbuntuStudio theme had issues with this. What happens is the panel becomes transparent easily enough but some applet is themed over it non-transparent. 

In GTK3 this happens whenever a widget (such as a button, a label, a menubar etc) within an applet that doesn't get the .mate-custom-panel-background style class to it (this is what turns it transparent) gets a non-transparent background set in the theme.

**Comment by JosephMcc** [comment]
> In GTK3 this happens whenever a widget (such as a button, a label, a menubar etc) within an applet that doesn't get the .mate-custom-panel-background style class to it (this is what turns it transparent) gets a non-transparent background set in the theme.

This isn't entirely true from what I can tell. Applets like wnck or the clock applet get this style class applied according to GtkInspector. However if they are themed with an image asset it still fails.

**Comment by lukefromdc** [comment]
The panel loads code to theme .mate-custom-panel-background transparent internally,  themes should never use it. It's just a matter of not setting a background on panel widgets that do NOT set that style class when a custom background is used. You can find the widgets in question by opening the panel preferences dialog, opening gtkinspector while the mouse is over it, then using it to check panel widgets. For some applets, you need to open gtkinspector over one of the applet's menus to gain access to the widgets the applet puts in thepanel.

**Comment by JosephMcc** [comment]
Sorry if I'm misunderstanding or just being dense :)

As I said the clock applet gets this style classed applied. From what you are saying, Mate panel should handle the transparency for this internally. My point is that it doesn't work with an image based asset like a border-image or background-image. Is that not properly handled by Mate panel or just a limitation?

I suppose I could have made this easier by looking at the Mate panel code or jumping in IRC ;)

**Comment by lukefromdc** [comment]
I'm guessing your theme is loading a background onto a widget which is drawn over the widgets that get .mate-custom-panel-background applied. This is because the code overrides background images.
A border images does NOT get overriden however.

The code in question, from panel-background.c  is
```

	gtk_css_provider_load_from_data (provider,
					 ".mate-custom-panel-background{\n"
					 " background-color: rgba (0, 0, 0, 0);\n"
					 " background-image: none;\n"
					 "}",
					 -1, NULL);
```

and should override all background colors and images-but will NOT override anything in the foreground, and does not override border images. Overriding border images could create problems on some widgets, though the window list does not apply the mate-custom-panel-background to its buttons, which thus should be themed with a partially transparent background or partially transparent  image to best support a transparent panel.

**Comment by JosephMcc** [comment]
Here is an example of something that breaks.
```
#PanelApplet .button {
    background-image: linear-gradient (to bottom, red, green);
}
```
Using this, the clock applet background will not turn transparent.

I fully appreciate and respect you guys are trying to support something that Mate has supported forever, and I want to make it work in Mint-X but what a pain :) This is not going to work as expected in a lot of 3rd party themes.

**Comment by lukefromdc** [comment]
Your code above styles ALL buttons within a panel applet, some of which are not turned transparent by .mate-custom-panel-background. This code is thus too general for the panel. No way this will work in all 3ed party themes, many of which do not style mate-panel or gnome-panel at all.  In that last case most but not all applets should actually work. In Adwaita the desktop applet was one of the few problems in my layout for instance. Sane defaults keep the panel itself usable when only the overall GTK theme is available.

**Comment by JosephMcc** [comment]
> Your code above styles ALL buttons within a panel applet, some of which are not turned transparent by .mate-custom-panel-background.

I understand that. I think there is a miscommunication or misunderstanding. If I use the above code and a specific applet supports the `.mate-custom-panel-background` style class, it should be turned transparent, correct?

If the above assumption is correct, the clock applet which supports the style class according to GtkInspector, should be turned transparent. Please correct me if I'm wrong. My point is that it is not. It still uses the gradient supplied by the theme.

**Comment by lukefromdc** [comment]
If any widget that renders on top of the applet in question is not transparent, that's what you will see.  It's not just the applet, its the exact widget (button etc and everything within it) that is the issue. If you can turn everything inside the button transparent with this test modification of your theme

#PanelApplet .button *{
    background-image: none;
   background-color: transparent;
}

and the button in question is getting .mate-custom-panel-background applied to it and you still see the grandient, check also widgets underneath it, as these would show through the transparency. If there are no such widgets without  .mate-custom-panel-background at all, then i don't know at that point what is going on. I would suggest  experimenting with changes to the theme, then report back your results.

**Comment by JosephMcc** [comment]
Thanks for your patience. I can figure out how to make it work. Just trying to understand how it's expected to work on the code side so I know if what I'm seeing is just "how it is" or if something isn't working as expected.

**Comment by Isakku** [comment]
Uhm... Guys?
I'm still learning about all this GTK API, and such but, in my screenshot, the panel options allow 3 settings:
1) None (Use system theme)
2) Color (color picker) Style (transparency slider)
3) Background image (Load file)

Shouldn't the code take those in consideration?
Anyways, if some applet doesn't work correctly it would be a problem with said applet, not the panel.
The Panel and all it's native applets do work correctly in former versions and that quality should remain.
 
@raveit65
Yes, I already reported the bug in the linuxmint blog
Also created a thread in the forums.
It seems they're too busy with all the 18.2 beta testing.

**Comment by JosephMcc** [comment]
@Isakku I have this fixed locally in Mint-X. I just need to update the color variations and then I'll push it up. Hopefully later today or tomorrow.

**Comment by monsta** [comment]
Thanks @JosephMcc. I guess we can close it now? The commit is pushed (https://github.com/linuxmint/mint-themes-gtk3/commit/7f816b55f85182d9b427681faceb316dc57e2ac9), and mint-themes-gtk3 package is updated to 3.18+17 in Mint 18.2 repo.

**Comment by JosephMcc** [comment]
@monsta Yes. It was really never an issue on your side anyway.

**Comment by monsta** [comment]
Indeed :slightly_smiling_face:
