### ISSUE TITLE
Mate menu moves if placed below vertical panel

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-panel#598]
#### Expected behaviour
I expect the menu to open directly above the mate menu, like in 
earlier versions. This new behaviour (which I assume is a bug) makes 
it hard to browse the menu.

#### Actual behaviour
Using both a vertical panel (left) and a horizontal panel (bottom), 
if the mate menu is below the vertical panel and clicked the menu 
that opens is displaced.

#### Steps to reproduce the behaviour
Create a left panel and a bottom panel. Place the Mate menu on the bottom panel to the left. It will unfold to the right of the vertical panel, making it hard to browse the menu.

#### MATE general version
1.16.2-1

#### Package version
Debian Stable (Stretch)

#### Linux Distribution
Debian Stable (Stretch)
![2017-06-26_18-12-41](https://user-images.githubusercontent.com/661685/27549555-9ac70158-5a9c-11e7-81fb-ddb062cca42c.png)

**Comment by JohnScott623** [comment]
This may be fixed as part of #157 and the pull requests that came about there.
