### ISSUE TITLE
Weather icon, temperature come up only some of the time on panel restart 

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#603]
#### Expected behaviour

If "show weather" is checked in clock-preferences, always show the weather icon when the panel starts
if "show temperature" is checked, always show the temperature when the panel starts

#### Actual behaviour
The weather icon and temperature sometimes are displayed on a panel start and sometimes not. The weather icon almost always comes up, but the temperature usually does not. It made no difference in my tests if only the temperature or both were selected. Going into the clock preferences, deselecting, then reselecting them will always bring them up as they are redrawn.

#### Steps to reproduce the behaviour
Add a location to the calendar so weather can be fetched from a server
Open clock-preferences, check "show weather," and  "show temperature," these can be tested together or separately with same results

#### MATE general version
1.19 from git master or branches therof

#### Package version
locally compiled mate-panel from ev-img-background-fixes branch as of June 29, 2017  but June 7 git master (before the background work) gave the same result. Panel background type (system,color, image) made no difference, neither did gtk theme.

#### Linux Distribution
Debian Unstable with locally compiled gtk 3.22.15 (no change with 3.22.16)  and glib 2.53.3

**Comment by monsta** [comment]
I can confirm this, it happens on panel restart, but not always. Using Debian Stretch. I don't remember when it started...

**Comment by vfscanf** [comment]
This also happens with the dedicated Weather widget, and not only when the panel restarts. It can happen every time the weather applet reloads the weather information. Sometimes it fails and will only show "--". If I click on reload it fixes it.
It is likely that the bug is actually in libmateweather.

I can remember that the GNOME weather applet had the exact same problem, and it was due to the weather service not always returning information. In that case, the code didn't retry but waited a certain time before trying again, due to terms and conditions of the weather service. I think they fixed it by keeping the old information around until the weather service worked again. I'll look into this.

**Comment by lukefromdc** [comment]
Workaround for situations where there is no old information (or it is too old and should not be displayed)  could be a "waiting" icon and/or text, and a "waiting for weather service" tooltip.

**Comment by vfscanf** [comment]
I personally don't like that, because I would rather see the old information instead of no weather information at all. The problem is that these failures are often only temporary and it works immediately after. You would end up with the weather applet only showing the loading icon a lot of times, despite the fact the weather service works.
It would be best to have a defined threshold, after which the weather applet changes to the loading icon if we not get valid weather information in that timeframe. This approach is more resilient to temporary failures but also avoids showing the user outdated weather information, if the service has a longer outage.

**Comment by lukefromdc** [comment]
Good idea, show recent but not outdated information if available, and the weather service not responding or cannot yet be queried

**Comment by vfscanf** [comment]
If I look through the journal (syslog) I can see some of these messages:

>mateweather-app[883]: METAR-Daten konnten nicht geholt werden: 502 Proxy Error.

It looks like the weather provider sometimes gives an error 502. Can somebody confirm this, or maybe look through their system logs for similar errors?

**Comment by monsta** [comment]
The clock applet actually keeps showing the latest info after the network problem happens. The weather tooltip doesn't work at that time though (shows clock's general tooltip about the calendar). Also if you open the calendar, the weather icons in the locations list are missing. Of course it works that way only when there's some old info available, not when the applet just started.

I saw error 502 a few times, but recently it doesn't show up in the log while the weather still doesn't load. Looks more like a slow connection, maybe timing out, I don't know.

**Comment by Safari77** [comment]
I changed location, testing Houston. Tooltip does not appear, icons do not appear in the panel (but in the calendar page it shows the scattered clouds  icon...) 
Toggling show weather/temperature or restarting mate-panel does not make it work, either.

If I change location, the panel is too stupid to fetch new data.

I added there a debug info, it received metar info OK but doesn't wanna show it.

```(mate-panel:2144295): MateWeather-WARNING **: metar_parse [ext>KIAH 221831Z 34012G21KT 10SM SCT027 SCT250 19/13 A3005]```

test_metar
```
Returned info:
  update:   Sun Apr 22 21:31:00 2018
  sky:      Scattered clouds
  cond:     -
  temp:     19.0 °C
  dewp:     13.0 °C
  humidity: 68%
  wind:     North - Northwest / 6.2 m/s
  pressure: 1017.49 hPa
  vis:      16093m
```

Then some debugs to mate-panel.
```
2018-04-22 22:57:37.579192043 (mate-panel:2215196): MateWeather-WARNING **: _weather_info_fill info=(nil)/reqs=0 location=0x55d83786f7b0/name=Helsinki,code=EFHF prefs=0x7ffdf973e0c0
2018-04-22 22:57:37.628208090 (mate-panel:2215196): MateWeather-WARNING **: metar_start_open stationString=EFHF reqs=0
2018-04-22 22:57:37.628208650 ** (mate-panel:2215196): WARNING **: weather_info_updated 377s
2018-04-22 22:57:37.754199334 ** (mate-panel:2215196): WARNING **: weather_info_updated 536s
2018-04-22 22:57:37.754199734 (mate-panel:2215196): MateWeather-WARNING **: _weather_info_fill info=0x55d836f76680/reqs=0 location=(nil)/name=,code= prefs=0x7ffdf973dab0
2018-04-22 22:57:37.754207074 (mate-panel:2215196): MateWeather-WARNING **: metar_start_open stationString=EFHF reqs=0
2018-04-22 22:57:37.754277889 ** (mate-panel:2215196): WARNING **: weather_info_updated 538s
2018-04-22 22:57:37.754278239 (mate-panel:2215196): MateWeather-WARNING **: _weather_info_fill info=0x55d836f76680/reqs=0 location=(nil)/name=,code= prefs=0x7ffdf973dab0
2018-04-22 22:57:37.754278758 (mate-panel:2215196): MateWeather-WARNING **: metar_start_open stationString=EFHF reqs=0
2018-04-22 22:57:37.764984860 ** (mate-panel:2215196): WARNING **: weather_info_updated 670s
blah blah
2018-04-22 22:57:38.485038015 ** (mate-panel:2215196): WARNING **: weather_info_updated 1580s
```

And no weather info displayed, naturally.
set_weather_update_timeout prints ```priv->weather_timeout```.

**Comment by Safari77** [comment]
Very funny! Look:
```metar_finish p=<raw_text>KIAH 222153Z 29009KT 10SM FEW040 FEW250 22/12 A2998 RMK AO2 SLP152 T02220122</raw_text>```
metar_parse gets this string ```ext>KIAH 222153Z 29009KT 10SM FEW040 FEW250 22/12 A2998```

because you do
```p += WEATHER_LOCATION_CODE_LEN + 2;```
instead of
```p += strlen("<raw_text>");```

I found a difference why sometimes weather is not shown, for example Houston airport:
```
2018-04-23 01:39:35.743856155 (mate-panel:2252185): MateWeather-WARNING **: request_done ok=1
2018-04-23 01:39:35.743892302 (mate-panel:2252185): MateWeather-WARNING **: request_done calling cb=0x561106a5d9a0
2018-04-23 01:39:35.743902662 (mate-panel:2252185): MateWeather-WARNING **: request_done called cb=0x561106a5d9a0
```
does not show weather in panel...

Then I edit location to Vantaa (EFHK):
```
2018-04-23 01:40:17.361496893 (mate-panel:2252185): MateWeather-WARNING **: request_done ok=1
2018-04-23 01:40:17.361509302 (mate-panel:2252185): MateWeather-WARNING **: request_done calling cb=0x561107107cd0
2018-04-23 01:40:17.361524281 (mate-panel:2252185): MateWeather-WARNING **: weather_info_get_icon_name valid=1
2018-04-23 01:40:17.361784113 (mate-panel:2252185): MateWeather-WARNING **: request_done called cb=0x561107107cd0
```
I get valid METAR for Houston, but..?! weather_info_get_icon_name not called.

**Comment by Safari77** [comment]
```location_weather_updated_cb``` returns because ```clock_location_is_current(location)==false```, even though metar was parsed ok.  Maybe it could do something smarter than just returning.

**Comment by lukefromdc** [comment]
Could some of the other devs take a look at this? @raveit65 ? @monsta ?

**Comment by monsta** [comment]
This code in libgweather seems to do the same, so I guess it works after all.

**Comment by muktupavels** [comment]
I would say that it is also bug in libgweather...

https://gitlab.gnome.org/GNOME/libgweather/commit/283afc2d23355def1c1bab70a641f40cea52ba7f

`searchkey` was changed, but `+ 2` remained same... it probably should be:
`p += 10 + WEATHER_LOCATION_CODE_LEN + 1;`

also it probably should not search for `\n`, but for `</raw_text>`...

**Comment by monsta** [comment]
Ah, I see. Forgot about that fix already. Not sure if it affects parsing though, as regex probably does its job anyway. But I'll try to correct this.

**Comment by monsta** [comment]
Ok, it's in https://github.com/mate-desktop/libmateweather/pull/55. Doesn't seem to correct the main issue for me though.

**Comment by lukefromdc** [comment]
At the moment I'm not getting the issue anymore with the same weather station originally tested, but that could relate to remote reliability I suppose

**Comment by lukefromdc** [comment]
With https://github.com/mate-desktop/libmateweather/pull/55 merged, we can close this if nobody else gets this issue back. I don't normally use the weather features, so will test one more time after rebuilding but would not see this in daily use

**Comment by monsta** [comment]
No, the issue is still present. I'm getting another version of it: the icon is shown right away, but the number (temperature) is shown a few seconds later. The tooltip shows the full info though.

**Comment by lukefromdc** [comment]
OK, we have a partial fix. What I originally got was a complete refusal of any icons or numbers to show at all until the panel was restarted. Still, if the tooltip has current information it should be on the panel, so this is probably another delayed redrawing issue

**Comment by monsta** [comment]
I've picked latest libmateweather fixes to 1.18 branch and tested it in older systems with GTK+ 3.14 and 3.18. This problem doesn't happen there. I'll check another VM which also has 1.18 but GTK+ 3.22, to see if the problem is in mate-panel 1.19/1.20 or in GTK+.

**Comment by monsta** [comment]
Ok, the problem happens with 1.18 and GTK+ 3.22...

**Comment by monsta** [comment]
Now this really gets in the way of testing https://github.com/mate-desktop/mate-panel/pull/901... the initial icon appears cropped from left and right, so I have to wait until temperature appears - then the icon is redrawn in full size.

**Comment by monsta** [comment]
It wouldn't be so annoying, but we have more bugs here: currently the weather icon doesn't seem to react to panel size change and icon theme change, so I have to restart the panel after any of these changes.

**Comment by msplival** [comment]
This is still an issue... running Mate 1.20 on UbuntuMATE 18.04.

**Comment by vfscanf** [comment]
Since a few days, the weather information in the clock applet doesn't load at all. But it seems to be an issue with the weather provider, because the standalone weather applet doesn't work either.

**Comment by raveit65** [comment]
Does the issue still exists?

**Comment by vfscanf** [comment]
I've not had this problem in quite a while, so for me at least it is fixed.
