### ISSUE TITLE
[1.18] Cascading applet crashes on login when using transparent panel background

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/mate-panel#604]
#### Expected behaviour

Upon login, panel and applets should load normally

#### Actual behaviour

Upon login, a random amount of applets are crashing after receiving signal 5. (SIGTRAP) 

#### Steps to reproduce the behaviour

Unclear, this does not seem to affect everyone so it might be hardware related or config-specific.
One factor though is that this happens only with a transparent panel background.

#### MATE general version

1.18 

#### Package version

mate-panel 1.18.1 ( 1.18.1-0ubuntu2 )

#### Linux Distribution

Ubuntu MATE 17.04

#### Additional information

Originally discussed here:

https://ubuntu-mate.community/t/zesty-multiple-applet-crashes-on-login-when-using-transparent-panels/13192

At least one other user is affected by this.

I've noticed the applets on the left side of the top panel (Brisk menu, firefox launcher) seem unaffected by this: I don't remember those ever crashing.

Hardware info:

```
CPU:       Quad core Intel Celeron N3150 (-MCP-) cache: 1024 KB 
           clock speeds: max: 2080 MHz 1: 801 MHz 2: 571 MHz 3: 745 MHz
           4: 558 MHz
Graphics:  Card: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller
           Display Server: X.Org 1.19.3 drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.06hz
           GLX Renderer: Mesa DRI Intel HD Graphics 400 (Braswell)
           GLX Version: 3.0 Mesa 17.0.3
```

Configuration: Marco + Compton

Attaching .crash files and the panel layout files to this report.

[ouroumov-tweak.layout.tar.gz](https://github.com/mate-desktop/mate-panel/files/1124069/ouroumov-tweak.layout.tar.gz)
[ouroumov-tweak.panel.tar.gz](https://github.com/mate-desktop/mate-panel/files/1124068/ouroumov-tweak.panel.tar.gz)
[_usr_lib_mate-applets_mate-multiload-applet.1000.crash.tar.gz](https://github.com/mate-desktop/mate-panel/files/1124072/_usr_lib_mate-applets_mate-multiload-applet.1000.crash.tar.gz)
[_usr_lib_mate-applets_stickynotes-applet.1000.crash.tar.gz](https://github.com/mate-desktop/mate-panel/files/1124077/_usr_lib_mate-applets_stickynotes-applet.1000.crash.tar.gz)
[_usr_lib_mate-applets_trashapplet.1000.crash.tar.gz](https://github.com/mate-desktop/mate-panel/files/1124073/_usr_lib_mate-applets_trashapplet.1000.crash.tar.gz)
[_usr_lib_mate-indicator-applet_mate-indicator-applet-complete.1000.crash.tar.gz](https://github.com/mate-desktop/mate-panel/files/1124075/_usr_lib_mate-indicator-applet_mate-indicator-applet-complete.1000.crash.tar.gz)
[_usr_lib_mate-panel_clock-applet.1000.crash.tar.gz](https://github.com/mate-desktop/mate-panel/files/1124074/_usr_lib_mate-panel_clock-applet.1000.crash.tar.gz)
[_usr_lib_mate-panel_notification-area-applet.1000.crash.tar.gz](https://github.com/mate-desktop/mate-panel/files/1124076/_usr_lib_mate-panel_notification-area-applet.1000.crash.tar.gz)
[_usr_lib_mate-panel_wnck-applet.1000.crash.tar.gz](https://github.com/mate-desktop/mate-panel/files/1124078/_usr_lib_mate-panel_wnck-applet.1000.crash.tar.gz)

**Comment by monsta** [comment]
Thanks, I'll take a look at these.

**Comment by monsta** [comment]
Ok... all these applets, except for clock, crash with the same backtrace:
https://pastebin.com/XxeJhmtN

Same backtrace as I got in https://github.com/mate-desktop/mate-panel/issues/369#issuecomment-229297741... 😕 

Clock crashes differently, somewhere inside GTK+ library:
https://pastebin.com/NUAfGqCq

**Comment by lukefromdc** [comment]
Confirmed here-but only if stickynotes is on the panel. In fact, setting a transparent color background with Marco and no compositing, then adding stickynotes to the panel crashed a bunch of applets, while restarting the panel over and over again did not.

Got lots of these kind of errors in the logs, this is just one applet's worth:

ul  5 13:52:39 ubuntu wnck-applet[21276]: Failed to get pattern 14680097,45,13
Jul  5 13:52:39 ubuntu wnck-applet[21276]: Failed to get pattern 14680097,45,13
Jul  5 13:52:39 ubuntu wnck-applet[21276]: Failed to get pattern 14680097,407,13
Jul  5 13:52:39 ubuntu wnck-applet[21276]: Failed to get pattern 14680097,407,13

**Comment by epgfm** [comment]
I've checked and I can still trigger this without sticky-notes applet.

**Comment by lukefromdc** [comment]
Yeah, I got that on some subsequent tests of another issue

**Comment by epgfm** [comment]
OK, I have a theory:

I've just removed "clock" from the panel, and then done 10 consecutive logins.
During the 10 logins, there was only one time where applets crashed.
The first crash report to show up was for notification-area, subsequently all applets from the bottom panel crashed too.
1/10 is way below what I've been seeing, I don't think this is a coincidence.
My theory is as follow:

- When an applet is dynamically resized during startup, it triggers the crash.

I think the bottom panel crashes are due to the "window list" resizing because of the need to show the crash reports.

I think people with US locale don't see the crash as often because the month field is fixed size? (three letters if I'm not mistaken?)

**Comment by epgfm** [comment]
Added clock back, did 10 more tests, crash ratio 7/10.

**Comment by monsta** [comment]
What annoys me the most here is that `XGetGeometry` called with invalid argument(s) causes the crash, like`gdk_error_trap_push` was never called before it (but it was).
It's the same as it was last year (https://github.com/mate-desktop/mate-panel/issues/369#issuecomment-167115233), and I also tried removing custom error handling code (https://github.com/mate-desktop/mate-panel/pull/385), but it didn't change anything at all. :confused:

**Comment by lukefromdc** [comment]
Last time around bugs in Cairo and libwnck were suspected, though in my GTK 3.14 through 3.22 tests of other fixes, I've not found any difference in this cascading crash on alpha color panels with GTK version or libwnck version.

A usable workaround for an end user might be to make an image containing only the desired transparent color and set that as the background. Make it higher than the desired panel height as it won't scale by default. I am about to test this, if it works handling all alpha/noncomposited bg's as images might be a fix.

**Comment by lukefromdc** [comment]
The transparent image of one color set as a panel background is applet crash free in GTK 3.22

**Comment by epgfm** [comment]
@lukefromdc, my Ubuntu MATE 17.04 install still show multiple panel crashes using attached image as background picture:
![void](https://user-images.githubusercontent.com/10635269/28049530-4dab2e78-65f8-11e7-956e-6c7baa7fb4db.png)

**Comment by lukefromdc** [comment]
OK, we have inconsistant behavior between distros. You might have a different version of cairo or wnck for instance. I will try to come up with a fix that works on my system, we can then see if it works on yours. I've been playing with the code in panel-background.c trying to narrow it down and come up with a workaround.

**Comment by epgfm** [comment]
Will provide any assistance I can testing this. Do you happen to know the name of the ubuntu packages for cairo and wnck so I can provide you with the version?

**Comment by lukefromdc** [comment]
libcairo2, you should have  1.14.8-1 I have 1.14.10-1 from Debian Unstable. I seem to remember prior bugfixes in cairo that solved the previous round of applet crashes, not sure when that was though.

libwnck-3-0, libwnck-3-common you should have  3.20.1-3, I have 3.24.0.1 from Debian Unstable. I did not find differences from that package in testing other GTK versions, nor from different GTK versions all the way back to 3.14

**Comment by epgfm** [comment]
```
ouroumov@Edge:~$ apt-cache policy libcairo2 libwnck-3-0 libwnck-3-common | grep Installed
  Installed: 1.14.8-1
  Installed: 3.20.1-3
  Installed: 3.20.1-3
```

**Comment by lukefromdc** [comment]
Try https://github.com/mate-desktop/mate-panel/pull/612 which in my tests with Marco, no compositing, and a transparent background entirely stopped the crashes. It works by avoiding a cairo function that in this case seems to be buggy, using instead code copied from panel-background.c

**Comment by raveit65** [comment]
I can confirm it with f26 without compositor and stick-note was added to panel.

**Comment by monsta** [comment]
Hmm but it crashes before that code, in `mate_panel_applet_create_foreign_surface_for_display`...

**Comment by monsta** [comment]
However, it seems to work for me in Debian Testing VM, using the same old method from https://github.com/mate-desktop/mate-panel/issues/369#issuecomment-229297741. No idea why. Probably it crashed not on the first run of the function, but on subsequent ones, and at that time something was already screwed up due to wrong cairo function. I can only guess - the backtrace won't tell me. :slightly_smiling_face:

**Comment by lukefromdc** [comment]
I just found that mate_panel_applet_create_foreign_surface_for_display.. may be responsible for https://github.com/mate-desktop/mate-panel/issues/468  which is the redrawing mess in GTK 3.22 with in-process applets. Looking for a way to fix or get around this.

**Comment by monsta** [comment]
Historical fact: both backtraces (in GDK and in mate-panel) are older than we could think: https://github.com/mate-desktop/mate-panel/issues/197. 🙂
