### ISSUE TITLE
[clock applet] The setting of the home location does not persist in a new session.

### ISSUE THREAD

**Issue by GarikTester** [mate-desktop/mate-panel#609]
#### Expected behaviour
Once set, my setting of the home location should persist after reboot, without manual intervention.

#### Actual behaviour
After every boot, I must set it manually, using my root password. It causes weather forecast not working until I do this.

#### Steps to reproduce the behaviour
Set your home location using clock applet preferences (require root password) and reboot.

#### MATE general version
1.18

#### Package version
mate-panel-1.18.3
libmateweather-1.18.1

#### Linux Distribution
Slackware64 14.2

**Comment by GarikTester** [comment]
Looks like this issue still persists since 2012). 
https://github.com/mate-desktop/mate-panel/issues/25#issuecomment-5916062

I remember Gnome 2 hadn't that.

**Comment by raveit65** [comment]
I can't reproduce this with Mate-1.18 on fedora 26.
I switched between my home (berlin/europe) and Kaumalapau (Honululu) and the home location is set to the new location after reboot.
The only issue i see is that there is a delay of 1 min or so, before you see the new time in panel.
And the system clock change only after a reboot here.
hwclock --test   shows the system time. 
Did you filed out a report against your Distro?
For getting specific help and to be sure that it isn't distro related.......
Sorry, i do not use slackware or gentoo.

**Comment by GarikTester** [comment]
Setting the home location requires elevated rights (root password). When I push the "Set" button, I see an invitation to enter my root password (mate-polkit handle this, I think). When finished, I see weather forecast appeared. There is also an icon in notification area, which says "reset all elevated privileges" or so, which disappears after two-three minutes. Location is set and I see weather until reboot, after reboot the elevated privileges is reset, and I must set the location again.

How can it be distro-specific, if Slackware ships vanilla packages only? Maybe because of lack of systemd?

**Comment by willysr** [comment]
I can confirm this bug on Slackware 14.2.

Although i didn't see the "reset all elevated priviledges" icon, but the home icon is no longer set upon reboot (the location is still there though).

**Comment by willysr** [comment]
@GarikTester : can you try the latest 1.19.1?
i tried to set home location today and rebooted on my current machine with latest 1.19.1 (development snapshot) and the home icon is still there after reboot, including the weather as well.

**Comment by GarikTester** [comment]
@willysr 
Very good news! Very annoying bug, but I can't try dev snapshots for now, because this Slack is my only home desktop and I like its stability. I will wait for 1.20 release. Otherwise, thanks for your work for Slack.

**Comment by willysr** [comment]
My experience with Development snapshot of MATE never broke my system since it's an incremental changes. 

Once you can confirm that it gets fixed in 1.19, you can simply reinstall or rebuilt 1.18 :)

**Comment by monsta** [comment]
@willysr: maybe use git bisect to find the commit that fixed it?

Also 1.18.5 has been released, maybe try it?

**Comment by GarikTester** [comment]
Fixed in 1.19.3, don't know about earlier versions.
