### ISSUE TITLE
Icon spacing too wide

### ISSUE THREAD

**Issue by pepa65** [mate-desktop/mate-panel#614]
On Ubuntu 16.04 I upgraded to mate-panel 1.18.3-0ubuntu1~16.04.york0 from 1.16 and expected the icon spacing to remain the same. They don't fit on the bar anymore.

Is there a way to adjust the spacing?

**Comment by lukefromdc** [comment]
Exactly one way-to move them by hand. Right click and select "move" then drag them with the mouse where you want them. Some applets and the launchers you can left click and hold, then drag them where you want them as well.

**Comment by pepa65** [comment]
Well I know about that, but they no longer all fit, but they used to in 1.16. I am looking for a way to decrease the padding, like adjusting the css (is that still available?).

**Comment by pepa65** [comment]
I've had to downgrade, because my start menu icon on the left was obscured by 4 other icons bunched on top of it (so the total width of each icon space --the padding-- increased). The general problem with mate-panel is, there is no way to access the panel settings, otherwise I could have made the panel (and thereby the icons) narrower.

I don't know whether it was the theme or what, but it would be good to have a general way to adjust spacing parameters.

**Comment by raveit65** [comment]
Honestly, we didn't increased the padding. ;-)
With an update from 1.16 from 16.04 to 1.18 from ppa you  switched from using gtk+-2 to gtk+-3.
Maybe there is a different....
But , you can try to reduce the icon-size which will increase the space on the panel.
```
[rave@mother ~]$ gsettings get org.mate.panel.menubar icon-size
'default'
[rave@mother ~]$ gsettings set org.mate.panel.menubar icon-size '16px'
[rave@mother ~]$ killall mate-panel
```
Last command restarts the panel.
Maybe you like to play with that value too?
```
[rave@mother ~]$ gsettings get org.mate.panel.menubar item-icon-size
'default'
```
Imo, the default value is 22px for both if i remember correctly.
Any way, those settings aren't really new, we have them since 1.13.1
https://github.com/mate-desktop/mate-panel/commits/1.14?after=2ead04a038fe540bf384d11d77718a8271acda13+50

**Comment by kn00tcn** [comment]
i would expect gtk3 to be different, would also expect PPAs to not exactly be ready/approved for use (compared to ubuntu 17 or 18)

can you make before & after screenshots?

**Comment by pepa65** [comment]
I have 25 icons on my 64 pixel panel (I think I could fit 2 more), but after upgrading to 1.18 I had to remove 5 icons and have no room left.
Because there was also a rapid flickering (tooltip?) artifact (that I used to get years ago as well), I decided to downgrade until I know how to space the icons closer together. I know there is a tweak on the Ubuntu fallback panel that used to do this, so there must be something that can be done about it -- hopefully without needing to recompile..!

**Comment by raveit65** [comment]
Is there a reason why you don't try out my hints?  :-)
And why not reducing the size of the panel a bit, this will make the icons smaller?

**Comment by pepa65** [comment]
Of course I can reduce the panel height and the icons will scale down, making more room. I'm just reporting that the padding has increased, and asking if there is a way to adjust that. I can also remove a number of icons. But unless this is an upstream setting --and it might be-- then there must be a way to adjust the padding.
