### ISSUE TITLE
Applications drop-down does not work for any user (new or existing) v1.82

### ISSUE THREAD

**Issue by NeedMopowa** [mate-desktop/mate-panel#615]
#### Expected behaviour
Applications drop-down should show installed applications

#### Actual behaviour
Applications drop-down gets highlighted to confirm you are selecting it and has a line but does not display any applications.

The only way I can get it to somewhat work is to run "sudo mate-panel" which allow the drop-down to be displayed but the following errors are generated and the terminal window is in a wait state.

**Message: Could not connect to session manager: Could not get owner of name 'org.mate.SessionManager': no such name

** (mate-panel:6777) WARNING **: Could not connect to session manager: Could not get owner of name 'org.mate.SessionManager': no such name

#### Steps to reproduce the behaviour
For me no matter what I do (remove, purge, reinstall) this behavior persists except workaround above.

#### MATE general version
1.82

#### Package version
1.8.1+dfsg1-3-trusty1

#### Linux Distribution
Ubuntu  14.04.5 LTS
14.04
trusty

**Comment by lukefromdc** [comment]
This appears to be a permissions issue, possibly with how one or more files in mate-menus got installed. If one of those files can only be read by root, you would get exactly the symptoms described: menus empty unless the panel run as root.

Check the permissions on /etc/xdg/menus/mate-applications.menu , which is the file that fills the application menu with entries.  It should be owned by root, writable only by root, but readable by all.

If this is not the problem, try purging and reinstalling mate-menus, as a permissions problem with one of the library files installed by it could also do this.

**Comment by NeedMopowa** [comment]
Hey Luke,
Thank you for responding. Yes it does look like a permissions issue. Sorry but I am still a Linux noob so not exactly sure what I need to do. I ran:
ls -l /etc/xdg/menus/mate-applications.menu 
and recieve: 
-rw-r--r-- 1 root root 3891 Jan 20  2015 /etc/xdg/menus/mate-applications.menu
but not really sure where to go from here.
I also tried to purge all of Mate and reinstalling but the problem persisted. Any additional guidance is greatly appreciated.

**Comment by lukefromdc** [comment]
Out of ideas and on my way out the door at the moment, but check a live CD/USB setup of the same version of Ubuntu MATE. I can confirm that I do not have and have never seen this problem in any of my Debian Unstable or the Ubuntu systems I used before I converted to Debian

**Comment by NeedMopowa** [comment]
Do the permissions I posted above look correct?

**Comment by lukefromdc** [comment]
Those should work,  check also the permissions on all other files installed by mate-menus. Never seen this happen on one of my own machines or heard of it before.  

Try creating a new user on your machine and try MATE in that user's session. If it works you've got a problem in the hidden  . (configuration) directores in your home directory. Put  all of them in a BAK directory (backup) directory and configure your desktop anew if that other user's session works. If not, try another install to   another hard drive, partition, or just a USB stick. I would highly recommend making a new install onto it and seeing what happens. If it works you could have a corrupted file somewhere in your root filesystem.

**Comment by flexiondotorg** [comment]
Ubuntu MATE 14.04 was an unofficial release and it is no longer supported. Sorry, but any patches to fix this issue will not be back ported to the Trusty PPA.
