### ISSUE TITLE
Window list — width of buttons

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/mate-panel#616]
Is it possible to change width of buttons of windows list in MATE panel via CSS style or dconf setting? It not, this would be useful feature. 
Currently buttons of windows list are small and small part of window title is visible.

**Comment by lukefromdc** [comment]
The #tasklist-button selector controls the window list button styling in the GTK3 theme CSS. You can set the "min-width" and "min-height" css properties, but this would cause problems if you have more buttons open than the panel has space for.

If you get tiny window list buttons with one or two windows open, make sure you don't have a spacer or something else limiting the available space. Just to be sure, create a new panel (it has nothing on it at first), move the window list to it(drag and drop), and see what you get.

**Comment by TomaszGasior** [comment]
Unfortunately, it does not work. When I set this stylesheet for `wnck-applet` by GTK inspector
`#tasklist-button { min-width: 500px; border: 1px solid red; }`
window list buttons have border but size is not changed. Also when I created new panel with window list applet, size was the same.

OS: Arch Linux. Packages: marco 1.18.1-1; mate-desktop 1.18.0-1; mate-panel 1.18.4-1.

**Comment by muesli4** [comment]
This is a feature that should be implemented in **libwnck** first and then **mate-panel** should pick up support. Since some people want to keep compatibility with older versions this could take a long time.

**Comment by TomaszGasior** [comment]
xfce4-panel also uses libwnck and its window list has bigger buttons. How they did it?

**Comment by rilian-la-te** [comment]
Xfce rewrote entire tasklist. You can take it from Xfce 4.13 or vala-panel and port it to MATE.
But MATE AFAIK uses libwnck's builtin tasklist widget.

**Comment by muesli4** [comment]
@TomaszGasior I've found something that might help you:
https://github.com/mate-desktop/mate-panel/blob/5b1061937c746c70a23d24e9a038465452b18bf8/applets/wncklet/window-list.c#L389

@rilian-la-te I don't think that is a good idea at all. You have to maintain a lot of copied code and once it fails then nobody is around that has a clue.

**Comment by seflerZ** [comment]
Any updates? The width is too small and not user friendly.
