### ISSUE TITLE
System monitor does adhere to large "system monitor width" settings

### ISSUE THREAD

**Issue by martinus** [mate-desktop/mate-panel#623]
#### Expected behaviour
I have changed the "System monitor width" to 956 pixels on a separate panel. That way the whole panel is used for two monitored resources. The panel should stay at that size.

#### Actual behaviour

When I restart (or the panel reloads, e.g. by changing the panel's size from 24 pixel to 25 pixels), the System monitor shrinks to the width as if "system monitor width" were set to 400.

#### Steps to reproduce the behaviour

1. Create a new panel, on top
1. Orientation: top
1. Right click panel > Add to panel > System Monitor
1. Right click newly created System Monitor > Preferences
1. `[x]` Processor, `[x]` Memory
1. System monitor width: 956
1. click close
1. right click panel > properties
1. Click `[+]` or `[-]` for pixel size

#### MATE general version

* MATE: 1.18.0
* The MATE Panel: 1.18.3

#### Package version

* mate-panel/sonya,now 1.18.3-2+sonya
* mate-panel-common/sonya,sonya,now 1.18.3-2+sonya all

#### Linux Distribution

Release Linux Mint 18.2 Sonya 64-bit

**Comment by monsta** [comment]
This applet is called "multiload" and is a part of [mate-applets](https://github.com/mate-desktop/mate-applets). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.
