### ISSUE TITLE
Launcher icons on panel flicker instead of displaying tool tip when panel is in 'top' orientation

### ISSUE THREAD

**Issue by QBFreak** [mate-desktop/mate-panel#625]
#### Expected behaviour
Mouse pausing over launcher on panel displays tool tip.

#### Actual behaviour
Mouse pausing over any one of most icons on the panel causing icon to flicker, no tool tip displayed. Moving the mouse to the top edge of the screen while over the icon displays the the tool tip as expected. It is also possible in rare circumstances for the tool tip to display properly on the first try. I have been unable to pin down the details.

#### Steps to reproduce the behaviour
Change panel **Orientation** to `Top` in **Panel Properties**, stop mouse over one of the launcher icons located on panel next to menu. On my system this affects *most* of the icons, but not all.

**My panel launcher icons:**

| App | Source | Affected |
| --- | --- | --- |
| Htop | Added | Flickers |
| Chromium | Added | Flickers |
| Show Desktop | Stock | Flickers |
| Caja File Browser | Stock | Flickers |
| MATE Terminal | Added | No problems |
| Terminology Terminal | Added | No problems |

#### MATE general version
MATE Desktop Environment 1.18.0

#### Package version
The MATE Panel 1.18.3

#### Linux Distribution
```bash
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial
```

**Comment by lukefromdc** [comment]
I can't duplicate this on Debian Unstable with either 1.19 from git master or my dev-inprocess-bgfix branch, and have never seen this happen.  Didn't see anything like this in the 1.18 development cycle either. While my main desktop has the panel on the bottom, I always test adding and removing things from a temporary panel on top or left(if orientation is under test) so as not to get anything that breaks in development stuck in my main panel.

I have a different set of launchers than you and its a long list, including several custom ones. None of them can be made to flicker. Wonder if this is a race condition somewhere?

**Comment by QBFreak** [comment]
I should also mention that I recently did an in-place upgrade from Linux Mint 18.1. This issue was originally reported by another Mint user (`banavara`) over in #mate on Freenode, but I don't know what his install path looked like (fresh install vs upgrade).

**Comment by smkent** [comment]
I filed #677 earlier which seems to be the same issue as this. It's reproducible on the Linux Mint 18.2 MATE live CD.

**Comment by lukefromdc** [comment]
I was again unable to reproduce this with the panel temporarily moved to the top (normally on the bottom). Using Debian Unstable, GTK as of today is 3.22.25.

**Comment by smkent** [comment]
Does it reproduce for you with the Linux Mint live CD? I just used VirtualBox, all that's needed to reproduce is to boot up the iso and move the default panel to the top so it should be fairly easy.

**Comment by lukefromdc** [comment]
I do not have a recent version of that around and do not have the bandwidth to download it anytime soon. Most recent Ubuntu MATE I have is 16.10 and never seen it there but not done a lot with it. Also no virtual machine setups or experience at all-everything I do is bare metal. Wonder if VM use is a contributing factor to this bug, as it has been before.

**Comment by lukefromdc** [comment]
Mobile only, no landline. No way in hell I can download any distro's installer this week.  I will leave this for the other MATE devs, thankfully this is a team effort and not a one person project.

**Comment by lukefromdc** [comment]
@monsta , @raveit65 , can someone help with this? I can't duplicate this and do not have the bandwidth to download an installer for the only reliable test indicated here.

**Comment by raveit65** [comment]
I am using fedora and i can't reproduce it with a running MATE-Compiz livecd, or an fedora installation in VM or on bare metal.
In our standard installation we have 4 launchers at top panel.
Sadly, reporter didn't file out a report against linuxmint distro first, so linuxmint maintainers aren't involved to check/confirm if it is a problem with their livecd or distro.
It has a reason that we ask for a downstream report in our template.
So, we have to wait for this.....

**Comment by QBFreak** [comment]
I apologise if I should have opened another ticket elsewhere first. If there's good doc explaining this I missed it.

As for the issue itself, I'm presently hospitalized and unable to do things like try the latest LiveCD.

**Comment by monsta** [comment]
I'm running Mint 18.2 as my home system, but all MATE stuff is built from git master. Well, it's not reproducible so far. I'll check in 18.2 VM as well.

**Comment by monsta** [comment]
Weird... I can reproduce it (not always) with the default launchers, Caja and mate-terminal. But if I add the same launchers somewhere on the same top panel, I can't reproduce it anymore.

I built and installed from git master too, but the behavior is the same.

**Comment by QBFreak** [comment]
IIRC (and sadly I lack the logs to confirm this), the reason I opened this for mate-panel and not under Mint was that it was originally brought to my attention by an IRC user who was _not_ using Mint. He only provided enough detail that I was able to reproduce it on my own machine, which is when I opened this issue. Since I'm doing this from memory, which is notoriously unreliable, I can't even say which distro he was using.

What do I need to do next? File this with linuxmint and see if we can reproduce it there? Provide the link to that issue here? I'm new to all this.

**Comment by monsta** [comment]
@clefebvre: maybe you could help us with this?

**Comment by lukefromdc** [comment]
@QBFreak , is this limited to panel launchers installed by default and not affecting user-set launchers?  If so it may explain why I never see this: With mate-panel from git master on Debian, if I reset the panels I have no default launchers at all, so all of mine are user-set. Also that would give a workaround for use until this is fixed: delete the launchers, then add them back

**Comment by monsta** [comment]
It also might be limited to GTK+ 3.18 (the one in Ubuntu 16.04/Mint 18.x), as I can't reproduce it in later versions of Ubuntu which have GTK+ 3.22. But it's just my guess.

**Comment by monsta** [comment]
I just created a new panel on the top and placed Caja and mate-terminal launchers on its left part. Well, the bug is reproducible. If I move the launchers to the middle or to the right side, it's not reproducible.

**Comment by lukefromdc** [comment]
With GTK 3.22.25, I just tested a new panel on top, with just caja and mate-terminal launchers in it. Each of them, when hovered over, flickered one time very faintly and then the tooltip appeared. With the bottom panel launchers I normally use, hovering over them brings up the tooltip without that single flicker.

**Comment by QBFreak** [comment]
I did some playing around with launcher positioning today and learned something very interesting: it's dependent on the width of the tool tip and how close it is to the left edge of the screen (but sometimes other stuff). If there isn't room to center the tool tip the icon flickers.

I built a new panel duplicating my main taskbar and using the launcher for Atom (it has a huge tool tip) tested as stated above. It seemed to treat the menu, launchers, and separator as the edge of the screen as stated above for not displaying/flickering icon. Moving it away would display the tool tip normally.

Unfortunately this doesn't seem to happen 100% of the time. Half way through testing the symptom switched to the tool tip failing to display, no flicker at all. Except occasionally the tool tip would display. This sounds like some ugly corner case somewhere.

What can I do to keep this moving forward? Obviously it's not anything critical but I'd like to help if I can. Should I start trying other Live CDs to find more than one distro affected? Should I mail the aforementioned Live CD where it was reproduced to @lukefromdc ? I don't even know where to start to go from git to compiled and testing, and I don't know if I have the spoons to get it sorted out. Is there some doc that would get me started?

**Comment by clefebvre** [comment]
@monsta I can reproduce it in 18.3 BETA.

**Comment by clefebvre** [comment]
It's a weird bug monsta. I'd suggest to test reverts on commits affecting button/launcher, or failing that a bissect... there's only a couple of commits on mate-panel which are recent so it should be easy to find where the issue starts.

**Comment by clefebvre** [comment]
It's reproducible in 18.2 also (mate-panel 1.18.3-2).

If you place the cursor high enough, the tooltip is always visible. Ideally it should show whenever the top of the cursor is on the launcher... but it shows when the middle of the cursor is on top.. very weird :)

**Comment by clefebvre** [comment]
I can't reproduce it with 18.1... mate-panel 1.16... but that's compiled in GTK2.

**Comment by nikamario** [comment]
Hi, i have install linux mint mate 18.3 Sylvia yesterday and i have this problem. Can i solve this problem ? Thanks guys

**Comment by lukefromdc** [comment]
With mate-panel 1.21 from git master I am not seeing this even with the panel on the top. I wonder if this relates to interaction with the window manager, as in https://github.com/mate-desktop/mate-panel/issues/897#issuecomment-448633175?

I just tested this with compiz-reloaded (from my dev-focus-WIP branch), with marco with composting enabled, and marco with composting disabled and could not duplicate it with the panel on the top. I never see it with the panel on the bottom.

Might this be hardware (as in speed of hardware) dependent? I have an AMD bulldozer 8-"core" (actually hyperthreaded big 4) proc, and if I stare closely at the icon I can see a barely perceptable flicker of the icon itself as the tooltip comes up. Rendering of the tooltip window is perfect right from the start here.

**Comment by Tehrasha** [comment]
Upgrading to mate-panel 1.21 did not solve the problem. 
Switching the window manager to **Marco (no compositor)** did.

**Comment by CreativeDuo-FR** [comment]
Thanks @Tehrasha for the tip about switching window managers (Mate-Tweak -> Windows -> Window Manager). When I am using Marco with the compositor I have the tooltip flickering behavior as described above. When I use Marco without the compositor, or Compiz I have no tooltip flickering. This is all with mate-panel 1.20.1 under Ubuntu 18.04.3. Looks like this is isolated to Marco with compositor.

**Comment by raveit65** [comment]
Does the issue still exists?

**Comment by QBFreak** [comment]
This is no longer an issue on Mate Panel 1.26.2.

Do I need to close this, or should someone else?

**Comment by raveit65** [comment]
Why asking....do it :-)
