### ISSUE TITLE
Advanced menu icon disappears with vertical panel

### ISSUE THREAD

**Issue by Eneen** [mate-desktop/mate-panel#626]
![peek 2017-07-24 17-10](https://user-images.githubusercontent.com/25537418/28530686-f4a66e62-7094-11e7-8e13-04d5d0948785.gif)

#### Expected behaviour
Advanced Menu button should be in place

#### Actual behaviour
There is no Advanced Menu button

#### Steps to reproduce the behaviour
Configure simple vertical panel with advanced menu. Save it. Then change location to left and save again.

#### MATE general version
1.18

#### Linux Distribution
Ubuntu Mate 17.04

**Comment by flexiondotorg** [comment]
This bug should have been raised against. [mate-menu](https://github.com/ubuntu-mate/mate-menu). 

But no need, because the bug is already fixed there and in Ubuntu MATE 17.10 daily 😀
