### ISSUE TITLE
Add a clear seperation between the week numbers and the dates in the clock applet

### ISSUE THREAD

**Issue by AXDOOMER** [mate-desktop/mate-panel#628]
#### Expected behaviour
Have a vertical line between the week numbers and the dates in the clock applet. Do something so that there can't be confusion between the week numbers and the dates. It may seem evident that both are different, but it can be weird to a new user... or somebody like me that doesn't sleep very much and takes a quick look at the calendar and sees that tomorrow is the 31th and goes crazy for 5 minutes. 

I would expect a demarcation between the two, something like this:
![screenshot at 2017-07-29 01-20-47 2](https://user-images.githubusercontent.com/6194072/28742442-41599830-73fe-11e7-9ffe-f1ae1d255c9d.png)

#### Actual behaviour
![screenshot at 2017-07-29 01-20-47](https://user-images.githubusercontent.com/6194072/28742431-f4a682aa-73fd-11e7-9362-aff96ad81e8a.png)

#### Steps to reproduce the behaviour
Open the applet to see the calendar. 

#### MATE general version or package version
1.16.2

#### Linux Distribution
Debian 9

**Comment by lukefromdc** [comment]
Not sure if this is even possible without a patch to the underlying GtkCalendar widget. It is because of exactly this problem that support for turning week numbers on and off was added to mate-panel some time back.  Open the clock preferences dialog, and you have an option to turn week numbers on or off, on is default.

**Comment by AXDOOMER** [comment]
>  Open the clock preferences dialog, and you have an option to turn week numbers on or off, on is default.

Thanks! That's what I needed. Now that I know this, it isn't really important for me that a separation would be added anymore.

**Comment by raveit65** [comment]
@AXDOOMER 
Which gtk+ theme are you using?
The MATE default from us (upstream) is Menta (BlueMenta) theme and should looks like this.
![clock-menta](https://user-images.githubusercontent.com/961604/28743210-8f6f52ee-7444-11e7-8864-6a5397339fa0.png)
![clock-bluementa](https://user-images.githubusercontent.com/961604/28743214-9811565e-7444-11e7-93c1-233216213eec.png)
Well, this is with mate-panel-1.19.x from master but i never noticed something in the old days with 1.16.x in fedora ;-)
Currently Fedora use actual and supported m-p-1.18 version, so i can't reproduce this with our themes and mate-panel-1.16.x any more  ;-)
I guess something like this is missing in your theme.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/gtk-widgets.css#L5068
```
calendar.highlight {
	background-color: @theme_selected_bg_color;
	color: @theme_selected_fg_color;
	border-radius: 0px;
	padding: 0px;
	border-width: 0px;
}
``'

**Comment by raveit65** [comment]
I suggest to file out a report against you theme in your distro.
It has a reason that we offer a template for filing out reports with
```
#### Link to downstream report of your Distribution
```

**Comment by lukefromdc** [comment]
It's worth keeping in mind that GtkCalendar is not the easiest widget to work out by experiment what responsds to what selector. Nothing inside it is displayed by GtkInspector, in which the innermost node is simply "calendar"

**Comment by AXDOOMER** [comment]
My theme is made from a mix of other themes. The controls that I selected are from the Greybird theme. 
```
axdoomer@debian:/usr/share/themes/Greybird/gtk-3.0$ ls
apps                 _gnome-apps.scss         gtk.gresource.xml
assets               gtk-contained.css        _lightdm-gtk-greeter.scss
_colors-public.scss  gtk-contained-dark.css   parse-sass.sh
_colors.scss         gtk-contained-dark.scss  README
_common.scss         gtk-contained.scss       settings.ini
_drawing.scss        gtk.css                  _unity.scss
Gemfile              gtk.gresource            _xfce.scss
```
There's no `gtk-widgets.css`.

I checked other themes and the days and week numbers appears in different colors, so it's clearly a Greybird bug. Since Greybird is not part of MATE, I'll be reporting this bug to the maintainers of this package. Thank you all.

**Comment by jbicha** [comment]
@AXDOOMER upstream for Greybird is https://github.com/shimmerproject/Greybird/issues

**Comment by AXDOOMER** [comment]
@jbicha Should I report it there too? I don't want to spam everyone with bug reports.

**Comment by jbicha** [comment]
@AXDOOMER Yes, that's the most likely place for it to be fixed :smile:

**Comment by AXDOOMER** [comment]
Ok then. Thanks!

**Comment by raveit65** [comment]
@AXDOOMER 
> @jbicha Should I report it there too? I don't want to spam everyone with bug reports. 

In that case yes,
But first address should  be always downstream (your distro= debian), for giving your distro MATE maintainer a chance to filter out if it is a distro issue or direct you to the right upstream.
Well, that way i know from fedora user/people which post mostly a issue first to my address ;-) before filing out an issue to a wrong upstream address.
I like to help you but we are a small team and a lot of ppl reporting issues.
So, a quick test how it works with another theme had been done at debian bug-reporting system and not here.
Mostly issues are not so easy like this one, in result we want to know about an existing/posted downstream report first.
;-)

Thank you

**Comment by jbicha** [comment]
@AXDOOMER Please report this issue to the Greybird developers as I originally suggested. Debian isn't actively developing the theme so this issue is unlikely to be fixed by Debian. (I am one of the Debian maintainers for this package.)
