### ISSUE TITLE
Higher CPU usage when Qt apps with tray icons are loaded

### ISSUE THREAD

**Issue by kajzersoze** [mate-desktop/mate-panel#629]
#### Expected behaviour
No higher CPU usage

#### Actual behaviour
Higher CPU usage

#### Steps to reproduce the behaviour
Just load any Qt app which has tray icon (I tried KeePassX and MEGASync) and you will see around 10% higher cpu usage per core, those apps are doing nothing, just sitting idle, the moment you exit from them cpu usage goes back to normal. This just happens with Qt apps, I don't have more of them but I guess it would be the same as with those two mentioned, I have one more actually (VirtualBox) but it doesn't have tray icon so the issue doesn't happen.

#### MATE general version
1.18

#### Package version
1.18.2

#### Linux Distribution
Gentoo

**Comment by kajzersoze** [comment]
Found one issue here: #506 , could be related, in there I found this code :

```
#include <QtGui>
#include <QApplication>
#include <QSystemTrayIcon>

int main(int argc, char **argv)
{
  QApplication app(argc, argv);
  
  if (! QSystemTrayIcon::isSystemTrayAvailable()) {
    return 1;
  }
  
  // or whichever image you like
  QIcon icon("/usr/share/pixmaps/qtconfig-qt4.png");
  QSystemTrayIcon trayicon(icon);
  trayicon.show();
  
  return app.exec();
}
```
...compiling and running this produces the same problem, so it's not something related to apps in question.

**Comment by sc0w** [comment]
I have installed KeePassX, configured to show the system tray icon when minimized

The cpu in mate-panel is normal, 0%

I noticed one process named **Kworker** with high cpu while running keepassx in the systray , this is the guilty,  I think

**Comment by lukefromdc** [comment]
Kworker sounds like a kernel thread

**Comment by monsta** [comment]
Does `enable-sni-support` setting from `org.mate.panel` schema affect this in any way?

**Comment by monsta** [comment]
While testing the fix for https://github.com/mate-desktop/mate-panel/issues/686, I used Calibre, which is a Qt 5 app. I haven't seen any higher CPU usage with it.

**Comment by monsta** [comment]
@kajzersoze: can you test Qt 5 apps as well?

**Comment by kajzersoze** [comment]
I'm not using Mate anymore so I can't test anything.
Maybe it was qt4 only maybe not, it was long time ago, can't remember I'm afraid.
I guess I can close this, it was probably just me, due to whatever reason.

**Comment by monsta** [comment]
No problem, we can reopen it if someone else encounters the same problem.
