### ISSUE TITLE
Calendar displays with odd column

### ISSUE THREAD

**Issue by spvkgn** [mate-desktop/mate-panel#630]
#### Expected behaviour
Calendar should display seven columns.

#### Actual behaviour
Calendar displays with odd column, left-most.

#### Steps to reproduce the behaviour
![mate-calendar](https://user-images.githubusercontent.com/4147135/28751717-6bb323be-7528-11e7-9a77-406ef2262ed0.png)

#### MATE general version
1.18.0

#### Package version
1.18.4

#### Linux Distribution
Ubuntu

**Comment by flexiondotorg** [comment]
That extra column is the week number. It is intended to be there.

**Comment by lukefromdc** [comment]
You can turn the week numbers on and off in the clock preferences. If you uncheck "show week numbers in calendar" the week numbers column is not displayed. This is useful for themes (like mine) that don't use a colored header or otherwise distinguish the week numbers column.
