### ISSUE TITLE
(Feature Request) Ability to change font colour of Mate-Panel text

### ISSUE THREAD

**Issue by Tea-Fox** [mate-desktop/mate-panel#638]
Hello,

big fan of the mate desktop, so I hope this request is in the right spot.

I would like to request a easy to use GUI function to change the font colour (maybe even the font itself) that is being displayed in the panel (like the colour of text like "Applications, Places, System" for example).

I always wanted such a easy to use feature since switching themes doesn't always change the font colour and you might end up with dark text on a dark panel or the other way around. So a simple and quick to use GUI setting in the panel's preferences window would be really handy.

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-panel/issues/278
