### ISSUE TITLE
Panel autohide + transparency

### ISSUE THREAD

**Issue by famfop** [mate-desktop/mate-panel#643]
#### Expected behaviour
Take background from "highest" window covered by panel.
Argument: When I hover the panel it goes *on top* of window 'alpha'. Now, why should the background taken be the one from beneath?

#### Actual behaviour
Take background from desktop background covered by panel.

#### Steps to reproduce the behaviour
Make a new panel, set transparency 100% (fully transparent) and activate autohide.

#### MATE general version
MATE 1.12.1

#### Package version
Don't know how to find that one out. I basically just took the Ubuntu-MATE 16.04 iso.

#### Linux Distribution
Ubuntu Release 16.04.3 LTS (Xenial Xerus) 64-bit

#### Link to downstream report of your Distribution
What is meant by this step? Is it even necessary?

**Comment by lukefromdc** [comment]
If you are using a non-compositing window manager such as Marco without compositing turned on? With compiz if I use a transparent panel and autohide it appears over the full desktop and all window over it. Without compositing this does not work. 

When compositing is not used, what is called pseudotransparency is used as a transparent (alpha) value renders black for a toplevel window on a noncompositing window manager. In pseudotransparency the relevant image of the desktop is copied into the panel and the panel background drawn over it within the process using cairo. This cannot "see" other windows.

GNOME has actually removed support for pseudotranaparency outright, meaning a current gnome-panel with a transparent background on a noncompositing WM shows the default desktop color underneath, not the desktop image background. We are not in the habit of removing features so we still support the noncompositing case but this still has the same limits it has always had.

**Comment by famfop** [comment]
Okay, if it's a feature this may be closed (even though in my opinion this results in miss-functioning at this specific point?!). Could you still tell me, before closing, how I can modify Marco's setting to use/not use compositing? Thanks!

**Comment by lukefromdc** [comment]
Two ways: In dconf-editor open org>mate>marco>general and check the "compositing manager" box, or in mate-control-center "windows" there will be a setting for enabling compositing there.

**Comment by monsta** [comment]
I'm not sure if the effect could be achieved even with the compositing, because the reporter uses GTK+2 build of MATE. Ubuntu 16.04 has MATE 1.12 built with GTK+2.

**Comment by famfop** [comment]
Actually the proposed method didn't work and I found this small "discussion" on the same(?) topic [here](https://ubuntu-mate.community/t/how-to-apply-real-transparency-on-the-panel/10863/10). So as far as I understand I cannot get true transparency as I have an "old" ATI Radeon HD5470 (512MB). (Actually I could get the true transparency with xfce4.)

**Comment by lukefromdc** [comment]
True transparency just requires a composting window manager. Marco can do this on the CPU quite independently of the GPU. Only GPU based compositors like compiz require any particular GPU. 

For that matter the ATI Radeon HD5470 is a rather modern part (I have nothing actually newer), supported by the good r600 driver, DRI2, et all. More than enough for compiz, hell gnome-shell and Cinnamon can run on the much older r500 parts and anything supporting OpenGL 2.0. They can also run in LLVMpipe when that does not work, though that is beyond heavy. Compiz can run with OpenGL 1.4 or at least use to.   Marco with compositing enabled does its work on the CPU only, with no dependency on OpenGL or the GPU at all.

**Comment by raveit65** [comment]
> MATE general version

>MATE 1.12.1
>Package version

>Don't know how to find that one out. I basically just took the Ubuntu-MATE 16.04 iso.
>Linux Distribution

>Ubuntu Release 16.04.3 LTS (Xenial Xerus) 64-bit

Again, 16.04 witth MATE 1.12.1 use gtk2 for compiling MATE.
You need minimum ubuntu 16.10 + using compositor with marco, for getting real transparency with mate-panel.
This is complete independent from you video driver.

I hope this makes it clearer.
