### ISSUE TITLE
removing or moving some applets is horrible

### ISSUE THREAD

**Issue by sixsixfive** [mate-desktop/mate-panel#644]
Its really annoying to remove or move some or empty applets since there is often just a 1px wide handle, maybe add an extra pane to the panel-settings notebook like xfce did to avoid this:

![screenshot at 2017-08-13 18-47-39](https://user-images.githubusercontent.com/3780774/29251627-746447d2-8058-11e7-91e4-ce844353d5eb.png)

**Comment by raveit65** [comment]
please use template.
Try again to file out a report.

**Comment by raveit65** [comment]
@flexiondotorg
Sorry, i don't spend my time on issues without template and infos.
Feel free to work on it for yourself :-)

**Comment by sixsixfive** [comment]
wow srsly? what an *-hole. good luck with him.
