### ISSUE TITLE
Missing icon causes shortcut to disappear in mate-panel

### ISSUE THREAD

**Issue by smikkelsendk** [mate-desktop/mate-panel#646]
#### Expected behaviour
When removing program/icon, the shortcut should have a placeholder icon (broken shortcut icon)

#### Actual behaviour
The shortcut disappears entirely until the program is reinstalled and mate-panel is restarted

#### Steps to reproduce the behaviour
1. Install program (ie audacious)
2. create shortcut in panel
3. remove audacious 
(now you can see the shortcut is broken in the panel)
4. restart mate-panel
(now the shortcut is gone)
5. reinstall audacious
6. restart mate-panel
7. Notice shortcut is back

Screenshot of the three states:
![beforeremoval](https://user-images.githubusercontent.com/3275361/29268588-c28e5084-80ed-11e7-848d-6cdf96512083.png)
![intermediate](https://user-images.githubusercontent.com/3275361/29268590-c490e694-80ed-11e7-9bd9-55f51280174c.png)
![afterremoval](https://user-images.githubusercontent.com/3275361/29268593-c6135b82-80ed-11e7-8001-95cee5a3be9c.png)

#### MATE general version
Mate from fresh install of Fedora 26 (64bit) 1.18.0

#### Package version
mate-panel-1.18.4-1.fc26.x86_64

#### Linux Distribution
Fedora 26

**Comment by raveit65** [comment]
yeah, the launcher won't be removed from gsettings object list.
```
[rave@mother ~]$ gsettings get org.mate.panel object-id-list
['menu-bar', 'file-browser', 'terminal', 'web-browser', 'email-client', 'show-desktop', 'object-0', 'object-1', 'object-2', 'object-3', 'object-4', 'object-5', 'object-6', 'object-7', 'object-8', 'object-9', 'object-10', 'object-11', 'object-12', 'object-13', 'object-14', 'object-15', 'object-16', 'object-21', 'object-20', 'object-18', 'object-17', 'object-19', 'object-22', 'object-23']
```
Old issue....

**Comment by raveit65** [comment]
As workaround you can delete the object from the list.

**Comment by smikkelsendk** [comment]
Is the bug not simply that the launcher "forgets" to load a broken-shortcut icon? If it did that, it would be possible to remove the shortcut or know what program to reinstall.
I dont think it would be very nice if it removed the launcher from the panel automatically, since after ie. reinstall of Fedora, you don't want all your launchers to be removed, but instead for the programs to be reinstalled.

**Comment by raveit65** [comment]
> Is the bug not simply that the launcher "forgets" to load a broken-shortcut icon?

No, i think that main problem is that the the launcher isn't removed from object list if a program is removed.
Same happens if you only create and remove a launcher without removing an application.
And that a broken link won't be loaded again after a panel restarts sounds like a good behaviour for me.

**Comment by raveit65** [comment]
Should be fixed with https://github.com/mate-desktop/mate-panel/commit/277418cea7b011520df9759301d416cd51709564
