### ISSUE TITLE
Notification area  and Windows list can't be locked, removed or moved easily

### ISSUE THREAD

**Issue by InfoLibre** [mate-desktop/mate-panel#647]
#### Expected behavior

Accessing to the locking, removing and moving menus in the **Notification area** (mate-panel-notification-area) and in the **Windows list** (mate-panel-window-list), with a right-click on one of the elements that are in the Notification area or in the Window list.
Others menus, applets... have this functionnality (see exemple in attached screenshot).

#### Actual behavior

We can access to the locking, removing and moving menus with a right-click only at the left of the Notification area or at the left of the Window list. It's difficult to do.

#### Steps to reproduce the behavior

Right-click on the Notification area or on the Window list.

#### MATE general version

1.18.0

#### Package version
![capture du 2017-08-19 16-11-34](https://user-images.githubusercontent.com/3955499/29487513-b7cb0cda-84fa-11e7-9565-dba6310e7f0b.png)

?

#### Linux Distribution
Linux Mint MATE 18.2

**Comment by raveit65** [comment]
Please unlock the applet :-)

Btw. github is for bug reporting, not for user questions....

**Comment by raveit65** [comment]
Btw, the click area is the grid left from na-area.
If you don#t see a grid report it against your distro theme. (mint-themes)

**Comment by Petrouchka** [comment]
I think you don't understand my bug report.
- On last version of MATE, grid on the left don't appear anywhere, I suppose they have been removed.
- The use of the grid on the left has been removed on all the applets and replaced by new menus added on the normal menus that appear after a right click ON the applets (and not on the left). Excepted for the Notification area (mate-panel-notification-area) and in the Windows list applets.

**Comment by raveit65** [comment]
> I think you don't understand my bug report.

i don't think

> - On last version of MATE, grid on the left don't appear anywhere, I suppose they have been removed.

This isn't true.
As i said, the left grid is there for notification-area, we never remove it, it's an issue by your theme if you don't see it.
Simply use a mate theme and not a linunxmint theme.
![na-tray-2](https://user-images.githubusercontent.com/961604/29489488-7c4c4d40-8522-11e7-8769-0ed6cb0b708b.png)


I have a grip left from na-tray applet with Blue-Submarine theme from MATE.

**Comment by Petrouchka** [comment]
My bug report is not about seeing or not the grid or about the theme. I suggest to add the Locking, Moving and Removing menus in the normal menu of Notification area applet and Windows list applet, as they are in all the others applets.
I don't want to use Grid because it isn't ergonomic and it's possible not to use it in all the applets, excepted Notification area applet and Windows list applet.

**Comment by Petrouchka** [comment]
Duplicate bug with https://github.com/perberos/Mate-Desktop-Environment/issues/122
