### ISSUE TITLE
When gtk-key-theme is overrided and changing the window manager mate-menu renderring is uncorrect

### ISSUE THREAD

**Issue by alexarnaud** [mate-desktop/mate-panel#649]
#### Description
When changing the value of the gtk-key-theme and changing the window manager mate-panel changes its appearance on the mate-menu and on tooltip text. The display of tooltip text  is also disturbed as the result: it not possible for me to read their content.

#### Expected behaviour
All the windows managers should produces the same result on mate-panel as it was on GTK2 release (Mate 1.8 from Debian 8 and Mate 1.12 from Ubuntu 16.04)

#### Actual behaviour
Screenshots: 
- With Marco: https://framapic.org/3E9yEltE3pZS/VYbpOijkCAuT.png
- With Metacity: https://framapic.org/mgvtbvvE3EjO/pFZLz5m8ilL6.png

#### Steps to reproduce the behaviour
1) Change the GSettings key "gtk-key-theme" on org.mate.interface from "Default" to "Adwaita"
2) Start Metacity or Compiz on Mate built with GTK3 (1.16 or 1.18)

#### MATE general version
1.16 and 1.18

#### Package version
1.16.2-1 and 1.18.1-0ubuntu2

#### Linux Distribution
Debian and Ubuntu

Best regards.

**Comment by alexarnaud** [comment]
I think I find what's happened it looks like mate-panel doesn't find the theme on the system
system.  For example replace "Adwaita" by "fff" you obtain the same result.as we have with Adwaita.

Best regards.

**Comment by raveit65** [comment]
I said it already at irc..
gtk-key-theme key isn't for setting a gtk theme.

**Comment by raveit65** [comment]
this is the right key
[rave@mother ~]$ gsettings get org.mate.interface gtk-theme
'Blue-Submarine'

**Comment by alexarnaud** [comment]
Le 23/08/2017 à 20:54, raveit65 a écrit :
> I said it already at irc..

I've not understand that, sorry.

> gtk-key-theme key isn't for setting a gtk theme.

Right, so it shouldn't disturb the rendering of mate-panel. I reproduce 
same behavior with gnome-panel. It is maybe due directly from GTK.

As it isn't configurable anywhere on the interface I think I should 
close this issue.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"
