### ISSUE TITLE
click top menu crash  when using mutiny panel layout

### ISSUE THREAD

**Issue by fastfading** [mate-desktop/mate-panel#650]
#### Expected behaviour
click menu , menu pop out

#### Actual behaviour
crash

#### Steps to reproduce the behaviour
set ubuntu mate -> mate tweak-> panel->panels->set to mutiny
open caja
click menu on the top
crash
#### MATE general version
ubuntu mate 17.04

#### Package version
1.18.1

#### Linux Distribution
ubuntu mate

**Comment by rilian-la-te** [comment]
Use my applet instead:)

**Comment by fastfading** [comment]
any tutorial how to use ?

2017-08-24 16:59 GMT+08:00 Konstantin <notifications@github.com>:

**Comment by raveit65** [comment]
Mutiny layout is only available in Ubuntu-MATE.
Same for broken old global-menu applet.
Why reporting here?
@flexiondotorg 
closing?

**Comment by fastfading** [comment]
move this bug to https://github.com/mate-desktop/caja/issues/833
sorry for report the wrong place

**Comment by rilian-la-te** [comment]
In 17.10 it will be default:)

**Comment by rilian-la-te** [comment]
or look to https://github.com/rilian-la-te/vala-panel-appmenu
