### ISSUE TITLE
1.18.4 FTBFS: undefined reference to 'grab_widget'

### ISSUE THREAD

**Issue by wally-mageia** [mate-desktop/mate-panel#651]
mate-panel 1.18.4 build fails in Mageia:
- gcc (Mageia 5.4.0-5.mga6) 5.4.0
- LDFLAGS =  -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags
- CFLAGS = -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4

make[2]: Entering directory '/home/wally/mageia/cauldron/mate-panel/BUILD/mate-panel-1.18.4/mate-panel'
  CCLD     mate-panel
mate_panel-menu.o: In function 'drag_end_menu_cb':
/home/wally/mageia/cauldron/mate-panel/BUILD/mate-panel-1.18.4/mate-panel/menu.c:680: undefined reference to 'grab_widget'
collect2: error: ld returned 1 exit status
Makefile:830: recipe for target 'mate-panel' failed
make[2]: *** [mate-panel] Error 1
make[2]: Leaving directory '/home/wally/mageia/cauldron/mate-panel/BUILD/mate-panel-1.18.4/mate-panel'
Makefile:1690: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wally/mageia/cauldron/mate-panel/BUILD/mate-panel-1.18.4/mate-panel'
Makefile:740: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by raveit65** [comment]
Hmm,#fedora builds are fine
https://src.fedoraproject.org/rpms/mate-panel/blob/f26/f/mate-panel.spec
https://kojipkgs.fedoraproject.org//packages/mate-panel/1.18.4/1.fc26/data/logs/x86_64/build.log

**Comment by lukefromdc** [comment]
grab_widget is a function defined in menu.c and defined well above drag_end_menu_cb so there is no reason in the world for this sort of error unless something went wrong with building the function itself. I've never worked with Magia but have never seen this in Debian, not even once.  Maybe somone who knows more about the CFLAGS you are using might have a clue?

Neither FORTIFY_SOURCE nor format-security shows up in any of my makefiles for mate-panel, in fact that text is not contained in any file in my built source. fstack-protector shows up in some of the scripts for making makefiles but not in the makefiles themselves

**Comment by wally-mageia** [comment]
Seems that FTBFS was caused by one patch [1] used with earlier mate-panel releases. Build is OK after removing the patch.

[1] http://svnweb.mageia.org/packages/cauldron/mate-panel/current/SOURCES/mate-panel_0023-GTK-3-panel-Remove-popup-menu-for-items-in-applicati.patch?revision=1076946&view=markup

**Comment by raveit65** [comment]
This patch of mine isn't needed any more ;-) ,
since 
https://github.com/mate-desktop/mate-panel/commit/a94e7d192e39fda1d5bba1921c676fec699ac533
https://github.com/mate-desktop/mate-panel/commit/4c7774639593d2e4793467061ddf10d59f8cc4a1
https://github.com/mate-desktop/mate-panel/commit/88474cac848891c362360b57cf4bc44d238bc82e
The dialog of adding a panel or desktop launcher is working again.
