### ISSUE TITLE
mate-panel drawer applet

### ISSUE THREAD

**Issue by caltrop-3** [mate-desktop/mate-panel#652]
#### Expected behaviour
a drawer

#### Actual behaviour
clicking on executes top program, does NOT open drawer
icon defaults to top program
show hide buttons does NOTHING

#### Steps to reproduce the behaviour
use it again

#### MATE general version
1.18.0

#### Package version
n/a

#### Linux Distribution
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64

#### Link to downstream report of your Distribution
n/a

**Comment by lukefromdc** [comment]
This looks like a duplicate of https://github.com/mate-desktop/mate-panel/issues/556

**Comment by caltrop-3** [comment]
Not quite...

I saw no options for displaying icons.
In fact none of the options listed in preferences do anything.

**Comment by lukefromdc** [comment]
Drawer seems to be working again as of mate-panel 1.19.3 from git master as of 12-30-2017

**Comment by muesli4** [comment]
Can't reproduce the issue with latest version from git.
