### ISSUE TITLE
CPU Frequency Scaling Monitor Applet

### ISSUE THREAD

**Issue by caltrop-3** [mate-desktop/mate-panel#658]
#### Expected behaviour
MHz not clipped to MH

#### Actual behaviour
MHz gets clipped to MH

#### Steps to reproduce the behaviour
use the applet

#### MATE general version
MATE 1.18.0

#### Package version
unknown

#### Linux Distribution
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64

#### Link to downstream report of your Distribution
none

**Comment by lukefromdc** [comment]
Wrong package, as the CPU frequency scaling monitor is part of mate-applets. This has already been reported there:
https://github.com/mate-desktop/mate-applets/issues/268
Several PR's are being worked on there to deal with it. Closing as this is a duplicate and against the wrong package
