### ISSUE TITLE
Launch Failure - Panel & Standard Menu

### ISSUE THREAD

**Issue by caltrop-3** [mate-desktop/mate-panel#659]
#### Expected behaviour
launch app

#### Actual behaviour
failure to launch

#### Steps to reproduce the behaviour
make application launcher using Application In Terminal
standard Mint Menu & Panel

temp fix: renamed link to 'mate-terminal' in /home/user/bin/ or /usr/bin/ to 'xterm'

#### MATE general version
MATE 1.18.0

#### Package version
unknown

#### Linux Distribution
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64

#### Link to downstream report of your Distribution
none

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-panel/issues/57
