### ISSUE TITLE
[1.18.4] Clock applet does not have transparency with transparent background for panel

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/mate-panel#670]
#### Expected behaviour

The clock applet should have a transparent background when the panel background is transparent

#### Actual behaviour

![screenshot at 2017-10-12 11-06-33](https://user-images.githubusercontent.com/10635269/31488437-edf8d4f0-af3d-11e7-8b10-df3a16c7dfdb.png)

#### Steps to reproduce the behaviour

Install Ubuntu MATE 17.10 Beta 2 and set a transparent background color for the top panel in the default layout.

#### MATE general version
1.18

#### Package version
1.18.4

mate-panel:
  Installed: 1.18.4-2
  Candidate: 1.18.4-2
  Version table:
 *** 1.18.4-2 500
        500 http://archive.ubuntu.com/ubuntu artful/universe amd64 Packages
        100 /var/lib/dpkg/status

#### Linux Distribution

Ubuntu MATE 17.10

#### Link to downstream report of your Distribution

https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/1723066

**Comment by monsta** [comment]
Probably a theme issue, because it works with TraditionalGreen for me.

**Comment by lukefromdc** [comment]
Also works with UbuntuStudio_Legacy(my theme), with top or bottom panel. Which theme are you using? Any theme drawing a background on a widget that does not get the .mate-custom-panel-background and accepts a background (such as the button) will cause this, and if this was not so you would lose the tasklist button backgrounds on setting a custom panel background.

**Comment by epgfm** [comment]
You guys are correct, this is a problem with ubuntu-mate-artwork.

**Comment by raveit65** [comment]
LOL, this is a collateral damage by maintainer whish.
https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/2
https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/14
https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/14/commits/be552f9abe45f8f24ef49341271a259824b53f7b
We wanted to make the clock-applet similar to main menubar.
For this reason i set up  a background on 
.mate-panel-menu-bar #PanelApplet #clock-applet-button.flat.toggle {}

**Comment by monsta** [comment]
@flexiondotorg: you might want to look at this...

**Comment by lukefromdc** [comment]
I don't see any easy way to fix this in those themes, as the menubar can styled by .mate-panel-menu-bar and this is replaced by .mate-custom-panel-background when a custom background is set,  but the clock button is not inside any widget that gets .mate-custom-panel-background, nor does any widget within it get  .mate-custom-panel-background. 

Normally the menu bar is themed transparent to match the background on the rest of the panel, and I don't see any way to set the clock button and the main menubar to something different than the panel background, match eatch other, and yet have the clock button background get out of the way for a custom background with our current code. 

Normally they match each other by being transparent and showing the background of the panel itself, and keeping any background not intended to be retained when a custom panel background is in use off the applet widgets is necessary to support custom panel backgrounds.
