### ISSUE TITLE
[feature request] The Clock applet needs an option to change first day of the week

### ISSUE THREAD

**Issue by NordenF** [mate-desktop/mate-panel#672]
Now Sunday is the first day of the week, and it's impossible to change it.
Please add the option to set Monday (or any other day) as the first day of the week in calendar in the Clock applet.
![clockcalendar](https://user-images.githubusercontent.com/7310498/31598675-922c1692-b257-11e7-9de5-072d12c7e3b6.png)

**Comment by raveit65** [comment]
In the past we had a issue about in fedora, here it was a problem with swiss_french locale.

**Comment by NordenF** [comment]
Thank you, I understood what the problem was! It was necessary to install the correct LC_TIME for my locale.

**Comment by raveit65** [comment]
So, can i close the report?

**Comment by NordenF** [comment]
Yes.

**Comment by AngryPhantom** [comment]
Sorry, but I'm having issues with the calendar. After setting LC_TIME="en_GB.UTF-8" as it is advised by Debian (https://wiki.debian.org/Locale), I'm getting error messages after every package upgrade, like "unknown locale" or something and still it DOESN'T affect the calendar: the first day of the week is Sunday, not Monday. Is it still possible to make an option for that? I'm sure a lot of people would be really grateful.

**Comment by raveit65** [comment]
What does this have to do with this close PR?
And did you filed out a report at debian bug reporting system about?

**Comment by cwendling** [comment]
> I'm getting error messages after every package upgrade, like "unknown locale" or something

Sounds like you didn't enable the `en_GB.UTF-8` locale on your system, so it doesn't know about it.  You should make sure to have it generated, see e.g. your own link https://wiki.debian.org/Locale#Standard:

> Get root and type `dpkg-reconfigure locales` and select the locale(s) you want to generate.

**Comment by AngryPhantom** [comment]
Oh, shi~
I'm really sorry, guys, for taking your time. I didn't enable this locale on my system...
Thank you very much. Have a nice day!
