### ISSUE TITLE
[applet] Gsettings relocatable schemas mess

### ISSUE THREAD

**Issue by info-cppsp** [mate-desktop/mate-panel#675]
https://github.com/mate-desktop/mate-sensors-applet/issues/22

I have worked on a PR for mate-sensor-applet, where I came across these relocatable schemas.
The problem is that with them, the dconf-editor becomes useless, as it only shows values that have previously been changed.
That means that all mate-panel applets using relocatable schemas in gsettings can no longer be set up using a nice and easy GUI, only with dconf-editor + command line and that is a pain.
Before everyone integrates all configuration options to the preferences dialogs of the respected applets, perhaps someone should find a better solution.

![screenshot at 2017-10-25 20-44-59](https://user-images.githubusercontent.com/31438307/32016937-7fcdaf9a-b9c5-11e7-9d58-776de1da8efe.png)
See here the missing options:
https://github.com/mate-desktop/mate-panel/blob/master/applets/clock/org.mate.panel.applet.clock.gschema.xml.in

Ideas?

**Comment by info-cppsp** [comment]
My idea would be to have a non relocatable 'master' schema to set applet options system wide.
Most people probably won't have 2 or more clock applets running.
With that one could see and set all applet options in one place with dconf-editor.
Individual applets would still have the relocatable schemas and object paths, but at least most people wouldn't have to deal with them.
Not a complete solution, but an improvement.

Another thing is to assign all relocatable paths a schema explicitly, as right now there is no correlation between the two.

**Comment by raveit65** [comment]
I am not really happy with relocatable schemas too, as it isn't easy to delete non existing paths from user dconf settings, beside from mentioned disadvantage.
Same for writing a override file for an admim or distro maintainer.
So, just calling the crew to discuss this.
@flexiondotorg @monsta @sc0w @XRevan86 @lukefromdc @clefebvre

**Comment by lukefromdc** [comment]
I'm no expert on gsettings but it seems to me the fix would be to split out the "relocatable" schemas which are parts of other schema files into their own files, then make whatever changes are needed to accomodate that.

**Comment by info-cppsp** [comment]
After some chat, it turns out, that dconf has little to do with this.
Now, I understand that GSettings made schemas.
GSettings is part of GIO, that is part of Glib.
So, I am investigating that.
Though I'm not happy... compiling glib can break my OS in two.

@ above
I'm not sure what you mean, as relocatable schemas or not, they are in separate files.
If you take msa:
org.mate.sensors-applet.gschema.xml.in
org.mate.sensors-applet.sensor.gschema.xml.in

**Comment by lukefromdc** [comment]
OK, what defines a schema as relocatable, and how can that be changed to define our schemas (which interact with but are not part of glib) as non-relocatable?

**Comment by info-cppsp** [comment]
AFAIK only that you don't write a path attribute to a gschema.xml file.
relocatable:
<schemalist gettext-domain="@GETTEXT_PACKAGE@">
  <schema id="org.mate.sensors-applet">
non r.:
/usr/share/glib-2.0/schemas/org.mate.panel.gschema.xml
<schemalist gettext-domain="mate-panel">
  <schema id="org.mate.panel" path="/org/mate/panel/general/">

from the chat, the r.s. were developed exactly for applets, i.e. things of which you could potentially have multiple at once.

**Comment by info-cppsp** [comment]
![screenshot at 2017-10-27 21-35-20](https://user-images.githubusercontent.com/31438307/32121890-c0787544-bb5e-11e7-9993-11e6989f0f94.png)
If you say
`dconf dump /org/mate/panel/menubar/`
you get nothing.
If you change a value, like show places in dconf-editor, you get
`[/]
show-places=false`
If you change it back:
`[/]
show-places=true`
If you click 'Set to default' in dconf-editor, you get nothing again.
So it seems, that as I though, dconf really only deals in paths.
Default data is not saved, only loaded by dconf-editor from schema files somehow.
So the configuration what you see in the pic is not stored in dconf.

So one could also explicitly store default data to dconf on applet init.
You would see all options, but no descriptions for them.

**Comment by info-cppsp** [comment]
commented here for help:
https://bugzilla.gnome.org/show_bug.cgi?id=755925

**Comment by info-cppsp** [comment]
https://git.gnome.org/browse/glib/tree/gio/gsettings.c

creating a new GSettings object from an applet non r.s.:
```c
GSettings *
g_settings_new (const gchar *schema_id);
```

takes schema_id string, returns new GObject with "schema-id" property

creating a new GSettings object from an applet r.s.:
```c
GSettings *
g_settings_new_with_path (const gchar *schema_id,
                          const gchar *path);
```

takes schema_id and path strings, returns new GObject with "schema-id" and path properties


let's say you want to SAVE something to GSettings.
the lowest common denomintator is:
```c
gboolean
g_settings_set_value (GSettings *settings,
                      const gchar *key,
                      GVariant *value);
```

NOTE: you would have to rewrite this to be able to directly save "schema-id" key that is not in schema for the applet, as this function checks if the key if valid or not

If success, this calls
```c
static gboolean
g_settings_write_to_backend (GSettings          *settings,
                             GSettingsSchemaKey *key,
                             GVariant           *value)
```

the original version:
```c
static gboolean
g_settings_write_to_backend (GSettings          *settings,
                             GSettingsSchemaKey *key,
                             GVariant           *value)
{
  gboolean success;
  gchar *path;

  path = g_strconcat (settings->priv->path, key->name, NULL);
  success = g_settings_backend_write (settings->priv->backend, path, value, NULL);
  g_free (path);

  return success;
}
```

updated version:
```c
static gboolean
g_settings_write_to_backend (GSettings          *settings,
                             GSettingsSchemaKey *key,
                             GVariant           *value)
{
  gboolean success;
  gchar *path;

  path = g_strconcat (settings->priv->path, key->name, NULL);
  success = g_settings_backend_write (settings->priv->backend, path, value, NULL);

  // NOTE do we check if schema-id has already been saved under this path?

  // if we don't want to write the "schema-id" drirectly
  // write it implicitly
  // params are NOT gchar
  if(0 != g_strcmp0 ((const char *) "schema-id", (const char *) key->name)) {

    gchar *gsschemapath = NULL;
    // get path property from gsettings object
    // last param must be NULL
    g_object_get((gpointer) settings, "path", &gsschemapath, NULL);

    gchar *gsschemaid = NULL;
    // get schema-id property from gsettings object
    // last param must be NULL
    g_object_get((gpointer) settings, "schema-id", &gsschemaid, NULL);

    // there is a path -> relocatable schema
    if((NULL != gsschemapath) && (NULL != gsschemaid)) {
      // reuse path variable
      path = g_strconcat (settings->priv->path, "schema-id", NULL);

      // create temp GVariant
      GVariant *gvsid = g_variant_new_string ((const gchar *) gsschemaid);

      // write schema-id to backend
      g_settings_backend_write (settings->priv->backend, path, gvsid, NULL);

      // g_settings_backend_write() does not free GVariant, as it is not floating
      g_variant_unref(gvsid);
    }

    g_free (gsschemapath);
    g_free (gsschemaid);
  }
  g_free (path);

  return success;
}
```

Of course after this change, you would have to make sure that no applet loads gsettings data en masse, but only with the right, named keys.

**Comment by Obsidien** [comment]
Maintainer of “main” dconf-editor here.

Relocatable schemas are great for applications, but not for a tool like dconf-editor. There’s no way to handle them, really. For now, I just have provided an explicit warning about it, so that people don’t remove a key defined by a relocatable schema thinking it’s unused (yes, it’s possible to remove old keys now! :þ ).

Offering a “schemaid” key, as proposed in GNOME bugzilla[1], doesn’t look like a really good idea for me, as it’s relying on conventions to implement missing functionnality –and that will cause bugs, one day, certainly.

What I plan to do in my branches is to have a gsettings key in /ca/desrt/dconf-editor/relocatable-schemas (probably), mapping schemas to paths (at least of type “a{sas}” for “{'schema1': ['path1', 'path2'], 'schema2': ['path1', 'path2']}” but probably more complex, handling case where “all the places in $(path) should have $(schema) applied”). But it’s not done.

[1] https://bugzilla.gnome.org/show_bug.cgi?id=755925#c6

**Comment by info-cppsp** [comment]
HI! Thanks for coming!

'not for a tool like dconf-editor'
Well, that kind of defeats the whole purpose, right?
I mean the general idea is to be able to set everything in one place.

Well, you know this way better than I, but if you add infos under the  /ca/desrt/dconf-editor/relocatable-schemas, you would have to manage them one-by-one, on your own.
That doesn't seem to be the best idea either. :P

I guess we can agree on one thing. An association between object path and schema id for r.s should be saved somewhere.

**Comment by Obsidien** [comment]
> 'not for a tool like dconf-editor'
> Well, that kind of defeats the whole purpose, right?
> I mean the general idea is to be able to set everything in one place.

Well, the tool works as expected for most uses, so things are not so bad. But yes, this corner-case is a little disappointing. ^^

> Well, you know this way better than I, but if you add infos under the /ca/desrt/dconf-editor/relocatable-schemas, you would have to manage them one-by-one, on your own.
> That doesn't seem to be the best idea either. :P

Yes, I’d have to manage a default value “one-by-one”. But most applications do not use relocatable schemas, so when the desktop internals would be done, things would be easy to maintain (I think). And that would allow to estimate how important is the problem. And to notify easily all concerned applications if another solution is found. And that wouldn’t impose to all applications maintainers to update their application –thing that would not be done in one month or one year, but would really finish when unmaintained apps would be removed from distributions repositories… Honestly, that doesn’t look like a so bad solution. And it’s a quite easy one.

> I guess we can agree on one thing. An association between object path and schema id for r.s should be saved somewhere.

It’s clear there’s a problem that needs to be solved, but I won’t say the solution is necessarily to “save an association between object path and schema id”; other solutions could be found, like the one I describe in the Gnome bugzilla. Deciding what to do requires to be completely informed of what’s necessary (see the use of relocatable schemas by gnome-builder, it’s fun), and having a powerful tool that does its best to handle all the cases is helpful for that. If you see what I mean. ;-)

**Comment by info-cppsp** [comment]
I have spent yesterday to set up a mint 18.2 VM and compile glib.
Some packages are already installed on mint:
autoconf
automake
libtool
gettext
pkg-config
gtk-doc
libffi

newly installed:
build-essential
libffi-dev
zlib -> zlib1g-dev, zlibc
libmount-dev
libpcre3-dev

Then the usual:
./autogen.sh
make
sudo make install

After restart, my new version is live (I can see the syslog strings I wrote), BUT there is no connection to dconf.
I see the following error in syslog:
Using the 'memory' GSettings backend.
or when starting dconf-editor from terminal, sg like 'dconf module not found.'
All configuration data seems to be lost.

To fix this I had to add a new path to /etc/environment like
GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/
(I have searched for 'modules' to find the right path.)
After restart I don't get the mem backend error anymore and things seem to work.

Now I can code...

**Comment by Obsidien** [comment]
Apply these patches before coding, it’s some future-proof cleaning.
[0001-Remove-search.patch.txt](https://github.com/mate-desktop/mate-panel/files/1427089/0001-Remove-search.patch.txt)
[0002-Remove-TreeView.patch.txt](https://github.com/mate-desktop/mate-panel/files/1427090/0002-Remove-TreeView.patch.txt)
[0003-Move-path_requested-in-DConfWindow.patch.txt](https://github.com/mate-desktop/mate-panel/files/1427091/0003-Move-path_requested-in-DConfWindow.patch.txt)
(GitHbut doesn’t like .patch files, so here are .patch.txt ones.)

**Comment by info-cppsp** [comment]
Thanks. So far I am only looking at glib.
Although I have tried to compile dconf as well, bc I thought that would help with the above mem backend problem, but it didn't.
I just wasted some time trying to figure out meson...

**Comment by Obsidien** [comment]
Gnome devs use Jhbuild[1] to build Gnome modules; it might be easier for you to setup a complete dev environment rather than dealing with behaviour caused by an unusual install (but it’s as you want).

[1] https://wiki.gnome.org/Newcomers/BuildSystemComponent

**Comment by info-cppsp** [comment]
Thanks. I usually keep a separate dev env anyway, but in the case of the mate-sensors-applet (from which this problem came) I didn't feel the need. I wanted to have the updated version on my main system, and I can't use it in a VM as it has no sensors...
I also didn't think that it could break my OS. (I just got segfaults and the applet died, so not much of a problem.)
In the case of GLib I knew it could break my system. In fact, I had to restore my VM from earlier snapshots, bc mate-terminal writes to gsettings as it starts (!), so basically a segfault there and I couldn't even re-make my code...
I wouldn't want to have a self-installed GLib on my working OS either. It's a critical component, for now I trust the OS devs to supply it bug free and with the right configure options. ;-)

Yesterday I have managed to rewrite the g_settings_write_to_backend() function.
This is 1/2 of the save work-flow.
I do the schema-id write on r.s. and dconf-editor shows them. :)

**Comment by info-cppsp** [comment]
OK, so after some testing, saving seems to work with g_settings_write_to_backend().
The schema-ids are shown in dconf-editor.
There is only one problem so far:
dconf-editor can't save the right value, so editing a schema-id in the mate terminal profile causes it to segfault a few times, until it finally starts...
d-e shouldn't show the schema-ids, so editing shouldn't happen.
Still, I wonder why the schema-id isn't saved. I have to check that again.

**Comment by info-cppsp** [comment]
[gliba.patch.txt](https://github.com/mate-desktop/mate-panel/files/1446300/gliba.patch.txt)
[glibb.patch.txt](https://github.com/mate-desktop/mate-panel/files/1446301/glibb.patch.txt)

I've made two patch files with diff -u in a separate patch folder.
They may need edit.
It is against the current glib master.
I have only modified the gsettings.c and the gsettingsbackend.c.
I have added syslog to both.
This is a preliminary patch, please test it.
It sets schema-id on reloc schemas.
Applications shouldn't be able to read schema-id through gsettings, so only the writing part is modified.

@Obsidien 
If you would please check this and see if you can use this schema-id in dconf-editor.
Thanks.

**Comment by Obsidien** [comment]
As I’ve already said, I’m highly convinced that this way to add the wanted functionality is not a good idea. But that’s not a good reason not to try it, right? So, let’s continue, just to see where this would lead (notably, the ‘dconf-editor’ code for that would be partly reusable in what I’ve planed to do).

But, here might not be the good place for that, as it is for the ‘mate-desktop’ issue. Maybe it would be best to work on some ‘glib’ and ‘dconf-editor’ clones on your own github, or in _a new_ bug to ‘dconf-editor’ product on GNOME bugzilla? As you prefer.

> I've made two patch files with diff -u in a separate patch folder.

Please use next time `git format-patch` for patches, that’s simpler to use. And if you don’t know how to use it, learn :·) that helps. (See also `git commit`, `git am`, `git reset`, `git reset --hard`, and probably some others, there’re enough good resources on the web for basic `git` use.)

> Applications shouldn't be able to read schema-id through gsettings, so only the writing part is modified.

Yes, it works as intended. But then, how would an application be able to know it should read the keys using a relocatable schema, without depending on the backend (that could change)?

> If you would please check this and see if you can use this schema-id in dconf-editor.

Doing that correctly is not easy, and I am currently working on more important things on ‘dconf-editor’, so no, I don’t plan to try that. But I’d happily comment on patches. :·)

**Comment by info-cppsp** [comment]
See my edits above.
I have made a new bug. It is okay if this stays here as well, as many mate panel applets have this problem if not all.

As quoted: 'Applications shouldn't be able to read schema-id through gsettings'
The only program that needs the schema-id is dconf-editor. (or any alike application)
Normal programs know their respective schema-id, no need to store it.
```c
settings = g_settings_new_with_path ("org.mate.sensors-applet", applet_path);
```
As written in the bug, an application has to state the schema id and object path to create a gsettings object for a reloc schema.
Behind gsettings there could be any backend, this function should stay the same.
It doesn't depend on dconf.
But of course if this patch will be causing problems with a new backend it will be removed...

OK. maybe I try something in dconf-editor then.

**Comment by info-cppsp** [comment]
I have tried building dconf-editor, but it needs the newest version of gtk+...

**Comment by info-cppsp** [comment]
![screenshot at 2017-11-15 17-24-14](https://user-images.githubusercontent.com/31438307/32847306-ee0b6514-ca29-11e7-92f0-9a6f87d09761.png)

Looking at dconf-schema.vala in the dconf-editor files, it seems to me that SchemaList load_directory() loads all schema files from the following directories:
`/usr/share/glib-2.0/schemas`
`/usr/local/share/glib-2.0/schemas`

On the picture you can see the SchemaList parse_file() that get called on all files from load_directory().
AFAIK the place marked by the warning is where I should do sg about the reloc schemas.
A partial list of things that get printed:
```
org.mate.sensors-applet.sensor
org.mate.sensors-applet
org.gnome.nm-applet.eap
org.gnome.desktop.app-folders.folder
org.gnome.desktop.notifications.application
org.gnome.desktop.peripherals.tablet
org.gnome.desktop.peripherals.touchscreen
org.gnome.orca
org.gnome.orca.general
org.gnome.orca.general.app
org.gnome.orca.general.braille
org.gnome.orca.general.speech
org.gnome.orca.keybinding
org.gnome.orca.pronunciation
org.gnome.orca.voice
org.gnome.orca.voice.family
org.gnome.rhythmbox.source
org.gnome.rhythmbox.encoding-settings
org.gnome.rhythmbox.podcast-source
org.gnome.rhythmbox.plugins.audioscrobbler.service
org.gnome.rhythmbox.plugins.daap.dacp
org.gnome.rhythmbox.plugins.iradio.source
org.gnome.settings-daemon.peripherals.mouse.deprecated
org.gnome.settings-daemon.peripherals.keyboard.deprecated
org.gnome.settings-daemon.peripherals.touchpad.deprecated
org.gnome.settings-daemon.peripherals.trackball.deprecated
org.gnome.settings-daemon.peripherals.wacom
org.gnome.settings-daemon.peripherals.wacom.stylus
org.gnome.settings-daemon.peripherals.wacom.eraser
org.gnome.settings-daemon.peripherals.wacom.tablet-button
org.gnome.settings-daemon.plugins.media-keys.custom-keybinding
org.gnome.settings-daemon.plugins.sharing.service
org.gnome.yelp.documents
org.mate.terminal.profile
org.mate.control-center.keybinding
org.mate.panel.applet.clock
org.mate.panel.applet.window-list
org.mate.panel.applet.workspace-switcher
org.mate.panel.toplevel
org.mate.panel.toplevel.background
org.mate.panel.applet.fish
org.mate.panel.object
org.mate.panel.applet.timer
org.mate.panel.applet.multiload
org.mate.panel.applet.cpufreq
org.mate.panel.applet.charpick
org.mate.panel.applet.geyes
org.mate.panel.applet.netspeed
org.mate.panel.applet.command
org.mate.panel.applet.battstat
org.mate.weather
```
I have removed the org.compiz.* entries. To me they all seem to be reloc schemas.

**Comment by info-cppsp** [comment]
![screenshot at 2017-11-15 21-40-05](https://user-images.githubusercontent.com/31438307/32859093-c7f6e83e-ca4d-11e7-8adc-57719b60f8b8.png)
w00t

**Comment by info-cppsp** [comment]
GLib version differences in gsettings.c from master
2-54 only documentation
2-52 same
2-50 more than just documentation, but patch should work
2-48 same
2-46 same
2-44 added rs documentation, many changes, check again, but should work
2-42 same
2-40 same

**Comment by info-cppsp** [comment]
![screenshot at 2017-12-02 17-12-52](https://user-images.githubusercontent.com/31438307/33517408-2683acbe-d784-11e7-99ee-066fb7b07673.png)

well, what do we have here...

**Comment by info-cppsp** [comment]
added commit to my fork of the dconf-editor
https://github.com/info-cppsp/dconf-editor/tree/relocsfix

format patch to gnome-3-18
[0001-Gsettings-relocatable-schemas-fix.patch.txt](https://github.com/mate-desktop/mate-panel/files/1523954/0001-Gsettings-relocatable-schemas-fix.patch.txt)

**Comment by Obsidien** [comment]
For information, GNOME’s version of `dconf-editor` now supports relocatable schemas, in the unstable release published this day. That’s done using an internal list of mappings schema→path, including “wildcards” (double slash) in the path. Users can also manually add some mappings using a key, but that’s less magic for them.

So, if you could publish a list of the usual mappings of relocatable schemas used by Mate, I could at least support them there. :·)

**Comment by info-cppsp** [comment]
# Summary

Problem:
dconf-editor doesn't show all options for applications that use a relocatable schema, like mate-sensors-applet. Therefore it is not possible to modify these options, unless they are settable in the application OR the user has to use CLI (gsettings or dconf).

Solution 1:
(This is my solution.)
With the glib patch, as the application opens gsettings to read the configuration values, an additional key is written in the background to the gsettings backend (likely dconf).
This key is then read by a patched version of dconf-editor, now showing/using the right schemas, enabling the user to set the application options.
Adv:
After the two patches are accepted/included noone has to do anything. Works like magic.
Disadv:
Bc the four wall surrounding me are more talkative/helpful than the glib devs, it is not likely that the glib patch is going to be accepted into mainstream. Thus distro maintainers have to include it themselves.
The bug is assigned to someone, who hasn't been around for nearly a year...

Solution 2:
(dconf-editor team)
Instead of writing the key as in solution 1, there would be a mapping handled and manually updated by the dconf-editor team to achieve the same effect.
Adv:
Should work in most cases.
Disadv:
The dconf-editor team will have to update the mapping manually for all eternity.

Solution 3:
Ask the application developers to
a, modify the programs gschema file(s) to include a mapping, which could be read by programs like dconf-editor
OR
b, add their mappings to Solution 2
Adv:
Should work in most cases.
The dconf-editor team would have less mappings to update manually for all eternity.
Disadv:
Not likely that any application developer would give a ****....
Maybe some would implement it, but most??

I have wasted too much this with this and the overwhelming response of 'how dare you try to fix a bug that has been around for years' makes me seriously regret it.
I have actually solved the problem, that others aren't capable of accepting my solution or providing a better one, is another matter...
So I'm closing this issue.

**Comment by lukefromdc** [comment]
Honestly, I think a fork of dconf-editor 3.18 with a fix for this would be a good fit in MATE, the newer GUI is more difficult to use (at least for me). Only thing is, our core team is small and we already have a lot of work. We already have several external community maintained apps though, notably the parrillada fork of Brasero disk burner. If someone gets a good quality fork of dconf-editor with the old UI but support for relocatable schemas it would be another. 

I don't know if we keep a list of community-supported apps, but as the number grows we probably should keep one somewhere.

**Comment by flexiondotorg** [comment]
We have some documented on the Wiki. I'll make sure the list of community maintained MATE software is up to date.

**Comment by Obsidien** [comment]
Happy new year everybody!

> Honestly, I think a fork of dconf-editor 3.18 with a fix for this would be a good fit in MATE, the newer GUI is more difficult to use (at least for me).

If you have a clear regression on a defined use case, don’t forget of course to report a bug. :)

About forking 3.18 –if someone wants to work on that– it should be made clear that the backend code is broken, really. Have a look at least to the changes made in 3.20, but better would be to have a look to GNOME head code and to contact myself.

> If someone gets a good quality fork of dconf-editor with the old UI but support for relocatable schemas it would be another.

There could be support of relocatable schemas added in one of the ways detailed by @info-cppsp, or with other solutions implying modification of the GLib in an other way than solution 1.

Or, you could help splitting GNOME head mappings list in a library, as we’re doing it that way. And, I already asked, but if you could publish a list of the usual mappings of relocatable schemas used by Mate, I could at least support them there. :·)

**Comment by raveit65** [comment]
Happy new year

> If you have a clear regression on a defined use case, don’t forget of course to report a bug. :)

> About forking 3.18 –if someone wants to work on that– it should be made clear that the backend code is broken, really. Have a look at least to the changes made in 3.20, but better would be to have a look to GNOME head code and to contact myself.

@Obsidien 
I think he meant the decision to drop the sidebar and moving navigation to headerbar.
I am using always latest version from fedora, but this change wasn' really easy to handle from user point of view. Now after more than 2 years it is OK for me.

> Or,  you could help splitting GNOME head mappings list in a library, as  we’re doing it that way. And, I already asked, but if you could publish a  list of the usual mappings of relocatable schemas used by Mate, I could  at least support them there. :·)

@flexiondotorg 
Can you please take a look at this task?

**Comment by Obsidien** [comment]
> I think he meant the decision to drop the sidebar and moving navigation to headerbar.

Yes. But in 3.20, there have been various changes, including the first evolution of the UI (I think the sidebar was there at this point, but anyway, the UI was a little strange, in-between two paradigms), *and* a cleaning of the model (removing raw loading of schemas, using GSettings instead). If someone wants to maintain a fork with the old UI, he or she will logically fork 3.18, but should really have a look to my cleaning patches that I applied during the 3.20 cycle.

> this change wasn't really easy to handle from user point of view. Now after more than 2 years it is OK for me.

Trust me, it wasn’t easy from a newly-named maintainer point of view also, but part of the work had been done while keeping a soft 3.18 cycle, and I couldn’t work any longer in local branches without some user testing. And it’s great if you find it OK now. :·)

**Comment by lukefromdc** [comment]
I found that the new UI required several more mouse clicks to do the same task as before, and much prefer the old treeview model

**Comment by Obsidien** [comment]
Ping @raveit65 @flexiondotorg ! Could you please publish a list of the usual mappings of relocatable schemas used by Mate, so I could at least support them  ? Else, where could I open a bug so it remains a “task to do ?”

**Comment by raveit65** [comment]
@Obsidien 
https://github.com/mate-desktop/mate-desktop/issues/300
Thanks for the reminder,  we are in release stress.
We will send you a list as soon as possible.
To gsettings at git gnome?
