### ISSUE TITLE
run dialog focus on list

### ISSUE THREAD

**Issue by bergentroll** [mate-desktop/mate-panel#676]
#### Expected behaviour
I expect easy way to go to list of appliactions like in xfce4-appfinder. In xfce4-appfinder when you type part of app name and press Enter you go to list of applications and can navigate throught it with arrows. More suitable way is to focus on the apps list by tab (and only then on other buttons, flag etc.).

#### Actual behaviour
I see no easy way to go from focused execution line straight for applications list (if it shown). I need to press Tab 5 times for it.

#### MATE general version
1.18.0

#### Linux Distribution
Ubuntu Mate 16.04

**Comment by info-cppsp** [comment]
picture please?

**Comment by bergentroll** [comment]
![](https://grotten.ru/index.php/s/zbuiIM9xiCWb0TE/download)

**Comment by info-cppsp** [comment]
Great!
I confirm the issue.

Note to self: https://askubuntu.com/questions/49149/how-to-open-the-run-application-dialog-from-a-terminal
CLI: `mate-panel --run-dialog`

https://github.com/mate-desktop/mate-panel/blob/master/mate-panel/panel-run-dialog.c
entry_event() has tab autocomplete

`gksudo xed /usr/share/mate-panel/ui/panel-run-dialog.ui`
Open ui file. I thought I can set tab order with GtkBuilder, but I don't know how.

Other way: add an event handler in entry_event() to set focus on the list if user presses down key.
