### ISSUE TITLE
1.18.5 at pre-release

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-panel#678]
@monsta 
As m-p is a major component of MATE, please test, tag and release if all is fine.

**Comment by monsta** [comment]
I see some more commits by @lukefromdc in master, aren't most of them bugfixes?

**Comment by raveit65** [comment]
Well i don't know from which commits are you speaking exactly?
Personal i wouldn't include all the in-process commits in 1.18.
All this admin core team questions can be easily discuss at irc channel,
or does Putin not allow communication at irc anymore;-)

**Comment by monsta** [comment]
I'm currently online there 🙂

**Comment by lukefromdc** [comment]
I don't know if any distro is shipping mate-panel 1.18 with in-process applets, if not it would not be fixing any bug in the distributed binaries to include the complex in-process work, and would risk 1.18 users having to test new code and risk new bugs that normally wait for the next feature release.

If any distro currently ships with in-process applets (I checked Ubuntu and they don't seem to be), then the in-process work would be a bugfix but a complex one.

**Comment by monsta** [comment]
I know, let's leave in-process stuff in master for now.
I meant other fixes like the ones from https://github.com/mate-desktop/mate-panel/pull/648 and https://github.com/mate-desktop/mate-panel/pull/671. But we can leave them for the future 1.18.x releases.

**Comment by lukefromdc** [comment]
I would strongly recommend both of those fixes: menus opening in the wrong place for status notifier icons is just nasty, and applet crashes are an old GNOME 2 bug that really needs to go and the fix is in master.

**Comment by raveit65** [comment]
> I would strongly recommend both of those fixes: menus opening in the wrong place for status notifier icons is just nasty, and applet crashes are an old GNOME 2 bug that really needs to go and the fix is in master.

Ok, which commits exactly please?

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-panel/pull/648
Fix crashes on moving/removing applets with glib 2.53.4 or later
(Debian Unstable now ships glib 2.54 and needs this)
and
https://github.com/mate-desktop/mate-panel/pull/671
GTK 3.22/status-notifer Fix menu position if size changed since last shown

**Comment by raveit65** [comment]
@flexiondotorg 
Can you please give @lukefromdc access to pre-release folder at server.
@lukefromdc 
We use that folder to upload and test tarballs before releasing.

**Comment by raveit65** [comment]
@monsta 
1.18.5 is updated at server.
@lukefromdc 
for the moment for you here to download :-)
https://www.dropbox.com/s/wrb81ermr0ug1mm/mate-panel-1.18.5.tar.xz?dl=0

**Comment by lukefromdc** [comment]
I have the tarball, will build and test as soon as this caja build is done

**Comment by lukefromdc** [comment]
I just tested this with both in and out of process applets. Nice bugfixes compared to 1.18.0 either way, and with in-process applets and the system background the only obvious problem is a new instance of the fish opening as a thin line, but since in-process applets invoke the redraw bug as soon as a user tries to use a custom background that may not be an issue. Very nice with out of process applets, and didn't get crashes on moiving or removing applets.

Test is over current Debian Unstable with GTK 3.22.5 and glib 2.54.2

**Comment by raveit65** [comment]
Thanks for detailed testing.
@monsta 
Do you want to test it again?
In this case please tag and release the tarball.
Otherwise give me a hint for releasing, please

**Comment by monsta** [comment]
Ok, tagged and released.

**Comment by raveit65** [comment]
@monsta 
So , should i do a new release (1.18.6) with latest fixes from
https://github.com/mate-desktop/mate-panel/pull/680   ?
Anything left for back porting to 1.18 ?
Hmm, you squashed commits from master in 1.18
https://github.com/mate-desktop/mate-panel/commit/86c64efc423448dfb3d069ba3b701bdae6c7db10
This makes it harder to compare branches because you have to read commit bodys.
If you compare only the commit historys in browser it is a bit confusing because Author is different :-)
.... and i thought why we have same commits from different authors :P 
Well, it was early in the morning, but I would prefer to see same commits in all branches .

**Comment by monsta** [comment]
I don't do that often, only when I see that some commits are fixes/improvements for the previous ones. This time it was optimization. I left a reference to the original commits in the squashed commit's message.

Ok, the fixes... I see one left, not sure what we should do about it. It's from https://github.com/mate-desktop/mate-panel/pull/669 and it should work together with the fix from https://github.com/mate-desktop/mate-polkit/pull/38.

**Comment by raveit65** [comment]
Not sure about as SNI support needs to enabled.
Are there any distros which use SNI for na-try at the moment?
For fedora /rhel i don't use it as default as i have several issue with some applets.
Maybe we leave it for 1.20 as mate-polkit needs a new release to?
But i am not against it if @lukefromdc like to see it in 1.18.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-panel/pull/669
and it's mate-polkit companion
https://github.com/mate-desktop/mate-polkit/pull/38
are bugfixes for https://github.com/mate-desktop/mate-polkit/issues/35 , which is the failure of the elevated privileges icon to ever go away when privileges are dropped if SNI support is enabled. They are needed if any only if any distro is building mate-polkit with SNI support. Keep in mind that a default build over mate-panel 1.18 will enable SNI support.

**Comment by alexarnaud** [comment]
Le 17/11/2017 à 14:35, raveit65 a écrit :
> Are there any distros which use SNI for na-try at the moment?

We used it at Hypra for Debian Stretch with Mate Panel 1.18. I recommend 
to screen reader users to enable SNI because it's the only way to access 
to the notification area without issues.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by monsta** [comment]
I only know one issue that SNI actually fixes: loss of focus for keyboard navigation on tray icons of Qt4 apps (https://github.com/mate-desktop/mate-panel/issues/506). Or maybe it's not completely fixed - the author didn't close it.

**Comment by raveit65** [comment]
> We used it at Hypra for Debian Stretch with Mate Panel 1.18. I recommend to screen reader users to enable SNI because it's the only way to access to the notification area without issues. 

Ok, reason enough to add the commit to 1.18 branch + a new mate-polkit release.

As a side not did you ever test the PR about we are speaking or any other visual-Impairment fixes from master branch (ie.atril)?

Sometimes i have a feeling that calls for testing are simply ingnored.....

**Comment by alexarnaud** [comment]
Le 17/11/2017 à 21:48, monsta a écrit :
> I only know one issue that SNI actually fixes: loss of focus for 
> keyboard navigation on tray icons of Qt4 apps (#506 
> <https://github.com/mate-desktop/mate-panel/issues/506>). Or maybe it's 
> not completely fixed - the author didn't close it.

The author worked for Hypra to implement this feature. The SNI support 
also fix keyboard navigation with Qt5 apps.
The only reason why the initial bug was not closed by cwendling was an 
oversight.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by alexarnaud** [comment]
Le 17/11/2017 à 21:51, raveit65 a écrit :
>     We used it at Hypra for Debian Stretch with Mate Panel 1.18. I
>     recommend to screen reader users to enable SNI because it's the only
>     way to access to the notification area without issues.
> 
> As a side not did you ever test the PR about we are speaking or any 
> other visual-Impairment fixes from master branch (ie.atril)?

I should do that indeed. Do you expect the test of #669 before release ?

> 
> Sometimes i have a feeling that calls for testing are simply ingnored.....

Hmm, it's not the feeling I would like to give you. Be sure I'm trying 
to test as much as possible and report bug when I found one. For the 
atril a11y implementation I thank you very much for the time you've 
spent. I'll test ASAP.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by raveit65** [comment]
@monsta 
mate-panel-1.18.6 and mate-polkit-18.2 are at pre-release and i picked
https://github.com/mate-desktop/mate-polkit/commit/8653bf4960f14810dc347d27f1f7e2d6660399ba
and
https://github.com/mate-desktop/mate-panel/commit/8dcfb668c104cf86097dcc6cd27f3a8024d4c22e to them.
I think both commits can be used independent from each other, so no update of version requiered in mate-polkit is needed.
But this or in other words 'the PRs' needs to be test again.
If everything is fine please tag them and release.

**Comment by monsta** [comment]
Ok, both packages are tested, tagged and released.
