### ISSUE TITLE
the right icons on bottom will offset when the resolution change larger

### ISSUE THREAD

**Issue by zhangwen2** [mate-desktop/mate-panel#682]
#### Expected behaviour
 the right icons on bottom will still stay on right positon when the resolution change larger

#### Actual behaviour
the right icons on bottom will offset when the resolution change larger

#### Steps to reproduce the behaviour
1.Set the resolution to 600*800, reboot the system.
2.Set the resolution to 1024*768 after the system started.
3.The workspace-switch will be offset rather than on the far right. 

#### MATE general version
1.18.4

#### Linux Distribution
Fedora-Mate 25

**Comment by raveit65** [comment]
Confirmed, i saw this very often if using MATE-Compiz spin from fedora.
And for some reasons a reboot is needed to confirming the issue.

**Comment by monsta** [comment]
I was just testing it in VirtualBox and found it's enough to restart the panel (`killall mate-panel`) instead of reboot.

**Comment by monsta** [comment]
Now I can't reproduce it at all if I have more then one right-sticked applet... even after restart.

**Comment by raveit65** [comment]
@zhangwen2 
Please test and leave karma before it's to late and f25 reach EOL :)
https://bodhi.fedoraproject.org/updates/mate-panel-1.18.6-2.fc25
