### ISSUE TITLE
calendar applet will not hide when it loses focus

### ISSUE THREAD

**Issue by chendonghai01** [mate-desktop/mate-panel#684]
#### Expected behaviour
calendar applet will be hiden when it loses focus

#### Actual behaviour
calendar applet will not hide when it loses focus

#### Steps to reproduce the behaviour
1.click on the calendar applet, the calendar windows will be pop-up.
2.click on the other areas of the desktop, the calender window will not be hidden.

#### MATE general version
1.18.4

#### Linux Distribution
Fedora-MATE_Compiz-Live 25

**Comment by flexiondotorg** [comment]
By design the calendar applet is intended to stay open when activated.
