### ISSUE TITLE
FIX Workspace Switcher: increase the height of workspace list or allow resizing the window

### ISSUE THREAD

**Issue by allanlaal** [mate-desktop/mate-panel#687]
currently the window only fits 2 workspaces and it is not possible to resize it

increase the list height or make it have automatic height based on the amount of workspaces. so it would start scrolling when its reaching the height of the screen

![screenshot at 2016-11-12 07 53 34](https://cloud.githubusercontent.com/assets/740826/20236009/6a094a86-a8ad-11e6-90be-ddb254ea070e.png)

**Comment by raveit65** [comment]
Do you really think someone will work on it if you don't file out the template?

**Comment by allanlaal** [comment]
I'm using MATE 1.12.1 on a Ubuntu Mate 16.04 and I am unable to test this in a newer release at this time, has this already been fixed?

**Comment by muesli4** [comment]
https://github.com/mate-desktop/mate-panel/pull/702

**Comment by info-cppsp** [comment]
@monsta 
If you would close this, as it seems to be fixed by the PR. Thanks.

**Comment by monsta** [comment]
Yes, this is fixed by now.

**Comment by allanlaal** [comment]
resize is fixed, but workspace list default height is still too small
