### ISSUE TITLE
Please fix mate panel font issue.

### ISSUE THREAD

**Issue by infuerano** [mate-desktop/mate-panel#690]
This particular issue not letting me update to the latest version of Linux mint mate or ubuntu mate. Everything was fine until ubuntu 16.04/ Mint 18.1. For me, the regular font in the status bar looks ugly. But I would ask if I can't even change the font from appearance setting then why it is there?

**Comment by lukefromdc** [comment]
Duplicate of https://github.com/mate-desktop/mate-panel/issues/503
