### ISSUE TITLE
Weather applet crashes from preference dialog

### ISSUE THREAD

**Issue by kwanzapili** [mate-desktop/mate-panel#693]
#### Expected behaviour
Select preference dialog to customise settings, then make and save appropriate changes.

#### Actual behaviour
Applet crashes immediately "Preferences" option is selected.

#### Steps to reproduce the behaviour
Add "weather applet" to panel -> is shows 0F initially
Select "preferences" by right clicking on icon
Crash! -> Reload -> Crash ... -> Delete

#### MATE general version
1.18

#### Package version
mate-applets-1.18.2

#### Linux Distribution
openSUSE Leap 43.3 (but mate is built from source)

#### Link to downstream report of your Distribution

In general, the weather applet has never worked for me since mate-1.16. I was using the clock applet which has weather information until it starting misbehaving by using up 99.9% of the CPU. I now only use the time element of that applet. 

From the gdb output, I think that problem is caused by mateweather_pref_create -> mateweather_pref_constructor -> mateweather_pref_new -> mate_panel_applet_factory_main. The last function seems to be called with user_data=0x0, but I don't know if that should be correct. The backtrace is as follows:

#0  0x00007f0c29b9a8a2 in g_type_check_instance_cast () at /opt/gnome/lib64/libgobject-2.0.so.0
#1  0x0000558e7219fb5a in mateweather_pref_create ()
#2  0x0000558e721a1978 in mateweather_pref_constructor ()
#3  0x00007f0c29b7a80e in  () at /opt/gnome/lib64/libgobject-2.0.so.0
#4  0x00007f0c29b7c710 in g_object_new_valist () at /opt/gnome/lib64/libgobject-2.0.so.0
#5  0x00007f0c29b7ca6c in g_object_new () at /opt/gnome/lib64/libgobject-2.0.so.0
#6  0x0000558e721a19bb in mateweather_pref_new ()
#7  0x0000558e721a4773 in pref_cb ()
#8  0x00007f0c29b7571d in g_closure_invoke () at /opt/gnome/lib64/libgobject-2.0.so.0
#9  0x00007f0c29b87bae in  () at /opt/gnome/lib64/libgobject-2.0.so.0
#10 0x00007f0c29b90245 in g_signal_emit_valist () at /opt/gnome/lib64/libgobject-2.0.so.0
#11 0x00007f0c29b90c02 in g_signal_emit () at /opt/gnome/lib64/libgobject-2.0.so.0
#12 0x00007f0c2a686a80 in  () at /opt/gnome/lib64/libgtk-3.so.0
#13 0x00007f0c2a686b6f in gtk_action_activate () at /opt/gnome/lib64/libgtk-3.so.0
#14 0x00007f0c2a8c0d70 in  () at /opt/gnome/lib64/libgtk-3.so.0
#15 0x00007f0c29b7571d in g_closure_invoke () at /opt/gnome/lib64/libgobject-2.0.so.0
#16 0x00007f0c29b87c7e in  () at /opt/gnome/lib64/libgobject-2.0.so.0
#17 0x00007f0c29b90245 in g_signal_emit_valist () at /opt/gnome/lib64/libgobject-2.0.so.0
#18 0x00007f0c29b90c02 in g_signal_emit () at /opt/gnome/lib64/libgobject-2.0.so.0
#19 0x00007f0c2aa685ab in gtk_widget_activate () at /opt/gnome/lib64/libgtk-3.so.0
#20 0x00007f0c2a8c66af in gtk_menu_shell_activate_item () at /opt/gnome/lib64/libgtk-3.so.0
#21 0x00007f0c2a8c536f in  () at /opt/gnome/lib64/libgtk-3.so.0
#22 0x00007f0c2a8b4a4f in  () at /opt/gnome/lib64/libgtk-3.so.0
#23 0x00007f0c2a89de7f in  () at /opt/gnome/lib64/libgtk-3.so.0
#24 0x00007f0c29b75956 in  () at /opt/gnome/lib64/libgobject-2.0.so.0
#25 0x00007f0c29b8ff14 in g_signal_emit_valist () at /opt/gnome/lib64/libgobject-2.0.so.0
#26 0x00007f0c29b90c02 in g_signal_emit () at /opt/gnome/lib64/libgobject-2.0.so.0
#27 0x00007f0c2aa68487 in  () at /opt/gnome/lib64/libgtk-3.so.0
#28 0x00007f0c2aa678a6 in gtk_widget_event () at /opt/gnome/lib64/libgtk-3.so.0
#29 0x00007f0c2a89c4b5 in  () at /opt/gnome/lib64/libgtk-3.so.0
#30 0x00007f0c2a89c79b in  () at /opt/gnome/lib64/libgtk-3.so.0
#31 0x00007f0c2a89c869 in gtk_propagate_event () at /opt/gnome/lib64/libgtk-3.so.0
#32 0x00007f0c2a89b4b5 in gtk_main_do_event () at /opt/gnome/lib64/libgtk-3.so.0
#33 0x00007f0c28f905bb in  () at /opt/gnome/lib64/libgdk-3.so.0
#34 0x00007f0c28fd4c5f in  () at /opt/gnome/lib64/libgdk-3.so.0
#35 0x00007f0c2989d9b7 in g_main_context_dispatch () at /opt/gnome/lib64/libglib-2.0.so.0
#36 0x00007f0c2989dbc8 in  () at /opt/gnome/lib64/libglib-2.0.so.0
#37 0x00007f0c2989ded2 in g_main_loop_run () at /opt/gnome/lib64/libglib-2.0.so.0
#38 0x00007f0c2a89a82f in gtk_main () at /opt/gnome/lib64/libgtk-3.so.0
#39 0x00007f0c2b222cb4 in mate_panel_applet_factory_main (factory_id=<optimized out>, out_process=1, applet_type=94070307159136, callback=<optimized out>, user_data=0x0) at mate-panel-applet.c:2321
#40 0x0000558e7219d79b in main ()

**Comment by lukefromdc** [comment]
First of all, the standalone weather applet is in mate-applets (as "mateweather" in the source) so you should open this as an issue against mate-applets and close it here.

I did a quick test to see if I could duplicate this. Using MATE from git master, mate-panel 1.19.3 from git master current as of 12-17-2017, GTK 3.22.26 and glib 2.55.0(new development release) over Debian Unstable I could put the weather applet on a new panel, then do seemingly anything from the preferences dialog without crashing it. Not only did selecting preferences work, so did the items within it.

Repost this against mate-applets, and add your GTK3 version to the report. I see the newest stable version of your OS as being openSUSE Leap 42.3 (not 43.3) and Tumbleweed(I am presuming this is the unstable) as next. https://software.opensuse.org/package/gtk3 lists 42..3 as using GTK3.20.10, so maybe that has an impact on this, or maybe something else since it affects your system but not mine

**Comment by monsta** [comment]
Yes, please repost at mate-applets - we're not able to move the reports between repositories.
