### ISSUE TITLE
Icon in drawers become in an arrow icon when mouse is moved near the panel

### ISSUE THREAD

**Issue by JorgeWCardoso** [mate-desktop/mate-panel#704]
#### Expected behaviour

The icon  in drawers  should be keep unchanged when mouse  is moved near the panel

#### Actual behaviour

The icon  in drawers  become in an arrow  when mouse  is moved near the panel
Sometimes the icon change to the same icon than the first item in the list

#### Steps to reproduce the behaviour

http://pub.mate-desktop.org/releases/1.18 

#### MATE general version
Mate 1.18

#### Package version
![mousefarthepanel](https://user-images.githubusercontent.com/35455200/34943674-847af934-f9f4-11e7-9440-cccd84dae002.png)
![mouseoverthepanel](https://user-images.githubusercontent.com/35455200/34943675-849c391e-f9f4-11e7-9b2d-fbc987fb5859.png)

I suspect that the problem is in mate-panel-1.18.7.tar.xz but not sure

#### Linux Distribution
Slackware 14.2 64 bits

**Comment by JorgeWCardoso** [comment]
I forgotten to say that I have installed  the following packages after run the msb scripts

-rw-r--r-- 1 root root  31800 ene 10 14:45 atril-1.18.3-x86_64-1_msb
-rw-r--r-- 1 root root  18365 ene 10 14:45 caja-1.18.5-x86_64-1_msb
-rw-r--r-- 1 root root  34138 ene 10 14:45 caja-actions-1.8.2-x86_64-1_msb
-rw-r--r-- 1 root root   2543 ene 10 14:45 caja-dropbox-1.18.0-x86_64-1_msb
-rw-r--r-- 1 root root  10884 ene 10 14:45 caja-extensions-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root  22659 ene 10 14:45 docutils-0.12-x86_64-1_msb
-rw-r--r-- 1 root root  19271 ene 10 14:45 engrampa-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root  23751 ene 10 14:45 eom-1.18.3-x86_64-1_msb
-rw-r--r-- 1 root root    913 ene 10 14:45 gksu-2.0.2-x86_64-2_msb
-rw-r--r-- 1 root root   2799 ene 10 14:45 gssdp-1.0.2-x86_64-1_msb
-rw-r--r-- 1 root root   9793 ene 10 14:45 gtk-engines-2.21.0-x86_64-1_msb
-rw-r--r-- 1 root root   7777 ene 10 14:45 gupnp-1.0.2-x86_64-1_msb
-rw-r--r-- 1 root root   1959 ene 10 14:45 libgksu-2.0.12-x86_64-3_msb
-rw-r--r-- 1 root root   2650 ene 10 14:45 libgxps-0.2.4-x86_64-1_msb
-rw-r--r-- 1 root root  17377 ene 10 14:45 libmatekbd-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root   9229 ene 10 14:45 libmatemixer-1.18.0-x86_64-1_msb
-rw-r--r-- 1 root root  41879 ene 10 14:45 libmateweather-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root  11884 ene 10 14:45 libpeas-1.20.0-x86_64-1_msb
-rw-r--r-- 1 root root   2422 ene 10 14:45 libunique-1.1.6-x86_64-2_msb
-rw-r--r-- 1 root root   2601 ene 10 14:45 libunique3-3.0.2-x86_64-1_msb
-rw-r--r-- 1 root root  13692 ene 10 14:45 libwnck3-3.20.1-x86_64-1_msb
-rw-r--r-- 1 root root  15493 ene 10 14:45 marco-1.18.1-x86_64-1_msb
-rw-r--r-- 1 root root  90085 ene 10 14:45 mate-applets-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root  13442 ene 10 14:45 mate-backgrounds-1.18.0-noarch-1_msb
-rw-r--r-- 1 root root  10538 ene 10 14:45 mate-calc-1.18.1-x86_64-1_msb
-rw-r--r-- 1 root root   1401 ene 10 14:45 mate-common-1.18.0-x86_64-1_msb
-rw-r--r-- 1 root root  42388 ene 10 14:45 mate-control-center-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root  18212 ene 10 14:45 mate-desktop-1.18.0-x86_64-1_msb
-rw-r--r-- 1 root root 217889 ene 10 14:45 mate-icon-theme-1.18.2-noarch-1_msb
-rw-r--r-- 1 root root 463073 ene 10 14:45 mate-icon-theme-faenza-1.18.1-noarch-1_msb
-rw-r--r-- 1 root root  15811 ene 10 14:45 mate-media-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root  13826 ene 10 14:45 mate-menus-1.18.1-x86_64-1_msb
-rw-r--r-- 1 root root  11603 ene 10 14:45 mate-notification-daemon-1.18.1-x86_64-1_msb
-rw-r--r-- 1 root root  30543 ene 10 14:45 mate-panel-1.18.7-x86_64-1_msb
-rw-r--r-- 1 root root   8949 ene 10 14:45 mate-polkit-1.18.1-x86_64-1_msb
-rw-r--r-- 1 root root  49525 ene 10 14:45 mate-power-manager-1.18.1-x86_64-1_msb
-rw-r--r-- 1 root root  13336 ene 10 14:45 mate-screensaver-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root  11912 ene 10 14:46 mate-sensors-applet-1.18.3-x86_64-1_msb
-rw-r--r-- 1 root root  15400 ene 10 14:45 mate-session-manager-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root  19905 ene 10 14:45 mate-settings-daemon-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root  18303 ene 10 14:45 mate-system-monitor-1.18.1-x86_64-1_msb
-rw-r--r-- 1 root root  17052 ene 10 14:45 mate-terminal-1.18.2-x86_64-1_msb
-rw-r--r-- 1 root root 335503 ene 10 14:45 mate-themes-3.18.7-noarch-1_msb
-rw-r--r-- 1 root root  41408 ene 10 14:46 mate-utils-1.18.3-x86_64-1_msb
-rw-r--r-- 1 root root  12160 ene 10 14:46 mozo-1.18.0-x86_64-1_msb
-rw-r--r-- 1 root root   1197 ene 10 14:45 murrine-0.98.2-x86_64-1_msb
-rw-r--r-- 1 root root   1050 ene 10 14:45 pangox-compat-0.0.2-x86_64-1_msb
-rw-r--r-- 1 root root  27616 ene 10 14:46 pluma-1.18.3-x86_64-1_msb
-rw-r--r-- 1 root root   2132 ene 10 14:45 rarian-0.8.1-x86_64-2_msb
-rw-r--r-- 1 root root  15992 ene 10 14:45 vala-0.34.4-x86_64-1_msb
-rw-r--r-- 1 root root  12194 ene 10 14:45 vte3-0.44.2-x86_64-1_msb
-rw-r--r-- 1 root root   1448 ene 10 14:45 yelp-tools-3.18.0-x86_64-1_msb
-rw-r--r-- 1 root root   7535 ene 10 14:45 yelp-xsl-3.20.1-x86_64-1_msb
-rw-r--r-- 1 root root  29938 ene 10 14:45 zenity-3.22.0-x86_64-1_msb

**Comment by lukefromdc** [comment]
Confirmed here on Debian Unstable with pre-release 1.20.0, happens some but not all of the time. Worse yet, if any applet is added to the drawer, instead of the arrow you get that applet's icon instead of the arrow. Having two or more applets in the drawer (the usual case) causes the drawer on a bad attempt to close to display the icon of the first applet, and a little bit of the icon of the second applet. At this point the drawer becomes unresponsive, the applets displayed swallowing all clicks on it. Sometimes clicking elsewhere on the panel properly closes the drawer-and adding an in-process built clock to it entirely prevents this.

It looks like the drawer is effectively failing to close, instead being resized. My panel background makes this clear, with the drawer getting the "convex" gradient bg perpendicular to the panel and retaining that on a failed close


![misrendered_drawer](https://user-images.githubusercontent.com/14036792/35876844-97154e92-0b41-11e8-9ba5-4b7e1ec414c0.png)

**Comment by info-cppsp** [comment]
I have been working on the drawer.
Now on ub 18.04 if you add a drawer, change to another window, nothing strange happens.
But if you open the drawer just once, if you change to another window, as you move the cursor back to mp, the icon changes between good icon and arrow...

**Comment by info-cppsp** [comment]
@monsta 
Can you perhaps tell me if there is a feature in the drawer, that displays the top widget inside the drawer, when the cursor is not inside the area of the parent mate-panel?
![screenshot at 2018-02-06 22-08-00](https://user-images.githubusercontent.com/31438307/35884253-5de2ad7e-0b8a-11e8-923c-23730ff49032.png)

(This is a command applet inside the drawer, showing `date +%T` - the local time.)
If there is, that is the problem...

Or if you can think of anything that would make this kind of overlay...
