### ISSUE TITLE
run dialog: Segfault with program list disabled

### ISSUE THREAD

**Issue by muesli4** [mate-desktop/mate-panel#706]
#### Expected behaviour
The run dialog should not crash.

#### Actual behaviour
The run dialog crashes when receiving input.

#### Steps to reproduce the behaviour
Set program list to disabled (by setting `enable-program-list` to `false`) and type something in a newly opened run dialog.

#### MATE general version
Latest from git.

#### Details

I tracked down the bug to the following line: https://github.com/mate-desktop/mate-panel/blob/dd14fcb2857f1376b5bf8f55d62324f7aaa4606f/mate-panel/panel-run-dialog.c#L1455

Apparently when hidden (`enabled-program-list` = `false`) the `program_list` member is not initialized (although I didn't look too close at it). Maybe someone with a bit more knowledge about the code can clear up my small confusion. I already wrote a fix (https://github.com/muesli4/mate-panel/tree/fix-program-list-crash) that seems to solve the issue but maybe someone can come up with something better.

**Comment by muesli4** [comment]
There you go:
```
Core was generated by `mate-panel --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f0a0307c422 in g_type_check_instance_cast ()
   from /usr/lib/libgobject-2.0.so.0
[Current thread is 1 (Thread 0x7f0a05a45980 (LWP 15708))]
(gdb) bt full
#0  0x00007f0a0307c422 in g_type_check_instance_cast () at /usr/lib/libgobject-2.0.so.0
#1  0x000055d2ea3f9964 in entry_event (entry=0x55d2ebfc04b0, event=0x55d2ebbe1e50, dialog=0x55d2ebf9cf20) at panel-run-dialog.c:1455
        selection = <optimized out>
#2  0x00007f0a0496b38c in  () at /usr/lib/libgtk-3.so.0
#3  0x00007f0a03054c5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#4  0x00007f0a03068b50 in  () at /usr/lib/libgobject-2.0.so.0
#5  0x00007f0a03071191 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#6  0x00007f0a03072240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#7  0x00007f0a04abe9e5 in  () at /usr/lib/libgtk-3.so.0
#8  0x00007f0a04ae0214 in gtk_window_propagate_key_event () at /usr/lib/libgtk-3.so.0
#9  0x00007f0a04ae3e5c in  () at /usr/lib/libgtk-3.so.0
#10 0x00007f0a0496b488 in  () at /usr/lib/libgtk-3.so.0
#11 0x00007f0a03054ea6 in  () at /usr/lib/libgobject-2.0.so.0
#12 0x00007f0a030714b4 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#13 0x00007f0a03072240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#14 0x00007f0a04abe9e5 in  () at /usr/lib/libgtk-3.so.0
#15 0x00007f0a049682c2 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007f0a0496a443 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#17 0x00007f0a044729f6 in  () at /usr/lib/libgdk-3.so.0
#18 0x00007f0a044a5375 in  () at /usr/lib/libgdk-3.so.0
#19 0x00007f0a02d7ae68 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#20 0x00007f0a02d7b0b1 in  () at /usr/lib/libglib-2.0.so.0
#21 0x00007f0a02d7b3e2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#22 0x00007f0a0496950f in gtk_main () at /usr/lib/libgtk-3.so.0
#23 0x000055d2ea3e511b in main (argc=<optimized out>, argv=<optimized out>)
    at main.c:172
        desktopfile = <optimized out>
        context = <optimized out>
        error = 0x0
```
I first noticed this bug with the archlinux package `mate-panel-1.18.6-1`. This probably happened around a week ago. My guess is that it is related to this upgrade:
```
[2018-01-12 02:45] [ALPM] upgraded glib2 (2.54.2-2 -> 2.54.3-1)
```
Could also be a bug in some of the dependencies (`glib2`, `gtk3`). That is why I asked for someone to have a look at it. My apologies for being imprecise.

**Comment by lukefromdc** [comment]
Confirmed here, and 
https://github.com/mate-desktop/mate-panel/pull/707
based on your patch is confirmed here to fix it

**Comment by monsta** [comment]
I still can't reproduce it, but I see how it could happen, and the fix looks safe. I'll test the PR.
