### ISSUE TITLE
Can't see workspace name with i3

### ISSUE THREAD

**Issue by anton-z-s** [mate-desktop/mate-panel#711]
#### Expected behaviour
Workspace swicher should be able to show workspace name when windowmanager is set to i3.

#### Actual behaviour
Workspace swicher doesn't show workspace name in the panel, only in tooltip.
![s_1516659811_2983012_d8ba5c5776](https://user-images.githubusercontent.com/3487683/35247674-3e4e5042-0006-11e8-94bb-9339380a45a6.png)

#### Steps to reproduce the behaviour
org > mate > desktop > session > required-components. Change windowmanager from marco to i3.
Log out and log in. Open properties of Workspace swicher. Option "Show workspace names in switcher" is missing.

#### MATE general version
v1.16.2 and v1.19.2

#### Package version
i3  v4.11.1 and v4.14.1

#### Linux Distribution
Ubuntu Mate 16.04 and Fedora 27

**Comment by raveit65** [comment]
How should that work without using libwwnck3 ?
http://pkgs.fedoraproject.org/cgit/rpms/i3.git/tree/i3.spec?h=f27#n11

**Comment by muktupavels** [comment]
@raveit65 How libwnck3 usage would change anything?

libwnck here does not do anything special. It all about reading / writing `_NET_DESKTOP_NAMES` root window property. Applet use libwnck to get workspace names and when names are changes also libwnck is used to update that property.

Metacity and Marco just sets workspace names from settings and also updates settings if someone changes `_NET_DESKTOP_NAMES`. Nothing fancy.

Quick look at i3 shows that they are setting this property. So it is applet bug that it considers i3 as unknown wm and because of that hides workspace names list. So fix probably is simple, just add i3 as known/recognized window manager.

Quick test shows that i3 ignores external changes to `_NET_DESKTOP_NAMES`. So applet should not allow to edit workspace name...

P.S. Metacity is also unknown wm...

**Comment by raveit65** [comment]
Ok, good to know...

**Comment by raveit65** [comment]
This looks like the code for it ?
https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/workspace-switcher.c#L148

**Comment by muktupavels** [comment]
Yes! Add new enum - `PAGER_WM_I3` and/or `PAGER_WM_METACITY`. In `window_manager_changed` assign correct enum based on `wm_name`. After that you should check all code that changes behavior based on current wm and adjust as needed - `pager_update` and `update_properties_for_wm`. Metacity probably works same as Marco, but i3 you will need to check/test, but if I remember correctly then i3 does not allow changing workspace names so that functionality should be disabled.

**Comment by anton-z-s** [comment]
i3 does allow changing workspace names: https://i3wm.org/docs/userguide.html#_changing_named_workspaces_moving_to_workspaces

**Comment by muktupavels** [comment]
@anton-z-s that will depend if someone will want to special case workspace name changing for i3. What I mean is that i3 does not support name changes with `wnck_workspace_change_name`:
https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/workspace-switcher.c#L685

According to specification `_NET_DESKTOP_NAMES` may be changed by a Pager or the Window Manager at any time, but quick grep in i3 source shows that i3 only sets / updates this property, but does not respond to external changes.

**Comment by raveit65** [comment]
Ok, *update_properties_for_wm* is at https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/workspace-switcher.c#L925
I guess i need to add code for METACITY_GENERAL_SCHEMA and METACITY_WORKSPACES_SCHEMA to 
*static void setup_dialog(GtkBuilder* builder, PagerData* pager)*.

I will start with adding support for metacity from scratch as this seems easier for me....
Adding I3 support should be easy if i know where i have to edit code.

**Comment by muktupavels** [comment]
Oh, did not notice this difference from `gnome-panel`. You don't need to use `metacity` schema here.

https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/workspace-switcher.c#L699
This is enough at least in `metacity` case. `libwnck` will update `_NET_DESKTOP_NAMES` and `metacity` will pick up this change and will update gsettings. Same goes with workspaces number.

So in metacity case it is enough to call needed libwnck functions, I was thinking same is true for marco...

**Comment by muktupavels** [comment]
- https://github.com/mate-desktop/marco/blob/master/src/core/display.c#L2471
- https://github.com/mate-desktop/marco/blob/master/src/core/screen.c#L1962

So using schemas should not be needed also with marco, you probably should search why schemas was added...

**Comment by raveit65** [comment]
I got the workspace-switcher dialog working with metacity :)
And switching all options are working.
I will do a PR and see what i can do for i3 WM.

**Comment by raveit65** [comment]
> According to specification `_NET_DESKTOP_NAMES` may be changed by a Pager or the Window Manager at any time, but quick grep in i3 source shows that i3 only sets / updates this property, but does not respond to external changes.

So, this needs to be disabled for I3 ?
gtk_widget_show(pager->workspace_names_label);
https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/workspace-switcher.c#L111

**Comment by muktupavels** [comment]
I would just disable editing (double clicking on name). That way user still can see workspace names.

**Comment by muktupavels** [comment]
https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/workspace-switcher.c#L913
https://developer.gnome.org/gtk3/stable/GtkCellRendererText.html#GtkCellRendererText--editable

Add `cell` to `PagerData` struct and then depending on wm set that it is editable or not:
`g_object_set (cell, "editable", FALSE, NULL);`

**Comment by raveit65** [comment]
But why at L913?
Isn't that for *Display all workspaces* function?
I think it is here https://github.com/mate-desktop/mate-panel/blob/master/applets/wncklet/workspace-switcher.c#L913

**Comment by raveit65** [comment]
Opps, sorry , you was right. forgot my last noise
...i looked at line numbers of local edited file.

**Comment by raveit65** [comment]
@anton-z-s 
Can you please test the PR?
I have no idea to test this with i3 and i don't want to learn it ;)

**Comment by lukefromdc** [comment]
We also don't support workspace names at all in compiz but I am not sure that would be possible as compiz handles this in a completely different way.

**Comment by muktupavels** [comment]
@lukefromdc is not workspace part disabled under compiz? Compiz does not have workspaces, it use viewports....

**Comment by lukefromdc** [comment]
Didn't catch the naming difference, but yeah-compiz is radically different than almost anything else in this regard, which has been a nuisance from the start. The workspace naming part of the dialog thus simply does not appear as is no doubt the intended behavior. For compiz it would be a matter of naming the viewports, same idea with a different name applied.
