### ISSUE TITLE
MatePanelApplet python introspection - set_size_hints does not accept a third parameter

### ISSUE THREAD

**Issue by robint99** [mate-desktop/mate-panel#732]
This is a follow up to #727 

I've built the latest version of MATE from source and Python introspection of set_size_hints is now working, but only if I omit the base_size parameter. If this is included e.g.

`size_hints = [500, 50]`
`applet.set_size_hints(size_hints, len(size_hints), 50)` 

I get  "TypeError: MatePanelApplet.Applet.set_size_hints() takes exactly 3 arguments (4 given)"

Whereas `applet.set_size_hints(size_hints, len(size_hints))` works.

In actual practice this isn't affecting me at all. Despite the missing parameter, calling set_size_hints seems to work fine and it is doing just what I need it to do, but I thought I'd better raise an issue anyway...

I've attached a modified version of the MATE University python applet which demonstrates this. To see the TypeErrors, you have to run the python code from a terminal and then add the applet to a panel.

[university-python-applet.tar.gz](https://github.com/mate-desktop/mate-panel/files/1710132/university-python-applet.tar.gz)

**Comment by info-cppsp** [comment]
Because now gir works, you don't need to set the length of the array.
Python does that automatically for you.
The three arguments are:
self - as alway in Python / C (you don't write it)
array - this has the sizes and the size of the array as well
base_size - obviously...

So to call that function you just write:
```Python
size_hints = [500, 50]
applet.set_size_hints(size_hints, base_size)
```
or
```Python
applet.set_size_hints([500, 50], base_size)
```

**Comment by robint99** [comment]
Brilliant, thanks for the info. ☺
