### ISSUE TITLE
Notification Area Does Not Elide Empty Space

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-panel#735]
#### Expected behaviour
When items are removed from the notification area (via application closing or otherwise), the notification area should shrink to fill the space that would otherwise exist from that item. 

#### Actual behaviour
When items are no longer in the notification area, the notification area stays the same, not eliding this space and closing the gap. This leaves empty space between applets.

#### Steps to reproduce the behaviour
Horizontal panel with an applet as far right as possible, a notification area next to it, locked after being occupied by items that will be removed. Close an application from the notification area, the area will now have a gap rather than sliding over.

#### MATE general version
1.18

#### Linux Distribution
Ubuntu MATE 17.10, Solus MATE, OpenSUSE Tumbleweed MATE, Antergos MATE, Manjaro MATE

**Comment by vaurelios** [comment]
No problem here,

```
pacman -Qi mate-panel | grep 'Version'
Version         : 1.20.0-1
```
