### ISSUE TITLE
[HiDPI] can't move default panel with window-scaling-factor=2

### ISSUE THREAD

**Issue by clayfreeman** [mate-desktop/mate-panel#737]
#### Expected behaviour

Default panel should remain on the original display and should be able to move freely between multiple displays.

#### Actual behaviour

Default panel becomes stuck on secondary display after editing `window-scaling-factor`.

#### Steps to reproduce the behaviour

1. Set `window-scaling-factor`=`2` with `dconf-editor`.
2. Observe that the default panel has moved to the secondary display.
3. Attempt to move the default panel back to the primary display.

#### MATE general version

`1.20.0`

#### Package version

`master` branch using Gentoo eBuild `>=mate-base/mate-9999`

#### Linux Distribution

Gentoo Linux

#### Link to downstream report of your Distribution

**Comment by lukefromdc** [comment]
I was unable to duplicate this with 1.20.0 on Debian Unstable, one 1920x1080 monitor and one 1024x768 secondary monitor. I had to add a second panel so I would have a spot not taken by an applet to click on for the panel-properties dialog, put it on the bottom with my other panel, then set window scaling to 2. No problem moving it top or bottom. I've never had panels on or moved to the secondary display at all

**Comment by clayfreeman** [comment]
Were you able to move panels across displays, even though they were never moved in the first place?

My default panel was forcibly rendered on the second display, even though `dconf-editor` claimed that it was on display `0`.

What other information should I provide so that this can be replicated successfully? I was using two Dell P2415Q displays running 3840x2160@60Hz.

**Comment by vkareh** [comment]
I experience this issue using a 3840x2160 laptop with a 1920x1080 monitor (using xrandr to scale the resolution and reposition the second screen). At the moment I'm getting a segfault when resetting the panel layout, but as soon as I manage to fix that I can start working on this issue.

For reference: https://github.com/mate-desktop/mate-settings-daemon/issues/213

**Comment by lukefromdc** [comment]
I have never moved a panel off the primary display, so I went looking in dconf-editor for a setting to do so. My panel is on the bottom, so the setting is org>mate>panel>toplevels.bottom>screen and by default is 0. Resetting this to another value with another monitor up and running was entirely ignored. That might be the root of the problem here

**Comment by lukefromdc** [comment]
One more point: any chance this is WM dependent? I normally use compiz on the desktop and marco on the laptop.

**Comment by vkareh** [comment]
@lukefromdc - something I've noticed is that because the panel re-calculates its geometry/position data after you move it, since it gets locked into the secondary screen, the recalculation essentially ends up resetting the value. I use marco everywhere, I have't tried this with compiz yet.

**Comment by lukefromdc** [comment]
The exact compiz version I am using is 0.8.15 with added GtkFrameExtent support from 
https://github.com/lukefromdc/compiz/tree/gtk-frame-extents
Wonder if compiz 0.9 behaves differently as well?

**Comment by clayfreeman** [comment]
@vkareh The thread that you linked seems to describe exactly what I'm experiencing on my end, although, I'm not aware of any segfault on my end.

@lukefromdc I think that the screen setting in `dconf-editor` is being overwritten instantly as @vkareh said. I would image that from a non-MATE DE you could edit the value and it would remain until attempting to load MATE again.

**Comment by clayfreeman** [comment]
@lukefromdc I just tried OpenBox as an alternative to Marco and it seems to exhibit the same functionality.

**Comment by vkareh** [comment]
@clayfreeman - that's expected. This behavior is entirely the panel's fault. The code that helps determine the position for HiDPI displays uses a slightly hacky calculation that needs to be adapted fort multi-monitor setups :/

**Comment by clayfreeman** [comment]
See https://github.com/mate-desktop/mate-panel/pull/710/commits/b34c7c44d9278c387abf9d0bc9a5d57a65ab7020#diff-3bfcfd676793593c71a6a0e86c54c4c9R310

**Comment by vkareh** [comment]
@clayfreeman - I submitted a possible fix here: #744 
Is this something you would be able to test on your end to see if it fixes it for you?

**Comment by clayfreeman** [comment]
Seems good to me! My panel shows on the correct monitor now.

However, applications seem to ignore that the panel is there (or at least take up more space than they should) when maximized.

**Comment by clayfreeman** [comment]
This issue appears to be fixed by #744. Thanks @vkareh for your help!
