### ISSUE TITLE
Menu doesn't open or rollover in top few pixel rows of screen

### ISSUE THREAD

**Issue by mdmayfield** [mate-desktop/mate-panel#741]
#### Expected behaviour
With Mutiny/Cupertino/etc. layout using global menu, moving mouse to very top of screen and clicking should pull down the menu. After a menu is pulled down, moving the mouse left/right between menus should change which menu is open, even if the cursor is "sliding" against the top of the screen.

#### Actual behaviour
Menu activation area in mate-panel does not extend all the way to the top of the screen; clicks and rollovers do nothing in the top row two of pixels. Extra precise mouse movement is then required to access the app menus, causing annoyance at best and accessibility issues at worst.

#### Steps to reproduce the behaviour
Video demonstration: https://photos.app.goo.gl/8BCBduDKZqoqtXJU2

#### MATE general version
1.20

#### Package version
1.20.0-0ubuntu1

#### Linux Distribution
Ubuntu MATE 18.04 beta, all packages updated as of 2018-02-22

#### Notes
- This appears to be a different issue from #653 
- That issue is about dead pixels with certain combinations of mouse and screen resolution
- This issue is about the panel menus' active areas not extending far enough
- This also appears to be a different issue from https://github.com/mate-desktop/mate-desktop/issues/291
- That issue is about window borders instead of panel active areas
- This issue appears to be specific to mate-panel, as the plugin in vala-panel works as expected at the top of the screen

**Comment by mdmayfield** [comment]
### Update

It seems that the GNOME 2-style menus *do* work as expected, so this may not be a mate-panel bug. Please also see issue https://github.com/rilian-la-te/vala-panel-appmenu/issues/208

**Comment by rilian-la-te** [comment]
Try in-process and out-of-process, please. It maybe a GtkSocket margin.

**Comment by mdmayfield** [comment]
Fixed in https://github.com/rilian-la-te/vala-panel-appmenu/commit/5a8f168b546d7b2fa73596955b3d82f4f480cb60
