### ISSUE TITLE
[HiDPI] Gaps between icons in Notification Area enlarged with window scaling

### ISSUE THREAD

**Issue by MingcongBai** [mate-desktop/mate-panel#742]
#### Expected behaviour

Gaps between icons in notification area to remain the same regardless of window scaling settings.

#### Actual behaviour

With `window-scaling-factor=2`, gaps between icons are visibly enlarged, inconsistent with original layout. See the following two screenshots for comparison.

1366x768 @ 1x

![2018-02-23 23-25-42](https://user-images.githubusercontent.com/5006263/36626049-e5396ac4-18f0-11e8-83f9-a6cce8f6436a.png)

2560x1440 @ 2x

![screenshot at 2018-02-23 20-43-47](https://user-images.githubusercontent.com/5006263/36626054-f08bb1fc-18f0-11e8-8def-82f00cb3d6b5.png)

#### Steps to reproduce the behaviour

Set `window-scaling-factor=2`.

#### MATE general version

MATE 1.20.0.

#### Package version

mate-* 1.20.0.

#### Linux Distribution

AOSC OS, package tree: https://github.com/AOSC-Dev/aosc-os-abbs/tree/staging/extra-mate.

#### Link to downstream report of your Distribution

N/A

**Comment by JosephMcc** [comment]
I'm seeing this exact issue with Mate-panel 1.20 under Ubunut 18.04. The spacing seems to be huge regardless of the theme being used. I'm running a 2x scaling factor on a 3840x2160 resolution.

**Comment by lukefromdc** [comment]
I saw this is well in an unrelated test last night using window-scaling=2

**Comment by lukefromdc** [comment]
closed by https://github.com/mate-desktop/mate-panel/pull/756
