### ISSUE TITLE
Make it possible to change in/out audio in the audio applet in the panel

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-panel#757]
#### Expected behaviour
This is not bug but rather a feature request. KDE Plamsa does this and I find it very useful. This is how it looks in Plasma.
https://boltimg.com/images/5P27X.png

#### Actual behaviour
Right now one needs to go to Settings and try to find the correct settings.

**Comment by info-cppsp** [comment]
could you please provide a picture?
(just to be clear)

**Comment by d9867eb** [comment]
@info-cppsp thanks, did so.
