### ISSUE TITLE
image border of applet doesn't appear with GNOME Theme [30$]

### ISSUE THREAD

**Issue by alexarnaud** [mate-desktop/mate-panel#758]
#### Expected behaviour
Image border should be displayed even if with GNOME themes

#### Actual behaviour
No image border appears. It makes removing applet such as the notification area really difficult for a user, especially a visual-impaired users because there is no locations displayed on the screen to perform the removal. You need to be aware of the existence of such image border to perform the deletion.

#### Steps to reproduce the behaviour
1) Change the theme to HighContrast
2) Add notification area to a panel
3) Try to remove the notification area

#### MATE general version
1.20

#### Package version
1.20.0-3

#### Linux Distribution
Debian Sid

**Comment by alexarnaud** [comment]
@raveit65 FYI, I've added a bounty for this bug as I found this a really annoying issue.

Best regards.

**Comment by raveit65** [comment]
Maybe this image can be added with a GtkCssProvider?
Same what we do in themes
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/mate-applications.css#L345
or
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlackMATE/gtk-3.0/mate-applications.css#L341
@lukefromdc 
Do you think this is possible?

**Comment by lukefromdc** [comment]
I would not want to see borders forced onto applets so that themes could not override them, as this would make some panel themes ugly. This should be done in themes only and should not be hardcoded into any applet. 

Already in my theme I have to ensure panel buttons (notably show desktop) do not show borders. Thus this would require a way for users to turn it off in dconf-settings.

**Comment by lukefromdc** [comment]
I just looked at the linked code, and see that is is the HANDLE, not the border of the tray applet and the window-list that is in question here. That is the part that is clicked on to move or bring up the preferences menu.

This part can be and should be hardcoded with a sane default that a theme can deliberately override, as would be necessary to set the color and pattern to match the theme. If the theme does not override it, the sane default is used. That's exactly how we get a panel background other than transparent in Adwaita and should be easy to do.

**Comment by raveit65** [comment]
No, description is misleading. He means the grip area left from na-tray- and wncktasklist-applet.
The three points in BlackMate.

**Comment by raveit65** [comment]
Yeah,  you posted faster than me.

**Comment by lukefromdc** [comment]
Try 
https://github.com/mate-desktop/mate-panel/pull/766
which should fix this. It's tuned for both Adwaita and Adwaita-dark, should work for any panel background between white and the color used in Adwaita-dark. Unfortunately there is no easy way to also support HighContrastInverse as that uses a black panel background while the default panel background in Adwaita is near white. Thus setting the background to be darker works in all themes except those with a black panel, and of all themes I have only HighContrastInverse sets black as a default background color and does not support MATE. To fix that would require detecting the panel background color and then loading one of two different CSS providers, don't know if that's needed or not.

**Comment by muktupavels** [comment]
You know that you can get currently used theme name, right? And based on theme name you can add custom css as needed... If theme is Adwaita add css x, if theme is HighContrast add css y...

**Comment by lukefromdc** [comment]
Without knowing all theme names that gets more than a little complicated.  I could special-case HighContrastInverse, but MATE ships its own ContrastHighInverse which does show the panel applet handles as it does support MATE. Other than that, it's not the theme name but the panel background itself that would be needed, as a new and random non-MATE theme would not be covered by name.

**Comment by raveit65** [comment]
Sadly gtk+/gnome doesn't ship an own theme folder for their ContrastHighInverse theme, with index.themes, etc. files.
So it isn't easy to use with mate-appearance-properties, otherwise i would would vote for droping our copy of it.

**Comment by alexarnaud** [comment]
Le 13/04/2018 à 00:59, lukefromdc a écrit :
> Try
> #766 <https://github.com/mate-desktop/mate-panel/pull/766>
> which should fix this. It's tuned for both Adwaita and Adwaita-dark, 
> should work for any panel background between white and the color used in 
> Adwaita-dark. Unfortunately there is no easy way to also support 
> HighContrastInverse as that uses a black panel background while the 
> default panel background in Adwaita is near white. Thus setting the 
> background to be darker works in all themes except those with a black 
> panel, and of all themes I have only HighContrastInverse sets black as a 
> default background color and does not support MATE. To fix that would 
> require detecting the panel background color and then loading one of two 
> different CSS providers, don't know if that's needed or not.

Does your PR support HighContrast theme from GNOME or Adwaita or both? I 
mean by HighContrast the one without inversion but important contrast 
between items.

Best regards,
Alex.

**Comment by raveit65** [comment]
> Does your PR support HighContrast theme from GNOME or Adwaita or both?

Every theme which don't set an image or a color for this handle of mate-panel.
For better understanding how themes selecting in Mate session works.
What you see in mate-appearance-properties thumbnails is provided by this index.theme file.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/ContrastHigh/index.theme.in
```
[X-GNOME-Metatheme]
GtkTheme=HighContrast
IconTheme=Adwaita
MetacityTheme=HighContrast
CursorTheme=Adwaita
CursorSize=24
```
We ship only this file, which activate HighContrast theme from gtk+.
We did that because their index.theme file doesn't have an entry for *MetacityTheme*, in result you don't see their theme in mate-appearance-properties main theme page.

**Comment by lukefromdc** [comment]
MATE's own ContrastHighInverse works, I might be able to special-case GNOME's version by name with another cssprovider data set but not random themes by that means

**Comment by lukefromdc** [comment]
I finally found a reasonably simple way to make this work, with a gradient image not requiring a file:
https://github.com/mate-desktop/mate-panel/pull/766/commits/2056fca0ab5be89fe822592773db44e8508e86e9

**Comment by raveit65** [comment]
I added gresource to atril a while ago, i will see if i can add this to mate-panel too.
But PR looks ready to go for me.
@alexarnaud 
You should test it...

**Comment by lukefromdc** [comment]
@alexarnaud <https://github.com/alexarnaud>
this is merged and works here, so test mate-panel from git master, your problem should be fixed in all of the mate themes. I tested every one of them,. and tested with applets both in and out of process.

**Comment by lukefromdc** [comment]
If you want to ensure that no matter what the theme, you get the highest possible contrast, drop the "gtk.css" file here into ~.config/gtk-3.0 and you will get a very sharp, clear image for the entire handle. It is rather glaring for themes like Adwaita but works very well in both HighContrast and HighContrastInverse. 
[gtk.css.gz](https://github.com/mate-desktop/mate-panel/files/1913158/gtk.css.gz)

**Comment by lukefromdc** [comment]
I finally managed to special case the HighContrast and HighContrastInverse theme names. The gnome-panel code https://github.com/muktupavels suggested worked fine, I just had a problem inside the first cssprovider block. Follow-in PR is
https://github.com/mate-desktop/mate-panel/pull/779
and uses white and black only for applet handles in the high contrast GNOME themes

**Comment by alexarnaud** [comment]
Hello lukefromdc,

Tank you very much for the fix.

Could it be possible for you to backport the changes on 1.20 and 1.18? I 
would like to provide mate-panel 1.18 on Debian Stretch for low-vision 
people and elderly.

Best regards,
Alex.

Le 16/04/2018 à 05:07, lukefromdc a écrit :

**Comment by lukefromdc** [comment]
I've never done the backporting to other branches here. Asking the rest of the team: @sc0w? @monsta? @raveit65?

**Comment by lukefromdc** [comment]
BTW: mate-panel 1.18 can be built with older GTK versions than 3.22 or even 3.20. GTK 3.14-3.18 would require different syntax, as the GTK theming code was entirely changed for 3.20. Thus 3.20 is the oldest version this could be applied to directly, and for mate-panel 1.18 it would have to be at least put behind GTK version selectors to limit it to GTK 3.20 and later builds. For Debian Stretch that would be enough, as it uses GTK 3.22.

I can no longer easily build test versions with older GTK versions, as too many other packages have now changed. On the other hand, at least GTK 3.14 used to show that applet handle by default, not sure when that stopped working.

There is of course no reason mate-panel 1.20 or even from master cannot be built and turned into debian packages or a single debian package for Debian Stretch, which has GTK 3.22 and thus can run mate-panel 3.20 or even git master. I build a single Debian package for each source package with Checkinstall, pull the files out of it (from /var/tmp) and load a custom Debian package with a DEBIAN/control file that "provides" the packages necessary for my other packages. For your purposes just "provide" the full list of packages Debian normall breaks mate-panel into, and list your version as "replaces" mate-panel. You might call it "mate-panel-all" so APT does not try to change it back.

**Comment by raveit65** [comment]
Commits are in 1.20 branch.

**Comment by lukefromdc** [comment]
I have not been able to submit a cashout request for the bounty, as Bountysource's site is not giving me an option to change the payment method from Paypal(which I do not have) to physical check

**Comment by raveit65** [comment]
@lukefromdc 
Should cherry-pick the commits to 1.18 branch and you add the syntax for < gtk+-3.20, or do you want to try out the 'git cherry-pick commit-id' command for yourself?

**Comment by lukefromdc** [comment]
I can no longer test older GTK versions without trashing half my MATE install, and I do recall that applet handle showing up by default in older GTK versions anyway. Thus, all I can do is put all of it behind GTK 3.20 or later selectors.  I can do a cherrypick easily enough from git gui

**Comment by lukefromdc** [comment]
Cherry picked to 1.18 and then pushed
https://github.com/mate-desktop/mate-panel/commit/3a8b1f66d2393a35f40dbcc211d3bf045d563a92
to limit this to GTK 3.20 and 3.22. A test build with GTK 3.22 worked fine, someone needs to ensure a test build with GTK 3.18 or earlier works as well. If someone wants to port the theming to GTK 3.18 or earlier, the syntax change would be to the name of the widget.

**Comment by lukefromdc** [comment]
The reason for using "MatePanelAppletFrameDBus > MatePanelAppletFrameDBus" is to ensure the image or background appears only on the handle and not on the whole applet. I had that problem in testing during some of the panel background work.. I can add that code if you want behind and #else for GTK 3.18 but cannot easily test it and prefer not to push untested code. If someone wants to test it I can submit it as a PR against 1.18

**Comment by raveit65** [comment]
I think @monsta have a LMDE release with Mate-1.18 and lower gtk+ running.
He should able to test the PR.
In general the selector was tested with our older mate-temes releases.

**Comment by alexarnaud** [comment]
Le 16/04/2018 à 21:23, raveit65 a écrit :
> Of course I will cherry-pick it to 1.20 branch as it is a bugfix. (git 
> cherry-pick commit-id)
> But i can only test it with mate-panel-1.18.x on distros with gtk+-3.20.
> Is there really a distro which use mate-1.18 with lower gtk+ version?

On Debian Stretch, we're using GTK 3.22.11.

Best regards,
Alex.

**Comment by alexarnaud** [comment]
Le 16/04/2018 à 21:37, lukefromdc a écrit :
> I have not been able to submit a cashout request for the bounty, as 
> Bountysource's site is not giving me an option to change the payment 
> method from Paypal(which I do not have) to physical check

For such question, you should contact the support of bounty at 
support@bountysource.com. I've already contact them and they have 
answered and do the best to find a solution.

Best regards,
Alex.

**Comment by lukefromdc** [comment]
I just heard back from Bountysource: they have disabled all payment except Paypal, but might re-enable cryptocurrency payment in the future. I will have to walk away from this one unless they agree to send one last check, presuambly while closing the account.

**Comment by lukefromdc** [comment]
The syntax in my UbuntuStudio_Legacy theme (well tested in the past) turns out to be exactly the same, using the 
MatePanelAppletFrameDBus>MatePanelAppletFrameDBus 
selector. I will submit a PR that just reverts the GTK version check against 1.18 for testing. See what it does

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-panel/pull/781 is for 1.18, to see if the rest of the syntax works in GTK 3.18 or earlier. It should: the selectors are the same, and I've got linear-gradient in the old GTK 3.14 version of UbuntuStudio_Legacy and it worked there

**Comment by lukefromdc** [comment]
I just heard back from Bountysource, they are NOT going to issue a physical check.  I can walk away from $30, I cannot get involved with Paypal and debit cards, nor will I be setting up a Bitcoin wallet in case Bountysource offers that in the future. At least I have been able to use the latest version of the fix myself by including it in my theme, that will have to do. The $30 bounty I consider uncollectable and have written off.

**Comment by lukefromdc** [comment]
Latest update from Bountysource: they may set up direct deposit to bank accounts in the future. Don't know what will come of that but I will ignore all future bounties until this is resolved, and have to consider collecting the existing $30 in my Bountysource account speculative at this time. I would sell that for as little as $10 cash to a third party with full disclosure of risk.

**Comment by lukefromdc** [comment]
I had to ask Bountysource to send the bounty back. They won't do anything but
Paypal or (in the near future) cryptocurrencies, and it's not worth the hassle(and 
expense) to set up either to use once and then discard over $30.

**Comment by lukefromdc** [comment]
I just sent you an email to the address in your profile to discuss details.

**Comment by alexarnaud** [comment]
@lukefromdc This seem to no longer works. Should we reopen this one?

**Comment by alexarnaud** [comment]
It seems this has been dropped by:

> commit 45b25410cddde852554b3153e81ad59a5e6722ad
> Author: lukefromdc <>
> Date:   Wed Apr 18 23:50:46 2018 -0400
> 
>     Theme: consistant theming for applet drag handles in all themes
>     
>     * applet drag-handle: use a symbolic image for the default drag handle image
>     * Use an .svg image with --gtk-recolor (like a symbolic icon), load it from the same directory as the css file so the css parser can find it, and use the theme fg color on it for good c
> ontrast
>     * load a css file to use the recolorable image globally for the panel, not for each applet to ensure only one cssprovider is loaded

**Comment by lukefromdc** [comment]
I have no problem with that. Be advised I was driven from my home be
extreme governmental reaction to the coronavirus, have very limited
and intermittant internet connecrivity on the road, and have to set up
and break down my desktop for each and every use.
No idea when I will be able to return home without risk of arrest.
Thus my ability to work in MATE has been limited until the stay at
home orders are lifted or collapse.

On 4/22/2020 at 7:25 AM, "Alex ARNAUD"  wrote:
	@lukefromdc This seem to no longer works. Should we reopen this one?

**Comment by lukefromdc** [comment]
Does the new GTK commit
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1749
"HC: export public colors "
 referenced in the panel drag handle issue reports help with this?

**Comment by alexarnaud** [comment]
I don't know, I'm waiting the new release to come to Debian Testing for trying but for sure I have it in mind.
