### ISSUE TITLE
panel autohides when opening menu

### ISSUE THREAD

**Issue by phunnar** [mate-desktop/mate-panel#773]
#### Expected behaviour
panel should not autohide when menu is open

#### Actual behaviour
panel started autohiding when opening menu

#### Steps to reproduce the behaviour

config:
![panel-config](https://user-images.githubusercontent.com/38381742/38770278-7f78d8fe-3fde-11e8-922d-f3ecdbb1b2e5.png)

click menu button -- the menu will open, but the panel will autohide

![panel-autohide-issue](https://user-images.githubusercontent.com/38381742/38770250-eba8e448-3fdd-11e8-873c-0e84a791fb5a.png)

#### MATE general version
1.18

#### Package version
1.18.8 (issue didn't start until 1.18.8)

#### Linux Distribution
Fedora

**Comment by raveit65** [comment]
Confirmed,
last good version in f26 is mate-panel-1.18.6-2.fc26
https://koji.fedoraproject.org/koji/buildinfo?buildID=1004052
which is the same as 
https://github.com/mate-desktop/mate-panel/commit/6ad87a9ae2a7310e8941941bd849c2fb88132d9c

**Comment by raveit65** [comment]
Issue still exists in master.....

**Comment by raveit65** [comment]
This commit sounds like it causes the issue
https://github.com/mate-desktop/mate-panel/commit/0d29acf6a70090ee771de2793b1af8e1388a430f

**Comment by vfscanf** [comment]
Author of the referenced pull request chiming in:
Unfortunately, I wasn't able to reproduce this issue neither on my Arch installation with mate-panel 1.20.1 nor on a Fedora 27 install (MATE spin) with mate-panel 1.19.3 .
@monsta : Would you mind reverting my commit and test if that fixes it?

**Comment by raveit65** [comment]
my 'git biscect' result

```
0d29acf6a70090ee771de2793b1af8e1388a430f is the first bad commit
commit 0d29acf6a70090ee771de2793b1af8e1388a430f
Author: xxxxxxxxxxxxxxxx
Date:   Wed Nov 29 17:44:13 2017 +0100

    panel-toplevel: Remove pointer boundary check in panel_toplevel_queue_auto_hide()

:040000 040000 a46f7a0c965374cd7ffe619dc6c0aaddc02e2c35 29fa41b0ca435d586ff9fca95812e5bdbed37025 M	mate-panel
```

Fedora 27 is just updated to 1.20, it should be testable there.
If reverting the commit fixes the problem i will use it for f26, as f26 becomes EOL after f28 release.
I don't want to leave it in a broken state.

**Comment by raveit65** [comment]
I created a branch with the reverted commit https://github.com/mate-desktop/mate-panel/commit/1b7cae289ebde445d08bd5fb3bd55bd0a65f4e4b
and i will use that for fixing fedora.
Maybe someone found another solution for both issues in the meanwhile.

**Comment by monsta** [comment]
Since the bad commit is already found, it should be easy. We'll have to reopen https://github.com/mate-desktop/mate-panel/issues/620 though and try to fix it in some other way.
