### ISSUE TITLE
Hide buttons on vertical panel are huge with mate-panel-1.20.1-1.fc27.x86_64

### ISSUE THREAD

**Issue by william8000** [mate-desktop/mate-panel#786]
#### Expected behaviour

Hide buttons as in earlier versions that had a limited depth.

#### Actual behaviour

The hide buttons are as deep as they are wide.
I have a vertical panel, and it is decently wide (around 150 pixels) to have space for the time and date to show without wrapping.
My laptop has a FullHD 1920x1080 display, so I can give the panel a lot of horizontal space.
The top and bottom hide buttons are now 150 pixels deep, so over 1/4 of my panel is hide buttons.

#### Steps to reproduce the behaviour

Make a vertical panel 150 pixels wide with hide buttons enabled.

#### MATE general version

1.20.1

#### Package version

mate-panel-1.20.1-1.fc27.x86_64

#### Linux Distribution

Fedora 27 x86_64

#### Link to downstream report of your Distribution

Is this caused by or fixed by https://github.com/mate-desktop/mate-panel/commit/fa5cde36593be06eabfb2f752f38c26b80ea269c ?

[Screen capture](https://plus.google.com/u/0/109904539145143933071/posts/7tCVjcaiMHi)

**Comment by raveit65** [comment]
Confirmed. I am using also a vertical panel for sensor-applet with auto-hide feature. So i never noticed that.
The vertical size of the button for a vertical panel should be reduced.

**Comment by raveit65** [comment]
Hmm, gtk3-inspector shows me that the button use the same height as panel size.
Eg. panel size is 70 that height-request is 70px for vertical panel.
In gtk3-inspector i am been able to limit height-request to 30, than it looks OK.

**Comment by raveit65** [comment]
@info-cppsp 
Can you please take a look at this?

**Comment by raveit65** [comment]
done.

**Comment by lukefromdc** [comment]
Confirmed here too

**Comment by william8000** [comment]
Thanks!

**Comment by monsta** [comment]
In other words, these buttons are always square now. It's so on a horizontal panel too.

**Comment by info-cppsp** [comment]
monsta is right. If you have a small panel, like I do, the other way around looks stupid. like 24 px high, but only 5 px wide... (it was like that at some point of developing the PR, that took weeks...)
let me think about this. probably the best way is going to be a gsetting for hide button width / height.
I would imagine that not many people are using 150 px wide panels, so let's not set things like that was the most important use case.

**Comment by raveit65** [comment]
Using a vertical panel with a huge width is a common usage with a widescreen monitor.
There are a lot of people who are using large monitors.
I am using a vertical panel of 70px for mate-sensor-applet.
And a squared button of 70x70 is to huge.
If you don't like a limited size than provide a solution with a proportion, 1/0.5 or 0.4 ?
Before your commit the button wasn't squared, so it is clear a regression for me.
Honestly, using the *panel_size* for vertical and horzontal button *size_request* is weird for me.
```
if (toplevel->priv->buttons_enabled) {
		gtk_widget_set_size_request (toplevel->priv->hide_button_top,    panel_size, panel_size);
		gtk_widget_set_size_request (toplevel->priv->hide_button_bottom, panel_size, panel_size);
		gtk_widget_set_size_request (toplevel->priv->hide_button_left,   panel_size, panel_size);
		gtk_widget_set_size_request (toplevel->priv->hide_button_right,  panel_size, panel_size);
```

**Comment by william8000** [comment]
I haven't tested it because I don't want to mess up Fedora, but I think that the commit in https://github.com/mate-desktop/mate-panel/pull/787/commits/00b01ef433c180a89ee539f1a39e4e2a6867f981 is reasonable.
Maybe you could say that the arrow needs about 20 pixels to show well, so the dimension parallel to the panel could be (panel_size < 20? panel_size: 20+(panel_size-20)/4)
A calculation like that would eliminate the need for all of the if/else cases in the patch and would make a button size that grows in proportion to panel width without becoming excessively large or small.

>Using a vertical panel with a huge width is a common usage with a widescreen monitor.

That is one of the reasons that I use mate. gnome and most other window managers have a top or bottom panel hard-coded. I want the full vertical space of my display for viewing code. Some of the lighter-weight window managers aren't as configurable and sometimes don't run complicated applications well. At least for me, mate is the only window manager that does what I want without getting in my way or causing problems with other applications. Thanks for continuing to develop and maintain it.

**Comment by raveit65** [comment]
I just updated fedora (f27/28) builds with the fix.
https://bodhi.fedoraproject.org/updates/FEDORA-2018-671402411d
https://bodhi.fedoraproject.org/updates/FEDORA-2018-23cccecd7e
Please test and leave karma if you have a fedora *fas* account.

**Comment by lukefromdc** [comment]
Closed by https://github.com/mate-desktop/mate-panel/commit/83be983eb6b57ffe8c2ebfb3701bcbe16926ad08
