### ISSUE TITLE
clock, window-list, workspace-switcher(all  in-process) can't be removed from unexpanded panel until restart

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-panel#799]
#### Steps to reproduce the behaviour
1:Build mate-panel with the clock and wncklet in-process and install
2: Add a new panel
3: Add the clock, (window list if built with https://github.com/mate-desktop/mate-panel/issues/797), or workspace switcher to that panel
4: try to remove the applet.
5: panel freezes: If "add to panel" is still open, adding another applet will force a redraw, and the panel will render with that applet added and the removed applet gone. Otherwise restart the panel and the removed applet will now be gone.

Note that if they are all on the panel at once, they may or may not be removable, depending on order of removal and probably other conditions.

#### MATE general version
1.20/1.21

#### Package version
mate-panel 1.21.0 from git master as of 4-28-2018
found while testing
https://github.com/mate-desktop/mate-panel/issues/797

#### Linux Distribution
Debian Unstable

#### Link to downstream report of your Distribution
None as this is a local build of MATE as a whole

**Comment by raveit65** [comment]
Related PR fixes the issue, tested with vertical and horizontal panel.

**Comment by lukefromdc** [comment]
This is partially fixed, all but the LAST in-process applet can now be removed from a nonexpanded panel without restarting it. There are also  issues (old issues) some but not all of the time with removing out-of-process applets from a non-expanded panel as well. With in-process applets, so long as one remains on the panel others can be freely added and removed now.

**Comment by raveit65** [comment]
@lukefromdc 
Can this be closed?

**Comment by lukefromdc** [comment]
It's now possible to remove all applets from a non-expanded panel that contained multiple in-process applets, closing
