### ISSUE TITLE
thickness border with image background

### ISSUE THREAD

**Issue by ghost** [mate-desktop/mate-panel#800]
#### Expected behaviour

I set a image background on panel, with some themes looks fine (image Greybird theme):

![pantallazo-2018-04-28 22-00-04](https://user-images.githubusercontent.com/10369607/39402815-200ac550-4b30-11e8-8bc2-1041a0152740.png)

#### Actual behaviour

But with another themes, appear a thickness border, sometimes white or sometimes black (image Blue Menta theme)

![screen](https://user-images.githubusercontent.com/10369607/39402824-5c9c3918-4b30-11e8-8d53-c10b97d467bd.png)

#### MATE general version

MATE versions: 1.16.2

#### Linux Distribution

Debian 9

**Comment by raveit65** [comment]
Closing as user is a ghost.
