### ISSUE TITLE
Duplicate parcellite panel icon when started via Startup Applications

### ISSUE THREAD

**Issue by danboid** [mate-desktop/mate-panel#801]
#### Expected behaviour

After installing parcellite under Ubuntu MATE 18.04 (which adds parcellite to the Startup Applications list) and restarting MATE/Ubuntu, only one parcellite icon should be displayed in the MATE panel.

#### Actual behaviour

Two identical looking icons are displayed for parcellite - one displays parcellites left-click menu whilst the other displays parcellites right click menu.  This problem didn't occur under UM 17.10 / MATE 1.18.

#### Steps to reproduce the behaviour

Install parcellite from 18.04 repos and restart MATE/Ubuntu

#### MATE general version

1.20.1

#### Package version

mate-desktop-environment 1.20.0+4

#### Linux Distribution

Ubuntu MATE 18.04 (Shouldn't this question be expanded to cover other Unices such as the BSDs, Illumos etc? The question should really read 'OS version')

The workaround for this bug is to remove parcellite from StartUp Applications and launch it from a shell script instead, which can be launched OK from Startup Applications without displaying two icons in the panel.

Here's the script I use to start parcellite:

```
#!/bin/bash
parcellite &
```

**Comment by alexarnaud** [comment]
Hello @danboid 

Could you let the start up of parcellite from the start-up applications and check how many process of parcellite you've ? And then check with your script ?

Best regards,
Alex.

**Comment by monsta** [comment]
> Two identical looking icons are displayed for parcellite - one displays parcellites left-click menu whilst the other displays parcellites right click menu. 

One is in the tray area and other is in mate-indicator-applet, displayed via indicator-application. Indicators are enabled by default in all panel layouts in Ubuntu MATE 18.04. Normally applications use only one of them (e.g. nm-applet, transmission-gtk), so this is a problem with parcellite.

@flexiondotorg: I'll close this as it's not a panel issue.

**Comment by danboid** [comment]
Hi monsta

Can o'worms time for ya then! :smile: 

If this is a parcellite bug then I will report it but I'm not sure exactly what I'm reporting here, parcellite bug wise. Can you please give a better outline of how this is a parcellite (packaging) bug?

If your diagnosis is correct monsta, then I presume that I should be able to get only 1 parcellite icon in the MATE panel by disabling indicators and disabling my workaround parcellite script but enabling the packaged Ubuntu/parcellite MATE startup app 'script'. I've just tried this without any success. There are multiple 'Indicator...' items in the App Startup list in a default UM 18.04. I've tried disabling them all but when I log out and back in they all get re-enabled.

So, Let's try deleting all the default UM panels then I can try adding in only the panel items I want, which doesn't include indicators BUT MATE prevents me from deleting the last panel so I'm at a loss of how to get this working properly without my custom script hence this still seems more like a MATE issue to me.

**Comment by danboid** [comment]
In regards to the final point about being able to delete the last panel - another reason for me wanting to do this is that not only do I only want 1 panel, I almost entirely customise the 1 panel I do have, such as replacing brisk menu with the Advanced MATE menu, which lets me easily add shortcuts to the panel - a feature seemingly lacking in brisk. I also prefer the look of the advanced menu but that could just be me.

It is faster for me to delete the last panel than individually remove each panel item. This was my old MATE panel customisation workflow.

**Comment by lukefromdc** [comment]
Here's how to get to a single, blank panel:

1: delete all but one panel
2: make a new panel, leave it empty
3: delete the OTHER panel

**Comment by lukefromdc** [comment]
This is for the panel's built-in sni support, not for a separate indicator applet which could just be not added to your new panel

**Comment by danboid** [comment]
Hi Luke

sni-support? How cryptic and unobvious can you get?

"Panels built-in sni support"? You've totally lost me now.

It might be worth adding a "Disable Indicators" option to MATE Tweak. I feel like I'm having to jump several hoops here to disable a feature I have no need for and I never would've guessed sni-support was related to indicators. 

Weren't Indicators a Unity 7 thing, which is now a dead project, anyway?

**Comment by lukefromdc** [comment]
sni support is the name given to it by the authors of the code (which I am not). I am not on Ubuntu and do not have MATE tweak installed, so I have never seen it. The indicator concept predates Ubuntu Indicators and some of the concepts and maybe code actually came out of KDE. There are now the Ayatana Indicators which are forked from Ubuntu, and indicator support is now available in many distros.

The indicator system has the advantage of not requiring Xembed, this not being incompatable with Wayland for a future port of mate-panel to Wayland.

**Comment by danboid** [comment]
Hi Luke

IIRC there is nothing Ubuntu specific about MATE tweak and it should run on any OS that can run MATE.

Being Wayland friendly is definitely a plus and a good reason to have them implemented but MATE, for me, is all about delivering desktop functionality whilst still trying to remain reasonably lightweight so there should be an easy way to disable indicators for those who don't require them.

I should probably open a new ticket for a feature request.

**Comment by danboid** [comment]
https://github.com/ubuntu-mate/mate-tweak/issues/46
