### ISSUE TITLE
panel "auto-hide"s when MATE Menu opened

### ISSUE THREAD

**Issue by tycho316** [mate-desktop/mate-panel#812]
#### Expected behaviour
The panel that contains the selected/opened MATE Menu should not auto-hide while the menu is open.

#### Actual behaviour
The panel "auto-hide"s when mousing to select an item from the MATE Menu causing the menu move/slide the direction of the auto-hide and can make it difficult to quickly and accurately select menu items.

#### Steps to reproduce the behaviour
I have a single bottom panel set to auto-hide with the MATE Menu item at the far left like windows 95.
mouse down to show the panel, click the MATE Menu and mouse up, slowly to the "Computer" item and it will shift. It will also shift if you mouse up quick then pause and mouse again.

#### MATE general version
1.20.1

#### Package version
1.20.1-3ubuntu1

#### Linux Distribution
ubuntu mate 18.04

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-panel/issues/773
https://github.com/mate-desktop/mate-panel/commit/cbdb7a568faea246062b02804e62998da8dbc555
New release coming soon.
