### ISSUE TITLE
drop elevated privileges icon looks weird in 1.16.2

### ISSUE THREAD

**Issue by alete89** [mate-desktop/mate-panel#814]
#### Expected behaviour
Icon is shown normally

#### Actual behaviour
Icon is weird

#### Steps to reproduce the behaviour
Do something that needs elevated privileges in mate, like mounting a fs or changin date/time in mate-panel applet

#### MATE general version
MATE Desktop Environment 1.16.2

#### Package version
1.16.2-1

#### Linux Distribution
Debian 9

### Screenshot
![screenshot at 2018-06-02 01-17-44](https://user-images.githubusercontent.com/4999277/40869023-a7bf559a-6603-11e8-9aba-2eb5a709f4fc.png)

**Comment by lukefromdc** [comment]
I wonder if this depends on the icon theme, or is specific to builds with SNI support disabled? I have SNI support enabled and do not get this partial repeat of an undersized icon

**Comment by alete89** [comment]
I tried another theme and same result:
![screenshot at 2018-06-02 01-33-19](https://user-images.githubusercontent.com/4999277/40870422-51c20b18-6605-11e8-9fe8-e311f8f9b282.png)

Sorry... I don't even know what SNI is, but I found that I could check if it's enabled like this:
`gsettings get org.mate.panel enable-sni-support`
but I don't even have that key.

**Comment by lukefromdc** [comment]
SNI (indicator) support came into mate-panel in version 1.18 so year, you would not have it. That means this is with the normal tray applet mode.

**Comment by alete89** [comment]
Ok, I guess I can close this issue then, since it's fixed in newer versions.

**Comment by monsta** [comment]
See the discussion at https://bugs.debian.org/870318
