### ISSUE TITLE
Translation esperanto weekdays

### ISSUE THREAD

**Issue by jorgesumle** [mate-desktop/mate-panel#819]
#### Expected behaviour

I expected to see the weekday abbreviations in Esperanto, instead they appear in English.

#### Actual behaviour

They appear in English. I tried searching for it in the translation files, but I can't find any reference to that. I hope you can help me submit the translation, I read the README to find out how translations work, but I didn't find anything and `grep -R` didn't find what I wanted to translate (`Sat`, `Mon`, etc.).

#### Steps to reproduce the behaviour

Click on the calendar applet, you'll see Sat, Mon... (in English).

#### MATE general version

This output from `apt-cache show mate-panel` should be enough:

```Depends: libmate-panel-applet-4-1 (= 1.12.2-1), mate-desktop, mate-menus, mate-panel-common (= 1.12.2-1), mate-polkit, menu-xdg, python, dconf-gsettings-backend | gsettings-backend, libatk1.0-0 (>= 1.12.4), libc6 (>= 2.7), libcairo2 (>= 1.2.4), libcanberra-gtk0 (>= 0.17), libcanberra0 (>= 0.2), libdbus-glib-1-2 (>= 0.78), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.37.3), libgtk2.0-0 (>= 2.24.0), libice6 (>= 1:1.0.0), libmate-desktop-2-17 (>= 1.10.0), libmate-menu2 (>= 1.6.0), libmateweather1 (>= 1.6.2), libpango-1.0-0 (>= 1.18.0), librsvg2-2 (>= 2.14.4), libsm6, libwnck22 (>= 1:2.30.2-0ubuntu3), libx11-6, libxrandr2 (>= 2:1.2.99.3)```

#### Package version

Architecture: i386
Version: 1.12.2-1

#### GNU/Linux Distribution

Uruk GNU/Linux 2.0 lugalbanda 

#### Link to downstream report of your Distribution

I didn't report it to downstream.

**Comment by raveit65** [comment]
Translations are done by Transifex.
https://www.transifex.com/mate/MATE/
Become a member there and start translating your language ;)

**Comment by jorgesumle** [comment]
I solved my issue. I had to change the regional format preference in **Sistemo>Agordoj>Persona>Lingvosubteno>Regionaj formatoj**. You just need to select Esperanto there.

> Translations are done by Transifex.

Transifex is proprietary, so I don't want to use that. But maybe in the future I can submit a untranslated string or fix a typo. Do you accept simple pull requests here?

**Comment by vkareh** [comment]
@jorgesumle unfortunately we don't. Translations are auto-generated from what's on Transifex, so pull requests don't actually work
