### ISSUE TITLE
"Global Application Menu" crashes consistently when scrolling over Firefox's Mutiny launcher icon

### ISSUE THREAD

**Issue by CreamyCookie** [mate-desktop/mate-panel#822]
Weirdly enough, this only seems to be true when scrolling over the Firefox icon, but it may also affect others.

#### Expected behaviour
Scrolling fast over the Firefox icon shouldn't crash the Global Menu panel.

#### Actual behaviour
It crashes and I get the `"Global Application Menu" has quit unexpectedly'` error message. I don't know if this is related, but I've got a ton of the following in my `.xsession-errors`:

    (mate-panel:2520): Gtk-CRITICAL **: 16:25:23.054: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

#### Steps to reproduce the behaviour
Scroll over the Firefox icon (multiple windows open) very fast and for quite a while. (I only noticed this because my trackball scrolls very quickly, which almost results in a flickering between the two open Firefox windows. (Side question: Is there a way to slow that down? It's nearly impossible to find the right window due to it changing so fast.)

#### MATE general version
The latest from Ubuntu Mate 18.04 (up to date): 1.20.1

#### Linux Distribution
Ubuntu Mate 18.04

**Comment by rilian-la-te** [comment]
Move Global Menu part to my GitLab, please, it is not Mate bug, AFAIK.

**Comment by CreamyCookie** [comment]
Okay, I wasn't sure what you meant by Global Menu part, so I've posted the complete issue: https://gitlab.com/vala-panel-project/vala-panel-appmenu/issues/247

But feel free to point out if there's anything I should remove.
