### ISSUE TITLE
[applets/notification_area] steam tray icon menu not displaying separators (libappindicator)

### ISSUE THREAD

**Issue by muesli4** [mate-desktop/mate-panel#83]
Hi,

when using the Steam linux version the layout of the menu in the notification_area applet does not show the separators, while it is confirmed that they show in other desktop environments (also gnome classic).

I'm not familiar with the method they use, but as far as I know it is libappindicator.
##

**Comment by monsta** [comment]
This is probably their issue, not ours. Anyway, time has passed, this is probably fixed by now.
Or not? Do you still see it?

**Comment by infirit** [comment]
This my be related to the indicator applet only showing gtk2 indicators. That is I believe an issue open there. Does it show in unity?

**Comment by monsta** [comment]
No, notification area is different and it's able to show tray icons for GTK+3 apps as well, the most known of them being network manager applet :smile:

**Comment by muesli4** [comment]
It's not fixed and I can see separators in the network manager GTK applet menu (with my ugly gtk3 style).

Sadly, I don't know the source, but I'm willing to help, if there is something I can do.

**Comment by monsta** [comment]
I guess it's fixed now?

**Comment by muesli4** [comment]
@monsta Correct. The issue has been solved a while ago and had nothing to do with **mate-panel**. I just found it while browsing the issues.

**Comment by monsta** [comment]
Good to know it wasn't a panel bug :slightly_smiling_face:
