### ISSUE TITLE
sleep inhibitor applet using up too much cpu

### ISSUE THREAD

**Issue by tecan** [mate-desktop/mate-panel#831]
uses 8% itself and causes xorg to go from 3-5% upto 20%

**Comment by lukefromdc** [comment]
What version of mate-power-manager do you have installed? There was a fix
for this committed a while back but it may have been after Ubuntu 18.04 was
released.

**Comment by monsta** [comment]
Closing like https://github.com/mate-desktop/mate-desktop/issues/328
