### ISSUE TITLE
Left-clicking indicator icons is broken

### ISSUE THREAD

**Issue by SwooshyCueb** [mate-desktop/mate-panel#838]
Left and right clicking indicator icons in the notification tray do not behave as expected. This started either during or after the move to gtk3.
Left clicking an indicator icon causes the right-click action to take place (usually a context menu). Right clicking an indicator icon opens the context menu for *the notification tray panel applet*. As far as I can tell, there is no longer any way to perform an actual left-click action on an indicator icon, which breaks programs like flameshot, which work fine in the old gtk2 version of mate-panel.

MATE indicator applet version 1.20.0
MATE panel version 1.20.1
Ubuntu MATE 18.04

**Comment by raveit65** [comment]
Wrong repo.
Sorry we can't move reports here.
Please file out again here https://github.com/mate-desktop/mate-indicator-applet/issues

**Comment by raveit65** [comment]
And please respect our template. Than chances are higher that someone will start to work on it ;)
