### ISSUE TITLE
Panel applets with "panel-right-stick=true" don't move correctly

### ISSUE THREAD

**Issue by Jacalz** [mate-desktop/mate-panel#839]
#### Expected behaviour
If I set the clock to position 10 it should get a space between the edge and clock, just like when I change an applet without "panel-right-stick=true".

Left menu with position set to 0:
![menu-position-0](https://user-images.githubusercontent.com/25466657/42708739-7b27cb4c-86de-11e8-8f26-ae6c85b2e812.png)

Left menu position set to 10, see the space between
![menu-position-10](https://user-images.githubusercontent.com/25466657/42708771-8db41040-86de-11e8-9cf9-f154497d4f1a.png)
 screen edge and applet:

#### Actual behaviour
I am trying to edit solus.layout to move the clock 10 steps from the right edge but it does not move when I change the position from 0 to 10. But when I change to 20 it pops to the left of the notification area that has the position set to 20.

Clock position set to 0:
![clock-possition-0](https://user-images.githubusercontent.com/25466657/42708428-94a5af9a-86dd-11e8-9299-7a1ad6503295.png)

Clock position set to 10:
![clock-position-10](https://user-images.githubusercontent.com/25466657/42708445-a21215a6-86dd-11e8-8225-e3fbd3f876af.png)

Clock position set to 20:
![clock-position-20](https://user-images.githubusercontent.com/25466657/42708460-af3947f4-86dd-11e8-909a-5db765d5e77a.png)

#### Steps to reproduce the behaviour
 1. Download [solus.layout](https://raw.githubusercontent.com/solus-project/mate-desktop-branding/master/panel/solus.layout)

 2. Use it as the panel layout

 3. Cange the clock applet position from 0 to 10 

#### MATE general version
1.20.2

#### Package version
1.20.2

#### Linux Distribution
[Solus](https://solus-project.com)

**Comment by raveit65** [comment]
Does the issue still exits?

**Comment by Jacalz** [comment]
I don't know unfortunately. Haven't used Mate in many years now.
