### ISSUE TITLE
CPU frequency monitor doesn't show frequency unit (entierely)

### ISSUE THREAD

**Issue by SharkEzz** [mate-desktop/mate-panel#840]
#### Expected behaviour
When adding the CPU frequency monitor to mate-panel, the current frequency is displayed as well as the unit (MHz, GHz, etc...)

#### Actual behaviour
When adding the CPU frequency monitor to mate-panel, the current frequency is displayed correctly but the unit is cut off. In both MHz and GHz as shown on the screenshot

![freq](https://user-images.githubusercontent.com/27637158/42723586-f01c24a2-8760-11e8-9495-a46429fde227.png)

I have 4 of these, on the first one, we only see one part of the unit whereas we can't see the unit on the others.

#### Steps to reproduce the behaviour
Add the CPU frequency monitor : 
Right click on the mate-panel -> Add to dashboard -> CPU frequency monitor.

#### MATE general version
1.20.3

#### Package version
1.20.2

#### Linux Distribution
Arch Linux

**Comment by raveit65** [comment]
Wrong repo. cpu-freq is part of mate-applets repo.
https://github.com/mate-desktop/mate-applets/issues
Sorry we can't move reports, so please try again.
Btw. i have a feeling that this is already fixed in master.

**Comment by raveit65** [comment]
Try those commits:
https://github.com/mate-desktop/mate-applets/commit/8bd11f81e05d8498c530e3951fa0f1c2b67a74b8
https://github.com/mate-desktop/mate-applets/commit/618ab266bc51aa7c7e880b8459f4389a12c3f21e
https://github.com/mate-desktop/mate-applets/commit/f0b33d1125f60bd5fe8b605d88efd37b2b0b2427
