### ISSUE TITLE
Scaling notification area icons not work for some apps

### ISSUE THREAD

**Issue by amir28** [mate-desktop/mate-panel#848]
#### MATE general version
mate-session 1.20.0

#### Package version
mate-panel-1.20.2-1

#### Linux Distribution
ArchLinux

## Description
Hello, I use ArchLinux with mate desktop. I want make small notification area's icon. I wrote this code in the file ~/.config/gtk-3.0/gtk.css:
```
.mate-panel-menu-bar na-tray-applet,
panel-toplevel.background na-tray-applet {
  -NaTrayApplet-icon-padding: 0;
  -NaTrayApplet-icon-size: 15px;
}
```
After reseting the mate panel, I saw this:
![screenshot at 2018-07-22 21-08-00](https://user-images.githubusercontent.com/22644254/43047870-6e1c7c92-8df3-11e8-86bf-51dfb1f81db7.png)
some applications' icons like Uget and Pacmac is very big but some applications' icons like VLC and Telegram Desktop is OK.
I have Ubuntu Mate in dual boot. This problem isn't be seen in My UbuntuMate.

**Comment by lukefromdc** [comment]
I see here you have a large panel height, but are setting much smaller icons in gtk.css. The fact that some but not all icons respond to this means the GTK theme is controlling some of them (looks like that is the status notifier applets) and the panel height is controlling the rest of it. By default the code tries to scale all icons in the panel to fit the panel height, and the case of a smaller icon size being forced in the theme or in gtk.css was never tested and I have no seen any experiments with it.
My guess is that the panel height is the last thing controlling icon scaling for tray icons, and the GTK theme the last thing (as in having the final word) controlling the height of status icons.

The status notifier code contains GTK_ICON_SIZE_MENU, while this code does not appear in the conventional tray (status icon)  code.

**Comment by amir28** [comment]
OK, What i can doing??

**Comment by lukefromdc** [comment]
If you remove that code to set the small icon size, all of them should display at or near full panel size. At the moment I don't know of anything else and am on my way out the door for an event. It might be a major overhaul to support reduced-size icons and at the moment my focus has been on finding a bad memory leak. Will take a look at it at some point but no promises, maybe one of the other devs here will think of something

**Comment by raveit65** [comment]
Seems issue is fixed.
