### ISSUE TITLE
alt-F1 shortcut is not transferring focus correctly

### ISSUE THREAD

**Issue by sthibaul** [mate-desktop/mate-panel#851]
Hello,

The background is in https://gitlab.gnome.org/GNOME/gtk/issues/85 . One of the conclusions, in https://gitlab.gnome.org/GNOME/gtk/issues/85#note_264804 , is that mate-panel is not properly transferring focus on alt-F1 keyboard shortcut. (on alt-F2 it is working properly).

#### How to reproduce

- install gtk3, which contains the fix for https://gitlab.gnome.org/GNOME/gtk/issues/85 (can be seen by gdk/x11/gdkdevicemanager-core-x11.c's APPEARS_FOCUSED testing for both has_focus and has_focus_window).
- run the mate desktop
- run accerciser, in its Event Monitor, open window element and enable window:activate and window:deactivate
- run e.g. mate-terminal, accerciser shows window:activate for it
- press alt-f1

#### Actual result

accerciser shows only window:activate for the mate-panel

#### Expected result

accerciser should show a window:deactivate for mate-terminal, and window:activate for mate-panel

It used to work only by luck before, only because gtk used to deactivate itself during a keyboard grab. But as discussed in https://gitlab.gnome.org/GNOME/gtk/issues/85 that behavior poses accessibility feedback issues, is not coherent, and keyboard grab feedback will not be available in wayland anyway. Thus @ebassi saying in https://gitlab.gnome.org/GNOME/gtk/issues/85#note_264804 that not transferring focus properly is the actual bug.

#### MATE general version

1.20

#### Package version

1.20

#### Linux Distribution

Debian

**Comment by raveit65** [comment]
@sthibaul @cwendling 
Looks like we have a regression with this PR, see https://github.com/mate-desktop/marco/issues/209#issuecomment-498196109
Can you please take a look at it?
