### ISSUE TITLE
Problem with volume slider

### ISSUE THREAD

**Issue by gabrielbarros** [mate-desktop/mate-panel#853]
(I'm not sure if I'm in the right repo)

With the mouse over the volume slider, when I scroll up, the volume decreases and when I scroll down, the volume increases. It should be the opposite.

![img](https://user-images.githubusercontent.com/3298817/43987377-1e7fc06a-9cf6-11e8-9ff9-20b443d66ba7.png)

Ubuntu 18.04.1 LTS

**Comment by raveit65** [comment]
This slider is a Ubuntu indicator, not from Mate
File out a report there.
And please don't ignore our template next time.
Nobody start to work on it if you don't file out the template
