### ISSUE TITLE
Strange dates in Calendar 

### ISSUE THREAD

**Issue by r3d9u11** [mate-desktop/mate-panel#855]
#### Actual behaviour
![screenshot at 2018-08-22 12-35-45](https://user-images.githubusercontent.com/15020827/44455993-1e1d8380-a608-11e8-83c7-411924589dc0.png)

#### MATE general version
1.18.0

#### Package version
1.18.0-1+sonya

#### Linux Distribution
Linux Mint 19 x64

**Comment by monsta** [comment]
These are week numbers. You can turn them off in the preferences dialog.

**Comment by r3d9u11** [comment]
thanks
