### ISSUE TITLE
Where is battery icon?

### ISSUE THREAD

**Issue by r3d9u11** [mate-desktop/mate-panel#861]
#### Expected behaviour
battery icon should be displayed (also icons of Guake and CPU Mode is looking ugly, but with Linux Mint 18.3 they are looks nice)

#### Actual behaviour
battery icon is missed
![screenshot at 2018-08-28 14-24-12](https://user-images.githubusercontent.com/15020827/44720072-3a209980-aace-11e8-9362-d3ea0ee3fcc3.png)

#### MATE general version
1.18.0

#### Package version
1.18.0-1+sonya

#### Linux Distribution
Linux Mint 19 x64

**Comment by raveit65** [comment]
File out a report at your distro and ask them why they don't use our na-tray-applet.

**Comment by r3d9u11** [comment]
moved [here](https://github.com/linuxmint/linuxmint/issues/69)
