### ISSUE TITLE
icons in panel are corrupt and blury

### ISSUE THREAD

**Issue by oz123** [mate-desktop/mate-panel#872]
#### Expected behaviour
Icons are not corrupt and blury

#### Actual behaviour

Icons are updated (for the sensors applet)
also see image 
![ugly panel icons](https://user-images.githubusercontent.com/1083045/45972019-e22c7280-c03a-11e8-9b71-198115ce8017.png)

#### Steps to reproduce the behaviour
add sensors applet I guess

#### MATE general version
1.18

#### Package version

 mate-base/mate-panel-1.18.7
#### Linux Distribution
I am using gentoo.

Also, I updated all my deskop to mate git versions and I still see this behaviour.

**Comment by raveit65** [comment]
Do you use a HIDPI monitor?

**Comment by oz123** [comment]
Yes, I do.

**Comment by monsta** [comment]
Proper HiDPI support appeared only in 1.20...

**Comment by oz123** [comment]
This problem appears also with all mate components I compiled from git. Maybe I am missing some compile time option?

**Comment by raveit65** [comment]
What you see with sensor-applet is a issue by gtk+ itself and it is fixed here.
https://gitlab.gnome.org/GNOME/gtk/commit/c8b0a0dea5cd129d8e023443dde5e44319d4631d
This can also happen with other applets, eg. multiload-applet.
You need update gtk+ to 3.24.x
Read this report for reference https://github.com/mate-desktop/mate-panel/issues/818

The blurred icons is something which we can fix.
It is already fixed for some applets, eg. clock-applet. panel launchers.
And there are open reports about.
Volume-applet:
https://github.com/mate-desktop/mate-media/issues/114

Can you please open single reports where you see the blurred icons?

Btw. those are my settings for using HIDPI 
https://github.com/mate-desktop/mate-desktop/issues/316#issuecomment-387223409

**Comment by oz123** [comment]
@raveit65 thank you very much for the detailed answered. I will rebuild gtk+3.24.1 in the coming days and will report further issue if I find them.

**Comment by oz123** [comment]
@raveit65  can one actually build mate with gtk-3.24.x?
I see that mate-themes still require gtk-3.22.x ...

**Comment by raveit65** [comment]
Sure, gtk+-3.24 rebuild from f29 runs without any problem in f28.
Mate-themes doesn't require a gtk+-3.0 version, see https://github.com/mate-desktop/mate-themes/blob/master/configure.ac
See what i use in spec file
https://src.fedoraproject.org/cgit/rpms/mate-themes.git/tree/mate-themes.spec#n35

**Comment by oz123** [comment]
let me get it - the file configure.ac specifies only gtk+-2?
Does this mean that I do need gtk+2 for the themes and gtk+3 for mate componentes?
(I appologize if I sound stupid, I am a total noob in understanding configure.ac macros)

**Comment by lukefromdc** [comment]
You canot build MATE 1.18 or later (or any part of it) with GTK2. Any reference in configure.ac to GTK2 in a version later than 1.16 is a mistake. MATE 1.10 through 1.16 can be built with eitther GTK3 or GTK2

**Comment by oz123** [comment]
I know mate has dropped gtk+2, 
but is mate-themes is gtk+2 only? I am confused.

**Comment by raveit65** [comment]
gtk2 build requires is needed for gtk2 theme engines i think.
It is in configure and you need it.
This doesn't have anything to do with other mate packages.

**Comment by oz123** [comment]
so ... mate is gtk+3 but it use a theme engine with gtk+2. I am confused ...

**Comment by raveit65** [comment]
Well, maybe gtk2 isn't really needed here and we can drop it.
I have no idea why gnome devs added the build requires in the past.
Maybe for building icons?

**Comment by oz123** [comment]
I guess you are right. 
From the [LFS book](http://www.linuxfromscratch.org/blfs/view/8.0/x/gdk-pixbuf.html)
```
The Gdk Pixbuf package is a toolkit for image loading and pixel buffer manipulation. It is used by GTK+ 2 and GTK+ 3 to load and manipulate images. In the past it was distributed as part of GTK+ 2 but it was split off into a separate package in preparation for the change to GTK+ 3. 
```
The version with 2 is misleading. The package has some binaries, which I guess are needed somehow in the build process.

**Comment by Safari77** [comment]
my bottom panel is mostly OK, but top panel displays blurry icons.
![mate-quod](https://user-images.githubusercontent.com/3876865/57219614-ebca7f80-6ff8-11e9-935a-f4d08229cda0.png)

**Comment by raveit65** [comment]
I guess you mean the windows-list-applet.
Doesn't matter if it is at bottom/top/left/right panel. :)
But why you posting without giving us some info's like version, distro, etc.
Sorry, my crystal ball is dead....

**Comment by Safari77** [comment]
> I guess you mean the windows-list-applet.
> Doesn't matter if it is at bottom/top/left/right panel. :)
> But why you posting without giving us some info's like version, distro, etc.
> Sorry, my crystal ball is dead....

From your reply I guess it works for you? I have mate-panel 1.22.1 and gtk-3.24.8 on Fedora 29.
