### ISSUE TITLE
How to code properly

### ISSUE THREAD

**Issue by braikar** [mate-desktop/mate-panel#878]
Hello,

this is not really an issue specific about mate-panel. But I don't know where to ask it.
I would like to be more helpful in coding on mate, but for that I need help to understand the basics of how to work from the git repository.

I'm on linux mint.. in general I've been used to debian.
I occasionally modify some code here and there to fit my needs, but how I do it and did it in the past was always by downloading the source of the deb package, modifying files inside it and rebuilding it.
But to work on mate-desktop in general and any other similar projects for that matter, I need to understand how it works.

Where I'm now, is at working on the notification area, but from the mate-panel 1.20 package (for the version for 1.21..), on git it's at 1.21 with a couple of new dependencies that cannot be met by 1.20.
I don't understand how to work with the git versions?

If I start with the branch I have on mate-panel,

git clone https://github.com/braikar/mate-panel
How do I compile that code.
I've figrued out how to get up to ./configure, by running aclocal, libtoolize, autoheader, autoconf, automake --add-missing etc.
At that point I can use "make" to compile the files I want (if the configure dependencies are met),
but using 'make' just creates the binary, it's a tedious process to copy them manually to the end directory everytime. I usually prefer reinstalling the package..

How do you, any active developer here, do to work with the git repository?
Is trying to debianize the code right? if so how is it done since the debian folder is missing?
Else what's the way to do it? So I can also install all the other dependencies when needed.

Basically what steps should I do to compile and fully install the git repository I just downloaded, wether it's mate-panel, mate-desktop, mate-menus, or anything else?

Then, the second very important question, when the configure/compile process creates all the additional files, how do I keep them in the folder without having them added to the repository?
Neither "git stash" or "git reset --hard" seem appropriate, I don't understand how to keep working with the repo properly once all the compile files are added/modified in it on each compile. Git needs just to ignore them, but how do I do that, or is it done in another way I don't understand?

Thank you

@lukefromdc you told me in the pull request 

> I can refer to the documentation to build a stock Debian package from its source and debian packages, but that's it.

Yes please, all I always found was to build simple hello world packages with static files, that's not really that useful..

**Comment by raveit65** [comment]
@monsta 
Why isn't debian-package updated with a branch for Mate master?
This would be helpful for people you do developing on debian distros.
Can you please give assists to build mate-panel >= 1.21.0

@braikar 
Sorry, i am living in rpm-land, with fedora or any other rpm-based distro i would be able to help you.

**Comment by braikar** [comment]
I had found https://github.com/mate-desktop/debian-packages and saw it was stuck at the official release 1.20.x
I found http://pub.mate-desktop.org/sources/ to get fixed release states.
But apparently no debian packages.. I guess I'm an outcast in deb world ;)

Btw. thanks about the backup suggestions, I always keep a good, not too old, working snapshot in case of ;) I don't intend to work on debian unstable, so I guess I'm a bit safer. And that's why I want to debianize the packages all the time anyway, hence if one fails, I just revert it.. Takes more time, but feels safer.

@muktupavels `sudo apt-get build-dep mate-panel` that would be easy, but usually there's always a couple of new dependencies on the next build. `autogen.sh` is not in the files when I download it directly from git, I have to run `autoconf` to create it..

Anyway, I'll learn to debianize the packages.
I've already figured out a rather "working" solution I need to get used to.

One folder with the git code, one folder with the (in my case Mint) package source, then any file that is in the deb package source but not git source, is copied there. And then I look at file diffs, 99% of the changes to be made are just in debian folder and some light changes in Makefile/configure (and ignore code files changes obviously). So it turns out to be easier than I thought to analyze and fix differences that way, in sort of a brute-force mode.

For mate-menus-1.21 it turned out to be a python version problem, Mint has been almost fully changed to python 3, whereas mate is not yet, so there's a specific patch to account for that.

There was a very distinct change in `configure.ac` (and a couple of other related changes here and there)..
`# Detect if we can build Python bindings (need python and python headers)
if test "x$enable_python" = "xyes" ; then
	AM_PATH_PYTHON(2.7)
	PKG_CHECK_MODULES([PYTHON], [python-${PYTHON_VERSION}], [have_python=yes], [have_python=no])
else
	have_python=no
fi
AC_SUBST(PYTHON_LIBS)
AC_SUBST(PYTHON_CFLAGS)

AM_CONDITIONAL(HAVE_PYTHON, test x$have_python = xyes)`

Anyway, now I have:
`In file included from matemenu.c:23:0:
./../libmenu/matemenu-tree.h:27:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
 #include <gio/gdesktopappinfo.h>
`
Since it doesn't give me an unmet dependency error in configure, I don't know what package/version is needed for that dependency?

**Comment by muktupavels** [comment]
> @muktupavels sudo apt-get build-dep mate-panel that would be easy, but usually there's always a couple of new dependencies on the next build. autogen.sh is not in the files when I download it directly from git, I have to run autoconf to create it..

- https://github.com/mate-desktop/mate-menus/blob/master/autogen.sh
- https://github.com/mate-desktop/mate-panel/blob/master/autogen.sh

Or what did you mean with download directly from git?

Do you have `libglib2.0-dev` installed?

**Comment by raveit65** [comment]
> autogen.sh is not in the files when I download it directly from git, I have to run autoconf to create it..

weird, autogen.sh is in every MATE repo. You should get the file if you use `git clone ......`
And the file is in our released tarballs which you can download from
http://pub.mate-desktop.org/releases/1.21/
for master branch.
Note, those 1.21.x tarball doesn't have latest changes in master branch.

> Anyway, now I have:
In file included from matemenu.c:23:0: ./../libmenu/matemenu-tree.h:27:10: fatal error: gio/gdesktopappinfo.h: No such file or directory #include <gio/gdesktopappinfo.h>
Since it doesn't give me an unmet dependency error in configure, I don't know what package/version is needed for that dependency?

Those deps are from glib2.

> For mate-menus-1.21 it turned out to be a python version problem, Mint has been almost fully changed to python 3, whereas mate is not yet, so there's a specific patch to account for that.

mate-menus don't have python2 dep. See https://github.com/mate-desktop/mate-menus/blob/master/configure.ac
I use those build dependencies:
```
BuildRequires:  gobject-introspection-devel
BuildRequires:  mate-common
```

**Comment by braikar** [comment]
Sorry for the mistakes, I didn't know autogen.sh would create all the configuration. My mind played tricks on me, I was so sure it wasn't there, that I didn't see it when I first checked, sorry. It's indeed there.
The deps from glib2 are find.
The problem I have in mate-menus is very specific to linux mint, because the mint package for 1.20 has a directory 'python' that is not at all in the mate-desktop git repository.
I'm almost certain they added that to make python bindings (the only code file in that python folder makes python bindings to matemenu-tree.h..
I suspect they added it for their specific menu: https://github.com/linuxmint/mintmenu/tree/master/usr/lib/linuxmint/mintMenu, that is coded entirely in python..
I'll play with removing it and removing the compile rules for that one.

**Comment by raveit65** [comment]
Ok, now i understand.
mintmenu isn't ported to use with mate-menus-1.21.0.
You need to uninstall it, and replace it with normal mate menus. Those menus you can add with the add-to-panel dialog.

**Comment by braikar** [comment]
I wasn't using that menu anyway, so that's not an issue, simple remove :) And I ended up removing all the python binding code in mate-menus and it compiled. The otehr packages ended up to be simple copy paste of the debian build info, with tiny changes.

I'm happy to report
https://launchpad.net/~braikar/+archive/ubuntu/mate-1.21/+packages
I'm on 1.21 without a hitch with the option to go back to previous packages correctly if needed :)
Thank you all

Then there's one last question that remains unanswered, if run autogen or package building functions, can I use it inside my working git directory and just tell git to ignore all the compile created files?

**Comment by raveit65** [comment]
A ppa is nice :)
There is no easy way to remove the generated make files and others , as far i know.
I would do a simply copy of the git repo which you can use for installing.

**Comment by muktupavels** [comment]
https://github.com/mate-desktop/mate-panel/blob/master/Makefile.am#L56

But I don't see git.mk in repo. It is supposed to autogenerate .gitignore file.

**Comment by braikar** [comment]
Okay, then it's either I make my own .gitignore or it's added back in the repo (git.mk to generate) or copying.
Thanks for the help, all my questions are solved :)
