### ISSUE TITLE
Window List - Setting for Maximum button Width

### ISSUE THREAD

**Issue by markd89** [mate-desktop/mate-panel#881]
I have the Window List horizontal on the bottom of the screen a-la-Windows style.

The buttons resize themselves horizontally -- i.e. as more windows are opened, the buttons get smaller. 

As windows are closed, the buttons grow wider -- up to a maximum point and then stop getting wider.

I'd like the maximum point to be smaller so that the buttons do not get as wide as they do by default.

Where can I find that setting?

Thanks much!
Mark

Debian Stretch/Mate 1.20.3

**Comment by lukefromdc** [comment]
I don't think there is any gsettings or other changeable preference to change this. We are not going to reduce that maximum width for all users.

**Comment by markd89** [comment]
Hi Luke, OK, thanks for the info!
