### ISSUE TITLE
Color does not persist after reboot

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [mate-desktop/mate-panel#882]
I change the panel color background in the mate panel properties. However, the background color does not persist after reboot, backing to default values. I'm using the arc theme, but this issue is not exclusively related to the theme.

Linux debianvbr 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

MATE Desktop Environment 1.16.2

**Comment by ViniciusBRodrigues** [comment]
**killall mate-panel** reverts the background color and back to default. The applets still ok, I didn't find nothing wrong after reboot or _killall_.
Many thanks

**Comment by ViniciusBRodrigues** [comment]
These are initial values:
```
viniciusbr@debianvbr:~$ dconf dump /org/mate/panel/toplevels/
[top]
enable-buttons=false
expand=true
enable-arrows=true
orientation='top'
screen=0
size=24

[top/background]
color='#545c5b'
type='color'

[toplevel-0]
enable-buttons=true
orientation='left'
enable-arrows=true
```

Then I changed to "use system theme"
```
viniciusbr@debianvbr:~$ dconf dump /org/mate/panel/toplevels/
[top]
enable-buttons=false
expand=true
enable-arrows=true
orientation='top'
screen=0
size=24

[top/background]
color='#545c5b'
type='none'

[toplevel-0]
enable-buttons=true
orientation='left'
enable-arrows=true
```

So a changed the color manually:
```
viniciusbr@debianvbr:~$ dconf dump /org/mate/panel/toplevels/
[top]
enable-buttons=false
expand=true
enable-arrows=true
orientation='top'
screen=0
size=24

[top/background]
color='rgb(46,52,54)'
type='color'

[toplevel-0]
enable-buttons=true
orientation='left'
enable-arrows=true
```

Then I killed the panel and the color back to default:
```
viniciusbr@debianvbr:~$ dconf dump /org/mate/panel/toplevels/
[top]
enable-buttons=false
expand=true
enable-arrows=true
orientation='top'
screen=0
size=24

[top/background]
color='#545c5b'
type='none'

[toplevel-0]
enable-buttons=true
orientation='left'
enable-arrows=true
```

So, the values are changing but the system are not keeping it.

**Comment by lukefromdc** [comment]
Note that MATE 1.16 is now quite old, though little has changed in the panel background code since mate-panel 1.16 came out and nothing I can see offhand that would affect panel background handling. The question is what is keeping your mate-panel install from reading the dconf/gsettings value for background-and only for background. @monsta, @raveit65, @muktupavels, any ideas?

**Comment by raveit65** [comment]
No idea.
I can't confirm that with rhel7 and mate-1.16.x with gtk2 in a VM.
Local problem?
Better update to a supported MATE version, which is 1.20 ?
Or file out a bugreport against the distro and ask maintainer for help?

**Comment by ViniciusBRodrigues** [comment]
> No idea.
> I can't confirm that with rhel7 and mate-1.16.x with gtk2 in a VM.
> Local problem?
> Better update to a supported MATE version, which is 1.20 ?
> Or file out a bugreport against the distro and ask maintainer for help?

Yeah, 1.16 is quite old. I will activate the debian backports to upgrade it.

Many thanks

**Comment by ViniciusBRodrigues** [comment]
Ok, I updated to 1.20.3 and the issue still persist.

**Comment by raveit65** [comment]
Does it happens with a new account too?

**Comment by ViniciusBRodrigues** [comment]
> Does it happens with a new account too?

No. I tested with a new account and worked fine. My session begins with the color that I picked and fade into default color in some seconds after new log in.

**Comment by raveit65** [comment]
Ok, than a setting in your home dir causes the issue.
You can try to reset dconf/gsettings keys. see `gsettings help`
1. list all schemas to get the right name of a schema
`gsettings list-schemas | sort`
2. `gsettings reset-recursively org.mate.panel.menubar && gsettings reset-recursively org.mate.panel`
This will reset the panel to default

Or do the hard way and remove whole dconf settings 
`sudo rm ~/.config/dconf/user && /var/run/user/1000/dconf/user`
and restart session. You can save the file before.
This will give you a clean new session.
Of course you need to setup your account again.

**Comment by ViniciusBRodrigues** [comment]
I found the problem: mate-dock-applet. Without this applet the panel work fine. 

Now the minor issue that I'm facing now is this black border in the popup:

![captura de tela em 2018-10-16 13-45-06](https://user-images.githubusercontent.com/12240167/47033185-8a20f180-d14a-11e8-9b4f-82a0755ccd50.png)

**Comment by raveit65** [comment]
mate-dock-applet is third party.

**Comment by selectiveduplicate** [comment]
Just looked at the code of mate-dock-applet, and the ``org.mate.panel.applet.dock.gschema.xml`` file describes two keys such as ``change-panel-color`` and ``change-panel-color-dock-only``- these might have something to do with the issue; it needs investigating, though I doubt the issue has something to do with MATE directly...

**Comment by ViniciusBRodrigues** [comment]
> mate-dock-applet is third party.

Yeap, I already remove it from system. Many thanks.

**Comment by ViniciusBRodrigues** [comment]
> Just looked at the code of mate-dock-applet, and the `org.mate.panel.applet.dock.gschema.xml` file describes two keys such as `change-panel-color` and `change-panel-color-dock-only`- these might have something to do with the issue; it needs investigating, though I doubt the issue has something to do with MATE directly...

No problem then. I can use something else. Many thanks.

**Comment by monsta** [comment]
The black borders on the notification window happen when the compositing in the window manager is disabled: https://github.com/mate-desktop/mate-notification-daemon/issues/98.
