### ISSUE TITLE
mate-drivemount-applet icons get smaller on some events

### ISSUE THREAD

**Issue by denispr** [mate-desktop/mate-panel#884]
#### Expected behaviour
Drives icons should keep the same size, whatever happens.

#### Actual behaviour
Each time I change mate theme in mate appearance window, the drive icons get smaller and smaller, even to a point they can hardly be seen. Same problem also happens when getting back from a "suspend to ram" state.

#### Steps to reproduce the behaviour
1) add mate-drivemount-applet to panel
2) plug in an external device so that an icon is displayed for it by mate-drivemount-applet
3) go to mate appearance window and change theme
you should notice that the device icon size has gotten smaller.

#### MATE general version
1.16.0

#### Package version
1.16.0+1

#### Linux Distribution
Debian 9 stretch

#### Link to downstream report of your Distribution
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911551

**Comment by raveit65** [comment]
Does the issue still exits?

**Comment by denispr** [comment]
Thanks for caring about that bug report, 
no more problem on Debian 11 bullseye !
