### ISSUE TITLE
application launcher (per default ALT+F2) missing UI files

### ISSUE THREAD

**Issue by oz123** [mate-desktop/mate-panel#910]
#### Expected behaviour
When I press Alt+F2 the application launcher dialogue should pop up.

#### Actual behaviour
Instead I see a dialogue with the warning:
```
Unable to load file '/usr/share/mate-panel/ui/panel-run-dialog.ui'
Failed to open file "/usr/share/mate-panel/ui/panel-run-dialog.ui": No such file or directory.
 ```
#### Steps to reproduce the behaviour
clone mate-panel
run ./autoge.sh --prefix=/usr
sudo make install
press Alt+F2

#### MATE general version
1.20 and 1.21

#### Package version
1.20 and 1.21

#### Linux Distribution
Gentoo

#### Link to downstream report of your Distribution
https://github.com/oz123/mate-de-gentoo

**Comment by lukefromdc** [comment]
In mate-panel  panel-gresource.xml builds a gresource which includes that ui file and loads as part of the binary. Thus the ui files are no longer installed at build time, all the way back to 
https://github.com/mate-desktop/mate-panel/commit/1b7c43adfa25eee678661e4d56dfa37888ff27c0#diff-34af51355d6d6e1b53d27c8d822c06b6
in 2012. Thus these UI files should not be installed or looked for at runtime,  and I've never had this problem.

I always build from source, using these options
`
./autogen.sh  --with-in-process-applets=wncklet,clock,fish,notification-area --prefix=/usr libdir=/usr/lib/x86_64-linux-gnu --sysconfdir=/etc --enable-shared=yes --disable-maintainer-mode --disable-schemas-compile`

**Comment by oz123** [comment]
@lukefromdc thanks for the details report. I will try your suggestion and report back.

**Comment by lukefromdc** [comment]
Odd though that you had to build the applets in-process to get something not related to the clock, fish, tray. or wncket to work. There have been no reported problems with out-of-process builds Fedora has used to avoid a memory leak issue, nor in my own testing. Theoretically that should have no effect on loading the gresource for the panel itself (which contains that file and is included in the built binary) unless it is somehow interacting with something else in your build system
