### ISSUE TITLE
Rendering issues with the tray icons

### ISSUE THREAD

**Issue by DmitriyTrt** [mate-desktop/mate-panel#92]
Steps to reproduce:
- Start some non-GTK app with tray icon (Skype in my case)
- Start another application with tray icon.
- The first icon will have dark background under it:

![Shot-2a9-01](https://f.cloud.github.com/assets/1159188/342718/600736b2-9dbf-11e2-87a8-006b55186ba9.png)

The panel size is 24, I have semi-transparent background, but the same happens with default opaque background too.

Similar problems are displayed in [another issue](https://github.com/mate-desktop/mate-panel/issues/50#issuecomment-13536976), but the issue topic is about different problem, so I've decided to start a new one.

To "refresh" icons I use the following trick: open panel properties and change its size (then set back to original). This is some kind of rendering bug, probably panel should be re-painted on new icons, I don't know. Just know that it looks ugly and quite annoying.

**Comment by FlashFMA** [comment]
Still there. Linux Mint 17.3 MATE
