### ISSUE TITLE
Can't Remove icon/display info in panel

### ISSUE THREAD

**Issue by ConnectionistSystems** [mate-desktop/mate-panel#926]
I added an icon that displays (Caps lock/Num Lock/ ScrollLock). I want to now remove this icon from the panel. I can no longer right click on icon to remove; it does nothing. Is there a way manually remove this by editing a file? Other I cans I can move or delete, it is just this icon. The panel is attached to the top of the screen.

**Comment by lukefromdc** [comment]
What program is that icon from? Also what version of MATE, what distro?

**Comment by ConnectionistSystems** [comment]
MATE Panel 1.20.4
OS Parrot 4.5
Kernel 4.19.0
Theme Blackbird
Icons maia

**Comment by lukefromdc** [comment]
I don't know what that icon is, how did you add it in the first place? In a pinch, you can trash your panel configuration and start over from the original panel configuration by running 
`mate-panel --reset `

**Comment by ConnectionistSystems** [comment]
Parrot has two panels, I'm not sure if I do this reset which panel it will reset, further if the reset will be applied to a specific and panel and reset as I first got it when I installed the OS. Is there another solution?

**Comment by lukefromdc** [comment]
Reset is applied to all panels showing, and resets them to the distro's default. My myself know zero about the icon in question or where it came from and thus cannot help further. I don't see an option for this in mate-control-center and the distro I am familiar with is Debian

**Comment by lukefromdc** [comment]
There is an icon for keyboard language mode input in mate-control-center that shows when two or more languages are configured (NOT the default) in mate-control-center>keyboard>layouts , the icon for that is usually a flag of the country whose language is selected. That icon however shows up in the system tray, not with the launchers.

**Comment by ConnectionistSystems** [comment]
Thanks for all the replies. After running the reset the icon is still there, perhaps it is part of the OS? But, I'm glad I did the reset, because it fixed another issue with application tabs not showing up when they are on a different screen, now they do. Thanks!

**Comment by monsta** [comment]
I don't remember if we have that in some UI, but it's possible to remove these icons from the command line:
```
gsettings reset org.mate.peripherals-keyboard-xkb.general duplicate-leds
```
