### ISSUE TITLE
Can't select the bottommost menu item

### ISSUE THREAD

**Issue by yetist** [mate-desktop/mate-panel#944]
In the main menu, if a category contains menu items that exceed the screen height, the up and down arrows are not displayed when you move the mouse.

#### Expected behaviour
The arrow is displayed at the top or bottom and the menu items can be scrolled.

![2019-03-07 16-39-46](https://user-images.githubusercontent.com/665058/53943342-d8ce2880-40f7-11e9-8fc1-3dc9c6aa2a43.png)

#### Actual behaviour
The mouse moves to the bottom, no arrows are displayed, and menu items do not scroll.
![2019-03-07 16-39-21](https://user-images.githubusercontent.com/665058/53943354-dff53680-40f7-11e9-8fe6-13ad6d164ca3.png)

#### Steps to reproduce the behaviour
- Install mate-panel 1.22 or master.
- Click on the main menu with your mouse
- Move the mouse to each menu category and enter the submenu
- If there are too many menu items in the menu category, one screen cannot be displayed completely, and the bottom menu item cannot be selected with the mouse.

#### MATE general version
mate-panel 1.22 and master

#### Package version
gtk-3.24.5-1 on Archlinux

Can someone reproduce this problem? Not sure if it is a problem with gtk3.

**Comment by yetist** [comment]
In my tests, this issue was not related to the theme, and was not related to the window manager.

**Comment by raveit65** [comment]
I can't reproduce it with my 28 ° monitor here the display is to huge for running in this issue.
But i see that problem if opening the context menu of folders and files in caja sometimes.
Usually the issue occurs only one time . If i try to open the menu again than it is fine.
But i recall that we fixed such a problem somewhere some times ago.

**Comment by yetist** [comment]
I think this may be a bug in gtk3. Using gnome-terminal will have the same problem.
![2019-03-07 17-20-16](https://user-images.githubusercontent.com/665058/53945828-78da8080-40fd-11e9-9bee-5db62f18684d.png)

**Comment by lukefromdc** [comment]
This is yet another instance of a bug in GTK 3.24.4 and 3.24.5 where menu scrollbars don't show up. It should be fixed by
https://gitlab.gnome.org/GNOME/gtk/commit/1d4eac211c09624d29b9309e2b92173f7477a9b7
but that won't be in a release (or supplied by a distro) until GTK 3.24.6 is released

**Comment by yetist** [comment]
Confirm that it is a bug in gtk3, so close this issue.
