### ISSUE TITLE
Start menu button big obtrusive arrow regression in 1.20.5

### ISSUE THREAD

**Issue by artixnous** [mate-desktop/mate-panel#948]
#### Expected behaviour
Small or no arrow at all.
#### Actual behaviour
Big, ~~ugly~~ obtrusive arrow over the icon.

Please, see the attached screenshot composition. Adding a `/schemas/apps/panel/objects/has_arrow` boolean as suggested with the closing commit in #24 doesn't solve the issue.

![startmenu-arrow-regression](https://user-images.githubusercontent.com/6310912/54898937-c49b7100-4ed6-11e9-8e66-06ec3b4f2d4d.png)

**Comment by lukefromdc** [comment]
Ugly is in the eye of the beholder. It does have the advantage of being eaiser to see, and according to
https://github.com/mate-desktop/mate-panel/issues/24 its appearance is set by the GTK theme. Keep in mind that we have transitioned to GTK3 since that issue was posted, and for that matter GTK3 has seen a LOT of changes

**Comment by artixnous** [comment]
Thanks for answering, is there any way to override this theme setting?

**Comment by lukefromdc** [comment]
I don't know off the top of my head, but everything in mate-panel responds to selectors following
`.mate-panel-menu-bar
`
Note that all themes are different, but in my highly customized "UbuntuStudio_Legacy" theme adding  this stanza to the theme css files (or presumably to ~/config/gtk-3.0/gtk.css will turn the arrow transparent and hide it. 
```

.mate-panel-menu-bar button {
	color: transparent;
}

```
Effects on all other themes untested, but no risk to try it other than maybe getting invisible text on some other panel button (e.g the clock) that is not set with more specific selectors until you take it back out. Note that this appears only on the menubutton, the menu bar does NOT show the arrow, and if you want you can set that to show only "applications" and not "places" and "system."

**Comment by artixnous** [comment]
It works, thank you. Putting the stanza it in ~/config/gtk-3.0/gtk.css seems to override many other theme settings (panel text colour and button backgrounds), so I appended it to its own CSS and got my intended result. Thank you again, I'm closing this.

**Comment by artixnous** [comment]
It works, thank you. Putting the stanza it in ~/config/gtk-3.0/gtk.css seems to override many other theme settings (panel text colour and button backgrounds), so I appended it to its own CSS and got my intended result. Thank you again, I'm closing this.

**Comment by artixnous** [comment]
Just for the sake of completion, I ended up with this gtk.css:
```
.mate-panel-menu-bar button {
    color: transparent;
}
panel-toplevel.background.horizontal,
.mate-panel-menu-bar,
#clock-applet-button,
#clock-applet-button:hover  {
   color: white;
}
#tasklist-button {
    color: white;
}
```
Now, it's all back to normal.
