### ISSUE TITLE
Is it possible to add launcher to panel from terminal?

### ISSUE THREAD

**Issue by MikeFalowski** [mate-desktop/mate-panel#950]
Until 2013 there was a command `mate-panel-add` which allowed user to add launcher to the panel. Now I can't find any info how to do this from the command line.

Is it still possible?

**Comment by raveit65** [comment]
Are you sure?
I can't remember about such a command. Which version of mate-panel?

**Comment by MikeFalowski** [comment]
I found reference to it on Ubuntu forum i 2012: [info about using it](https://askubuntu.com/questions/229511/how-can-i-add-an-applet-to-mate-from-the-terminal)
[Commit where it was removed](https://github.com/mate-desktop/mate-panel/commit/a5d68a6579c56d5fd09f2087d31a84dd438ccc67#diff-e43755346e20f9e3d1f6b266c7ebe342).

**Comment by raveit65** [comment]
We are using `gsettings` not `mateconf` since a long time.
Honestly, i have no idea when/why this was removed, probably during port to gsettings,.....maybe.
Feel free to search in git log for a commit.
https://github.com/mate-desktop/mate-panel/tree/1.10

**Comment by MikeFalowski** [comment]
Ok, thanks for the reply. I will try to find something.

Anyway, do you have any idea it is possible to add launcher to top panel with CLI in easy way?

**Comment by raveit65** [comment]
Don't know if it is easy but you can edit the panel-layout file witt the `sed` or `vim` command under.
```
ls /usr/share/mate-panel/layouts/
default.layout  linuxmint.layout  opensuse.layout
fedora.layout   mageia.layout     ubuntu.layout
```
Or write your own panel layout.
A layout file can be loaded via gsettings.
```
[rave@mother ~]$ gsettings get org.mate.panel default-layout
'fedora'
```
with 
```
[rave@mother ~]$ gsettings set org.mate.panel default-layout 'your-layout'
```
Than reload the panel with `mate-panel --replace --reset`
Or use the `--layout` option.
You can find here an example where i added a panel-applet to the layout file (object volume-control).
https://src.fedoraproject.org/cgit/rpms/mate-panel.git/tree/mate-panel_fedora-30.layout?id=31c296bda91ec0c2956bfa1b3a66a31c4b16ab80#n45

**Comment by vkareh** [comment]
Wow that `mate-panel-add` is a really ugly Python script that for all effects, modifies the mateconf settings for the panel. There might be a way to write a "clever" script that would do the same through a combination of layout files and gsettings, but I would not count on something like that being merged.

Maybe if the panel exposes an API that allows a small binary file to interact with the panel toplevels, we could pull it off, but it seems like a stretch, given that you can have multiple layout files and switch between them in the command line already.
