### ISSUE TITLE
workspace switcher: keyboard trap when moving on it with the keyboard

### ISSUE THREAD

**Issue by alexarnaud** [mate-desktop/mate-panel#952]
#### Expected behaviour
Same behavior as in earlier releases (< 1.22): only the context menu key opens the context menu.

#### Actual behaviour
The workspace switcher handles all keys and open the context menu so it's not possible to leave it without a mouse. In short term, a blind user or keyboard-only user is blocked on the workspace switcher.

#### Steps to reproduce the behaviour
1. Enable the default Mate layout to ensure a easier reproduction
2. Press control + alt + tab to move to the bottom panel (or control + alt + espace on Ubuntu)
3. Move on the workspace switcher if you're not on it already
4. Press tab or try to leave the panel with control + alt + tab

#### MATE general version
1.22.0

#### Linux Distribution
Both Fedora 30 and Arch Linux

#### Link to downstream report of your Distribution
Pointed to me by a blind user on the orca list: https://mail.gnome.org/archives/orca-list/2019-April/msg00019.html

**Comment by alexarnaud** [comment]
Le 09/04/2019 à 17:04, Victor Kareh a écrit :
> It happens also with the window-list and with the clock applets. Once 
> focused, pressing any key will trigger the context menu, so a 
> keyboard-only user will be stuck.

Could you help us to find the culprit commit which introduces the 
regression ?

Best regards,
Alex.

**Comment by alexarnaud** [comment]
@raveit65 @lukefromdc @vkareh This is a regression, could you help us to figure out this one ?

This issue makes Mate Panel 1.22 really difficult to use for a keyboard-only user like a blind person.

Best regards,
Alex.

**Comment by lukefromdc** [comment]
Any chance you can bisect for the offending commit? If not we can do it but it would speed things up

**Comment by raveit65** [comment]
I hope that is a regression caused by MATE and not by gtk+, because I noticed other issues with menus in f30.
But maybe that is another fallout out by fixing deprecated gtk_menu_popup.

**Comment by lukefromdc** [comment]
it in indeed from fixing deprecated gtk_menu_popup and affects other applets using mate-panel-applet.c as well.
dacbd08684d6081f21041928e01072ed83c80dd8 
" mate-panel-applet.c: replace deprecated gtk_menu_popup"
is the offending commit-and I noticed that prior to it, neither the panel tasklist, nor other wncklet apps could be interacted with by the keyboard at all (at least with what I was doing) other than to tab past them and keep going. Now the window list, show-desktop, plus the clock, trash etc all open their menus when tab is pressed again once they are focussed.

**Comment by lukefromdc** [comment]
I just found that gnome-panel also has this keyboard trap

**Comment by lukefromdc** [comment]
So how to we get the tab to continue through, but return to pop up the menu?

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-panel/pull/958 fixes the keyboard trap, sets the context menus to open only on the menu key. Can't use return for this as it is needed for things like opening the calendar. Some applets (notably the new volume control panel applet) will need further work to traps properly use the "return" keypress as some others (e.g. the clock/calendar) already do or partially do with this.  

Also: note that ESC will exit the menus with current master and get out of the keyboard trap, and also escape menus opened in the PR version of mate-panel with the menu key

**Comment by alexarnaud** [comment]
Le 06/05/2019 à 08:13, lukefromdc a écrit :
> #958 <https://github.com/mate-desktop/mate-panel/pull/958> fixes the 
> keyboard trap, sets the context menus to open only on the menu key. 
> Can't use return for this as it is needed for things like opening the 
> calendar. Some applets (notably the new volume control panel applet) 
> will need further work to traps properly use the "return" keypress as 
> some others (e.g. the clock/calendar) already do or partially do with this.

Thanks a lot lukefrommdc to figure out this issue.

Best regards,
Alex.

**Comment by alexarnaud** [comment]
Does this fix has been backported to 1.22 branch ?

Mate 1.22 lands into Debian unstable and a blind colleague told me that the bug occurs on Debian too.

The Debian issue is: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933714

Best regards,
Alex.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-panel/commits/1.22

**Comment by alexarnaud** [comment]
@raveit65 Thanks so it has been backported but no released has been published since that.

We'll wait the next release point.

Best regards.
