### ISSUE TITLE
wrong icons in add-to-panel dialog with gtk+-3.24.8

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-panel#959]
#### Expected behaviour
with gtk+-3.24.7
![add-panel-dialog-good](https://user-images.githubusercontent.com/961604/57214310-e4e84080-6fe9-11e9-8116-340ae107637e.png)

#### Actual behaviour
with gtk+-3.24.8
![add-panel-dialog-bad](https://user-images.githubusercontent.com/961604/57214562-a69f5100-6fea-11e9-8168-469efdfbf267.png)
We are MATE logo, you will be assimilated, resistance is futile!
#### Steps to reproduce the behaviour
1. update to gtk+-3.24.8
2. open the add to panel dialog

#### MATE general version
1.22.1

#### Package version
1.22.1 and master branch

#### Linux Distribution
Fedora

#### Link to downstream report of your Distribution
Fedora maintainer has confirmed the issue.

This is is clearly reproducible with updating to latest gtk+ release.

**Comment by raveit65** [comment]
Issue is caused by this commit https://gitlab.gnome.org/GNOME/gtk/commit/d151223b1bd7890c6614fd648c1f45e91fd8b730
https://gitlab.gnome.org/GNOME/gtk/issues/1809
Btw. reverting this commit solves using wrong icons.
So, the question is why some applets , eg, fish-applet, use new `use-fallback-icons on the GThemedIcon`, which seems to be our logo?
And why doesn't have adwaita icon-theme this issue and found the icon in hicolor dir?
`/usr/share/icons/hicolor/*/apps/mate-panel-fish.*`

**Comment by raveit65** [comment]
@monsta 
You was right.
This happens with that feature
https://developer.gnome.org/gio/stable/GThemedIcon.html#GThemedIcon--use-default-fallbacks
Our icons from panel, eg. 32px
```
size = 32x32

iconsdir = $(datadir)/icons/hicolor/$(size)/apps

icons_DATA =					\
	mate-panel-clock.png			\
	mate-panel-drawer.png			\
	mate-panel-fish.png			\
	mate-panel-force-quit.png		\
	mate-panel-launcher.png		\
	mate-panel-notification-area.png	\
	mate-panel-separator.png		\
	mate-panel.png				\
	mate-panel-window-list.png		\
	mate-panel-window-menu.png		\
	mate-panel-workspace-switcher.png
```
All icon names will be cut to `mate` with use-default-fallbacks feature, and the mate.png/svg from mate-icon-theme will be used instead of the right icon in hi-color dir.
Of course adwaita-icon-theme doesn't have the mate icon (fallback) and can use the normal icons in hi-color dir.
For testing i deleted all mate.png/svg icons from our icon theme,
Than the error is gone and all applets use the correct icon in add-to-panel dialog.

For me sounds that this fallback feature has some negative side-effect.

**Comment by raveit65** [comment]
I filed out a report. Let see what happens.
https://gitlab.gnome.org/GNOME/gtk/issues/1867

**Comment by lukefromdc** [comment]
Apparently some icon themes will trigger or be affected by this bug and others will not. I don't get it in my UbuntuStudio_Legacy icon theme
https://github.com/lukefromdc/ubuntustudio-legacy-icon-theme
but did get it with both the mate and menta icon themes.

**Comment by raveit65** [comment]
Yes, does UbuntuStudio_Legacy icon theme ship the mate.png or mate.svg?
Only icon themes which ship our logo are affected.
mate-panel-clock.png --> mate.png
etc.

I think for most places we use mate-desktop.png nowadays, and maybe mate.png is unused.
But it can't can't be the solution that we remove our logo.

**Comment by raveit65** [comment]
After a talk with gtk+ dev , see https://gitlab.gnome.org/GNOME/gtk/issues/1867#note_506417 ,
it might be better to rename our applet icons, to avoid to run in same issue if someone enable turns on default fallbacks in another place.
I will try to rename icons from `mate-panel-xxx` to `m-panel-xxx` in mate-panel and mate-applets repo.
Another solution might be to use `mate-desktop` icon everywhere and drop mate.png in mate-icon-theme.

@mate-desktop/core-team 
Thoughts?

**Comment by vkareh** [comment]
m-panel-xxx looks really ugly, what happens if we rename `mate.png` to `mate-desktop.png`? The project is technically MATE Desktop, so this change should be fine (assuming it fixes the issue).

**Comment by sc0w** [comment]
I think if gtk developers revert the culprit commit, I vote to do nothing, and just talk about it to the gtk maintainers of our distros to apply patch

**Comment by raveit65** [comment]
> m-panel-xxx looks really ugly, what happens if we rename `mate.png` to `mate-desktop.png`?

Using mate.png from mate-icon-theme is the main problem. For testing purposes i deleted the icon and the problem was gone after updating the icon-cache.
And gnome-panel which use icons like gnome-panel-xxx for the applets doesn't have the issue because there isn't a gnome.png icon in gnome-icon-, or adwaita-icon-theme.
Btw. you should see the issue in your f30 installation with current gtk+-3.24.8.

We have already mate-desktop.png as icon in our theme, so in the end we need only change the code where it is used.
But during my short test i didn't saw a place where the mate.png icon was missing.
And @rbuj  changed using mate.png to mate-desktop.png in a commit sometime ago, if i recall correctly.

> I think if gtk developers revert the culprit commit, I vote to do nothing, and just talk about it to the gtk maintainers of our distros to apply patch

see comment from M.Clasen
https://gitlab.gnome.org/GNOME/gtk/issues/1867#note_506417
It might be possible that we run again in this issue with our icon structure.
I can try to speak with fedora's gtk+ maintainer which are gtk+ devs itself :)
But i know that they prefer to use a vanila gtk+ version in fedora.
And do you really think that debian with his conservative package politics will add a patch which isn't from upstream for us?
Well, maybe you like to speak with debian gtk+ maintainer?

**Comment by rbuj** [comment]
It's a gtk+ bug. The look up for a icon-name should never override hicolor icons.

**Comment by lukefromdc** [comment]
Confirmed my icon these does not provide mate.png or mate.svg , though it inherits from mate
