### ISSUE TITLE
Unable to scroll interface tabs with mouse wheel on Clock Preferences called from Clock Applet

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-panel#967]
#### Expected behaviour
On Ubuntu MATE 16.04 LTS user was able to use mouse wheel to scroll interface tabs.

#### Actual behaviour
On development version of Ubuntu 19.10 this is not possible - tabs do not react on mouse wheel.

#### Steps to reproduce the behaviour
1. Install Ubuntu MATE 19.10
2. Open *Clock Applet* from MATE Panel, click *Locations*, then *Edit*
3. Try to switch interface tabs with mouse wheel

#### MATE general version
1.22.1

#### Package version
1.22.1-0ubuntu1

#### Linux Distribution
Ubuntu 19.10

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/mate-panel/+bug/1828808

**Comment by raveit65** [comment]
Scrolling on tabs wasn't intended.

**Comment by N0rbert** [comment]
As long time GNOME2 user this functionality is intended for me. Seems to be GTK3-caused regression.
