### ISSUE TITLE
global-menu with qt apps has problem showing submenu

### ISSUE THREAD

**Issue by mmishut** [mate-desktop/mate-panel#970]
#### Expected behaviour
Submenu box should be fully drawn. 

#### Actual behaviour
Submenu is partially drawn when I open it frst time. On second time I see submenu opens fine.
![image](https://user-images.githubusercontent.com/38864264/57771697-241a3e00-771c-11e9-805f-180f19f6807c.png)

#### Steps to reproduce the behaviour
Change desktop settings to use Global Menu instead of local. I use "MATE Tweak" tool for it. And select "Coupertino" style panels
Open any QT based application with 2-levels of menu. I used qtcreator
Go to [menu]->[submenu]

#### MATE general version
1.20.4

#### Package version
mate-panel 1.20.5-1

#### Linux Distribution
Ubuntu MATE 19.04

**Comment by rilian-la-te** [comment]
@mmishut, go here:
https://gitlab.com/vala-panel-project/vala-panel-appmenu

It is already fixed at https://gitlab.com/vala-panel-project/vala-panel-appmenu/commit/e11b24c052fdb130ea9fbb343fe6613f7592f538

Please, close bug and do not disturb MATE developers.

**Comment by lukefromdc** [comment]
Wonder how many end users are aware that not everything they see in the panel necessarily comes from MATE itself?

**Comment by mmishut** [comment]
Some problems could be integration bugs instead of bugs in dependant components, so I just had intention to inform developers of MATE panel component.
