### ISSUE TITLE
the mate-panel offset on screen is misaligned upon restoring from the freeze trick

### ISSUE THREAD

**Issue by ohlogic** [mate-desktop/mate-panel#995]
#### Expected behaviour
the mate panel to go to 0,0 from bottom left 

#### Actual behaviour
related to issue [#994](https://github.com/mate-desktop/mate-panel/issues/994) when froze I did the ctrl+alt+f1 and then ctrl+alt+f7 trick to restore the desktop unfrozen, instead there was a gap of about 10 pixels of desktop blank space, though the wallpaper was there.

This offset is due to running a modified screen setting due to overscan/underscan.  The command I run to fix it is

nvidia-settings --assign CurrentMetaMode="DVI-D-0: nvidia-auto-select +0+720, HDMI-0: 1360x768 +0+0 {viewportin=1360x768, viewportout=1300x748+25+10, ForceCompositionPipeline = On}"

#### Steps to reproduce the behaviour
If it freezes related to issue  [#994](https://github.com/mate-desktop/mate-panel/issues/994) then fixing by ctrl+alt+f1 and then ctrl+alt+f7 with the modified screen settings still in effect the offset should occur.

However I have a fix for this as well.  I run the command 'mate-panel --replace' and it puts the mate-panel to the correct offset at 0,0 right-left of screen.  However, I have this command in a .sh file then use a launcher to run it without a extra terminal window in the window list program.
For whatever reason I could not put an ampersand after the 'mate-panel --replace &' as so.  This issue and the previous are my only issues at this time.  Thanks for making MATE Linux Mint 19.1, other than these two minor issues.  It's been very reliable for me.

#### MATE general version
1.20.1

#### Package version
1.20.1

#### Linux Distribution
Linux Mint MATE 19.1 tessa

**Comment by raveit65** [comment]
> Link to downstream report of your Distribution

????

**Comment by ohlogic** [comment]
I'm sorry, what are you asking?

**Comment by vkareh** [comment]
I think you might want to report this to Linux Mint first. I'm not sure what issues you might be having, but I haven't experienced a freezing panel, nor do I see how it would be fixed by changing to tty and back... Maybe it's a Mint/nvidia issue specifically?

**Comment by ohlogic** [comment]
Thank you for your response. I will report the matter to Linux Mint also and next time first to them.  Thank You.

**Comment by vkareh** [comment]
Thanks! When you do, post the link in the Downstream Report part above. That way we can coordinate with the their team if necessary

**Comment by raveit65** [comment]
Does the issue still exists?

**Comment by LinuxBusiness** [comment]
No, Linux Mint 21.2 Victoria running perfectly.
