### ISSUE TITLE
Pinning Chromium doesn't persist after reboot

### ISSUE THREAD

**Issue by testbughub** [mate-desktop/mate-panel#997]
#### Expected behaviour
The icon should stay after reboots.

#### Actual behaviour
It doesn't.

#### Steps to reproduce the behaviour
Don't know.

#### MATE general version
1.20.3

#### Package version
1.20.3-1

#### Linux Distribution
Ubuntu 18.10

#### Link to downstream report of your Distribution
?

(First time submitting an issue, so forgive me if I missed anything.)

**Comment by vkareh** [comment]
@testbughub - what do you mean by pinning? To the panel? Or to the dock applet? How are you attempting to "pin" chromium?

**Comment by testbughub** [comment]
> @testbughub - what do you mean by pinning? To the panel? Or to the dock applet? How are you attempting to "pin" chromium?

Sorry for not clarifying. The dock applet. 
I open Chromium and right click to pin it to the dock.

**Comment by vkareh** [comment]
Here's the repo https://github.com/ubuntu-mate/mate-dock-applet and it seems like there's a bug reported for this: https://github.com/ubuntu-mate/mate-dock-applet/issues/178

Does that bug over there sound similar to your issue? If so, could you close this one and add this information there? That way we have a bit more data when working on it :)

Thanks!!

**Comment by testbughub** [comment]
Sorry! Looks like I didn't do enough research beforehand.
I'll do just that. Is there any more info you could use from me before posting there?
Thanks for replying!

**Comment by vkareh** [comment]
no worries, thanks for reporting this issue. Just make sure you post your issue over there with reproduction steps, the more data the better. I'll close this for now
